### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by madanvparadkar** [chatwoot/chatwoot#10106]
### Describe the bug

When users are trying to send chat messages, it is throwing an error. This happened after the recent docker upgrade. The error shown in logs is as follows . Please suggest how to resolve it. 

rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] NoMethodError (undefined method `blocked?' for an instance of Contact):
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19]   
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/models/conversation.rb:227:in `determine_conversation_status'
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/controllers/api/v1/widget/base_controller.rb:24:in `create_conversation'
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/controllers/api/v1/widget/messages_controller.rb:46:in `set_conversation'
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails-1     | [e99182f7-75e5-4ca3-b221-5890a62b5d19] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'

### To Reproduce

Use the chat widget to chat. It gives an error while sending a message

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux CentOS 7

### Browser and version

Chrome or any browser

### Docker (if applicable)

Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:12:51 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:11:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by madanvparadkar** [comment]
I did not upgrade the database. After upgrading, it started working so closing the issue

**Comment by madanvparadkar** [comment]
I did not upgrade the database. After upgrading, it started working so closing the issue
