### ISSUE TITLE
Unable to download agent report 

### ISSUE THREAD

**Issue by Physicx101** [chatwoot/chatwoot#10220]
### Describe the bug

Upon trying to download agent report within Report -> Conversations or Report -> Agents, it throws a 500 internal server error. I have tried the other reports and they seem to be working just fine. Inspecting the browser console shows me this:

![image](https://github.com/user-attachments/assets/976f6d75-7dd8-4fd6-920b-e475b999d807)

### To Reproduce

1. Go to Reports then Conversations, or Reports then Agents
2. Click the green download agent report button

### Expected behavior

I should be able to get the report upon clicking the green download button

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Chrome, but it happens regardless of browser

**Comment by vishnu-narayanan** [comment]
@Physicx101 Please share the server logs.

**Comment by Physicx101** [comment]
@vishnu-narayanan Here are the logs: 
![image](https://github.com/user-attachments/assets/187b8ba1-c9f8-4b40-ad40-a283d627a587)
The locale that I'm using at the moment is "id"

**Comment by vishnu-narayanan** [comment]
@Physicx101 Could you share a bit more log on both sides as text?

**Comment by Physicx101** [comment]
@vishnu-narayanan I'm sorry but I'm not sure what you mean by both sides. But here it is as text:

```
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:15:36.705508 #356012] INFO -- : [13fefd41-a8f9-45ze-8c25-199898c4b96] Started GET "/api/v2/accounts/2/reports/agents?since=1727456400&until=1728061199" for 36.68.69.252 at 2024-10-04 09:15:36 +
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:15:36.709807 #356012] INFO -- : [13fefd41-a8f9-45ze-8c25-199898c4b96] Processing by Api::V2::Accounts::ReportsController#agents as JSON
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:15:36.709837 #356012] INFO -- : [13fefd41-a8f9-45ze-8c25-199898c4b96]   Parameters: {"since"=>"1727456400", "until"=>"1728061199", "account_id"=>"2"}
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: F, [2024-10-04T09:15:36.763472 #356012] FATAL -- : [13fefd41-a8f9-45ze-8c25-199898c4b96]   
I18n::InvalidPluralizationData (translation data {:others=>"%{count} hours"} can not be used with :count => 1. key 'one' is missing.):
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/presenters/reports/time_format_presenter.rb:31:in `each'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/presenters/reports/time_format_presenter.rb:31:in `map'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/helpers/api/v2/accounts/reports_helper.rb:54:in `generate_readable_report_metrics'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/helpers/api/v2/accounts/reports_helper.rb:53:in `block in generate_agents_report'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/controllers/api/v2/accounts/reports_controller.rb:22:in `agents'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/controllers/concerns/switch_locale.rb:39:in `set_locale'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/controllers/concerns/switch_locale.rb:39:in `switch_locale_using_account_locale'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: app/controllers/concerns/switch_locale.rb:23:in `handle_with_exception'
Oct 04 09:15:36 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:15:36.765952 #356012] INFO -- : source=rack-timeout id=13fefd41-a8f9-45ze-8c25-199898c4b96 timeout=15000ms service=54ms state=completed
Oct 04 09:15:55 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:15:55.370950 #356012] INFO -- : RoomChannel#update_presence 
Oct 04 09:16:16 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:16.101429 #356012] INFO -- : Finished channel PresenceChannel stopped streaming from RoomChannel
Oct 04 09:16:16 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:16.101789 #356012] INFO -- : RoomChannel stopped streaming for presence
Oct 04 09:16:21 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:21.184917 #356012] INFO -- : [ActionCable] [ab1189de-6935-4dfe-abba-99ae249a97b2] RoomChannel#update_presence 
Oct 04 09:16:41 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:41.010799 #356012] INFO -- : Finished channel PresenceChannel
Oct 04 09:16:41 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:41.010799 #356012] INFO -- : RoomChannel stopped streaming for presence
Oct 04 09:16:55 ubuntu-s-4vcpu-8gb-sgp1-01 chatwoot-web.1[356012]: I, [2024-10-04T09:16:55.387191 #356012] INFO -- : RoomChannel#update_presence 
```

**Comment by vishnu-narayanan** [comment]
@Physicx101 Thank you for reporting this. I have the PR https://github.com/chatwoot/chatwoot/pull/10228, which will fix this issue. This will be available in the Chatwoot October release.
