### ISSUE TITLE
Error in new article

### ISSUE THREAD

**Issue by Jaedson-Digiliza** [chatwoot/chatwoot#10351]
### Describe the bug

```
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] NoMethodError (undefined method `locale=' for an instance of Article):
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2]   
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/models/article.rb:147:in `add_locale_to_article'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/api/v1/accounts/articles_controller.rb:23:in `create'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/concerns/switch_locale.rb:17:in `switch_locale_using_account_locale'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails-1        | [d3e135ef-cb51-426b-95fe-e77dd9e141f2] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'

```

### To Reproduce

Enter in a previous existing portal and click on new article

### Environment

Docker

### Cloud Provider

Azure

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
Please share your chatwoot version and the locale of your portal.

**Comment by Jaedson-Digiliza** [comment]
3.14.1 and the locale is pt_BR

**Comment by Jaedson-Digiliza** [comment]
maybe an edge case, i just recreated database and it started working

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
