### ISSUE TITLE
Docker 1.7 db migration crash

### ISSUE THREAD

**Issue by xpayserver** [chatwoot/chatwoot#1142]
**Describe the bug**
I spend all night trying to deploy via docker but no luck as some postgres tables not created apparently. Docker compose is here: https://github.com/xpayserver/btcpayserver-docker/blob/a/docker-compose-generator/docker-fragments/opt-add-chatwoot.yml

First issue is if I have existing postgres container, I cannot make it create another database. Good practice is for the application to create the database if it can connect to db engine especially when postgres used as it not has syntax for `CREATE DATABASE IF NOT EXISTS chatwoot_db` . 

Also db name is `chatwoot_production` not `chatwoot` : just docs issue

Then, I create new postgres container (wasteful) dedicate to chatwoot but i get errors in postgres after connection:
```
2020-08-13 13:59:50.396 UTC [75] ERROR:  relation "installation_configs" does not exist at character 454
2020-08-13 13:59:50.396 UTC [75] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
               pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
               c.collname, col_description(a.attrelid, a.attnum) AS comment
          FROM pg_attribute a
          LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
          LEFT JOIN pg_type t ON a.atttypid = t.oid
          LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
         WHERE a.attrelid = '"installation_configs"'::regclass
           AND a.attnum > 0 AND NOT a.attisdropped
         ORDER BY a.attnum
```
and in chatwoot container log:
```
2020-08-13T13:59:26.666359982Z + rm -rf /app/tmp/pids/server.pid
2020-08-13T13:59:26.667406899Z + rm -rf /app/tmp/cache/assets /app/tmp/cache/bootsnap-compile-cache /app/tmp/cache/bootsnap-load-path-cache /app/tmp/cache/webpacker
2020-08-13T13:59:26.918005199Z + echo 'Waiting for postgres to become ready....'
2020-08-13T13:59:26.918044194Z + PGPASSWORD=
2020-08-13T13:59:26.918044471Z Waiting for postgres to become ready....
2020-08-13T13:59:26.918056799Z + PSQL='pg_isready -h chatwoot_postgres -p 5432 -U postgres'
2020-08-13T13:59:26.918088538Z + pg_isready -h chatwoot_postgres -p 5432 -U postgres
2020-08-13T13:59:26.937384446Z + echo 'Database ready to accept connections.'
2020-08-13T13:59:26.937422622Z + bundle install
2020-08-13T13:59:26.937560588Z chatwoot_postgres:5432 - accepting connections
2020-08-13T13:59:26.937576409Z Database ready to accept connections.
2020-08-13T13:59:27.625425476Z Using rake 13.0.1
2020-08-13T13:59:27.625470369Z Using concurrent-ruby 1.1.6
2020-08-13T13:59:27.625545684Z Using i18n 1.8.3
2020-08-13T13:59:27.625597375Z Using minitest 5.14.1
2020-08-13T13:59:27.625804742Z Using thread_safe 0.3.6
2020-08-13T13:59:27.625872592Z Using tzinfo 1.2.7
2020-08-13T13:59:27.626081123Z Using zeitwerk 2.3.0
2020-08-13T13:59:27.626150875Z Using activesupport 6.0.3.2
2020-08-13T13:59:27.626226299Z Using builder 3.2.4
2020-08-13T13:59:27.626321249Z Using erubi 1.9.0
2020-08-13T13:59:27.626459653Z Using mini_portile2 2.4.0
2020-08-13T13:59:27.626565483Z Using nokogiri 1.10.9
2020-08-13T13:59:27.626683706Z Using rails-dom-testing 2.0.3
2020-08-13T13:59:27.626760023Z Using crass 1.0.6
2020-08-13T13:59:27.626867854Z Using loofah 2.6.0
2020-08-13T13:59:27.626975274Z Using rails-html-sanitizer 1.3.0
2020-08-13T13:59:27.627102313Z Using actionview 6.0.3.2
2020-08-13T13:59:27.627210179Z Using rack 2.2.3
2020-08-13T13:59:27.627324580Z Using rack-test 1.1.0
2020-08-13T13:59:27.627398617Z Using actionpack 6.0.3.2
2020-08-13T13:59:27.627546195Z Using nio4r 2.5.2
2020-08-13T13:59:27.627744058Z Using websocket-extensions 0.1.5
2020-08-13T13:59:27.627939674Z Using websocket-driver 0.7.2
2020-08-13T13:59:27.628036924Z Using actioncable 6.0.3.2
2020-08-13T13:59:27.628140654Z Using globalid 0.4.2
2020-08-13T13:59:27.628226819Z Using activejob 6.0.3.2
2020-08-13T13:59:27.628390429Z Using activemodel 6.0.3.2
2020-08-13T13:59:27.628475093Z Using activerecord 6.0.3.2
2020-08-13T13:59:27.628600977Z Using mimemagic 0.3.5
2020-08-13T13:59:27.628830859Z Using marcel 0.3.3
2020-08-13T13:59:27.628939994Z Using activestorage 6.0.3.2
2020-08-13T13:59:27.629054190Z Using mini_mime 1.0.2
2020-08-13T13:59:27.629165235Z Using mail 2.7.1
2020-08-13T13:59:27.629309280Z Using actionmailbox 6.0.3.2
2020-08-13T13:59:27.629398016Z Using actionmailer 6.0.3.2
2020-08-13T13:59:27.629540564Z Using actiontext 6.0.3.2
2020-08-13T13:59:27.629710504Z Using acts-as-taggable-on 6.5.0
2020-08-13T13:59:27.630025950Z Using public_suffix 4.0.5
2020-08-13T13:59:27.630107990Z Using addressable 2.7.0
2020-08-13T13:59:27.630272458Z Using execjs 2.7.0
2020-08-13T13:59:27.630348984Z Using autoprefixer-rails 9.8.2
2020-08-13T13:59:27.630478764Z Using method_source 1.0.0
2020-08-13T13:59:27.630646015Z Using thor 1.0.1
2020-08-13T13:59:27.630758209Z Using railties 6.0.3.2
2020-08-13T13:59:27.630920194Z Using momentjs-rails 2.20.1
2020-08-13T13:59:27.631076921Z Using datetime_picker_rails 0.0.7
2020-08-13T13:59:27.631192227Z Using jquery-rails 4.4.0
2020-08-13T13:59:27.631331661Z Using kaminari-core 1.2.1
2020-08-13T13:59:27.631438720Z Using kaminari-actionview 1.2.1
2020-08-13T13:59:27.631622021Z Using kaminari-activerecord 1.2.1
2020-08-13T13:59:27.631715988Z Using kaminari 1.2.1
2020-08-13T13:59:27.631826535Z Using ffi 1.13.1
2020-08-13T13:59:27.631961021Z Using sassc 2.4.0
2020-08-13T13:59:27.632091336Z Using sprockets 3.7.2
2020-08-13T13:59:27.632242370Z Using sprockets-rails 3.2.1
2020-08-13T13:59:27.632371868Z Using tilt 2.0.10
2020-08-13T13:59:27.632624775Z Using sassc-rails 2.1.2
2020-08-13T13:59:27.632783220Z Using selectize-rails 0.12.6
2020-08-13T13:59:27.632916079Z Using administrate 0.13.0
2020-08-13T13:59:27.633021038Z Using ast 2.4.1
2020-08-13T13:59:27.633173722Z Using attr_extras 6.2.4
2020-08-13T13:59:27.633368578Z Using aws-eventstream 1.1.0
2020-08-13T13:59:27.633471776Z Using aws-partitions 1.332.0
2020-08-13T13:59:27.633587765Z Using aws-sigv4 1.2.0
2020-08-13T13:59:27.633741190Z Using jmespath 1.4.0
2020-08-13T13:59:27.633887522Z Using aws-sdk-core 3.100.0
2020-08-13T13:59:27.634104802Z Using aws-sdk-kms 1.34.1
2020-08-13T13:59:27.634235209Z Using aws-sdk-s3 1.69.1
2020-08-13T13:59:27.634419657Z Using descendants_tracker 0.0.4
2020-08-13T13:59:27.634577502Z Using ice_nine 0.11.2
2020-08-13T13:59:27.634690775Z Using axiom-types 0.1.1
2020-08-13T13:59:27.634876336Z Using multipart-post 2.1.1
2020-08-13T13:59:27.635101741Z Using faraday 1.0.1
2020-08-13T13:59:27.635231790Z Using faraday_middleware 1.0.0
2020-08-13T13:59:27.635374831Z Using azure-storage-common 2.0.1
2020-08-13T13:59:27.635489968Z Using azure-storage-blob 2.0.0
2020-08-13T13:59:27.635623372Z Using bcrypt 3.1.13
2020-08-13T13:59:27.635792411Z Using msgpack 1.3.3
2020-08-13T13:59:27.635983879Z Using bootsnap 1.4.6
2020-08-13T13:59:27.636096813Z Using brakeman 4.8.2
2020-08-13T13:59:27.636218409Z Using browser 4.2.0
2020-08-13T13:59:27.636356011Z Using bundler 2.1.4
2020-08-13T13:59:27.636475989Z Using coercible 1.0.0
2020-08-13T13:59:27.636607647Z Using connection_pool 2.2.3
2020-08-13T13:59:27.636760646Z Using declarative 0.0.10
2020-08-13T13:59:27.636878449Z Using declarative-option 0.1.0
2020-08-13T13:59:27.637017037Z Using orm_adapter 0.5.0
2020-08-13T13:59:27.637160089Z Using responders 3.0.1
2020-08-13T13:59:27.637441319Z Using warden 1.2.8
2020-08-13T13:59:27.637596657Z Using devise 4.7.2
2020-08-13T13:59:27.637773153Z Using rails 6.0.3.2
2020-08-13T13:59:27.637944123Z Using devise_token_auth 1.1.4
2020-08-13T13:59:27.638132032Z Using digest-crc 0.5.1
2020-08-13T13:59:27.638240742Z Using unf_ext 0.0.7.7
2020-08-13T13:59:27.638531703Z Using unf 0.1.4
2020-08-13T13:59:27.638633518Z Using domain_name 0.5.20190701
2020-08-13T13:59:27.638775380Z Using dotenv 2.7.5
2020-08-13T13:59:27.638897971Z Using dotenv-rails 2.7.5
2020-08-13T13:59:27.639064604Z Using equalizer 0.0.11
2020-08-13T13:59:27.639269223Z Using mime-types-data 3.2020.0512
2020-08-13T13:59:27.639378103Z Using mime-types 3.3.1
2020-08-13T13:59:27.639523110Z Using multi_xml 0.6.0
2020-08-13T13:59:27.639667663Z Using httparty 0.18.1
2020-08-13T13:59:27.639882797Z Using facebook-messenger 1.5.0
2020-08-13T13:59:27.640018400Z Using fcm 1.0.1
2020-08-13T13:59:27.640158303Z Using flag_shih_tzu 0.3.23
2020-08-13T13:59:27.640288764Z Using foreman 0.87.1
2020-08-13T13:59:27.640423791Z Using gli 2.19.1
2020-08-13T13:59:27.640566564Z Using jwt 2.2.1
2020-08-13T13:59:27.640711578Z Using memoist 0.16.2
2020-08-13T13:59:27.641008321Z Using multi_json 1.14.1
2020-08-13T13:59:27.641161224Z Using os 1.1.0
2020-08-13T13:59:27.641364464Z Using signet 0.14.0
2020-08-13T13:59:27.641497593Z Using googleauth 0.13.0
2020-08-13T13:59:27.641633209Z Using httpclient 2.8.3
2020-08-13T13:59:27.641967332Z Using uber 0.1.0
2020-08-13T13:59:27.642422219Z Using representable 3.0.4
2020-08-13T13:59:27.642557304Z Using retriable 3.1.2
2020-08-13T13:59:27.642858889Z Using google-api-client 0.41.0
2020-08-13T13:59:27.643140294Z Using google-cloud-env 1.3.2
2020-08-13T13:59:27.643423909Z Using google-cloud-errors 1.0.1
2020-08-13T13:59:27.643707082Z Using google-cloud-core 1.5.0
2020-08-13T13:59:27.644086052Z Using google-cloud-storage 1.26.2
2020-08-13T13:59:27.644381339Z Using groupdate 5.0.0
2020-08-13T13:59:27.644649940Z Using haikunator 1.1.0
2020-08-13T13:59:27.644982425Z Using hashie 4.1.0
2020-08-13T13:59:27.645327055Z Using hkdf 0.3.0
2020-08-13T13:59:27.645691832Z Using http-accept 1.7.0
2020-08-13T13:59:27.646018873Z Using http-cookie 1.0.3
2020-08-13T13:59:27.646306273Z Using inflecto 0.0.2
2020-08-13T13:59:27.646615640Z Using jbuilder 2.10.0
2020-08-13T13:59:27.646916245Z Using json 2.3.0
2020-08-13T13:59:27.647217643Z Using koala 3.0.0
2020-08-13T13:59:27.647576624Z Using liquid 4.0.3
2020-08-13T13:59:27.647931120Z Using mini_magick 4.10.1
2020-08-13T13:59:27.648238685Z Using netrc 0.11.0
2020-08-13T13:59:27.648514571Z Using oauth 0.5.4
2020-08-13T13:59:27.648851093Z Using parser 2.7.1.4
2020-08-13T13:59:27.649287094Z Using pg 1.2.3
2020-08-13T13:59:27.649561762Z Using puma 4.3.5
2020-08-13T13:59:27.649896451Z Using pundit 2.1.0
2020-08-13T13:59:27.650198494Z Using rack-cache 1.12.0
2020-08-13T13:59:27.650473996Z Using rack-cors 1.1.1
2020-08-13T13:59:27.650879004Z Using rack-protection 2.0.8.1
2020-08-13T13:59:27.651101224Z Using rack-proxy 0.6.5
2020-08-13T13:59:27.651396594Z Using redis 4.2.1
2020-08-13T13:59:27.651743837Z Using redis-namespace 1.7.0
2020-08-13T13:59:27.651978732Z Using redis-store 1.9.0
2020-08-13T13:59:27.652285564Z Using redis-rack-cache 2.2.1
2020-08-13T13:59:27.652621535Z Using rest-client 2.1.0
2020-08-13T13:59:27.653013453Z Using scout_apm 2.6.7
2020-08-13T13:59:27.653340003Z Using semantic_range 2.3.0
2020-08-13T13:59:27.653731108Z Using sentry-raven 3.0.0
2020-08-13T13:59:27.654085635Z Using sidekiq 6.0.7
2020-08-13T13:59:27.654427573Z Using slack-ruby-client 0.14.6
2020-08-13T13:59:27.654799619Z Using virtus 1.0.5
2020-08-13T13:59:27.655258013Z Using telegram-bot-ruby 0.12.0
2020-08-13T13:59:27.655599088Z Using telephone_number 1.4.7
2020-08-13T13:59:27.655926174Z Using time_diff 0.3.0
2020-08-13T13:59:27.656282076Z Using twilio-ruby 5.32.0
2020-08-13T13:59:27.656732886Z Using twitty 0.1.1
2020-08-13T13:59:27.657101865Z Using tzinfo-data 1.2020.1
2020-08-13T13:59:27.657525129Z Using uglifier 4.2.0
2020-08-13T13:59:27.657873998Z Using valid_email2 3.2.2
2020-08-13T13:59:27.658270926Z Using webpacker 5.1.1
2020-08-13T13:59:27.658607279Z Using webpush 1.0.0
2020-08-13T13:59:27.659073095Z Using wisper 2.0.0
2020-08-13T13:59:27.678646171Z Bundle complete! 77 Gemfile dependencies, 167 gems now installed.
2020-08-13T13:59:27.678675402Z Gems in the groups development and test were not installed.
2020-08-13T13:59:27.678791325Z Bundled gems are installed into `/gems`
2020-08-13T13:59:27.687421507Z + BUNDLE='bundle check'
2020-08-13T13:59:27.687461054Z + bundle check
2020-08-13T13:59:28.114265962Z The Gemfile's dependencies are satisfied
2020-08-13T13:59:28.120703991Z + exec bundle exec rails s -p 3000 -b 0.0.0.0
2020-08-13T13:59:34.930216088Z => Booting Puma
2020-08-13T13:59:34.930263914Z => Rails 6.0.3.2 application starting in production
2020-08-13T13:59:34.930271140Z => Run `rails server --help` for more startup options
2020-08-13T13:59:35.371160288Z `Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
2020-08-13T13:59:36.639280396Z FlagShihTzu#has_flags: Table "notification_settings" doesn't exist.  Have all migrations been run?
2020-08-13T13:59:36.639367346Z FlagShihTzu says: Flag column email_flags appears to be missing!
2020-08-13T13:59:36.639382154Z To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/notification_setting.rb:32:in `<class:NotificationSetting>'
2020-08-13T13:59:36.640237346Z FlagShihTzu#has_flags: Table "notification_settings" doesn't exist.  Have all migrations been run?
2020-08-13T13:59:36.640385233Z FlagShihTzu says: Flag column push_flags appears to be missing!
2020-08-13T13:59:36.640399383Z To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/notification_setting.rb:33:in `<class:NotificationSetting>'
2020-08-13T13:59:36.682217073Z FlagShihTzu#has_flags: Table "accounts" doesn't exist.  Have all migrations been run?
2020-08-13T13:59:36.682266168Z FlagShihTzu says: Flag column feature_flags appears to be missing!
2020-08-13T13:59:36.682274744Z To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/concerns/featurable.rb:16:in `block in <module:Featurable>'
2020-08-13T13:59:36.704023008Z FlagShihTzu#has_flags: Table "accounts" doesn't exist.  Have all migrations been run?
2020-08-13T13:59:36.704272554Z FlagShihTzu says: Flag column settings_flags appears to be missing!
2020-08-13T13:59:36.704293194Z To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/account.rb:53:in `<class:Account>'
2020-08-13T13:59:36.952741133Z FlagShihTzu#has_flags: Table "channel_web_widgets" doesn't exist.  Have all migrations been run?
2020-08-13T13:59:36.952851142Z FlagShihTzu says: Flag column feature_flags appears to be missing!
2020-08-13T13:59:36.952875453Z To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/channel/web_widget.rb:32:in `<class:WebWidget>'
2020-08-13T13:59:50.248254992Z I, [2020-08-13T13:59:35.371817 #1]  INFO -- : Raven 3.0.0 configured not to capture errors: DSN not set
2020-08-13T13:59:50.248312899Z W, [2020-08-13T13:59:36.726354 #1]  WARN -- : Creating scope :open. Overwriting existing method Conversation.open.
2020-08-13T13:59:50.248320359Z Puma starting in single mode...
2020-08-13T13:59:50.248324666Z * Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
2020-08-13T13:59:50.248328800Z * Min threads: 5, max threads: 5
2020-08-13T13:59:50.248333713Z * Environment: production
2020-08-13T13:59:50.248337732Z * Listening on tcp://0.0.0.0:3000
2020-08-13T13:59:50.248341726Z Use Ctrl-C to stop
2020-08-13T13:59:50.336662597Z I, [2020-08-13T13:59:50.336340 #1]  INFO -- : [e9be0338-b857-4beb-b18f-0276c5cff65a] Started GET "/" for 77.71.239.8 at 2020-08-13 13:59:50 +0000
2020-08-13T13:59:50.340685572Z I, [2020-08-13T13:59:50.340418 #1]  INFO -- : [e9be0338-b857-4beb-b18f-0276c5cff65a] Processing by DashboardController#index as HTML
2020-08-13T13:59:50.397887003Z I, [2020-08-13T13:59:50.397650 #1]  INFO -- : [e9be0338-b857-4beb-b18f-0276c5cff65a] Completed 500 Internal Server Error in 57ms (ActiveRecord: 6.9ms | Allocations: 2521)
2020-08-13T13:59:50.399523184Z F, [2020-08-13T13:59:50.399357 #1] FATAL -- : [e9be0338-b857-4beb-b18f-0276c5cff65a]
2020-08-13T13:59:50.399547456Z [e9be0338-b857-4beb-b18f-0276c5cff65a] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "installation_configs" does not exist
2020-08-13T13:59:50.399553357Z LINE 8:  WHERE a.attrelid = '"installation_configs"'::regclass
2020-08-13T13:59:50.399557554Z                             ^
2020-08-13T13:59:50.399561413Z ):
2020-08-13T13:59:50.399565043Z [e9be0338-b857-4beb-b18f-0276c5cff65a]
2020-08-13T13:59:50.399568951Z [e9be0338-b857-4beb-b18f-0276c5cff65a] app/models/installation_config.rb:20:in `block in <class:InstallationConfig>'
2020-08-13T13:59:50.399573526Z [e9be0338-b857-4beb-b18f-0276c5cff65a] lib/global_config.rb:41:in `db_fallback'
2020-08-13T13:59:50.399577641Z [e9be0338-b857-4beb-b18f-0276c5cff65a] lib/global_config.rb:32:in `load_from_cache'
2020-08-13T13:59:50.399581464Z [e9be0338-b857-4beb-b18f-0276c5cff65a] lib/global_config.rb:12:in `block in get'
2020-08-13T13:59:50.399585301Z [e9be0338-b857-4beb-b18f-0276c5cff65a] lib/global_config.rb:11:in `each'
2020-08-13T13:59:50.399589107Z [e9be0338-b857-4beb-b18f-0276c5cff65a] lib/global_config.rb:11:in `get'
2020-08-13T13:59:50.399592862Z [e9be0338-b857-4beb-b18f-0276c5cff65a] app/controllers/dashboard_controller.rb:11:in `set_global_config'
```

**Expected behavior**

**Desktop (please complete the following information):**
Ubuntu w Docker & compose

**Smartphone (please complete the following information):**
N/A

**Comment by xpayserver** [comment]
I have fix by running ` docker exec -ti chatwoot sh -c "export DISABLE_DATABASE_ENVIRONMENT_CHECK=1 && bundle exec rails db:reset"`

But no way to have db set up automatically on first load?

**Comment by pranavrajs** [comment]
@xpayserver Sorry about this experience. Are you trying to upgrade the server from 1.6 to 1.7 or are trying to do a fresh install?

**Comment by xpayserver** [comment]
> @xpayserver Sorry about this experience. Are you trying to upgrade the server from 1.6 to 1.7 or are trying to do a fresh install?

it ok, I greatly appreciate FOSS. fresh install

**Comment by sojan-official** [comment]
we have updated docker deployment guides: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker . 
We will continue our work on documentation further.
