### ISSUE TITLE
enhancement: Add validation error for label create modal

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1298]
# Enhancement 

Label names in chatwoot only support alphabets, numbers, hyphen and underscore.  
At the moment the available validation doesn't show the user any errors, which would leave the user confused. 

So let's add a validation error describing this behaviour

### Current behaviour
<img width="1273" alt="Screenshot 2020-10-02 at 4 29 03 PM" src="https://user-images.githubusercontent.com/73185/94916498-66d4e580-04cc-11eb-859d-6de5dea0a4e0.png">

### Expected

<img width="1368" alt="Screenshot 2020-10-02 at 4 26 55 PM" src="https://user-images.githubusercontent.com/73185/94916344-26756780-04cc-11eb-85c0-042087a9232b.png">

**Comment by m4tr1k** [comment]
@sojan-official Hi! Can I work on this issue please?

**Comment by sojan-official** [comment]
@m4tr1k sure. let us know if you need any help :)

**Comment by m4tr1k** [comment]
@sojan-official the setup is quite a ride 😅 

when running `bundle exec rake db:create` it shows an error:
```
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
Couldn't create 'chatwoot_dev' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:189:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:126:in `create'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

I don't know what to do next... Can you help me please?

**Comment by m4tr1k** [comment]
Also I changed ruby version on Gemfile to 2.6.3 to run `bundle`, I don't know if has any implications....

**Comment by sojan-official** [comment]
@m4tr1k  do you have Postgres installed on the machine and running on port 5432 ?  
Could you also check whether the Postgres credentials provided in .env file is the correct ones ? 

the app should work with `2.6.3` as well.

**Comment by m4tr1k** [comment]
@sojan-official you're talking about these credentials?
![image](https://user-images.githubusercontent.com/12871065/94929275-c4613600-04bc-11eb-9d46-462be2ced040.png)

I'm not used to working with Ruby and Postgres, although I already verified that I have Postgres installed on the machine.

**Comment by sojan-official** [comment]
@m4tr1k  no worries, could you also check whether Postgres server is running? if you installed Postgres via brew you could restart  via `brew services restart postgres`

**Comment by m4tr1k** [comment]
@sojan-official 
![image](https://user-images.githubusercontent.com/12871065/94929970-acd67d00-04bd-11eb-8a45-470ef6cf4efe.png)

postgres server is now running? Or do I need to do something in order to check it?

**Comment by sojan-official** [comment]
@m4tr1k  no this should be good. you can now continue with the commands.

**Comment by m4tr1k** [comment]
@sojan-official running `bundle exec rake db:create` still gives the error, this time with the database creation
```
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
FATAL:  role "admin" does not exist
Couldn't create 'chatwoot_production' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: FATAL:  role "admin" does not exist
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/connection_handling.rb:189:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:126:in `create'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

**Comment by sojan-official** [comment]
@m4tr1k seems like the Postgres user and role is missing with the installation. could you try https://stackoverflow.com/a/35308200/939299

**Comment by m4tr1k** [comment]
@sojan-official sorry for the late response and for being quite annoying with this situation
Your link helped a bit and I am able to create the database now. Also I can't use `admin` as username, I have to use my username to create the database.
But running the reset command it gives me this error:

```
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
Dropped database 'chatwoot_production'
Dropped database 'chatwoot_production'
Created database 'chatwoot_production'
Database 'chatwoot_production' already exists
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:617:in `block in keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:616:in `keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:476:in `call_with_namespace'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:289:in `keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/lib/global_config.rb:19:in `clear_cache'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/db/seeds.rb:2:in `<main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.3/lib/rails/engine.rb:559:in `load_seed'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
SocketError: getaddrinfo: nodename nor servname provided, or not known
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/connection/ruby.rb:189:in `getaddrinfo'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/connection/ruby.rb:189:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/connection/ruby.rb:299:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:349:in `establish_connection'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:617:in `block in keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-4.2.1/lib/redis.rb:616:in `keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:476:in `call_with_namespace'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.8.0/lib/redis/namespace.rb:289:in `keys'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/lib/global_config.rb:19:in `clear_cache'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/db/seeds.rb:2:in `<main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.3/lib/rails/engine.rb:559:in `load_seed'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.3/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/Users/franfernandes88/Desktop/hacktoberfest/chatwoot/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
```

**Comment by m4tr1k** [comment]
@sojan-official I found out that I forgot to set up a variable in the env file and I can now host in localhost:3000

But it is giving me this error:
![image](https://user-images.githubusercontent.com/12871065/94954018-5dee0f00-04e0-11eb-9e03-9715e60e93b3.png)

**Comment by m4tr1k** [comment]
@sojan-official I figure it out and it's now working! Thanks for your patience and now it's time to work on the issue 😆
