### ISSUE TITLE
Conversation continuity doesn't work

### ISSUE THREAD

**Issue by KonstantinReido** [chatwoot/chatwoot#1425]
**Describe the bug**

I tried to configure "Conversation continuity" by this [instration](https://www.chatwoot.com/docs/conversation-continuity) but:
1) found that the system expects that will be set MAILGUN_INGRESS_API_KEY, not MAILGUN_INGRESS_SIGNING_KEY
2) when the system receives an email from Mailgun it generates an error (logs below)

**To Reproduce**

1. Setup "Conversation continuity" by this [instration](https://www.chatwoot.com/docs/conversation-continuity)
2. Send email on the address specified on the previous step
3. Open Sidekiq or server logs

**Expected behavior**

I assume it should work without errors.

**Server logs**

```
app[worker.1]: E, [2020-11-17T20:45:33.118713 #4] ERROR -- : [ActiveJob] [ActionMailbox::RoutingJob] [0341536d-10f5-41e4-99b7-d387bf672778] Error performing ActionMailbox::RoutingJob (Job ID: 0341536d-10f5-41e4-99b7-d387bf672778) from Sidekiq(action_mailbox_routing) in 138.58ms: NoMethodError (undefined method `each' for nil:NilClass):
app[worker.1]: /app/app/mailboxes/application_mailbox.rb:9:in `block in reply_mail?'
app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionmailbox-6.0.3.4/lib/action_mailbox/router/route.rb:25:in `match?'
...
app[worker.1]: pid=4 tid=30d8 class=ActionMailbox::RoutingJob jid=a678fd41d62c81e4a23f45f1 elapsed=0.145 INFO: fail
app[worker.1]: pid=4 tid=30d8 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"action_mailbox_routing","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailbox::RoutingJob","args":[{"job_class":"ActionMailbox::RoutingJob","job_id":"0341536d-10f5-41e4-99b7-d387bf672778","provider_job_id":null,"queue_name":"action_mailbox_routing","priority":null,"arguments":[{"_aj_globalid":"gid://chatwoot/ActionMailbox::InboundEmail/11"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2020-11-17T20:45:32Z"}],"jid":"a678fd41d62c81e4a23f45f1","created_at":1605645932.97048,"enqueued_at":1605645932.9705355},"jobstr":"{\"retry\":true,\"queue\":\"action_mailbox_routing\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailbox::RoutingJob\",\"args\":[{\"job_class\":\"ActionMailbox::RoutingJob\",\"job_id\":\"0341536d-10f5-41e4-99b7-d387bf672778\",\"provider_job_id\":null,\"queue_name\":\"action_mailbox_routing\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/ActionMailbox::InboundEmail/11\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2020-11-17T20:45:32Z\"}],\"jid\":\"a678fd41d62c81e4a23f45f1\",\"created_at\":1605645932.97048,\"enqueued_at\":1605645932.9705355}"}
app[worker.1]: pid=4 tid=30d8 WARN: NoMethodError: undefined method `each' for nil:NilClass
app[worker.1]: pid=4 tid=30d8 WARN: /app/app/mailboxes/application_mailbox.rb:9:in `block in reply_mail?'
app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionmailbox-6.0.3.4/lib/action_mailbox/router/route.rb:25:in `match?'
```

**Environment**

A self hosted installation of Chatwoot (Heroku)

**Additional context**

MAILGUN_INGRESS_SIGNING_KEY: https://edgeguides.rubyonrails.org/action_mailbox_basics.html#mailgun
MAILGUN_INGRESS_API_KEY: https://api.rubyonrails.org/classes/ActionMailbox/Ingresses/Mailgun/InboundEmailsController.html

```
About your application's environment
Rails version             6.0.3.4
Ruby version              ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
RubyGems version          3.1.2
Rack version              2.2.3
JavaScript Runtime        Node.js (V8)
Middleware                Raven::Rack, Rack::Cors, ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Warden::Manager, ScoutApm::Middleware
Application root          /app
Environment               production
Database adapter          postgresql
```

**Comment by pranavrajs** [comment]
@KonstantinReido I guess this is probably a setup error. @sony-mathew Can you please take a look at this?

**Comment by sony-mathew** [comment]
@KonstantinReido Does the email continuity work with the new environment variable `MAILGUN_INGRESS_API_KEY` set? 

I guess this gap is due to a missed documentation when Rails version was upgraded. We will create a task to update the documentation and thanks for bringing this up to our notice.

**Comment by KonstantinReido** [comment]
@sony-mathew with this environment variable I start to receive requests from Mailgun but facing with the second issue in Sidekiq (you can see logs above)

**Comment by sony-mathew** [comment]
@KonstantinReido Cool. I will test the email continuity with Mailgun and get back to you. Expect some delay for this.

**Comment by kgdev** [comment]
In app/builders/contact_builder.rb, we should change

      contact = account.contacts.create!(

to

      contact = account.contacts.find_by(email: contact_attributes[:email])
      contact ||= account.contacts.create!(

**Comment by sojan-official** [comment]
@kgdev  thanks for looking into this. Equivalent change for this has been committed to develop via https://github.com/chatwoot/chatwoot/commit/13073629bb2412ef6fc0e112485aa70f891f496d

this should be fixed now v1.12.0

**Comment by orlando** [comment]
Here's a PR to fix the Mailgun env variable in the docs https://github.com/chatwoot/docs/pull/4
