### ISSUE TITLE
Unable to start webpack-dev-server

### ISSUE THREAD

**Issue by the-spectator** [chatwoot/chatwoot#148]
### Steps to reproduce
1. Fresh clone chatwoot application
2. yarn install
3. ./bin/webpack-dev-server

### Expected behavior
The webpack-dev-server starts without error

### Actual behaviour
The web-dev-server fails with following error message:
```
ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/akshay/personal-projects/open-source/my-forks/chatwoot/app/javascript/packs/application.js: Invalid Option: corejs is not a valid top-level option.
        Maybe you meant to use 'targets'? (While processing: "/home/akshay/personal-projects/open-source/my-forks/chatwoot/babel.config.js$0")
    at validateTopLevelOptions (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/preset-env/lib/normalize-options.js:49:13)
    at normalizeOptions (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/preset-env/lib/normalize-options.js:160:3)
    at /home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/preset-env/lib/index.js:168:37
    at /home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/full.js:167:14
    at cachedFunction (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/full.js:257:36)
    at /home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/full.js:79:21
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/full.js:76:38)
    at loadFullConfig (/home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/config/full.js:110:6)
    at /home/akshay/personal-projects/open-source/my-forks/chatwoot/node_modules/@babel/core/lib/transform.js:28:33
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
### Other information
Node version: **v12.6.0** with nvm
Yarn version: **v1.19.1**
Issue reproduced at: master, 01b72ca05142eadd39142b66a91724f73bc4d86d
Os: **Ubuntu 18.04**

**Comment by pranavrajs** [comment]
@the-spectator Please see the latest master branch, the command should be working.

**Comment by the-spectator** [comment]
@pranavrajs I have tested on the master branch and it is working now :tada:
