### ISSUE TITLE
Can't receive message on slack side, undefined method `id`

### ISSUE THREAD

**Issue by lgezyxr** [chatwoot/chatwoot#1549]
Hello, I just deployed chatwoot on my k8s cluster. I setup the slack integration but no message came out. I checked the log and it says 

> E, [2020-12-24T10:26:06.375546 #1] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"zV2vfiwKMgbQZ18tXCJhULDw\"}", "data"=>"{\"action\":\"update_presence\"}"}) [NoMethodError - undefined method `id' for nil:NilClass]: /app/app/channels/room_channel.rb:29:in `update_subscription' | /app/app/channels/room_channel.rb:11:in `update_presence' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:270:in `public_send' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:270:in `dispatch_action' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:170:in `block in perform_action'

Can anyone help me with this error?

**Comment by lgezyxr** [comment]
looks like it failed because of slack channel wasn't successfully created.

> F, [2020-12-24T11:04:12.274434 #1] FATAL -- : [e3b3efc6f9beec99342c5b8b8c4ff0ab]   
[e3b3efc6f9beec99342c5b8b8c4ff0ab] Slack::Web::Api::Errors::NameTaken (name_taken):
[e3b3efc6f9beec99342c5b8b8c4ff0ab]   
[e3b3efc6f9beec99342c5b8b8c4ff0ab] lib/integrations/slack/channel_builder.rb:25:in `find_or_create_channel'
[e3b3efc6f9beec99342c5b8b8c4ff0ab] lib/integrations/slack/channel_builder.rb:9:in `perform'
[e3b3efc6f9beec99342c5b8b8c4ff0ab] app/controllers/api/v1/accounts/integrations/slack_controller.rb:36:in `create_chatwoot_slack_channel'
[e3b3efc6f9beec99342c5b8b8c4ff0ab] app/controllers/api/v1/accounts/integrations/slack_controller.rb:11:in `create'
[e3b3efc6f9beec99342c5b8b8c4ff0ab] app/controllers/application_controller.rb:17:in `handle_with_exception'
[e3b3efc6f9beec99342c5b8b8c4ff0ab] app/controllers/application_controller.rb:82:in `switch_locale'

**Comment by pranavrajs** [comment]
@lgezyxr Do you have a slack channel named #customer-conversations already which is private? Slack integration works with public channels only.

**Comment by lgezyxr** [comment]
> @lgezyxr Do you have a slack channel named #customer-conversations already which is private? Slack integration works with public channels only.

I have the channel but its public. I've used official chatwoot for test before this deployment and that created one channel for me. I delete the old chatwoot bot and also rename the self-host version chatwoot app to chatwoottest in slack so it won't have conflict.

**Comment by lgezyxr** [comment]
I also find that, in the integrate page of webapp, after I click on "slack->connect", it will show an install prompt from slack, and after I click "allow", it will come back to the integrate page and receive a 500 http error from slack.

**Comment by pranavrajs** [comment]
@lgezyxr It looks like the slack channel is not listed in the API. Is it happening on Chatwoot cloud or your self hosted installation?

**Comment by lgezyxr** [comment]
Its my self hosted installation

**Comment by pranavrajs** [comment]
@lgezyxr Can you please share the entire logs from the time you try to connect the Slack account -> redirect from slack from auth?

**Comment by lgezyxr** [comment]
```
I, [2020-12-28T05:46:54.791853 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee] Started GET "/app/accounts/1/settings/integrations/slack?code=23384775268.160115685cc56b29157b658eb04484ba4f816e4fcc60c9bba623d5db9b13&state=" for 10.4.28.103 at 2020-12-28 05:46:54 +0000
I, [2020-12-28T05:46:54.792923 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee] Processing by DashboardController#index as HTML
I, [2020-12-28T05:46:54.792998 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee]   Parameters: {"code"=>"23384775268.1601155b1065cc56b29157b658eb04484ba4f816e4fcc60c9bba623d5db9b13", "state"=>"", "params"=>"accounts/1/settings/integrations/slack"}
I, [2020-12-28T05:46:54.796600 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee]   Rendering dashboard/index.html.erb within layouts/vueapp
I, [2020-12-28T05:46:54.796789 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.1ms | Allocations: 4)
I, [2020-12-28T05:46:54.798937 #1]  INFO -- : [3ae2dbeea2278d32355ada203ce07bee] Completed 200 OK in 6ms (Views: 2.6ms | ActiveRecord: 0.0ms | Allocations: 2213)
I, [2020-12-28T05:46:55.489902 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b] Started GET "/api/v1/accounts/1/integrations/apps" for 10.4.38.150 at 2020-12-28 05:46:55 +0000
I, [2020-12-28T05:46:55.491511 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b] Processing by Api::V1::Accounts::Integrations::AppsController#index as JSON
I, [2020-12-28T05:46:55.493216 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b]   Parameters: {"account_id"=>"1"}
I, [2020-12-28T05:46:55.493099 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a] Started GET "/api/v1/accounts/1/inboxes" for 10.4.28.103 at 2020-12-28 05:46:55 +0000
I, [2020-12-28T05:46:55.495170 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a] Processing by Api::V1::Accounts::InboxesController#index as JSON
I, [2020-12-28T05:46:55.495431 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a]   Parameters: {"account_id"=>"1"}
I, [2020-12-28T05:46:55.493856 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5] Started GET "/api/v1/accounts/1/" for 10.4.13.147 at 2020-12-28 05:46:55 +0000
I, [2020-12-28T05:46:55.497063 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5] Processing by Api::V1::AccountsController#show as JSON
I, [2020-12-28T05:46:55.492723 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157] Started GET "/auth/validate_token" for 10.4.28.103 at 2020-12-28 05:46:55 +0000
I, [2020-12-28T05:46:55.497911 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157] Processing by DeviseOverrides::TokenValidationsController#validate_token as HTML
I, [2020-12-28T05:46:55.498012 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5]   Parameters: {"id"=>"1"}
I, [2020-12-28T05:46:55.490420 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5] Started GET "/api/v1/accounts/1/labels" for 10.4.13.147 at 2020-12-28 05:46:55 +0000
I, [2020-12-28T05:46:55.499826 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5] Processing by Api::V1::Accounts::LabelsController#index as JSON
I, [2020-12-28T05:46:55.499983 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5]   Parameters: {"account_id"=>"1"}
I, [2020-12-28T05:46:55.509456 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157]   Rendering devise/token.json.jbuilder
I, [2020-12-28T05:46:55.529869 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a]   Rendering api/v1/accounts/inboxes/index.json.jbuilder
I, [2020-12-28T05:46:55.546351 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5]   Rendering api/v1/accounts/show.json.jbuilder
I, [2020-12-28T05:46:55.546912 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5]   Rendered api/v1/accounts/show.json.jbuilder (Duration: 0.4ms | Allocations: 190)
I, [2020-12-28T05:46:55.566421 #1]  INFO -- : [ce1e9e440cbf18bce082baf79939d3a5] Completed 200 OK in 68ms (Views: 1.5ms | ActiveRecord: 55.9ms | Allocations: 9600)
I, [2020-12-28T05:46:55.586560 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a]   Rendered api/v1/models/_inbox.json.jbuilder (Duration: 0.5ms | Allocations: 162)
I, [2020-12-28T05:46:55.586986 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a]   Rendered api/v1/accounts/inboxes/index.json.jbuilder (Duration: 57.0ms | Allocations: 2675)
I, [2020-12-28T05:46:55.607110 #1]  INFO -- : [cf82cd1ed4b9674a74b7d400e0efd18a] Completed 200 OK in 112ms (Views: 4.6ms | ActiveRecord: 95.1ms | Allocations: 12214)
I, [2020-12-28T05:46:55.626474 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157]   Rendered api/v1/models/_user.json.jbuilder (Duration: 112.8ms | Allocations: 6352)
I, [2020-12-28T05:46:55.626595 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157]   Rendered devise/_auth.json.jbuilder (Duration: 113.1ms | Allocations: 6438)
I, [2020-12-28T05:46:55.626927 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157]   Rendered devise/token.json.jbuilder (Duration: 113.8ms | Allocations: 6935)
I, [2020-12-28T05:46:55.646084 #1]  INFO -- : [206095afb516ba4aa699392dcbc1d157] Completed 200 OK in 147ms (Views: 79.6ms | ActiveRecord: 59.8ms | Allocations: 12617)
I, [2020-12-28T05:46:56.056431 #1]  INFO -- : [fe81a9ea8cc725ec46af28a5b261f121] Started GET "/cable" for 10.4.28.103 at 2020-12-28 05:46:56 +0000
I, [2020-12-28T05:46:56.056982 #1]  INFO -- : [fe81a9ea8cc725ec46af28a5b261f121] Started GET "/cable/" [WebSocket] for 10.4.10.10 at 2020-12-28 05:46:56 +0000
I, [2020-12-28T05:46:56.057084 #1]  INFO -- : [fe81a9ea8cc725ec46af28a5b261f121] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
I, [2020-12-28T05:46:56.249486 #1]  INFO -- : RoomChannel is streaming from mD34WgN34mtc4gv5CdzoPui8
I, [2020-12-28T05:46:56.264598 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b]   Rendering api/v1/accounts/integrations/apps/index.json.jbuilder
I, [2020-12-28T05:46:56.303603 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b]   Rendered api/v1/accounts/integrations/apps/index.json.jbuilder (Duration: 38.8ms | Allocations: 1057)
I, [2020-12-28T05:46:56.323540 #1]  INFO -- : [80b3cc04bc2ec5679414f19df83ac36b] Completed 200 OK in 829ms (Views: 2.9ms | ActiveRecord: 812.1ms | Allocations: 17546)
I, [2020-12-28T05:46:56.326617 #1]  INFO -- : RoomChannel is transmitting the subscription confirmation
I, [2020-12-28T05:46:56.526629 #1]  INFO -- : [2737ccd3813d3cdb3494790de871bf7c] Started POST "/api/v1/accounts/1/integrations/slack" for 10.4.13.147 at 2020-12-28 05:46:56 +0000
I, [2020-12-28T05:46:56.528021 #1]  INFO -- : [2737ccd3813d3cdb3494790de871bf7c] Processing by Api::V1::Accounts::Integrations::SlackController#create as JSON
I, [2020-12-28T05:46:56.528108 #1]  INFO -- : [2737ccd3813d3cdb3494790de871bf7c]   Parameters: {"code"=>"23384775268.1601156845cc56b29157b658eb04484ba4f816e4fcc60c9bba623d5db9b13", "account_id"=>"1", "slack"=>{"code"=>"233847752684ba4f816e4fcc60c9bba623d5db9b13"}}
W, [2020-12-28T05:46:56.528535 #1]  WARN -- : [2737ccd3813d3cdb3494790de871bf7c] HTTP Origin header (https://chatwoot.dev.lgezyxr.com) didn't match request.base_url (http://chatwoot.dev.lgezyxr.com)
I, [2020-12-28T05:46:57.390145 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5]   Rendering api/v1/accounts/labels/index.json.jbuilder
I, [2020-12-28T05:46:57.441275 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5]   Rendered api/v1/accounts/labels/index.json.jbuilder (Duration: 51.0ms | Allocations: 17244)
I, [2020-12-28T05:46:57.468936 #1]  INFO -- : [22fc355eed5ea79ba123d67f2373ddd5] Completed 200 OK in 1969ms (Views: 20.7ms | ActiveRecord: 486.6ms | Allocations: 43700)
I, [2020-12-28T05:46:57.633625 #1]  INFO -- : [2737ccd3813d3cdb3494790de871bf7c] Completed 500 Internal Server Error in 1105ms (ActiveRecord: 124.4ms | Allocations: 27177)
F, [2020-12-28T05:46:57.634536 #1] FATAL -- : [2737ccd3813d3cdb3494790de871bf7c]   
[2737ccd3813d3cdb3494790de871bf7c] Slack::Web::Api::Errors::NameTaken (name_taken):
[2737ccd3813d3cdb3494790de871bf7c]   
[2737ccd3813d3cdb3494790de871bf7c] lib/integrations/slack/channel_builder.rb:25:in `find_or_create_channel'
[2737ccd3813d3cdb3494790de871bf7c] lib/integrations/slack/channel_builder.rb:9:in `perform'
[2737ccd3813d3cdb3494790de871bf7c] app/controllers/api/v1/accounts/integrations/slack_controller.rb:36:in `create_chatwoot_slack_channel'
[2737ccd3813d3cdb3494790de871bf7c] app/controllers/api/v1/accounts/integrations/slack_controller.rb:11:in `create'
[2737ccd3813d3cdb3494790de871bf7c] app/controllers/application_controller.rb:17:in `handle_with_exception'
[2737ccd3813d3cdb3494790de871bf7c] app/controllers/application_controller.rb:82:in `switch_locale'
```

**Comment by lgezyxr** [comment]
Behind is the log of the kubernetes pod which runs self hosted web server.

**Comment by pranavrajs** [comment]
@lgezyxr Looks like there is some issue with the channel name. Can you please delete `#customer-conversations` channels as described here (https://slack.com/intl/en-in/help/articles/213185307-Delete-a-channel) and try again?

**Comment by ruruiye** [comment]
@pranavrajs deleted the channel and retry again, same issue. and I don't think the public change has any problem.

**Comment by lgezyxr** [comment]
Turns out it's because of the limitation of return number of the [slack list api](https://api.slack.com/methods/conversations.list).
When the number of slack channels beyond 100, the conversations_list method would only return the first 100 of them. 
I've fixed that on my machine by using a loop with passing the "next_cursor" parameter to the api. Please add me to the contributors so that I can help to the project.
