### ISSUE TITLE
Getting ActionView::Template::Error (Missing host to link...) when trying to update profile

### ISSUE THREAD

**Issue by diego-vieira** [chatwoot/chatwoot#1557]
**Describe the bug**

When saving Account Settings, a 500 error is returned.

**To Reproduce**

1. Deploy using Docker with tag v1.11.1
2. Create an account
3. Go to Account Settings
4. Click Update Profile
5. A 500 error is returned.

**Expected behavior**

For the update profile to update.

**Screenshots**

![image](https://user-images.githubusercontent.com/930792/103179272-2b0aab80-4882-11eb-96b2-280d65791bb8.png)

**Browser logs**
```
vue.common.prod.js:659 TypeError: Cannot read property 'replace' of undefined
    at T (core.js:98)
    at p (core.js:2143)
    at Object.E [as highlight] (core.js:1680)
    at o.highlighted (core.js:1522)
    at _n.get (vue.common.prod.js:1445)
    at _n.evaluate (vue.common.prod.js:1495)
    at o.highlighted (vue.common.prod.js:1607)
    at o.render (core.js:1541)
    at o.e._render (vue.common.prod.js:1880)
    at o.a (vue.common.prod.js:3525)
ze @ vue.common.prod.js:659
www.gravatar.com/avatar/fc06da231149288d8e1c6d3f783e5af6?d=404:1 Failed to load resource: the server responded with a status of 404 ()
/auth/validate_token:1 Failed to load resource: the server responded with a status of 500 ()
VM576:1 PUT https://chat.domain.com/api/v1/profile 500
(anonymous) @ VM576:1
(anonymous) @ xhr.js:175
e.exports @ xhr.js:18
e.exports @ dispatchRequest.js:39
Promise.then (async)
l.request @ Axios.js:64
a.forEach.l.<computed> @ Axios.js:88
(anonymous) @ bind.js:11
profileUpdate @ auth.js:139
(anonymous) @ auth.js:100
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
Q @ application-88d347c622ffcbd98962.js:2
o @ application-88d347c622ffcbd98962.js:2
(anonymous) @ application-88d347c622ffcbd98962.js:2
(anonymous) @ application-88d347c622ffcbd98962.js:2
(anonymous) @ auth.js:98
(anonymous) @ vuex.js:778
S.dispatch @ vuex.js:497
S.dispatch @ vuex.js:416
(anonymous) @ Index.vue:192
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ra @ application-88d347c622ffcbd98962.js:2
o @ application-88d347c622ffcbd98962.js:2
(anonymous) @ application-88d347c622ffcbd98962.js:2
(anonymous) @ application-88d347c622ffcbd98962.js:2
updateUser @ application-88d347c622ffcbd98962.js:2
submit @ Index.vue?0680:1
We @ vue.common.prod.js:638
n @ vue.common.prod.js:748
Xa.i._wrapper @ vue.common.prod.js:2568
```

![image](https://user-images.githubusercontent.com/930792/103179275-3c53b800-4882-11eb-89d7-5904ba3e50a4.png)

**Server logs**

```
2020-12-27T20:25:00.323000746Z I, [2020-12-27T20:25:00.320604 #1] INFO -- : [9cce031c-1ac0-4fc0-88e4-283972b589a6] Completed 500 Internal Server Error in 404ms (ActiveRecord: 21.8ms | Allocations: 37701)
2020-12-27T20:25:00.327677066Z F, [2020-12-27T20:25:00.323757 #1] FATAL -- : [9cce031c-1ac0-4fc0-88e4-283972b589a6] 
2020-12-27T20:25:00.327726161Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
2020-12-27T20:25:00.327737621Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 10: json.role resource.active_account_user&.role
2020-12-27T20:25:00.327743246Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 11: json.inviter_id resource.active_account_user&.inviter_id
2020-12-27T20:25:00.327748439Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 12: json.confirmed resource.confirmed?
2020-12-27T20:25:00.327753422Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 13: json.avatar_url resource.avatar_url
2020-12-27T20:25:00.327758243Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 14: json.access_token resource.access_token.token
2020-12-27T20:25:00.327762879Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 15: json.availability_status resource.availability_status
2020-12-27T20:25:00.327767593Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 16: json.accounts do
2020-12-27T20:25:00.327772057Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] 
2020-12-27T20:25:00.327776586Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/models/concerns/avatarable.rb:12:in `avatar_url'
2020-12-27T20:25:00.327781126Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/views/api/v1/models/_user.json.jbuilder:13
2020-12-27T20:25:00.327785746Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/views/api/v1/profiles/update.json.jbuilder:1
2020-12-27T20:25:00.327790297Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/controllers/application_controller.rb:18:in `handle_with_exception'
2020-12-27T20:25:00.327795021Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2020-12-27T20:25:00.327799586Z [9cce031c-1ac0-4fc0-88e4-283972b589a6] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

```

**Environment**

Deployed Chatwoot v1.11.1 on top of a fresh install of Caprover

**Desktop (please complete the following information):**
Irrelevant 

**Smartphone (please complete the following information):**
Irrelevant

**Comment by diego-vieira** [comment]
After setting up SMTP settings it worked.
