### ISSUE TITLE
1.12.0 Compilation fails

### ISSUE THREAD

**Issue by Rid** [chatwoot/chatwoot#1666]
**Describe the bug**

After updating dependancies running `rake assets:precompile RAILS_ENV=production` produces a compilation failure:

```
root@chatwoot:~/chatwoot# rake assets:precompile RAILS_ENV=production
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
I, [2021-01-18T11:27:31.593372 #1324]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.08s.
Compiling...
Compilation failed:

warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 305 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 205 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-disabled`
         from line 326 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `foundation-button`
         from line 107 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #35c5ff is pretty bad, just 2
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #44ce4b is pretty bad, just 2.1
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of stdin

WARNING: Contrast ratio of #fff on #ffc532 is pretty bad, just 1.6
         on line 78 of node_modules/foundation-sites/scss/util/_color.scss, in function `color-pick-contrast`
         from line 143 of node_modules/foundation-sites/scss/components/_button.scss, in mixin `button-style`
         from line 217 of node_modules/foundation-sites/scss/components/_button-group.scss, in mixin `foundation-button-group`
         from line 108 of node_modules/foundation-sites/scss/foundation.scss, in mixin `foundation-everything`
         from line 19 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
         on line 43 of node_modules/foundation-sites/scss/util/_flex.scss, in mixin `flex-align`
         from line 85 of app/javascript/dashboard/assets/scss/widgets/_modal.scss
         from line 12 of app/javascript/dashboard/assets/scss/_woot.scss
         from line 20 of stdin

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
         on line 43 of node_modules/foundation-sites/scss/util/_flex.scss, in mixin `flex-align`
         from line 85 of app/javascript/dashboard/assets/scss/widgets/_modal.scss
         from line 12 of app/javascript/dashboard/assets/scss/_woot.scss
         from line 20 of app/javascript/dashboard/assets/scss/app.scss
         from line 54 of stdin
```

**To Reproduce**

1. Clone repo
2. Install depedancies
3. Run `rake assets:precompile RAILS_ENV=production`

**Expected behavior**

Compilation to complete successfully

**Server logs**

Accessing the server causes:

```
I, [2021-01-18T11:32:35.277287 #455]  INFO -- : [aacef7b2-78cd-485e-93fa-3df8458b3344] Started GET "/" for x.x.x.x at 2021-01-18 11:32:35 +0000
I, [2021-01-18T11:32:35.278211 #455]  INFO -- : [aacef7b2-78cd-485e-93fa-3df8458b3344] Processing by DashboardController#index as HTML
I, [2021-01-18T11:32:35.280469 #455]  INFO -- : [aacef7b2-78cd-485e-93fa-3df8458b3344]   Rendering dashboard/index.html.erb within layouts/vueapp
I, [2021-01-18T11:32:35.280718 #455]  INFO -- : [aacef7b2-78cd-485e-93fa-3df8458b3344]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.1ms | Allocations: 4)
I, [2021-01-18T11:32:35.283025 #455]  INFO -- : [aacef7b2-78cd-485e-93fa-3df8458b3344] Completed 500 Internal Server Error in 5ms (Allocations: 2285)
F, [2021-01-18T11:32:35.284314 #455] FATAL -- : [aacef7b2-78cd-485e-93fa-3df8458b3344]
[aacef7b2-78cd-485e-93fa-3df8458b3344] ActionView::Template::Error (Webpacker can't find application.js in /home/chatwoot/chatwoot/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
[aacef7b2-78cd-485e-93fa-3df8458b3344]     43:       }
[aacef7b2-78cd-485e-93fa-3df8458b3344]     44:       window.globalConfig = <%= raw @global_config.to_json %>
[aacef7b2-78cd-485e-93fa-3df8458b3344]     45:     </script>
[aacef7b2-78cd-485e-93fa-3df8458b3344]     46:     <%= javascript_pack_tag 'application' %>
[aacef7b2-78cd-485e-93fa-3df8458b3344]     47:     <%= stylesheet_pack_tag 'application' %>
[aacef7b2-78cd-485e-93fa-3df8458b3344]     48:   </head>
[aacef7b2-78cd-485e-93fa-3df8458b3344]     49:   <body>
[aacef7b2-78cd-485e-93fa-3df8458b3344]
[aacef7b2-78cd-485e-93fa-3df8458b3344] app/views/layouts/vueapp.html.erb:46
[aacef7b2-78cd-485e-93fa-3df8458b3344] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[aacef7b2-78cd-485e-93fa-3df8458b3344] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

**Environment**

Self hosted installation of Chatwoot using a custom Docker image.

**Comment by Rid** [comment]
It seems that `GEM_HOME` and `GEM_PATH` were not properly set, please disregard.

**Comment by startshineye** [comment]
I also meet this problem
GEM_HOME and GEM_PATH as Following:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/19678129/164952483-6bd2d527-396d-446a-8986-a4a73a5aa9a7.png">

how can I config?
@Rid 
> It seems that `GEM_HOME` and `GEM_PATH` were not properly set, please disregard.
