### ISSUE TITLE
terminated by SIGTERM - foreman

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1706]
**Describe the bug**

Project setup errors. Running ```foreman start -f Procfile.dev``` fails

**To Reproduce**
1. Followed all the steps in Installing for Mac and Quick Project setup.

**Expected behavior**

**Screenshots**

NA
**Browser logs**

NA
**Server logs**

```
foreman start -f Procfile.dev
23:30:00 backend.1  | started with pid 27451
23:30:00 frontend.1 | started with pid 27452
23:30:00 worker.1   | started with pid 27453
23:30:05 frontend.1 | ℹ ｢wds｣: Project is running at http://0.0.0.0:3035/
23:30:05 frontend.1 | ℹ ｢wds｣: webpack output is served from /packs/
23:30:05 frontend.1 | ℹ ｢wds｣: Content not from webpack is served from /Users/myusername/Desktop/code/apps/chatwoot/public/packs
23:30:05 frontend.1 | ℹ ｢wds｣: 404s will fallback to /index.html
23:30:08 backend.1  | => Booting Puma
23:30:08 backend.1  | => Rails 6.0.3.4 application starting in development 
23:30:08 backend.1  | => Run `rails server --help` for more startup options
23:30:08 backend.1  | `Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
23:30:09 worker.1   | `Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
23:30:09 worker.1   | 2021-01-29T18:00:09.347Z pid=27453 tid=e3h INFO: Booting Sidekiq 6.1.1 with redis options {:url=>"redis://redis:6379", :password=>"REDACTED", :size=>25}
23:30:09 worker.1   | 2021-01-29T18:00:09.371Z pid=27453 tid=e3h WARN: Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)
23:30:09 worker.1   | 2021-01-29T18:00:09.371Z pid=27453 tid=e3h WARN: /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:362:in `rescue in establish_connection'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:343:in `establish_connection'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis.rb:2192:in `block in hget'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/redis-4.2.1/lib/redis.rb:2191:in `hget'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:361:in `block in status_from_redis'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-6.1.1/lib/sidekiq.rb:98:in `block in redis'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-6.1.1/lib/sidekiq.rb:95:in `redis'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:360:in `status_from_redis'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:272:in `initialize'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `new'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `block in load_from_array'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `each'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `load_from_array'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:157:in `load_from_hash'
23:30:09 worker.1   | /Users/myusername/Desktop/code/apps/chatwoot/config/initializers/sidekiq.rb:12:in `<main>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
23:30:09 worker.1   | /Users/myusername/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
23:30:09 worker.1   | /Users/myusername/Desktop/code/apps/chatwoot/config/environment.rb:5:in `<top (required)>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:252:in `boot_application'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:37:in `run'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/gems/sidekiq-6.1.1/bin/sidekiq:31:in `<top (required)>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/bin/sidekiq:23:in `load'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/bin/sidekiq:23:in `<main>'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
23:30:09 worker.1   | /Users/myusername/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
23:30:10 worker.1   | exited with code 1
23:30:10 system     | sending SIGTERM to all processes
23:30:10 backend.1  | Exiting
23:30:10 backend.1  | terminated by SIGTERM
23:30:15 system     | sending SIGKILL to all processes
```
**Environment**

MacOSX Mojave. Non docker env setup.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
Please provide a valid REDIS_URL `Redis::CannotConnectError: Error connecting to Redis on redis:6379`

**Comment by KtKeaton** [comment]
this is my sever log, I want to know what is wrong

```
% foreman s
10:34:24 web.1     | started with pid 17926
10:34:24 redis.1   | unknown command: redis-server --port 6379
10:34:24 sidekiq.1 | started with pid 17929
10:34:41 web.1     | SQLite3 optional dependency not found. Sketch files are not supported in this mode.
10:34:41 sidekiq.1 | SQLite3 optional dependency not found. Sketch files are not supported in this mode.
10:34:41 web.1     | => Booting Puma
10:34:41 web.1     | => Rails 5.1.7 application starting in development 
10:34:41 web.1     | => Run `rails server -h` for more startup options
10:34:45 sidekiq.1 | 2021-12-27T02:34:45.188Z 17929 TID-ox375hs61 INFO: Booting Sidekiq 5.2.8 with redis options {:url=>"redis://localhost:6379/0", :id=>"Sidekiq-server-PID-17929"}
10:34:48 sidekiq.1 | 2021-12-27T02:34:48.622Z 17929 TID-ox375hs61 INFO: Running in ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
10:34:48 sidekiq.1 | 2021-12-27T02:34:48.630Z 17929 TID-ox375hs61 INFO: See LICENSE and the LGPL-3.0 for licensing details.
10:34:48 sidekiq.1 | 2021-12-27T02:34:48.640Z 17929 TID-ox375hs61 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
10:34:48 sidekiq.1 | Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:343:in `establish_connection'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:106:in `block in connect'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis.rb:286:in `block in info'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-4.1.3/lib/redis.rb:285:in `info'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:115:in `block in redis_info'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:97:in `block in redis'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:94:in `redis'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq.rb:108:in `redis_info'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/lib/sidekiq/cli.rb:73:in `run'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-5.2.8/bin/sidekiq:12:in `<top (required)>'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/bin/sidekiq:23:in `load'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/bin/sidekiq:23:in `<top (required)>'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
10:34:48 sidekiq.1 | /Users/Keaton/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
10:34:49 web.1     | Puma starting in single mode...
10:34:49 web.1     | * Version 3.12.4 (ruby 2.6.6-p146), codename: Llamas in Pajamas
10:34:49 web.1     | * Min threads: 5, max threads: 5
10:34:49 web.1     | * Environment: development
10:34:49 web.1     | * Listening on tcp://localhost:8000
10:34:49 web.1     | Use Ctrl-C to stop
10:34:49 sidekiq.1 | exited with code 1
10:34:49 system    | sending SIGTERM to all processes
10:34:49 web.1     | - Gracefully stopping, waiting for requests to finish
10:34:49 web.1     | === puma shutdown: 2021-12-27 10:34:49 +0800 ===
10:34:49 web.1     | - Goodbye!
10:34:49 web.1     | Exiting
10:34:49 web.1     | terminated by SIGTERM
10:34:54 system    | sending SIGKILL to all processes
```

**Comment by vishnu-narayanan** [comment]
@KtKeaton This error occurs when Chatwoot cannot connect with `redis`. Could you verify your `redis` connectivity?

**Comment by KtKeaton** [comment]
@vishnu-narayanan You are right, I later found out that I haven't installed Redis yet.
