### ISSUE TITLE
Integrate chatwoot on my app

### ISSUE THREAD

**Issue by ahmlouati** [chatwoot/chatwoot#1723]
**Describe the bug**

I have created a website inboxes and I added the script generated on my app. But I have found the error bellow.

![image](https://user-images.githubusercontent.com/70566996/106655688-f7feba80-6599-11eb-9744-643d7c1e8123.png)

**Comment by pranavrajs** [comment]
@ahmlouati Can you please share the logs? There is no information here for us to debug.

**Comment by ahmlouati** [comment]
***logs
2021-02-03T08:38:50+01:00 I, [2021-02-03T07:38:50.252056 #5778] INFO -- : [6d224460-a64d-42d6-b39f-d9dd23c10556] Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.1ms | Allocations: 4)
2021-02-03T08:38:50+01:00 I, [2021-02-03T07:38:50.254099 #5778] INFO -- : [6d224460-a64d-42d6-b39f-d9dd23c10556] Completed 200 OK in 10ms (Views: 2.4ms | ActiveRecord: 0.0ms | Allocations: 2049)
2021-02-03T08:38:50+01:00 I, [2021-02-03T07:38:50.243166 #5778] INFO -- : [6d224460-a64d-42d6-b39f-d9dd23c10556] Started GET "/" for 127.0.0.1 at 2021-02-03 07:38:50 +0000
2021-02-03T08:38:50+01:00 I, [2021-02-03T07:38:50.244345 #5778] INFO -- : [6d224460-a64d-42d6-b39f-d9dd23c10556] Processing by DashboardController#index as HTML
2021-02-03T08:38:50+01:00 I, [2021-02-03T07:38:50.251861 #5778] INFO -- : [6d224460-a64d-42d6-b39f-d9dd23c10556] Rendering dashboard/index.html.erb within layouts/vueapp
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.587344 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Started GET "/api/v1/accounts/1/agents" for 185.42.117.192 at 2021-02-03 07:38:59 +0000
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.588408 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Processing by Api::V1::Accounts::AgentsController#index as JSON
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.588471 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Parameters: {"account_id"=>"1"}
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.598321 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Rendering api/v1/accounts/agents/index.json.jbuilder
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.609325 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Rendered api/v1/models/_agent.json.jbuilder (Duration: 6.0ms | Allocations: 985)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.613113 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Rendered api/v1/accounts/agents/index.json.jbuilder (Duration: 14.7ms | Allocations: 2909)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.614819 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Completed 200 OK in 26ms (Views: 13.4ms | ActiveRecord: 5.7ms | Allocations: 6681)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.816198 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Rendered api/v1/accounts/inbox_members/show.json.jbuilder (Duration: 10.6ms | Allocations: 1740)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.817964 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Completed 200 OK in 43ms (Views: 9.6ms | ActiveRecord: 11.9ms | Allocations: 13452)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.634774 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Rendered api/v1/models/_inbox.json.jbuilder (Duration: 1.2ms | Allocations: 392)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.635324 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Rendered api/v1/models/_inbox.json.jbuilder (Duration: 0.3ms | Allocations: 177)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.635722 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Rendered api/v1/accounts/inboxes/index.json.jbuilder (Duration: 10.3ms | Allocations: 2193)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.637605 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Completed 200 OK in 21ms (Views: 7.9ms | ActiveRecord: 6.7ms | Allocations: 5862)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.615393 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Started GET "/api/v1/accounts/1/inboxes" for 185.42.117.192 at 2021-02-03 07:38:59 +0000
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.616455 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Processing by Api::V1::Accounts::InboxesController#index as JSON
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.616522 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Parameters: {"account_id"=>"1"}
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.774153 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Started GET "/api/v1/accounts/1/inbox_members/4" for 185.42.117.192 at 2021-02-03 07:38:59 +0000
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.625315 #5776] INFO -- : [1665072c-6163-463b-8961-36e271ddaab8] Rendering api/v1/accounts/inboxes/index.json.jbuilder
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.775238 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Processing by Api::V1::Accounts::InboxMembersController#show as JSON
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.775304 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Parameters: {"account_id"=>"1", "inbox_id"=>"4"}
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.805402 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Rendering api/v1/accounts/inbox_members/show.json.jbuilder
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.815932 #5780] INFO -- : [03613d81-109b-4cdf-9d69-805ca24145ea] Rendered api/v1/models/_agent.json.jbuilder (Duration: 7.5ms | Allocations: 1275)
2021-02-03T08:38:59+01:00 I, [2021-02-03T07:38:59.612795 #5781] INFO -- : [47151ec0-565f-43cb-89e3-38c67e8e33e0] Rendered api/v1/models/_agent.json.jbuilder (Duration: 3.2ms | Allocations: 803)
2021-02-03T08:39:00+01:00 I, [2021-02-03T07:39:00.248422 #5776] INFO -- : RoomChannel#update_presence
2021-02-03T08:39:16+01:00 2021-02-03T07:39:15.901Z pid=5690 tid=31be class=EventDispatcherJob jid=724cc767bbf6913ac42aea1e elapsed=0.043 INFO: done
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.901276 #5690] INFO -- : [ActiveJob] [ActionCableBroadcastJob] [c487ee92-b05b-4a67-8099-9ca973da1c52] Performed ActionCableBroadcastJob (Job ID: c487ee92-b05b-4a67-8099-9ca973da1c52) from Sidekiq(default) in 11.15ms
2021-02-03T08:39:16+01:00 2021-02-03T07:39:15.902Z pid=5690 tid=318y class=ActionCableBroadcastJob jid=9178d894bb572a9b9ca9c717 elapsed=0.047 INFO: done
2021-02-03T08:39:16+01:00 E, [2021-02-03T07:39:15.901019 #5690] ERROR -- : Skipping job because of ActiveJob::DeserializationError (Error while trying to deserialize arguments: FATAL: too many connections for role "u3pea8sjbqt6pxk4kj2s"
2021-02-03T08:39:16+01:00 )
2021-02-03T08:39:16+01:00 E, [2021-02-03T07:39:15.901371 #5690] ERROR -- : Discarded EventDispatcherJob due to a ActiveJob::DeserializationError.
2021-02-03T08:39:16+01:00 F, [2021-02-03T07:39:15.860319 #5781] FATAL -- : [c6c5b913-5d55-440f-9d05-c1669736f283]
2021-02-03T08:39:16+01:00 [c6c5b913-5d55-440f-9d05-c1669736f283] TypeError (no implicit conversion of Integer into String):
2021-02-03T08:39:16+01:00 [c6c5b913-5d55-440f-9d05-c1669736f283]
2021-02-03T08:39:16+01:00 [c6c5b913-5d55-440f-9d05-c1669736f283] app/services/widget/token_service.rb:5:in `generate_token'
2021-02-03T08:39:16+01:00 [c6c5b913-5d55-440f-9d05-c1669736f283] app/controllers/widgets_controller.rb:48:in `build_contact'
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.776672 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] Started GET "/widget?website_token=[FILTERED]&cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiI1ZmRmZmRiNi03MDQ0LTRjOTUtYTdlZS1lNjdmYjFlZTMwMGIiLCJpbmJveF9pZCI6MX0.MEhUO5OE1GmPBe8ZUGhTfH3t81RHCLPYNmdaMzQa3WA" for 185.42.117.192 at 2021-02-03 07:39:15 +0000
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.778516 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] Processing by WidgetsController#show as HTML
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.778594 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] Parameters: {"website_token"=>"[FILTERED]", "cw_conversation"=>"eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiI1ZmRmZmRiNi03MDQ0LTRjOTUtYTdlZS1lNjdmYjFlZTMwMGIiLCJpbmJveF9pZCI6MX0.MEhUO5OE1GmPBe8ZUGhTfH3t81RHCLPYNmdaMzQa3WA"}
2021-02-03T08:39:16+01:00 2021-02-03T07:39:15.855Z pid=5690 tid=318y class=ActionCableBroadcastJob jid=9178d894bb572a9b9ca9c717 INFO: start
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.856683 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: c487ee92-b05b-4a67-8099-9ca973da1c52) to Sidekiq(default) with arguments: ["3mcQM9iUvxuQpKdqTWHTYKET", "x8C4oxnuo7U9rLqucvjgJoSr"], "contact.created", {:additional_attributes=>{}, :email=>nil, :id=>42, :identifier=>nil, :name=>"purple-frog-329", :phone_number=>nil, :pubsub_token=>"jz35gDqqJWC9B3BDZrFH1N55", :thumbnail=>"", :type=>"contact", :account_id=>1}
2021-02-03T08:39:16+01:00 2021-02-03T07:39:15.858Z pid=5690 tid=31be class=EventDispatcherJob jid=724cc767bbf6913ac42aea1e INFO: start
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.858898 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] [ActiveJob] Enqueued EventDispatcherJob (Job ID: e6bf2bd6-0abd-4aa4-8c61-2a34c9685638) to Sidekiq(events) with arguments: "contact.created", Wed, 03 Feb 2021 07:39:15 UTC +00:00, {:contact=>#<GlobalID:0x0000555b3c8a9980 @uri=#<URI::GID gid://chatwoot/Contact/42>>}
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.859627 #5781] INFO -- : [c6c5b913-5d55-440f-9d05-c1669736f283] Completed 500 Internal Server Error in 81ms (ActiveRecord: 19.1ms | Allocations: 20510)
2021-02-03T08:39:16+01:00 I, [2021-02-03T07:39:15.889879 #5690] INFO -- : [ActiveJob] [ActionCableBroadcastJob] [c487ee92-b05b-4a67-8099-9ca973da1c52] Performing ActionCableBroadcastJob (Job ID: c487ee92-b05b-4a67-8099-9ca973da1c52) from Sidekiq(default) enqueued at 2021-02-03T07:39:15Z with arguments: ["3mcQM9iUvxuQpKdqTWHTYKET", "x8C4oxnuo7U9rLqucvjgJoSr"], "contact.created", {:additional_attributes=>{}, :email=>nil, :id=>42, :identifier=>nil, :name=>"purple-frog-329", :phone_number=>nil, :pubsub_token=>"jz35gDqqJWC9B3BDZrFH1N55", :thumbnail=>"", :type=>"contact", :account_id=>1}
2021-02-03T08:39:50+01:00 I, [2021-02-03T07:39:50.245015 #5778] INFO -- : [1a50dd36-a12f-493c-b6f1-10d686c6f580] Processing by DashboardController#index as HTML
2021-02-03T08:39:50+01:00 I, [2021-02-03T07:39:50.252858 #5778] INFO -- : [1a50dd36-a12f-493c-b6f1-10d686c6f580] Rendering dashboard/index.html.erb within layouts/vueapp
2021-02-03T08:39:50+01:00 I, [2021-02-03T07:39:50.244057 #5778] INFO -- : [1a50dd36-a12f-493c-b6f1-10d686c6f580] Started GET "/" for 127.0.0.1 at 2021-02-03 07:39:50 +0000
2021-02-03T08:39:50+01:00 I, [2021-02-03T07:39:50.253082 #5778] INFO -- : [1a50dd36-a12f-493c-b6f1-10d686c6f580] Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.1ms | Allocations: 4)
2021-02-03T08:39:50+01:00 I, [2021-02-03T07:39:50.255031 #5778] INFO -- : [1a50dd36-a12f-493c-b6f1-10d686c6f580] Completed 200 OK in 10ms (Views: 2.3ms | ActiveRecord: 0.0ms | Allocations: 2045)
2021-02-03T08:40:00+01:00 I, [2021-02-03T07:40:00.436159 #5776] INFO -- : RoomChannel#update_presence

**Comment by pranavrajs** [comment]
@ahmlouati Have you set `SECRET_KEY_BASE` in the env variables? Looks like it is missing.

**Comment by ahmlouati** [comment]
Yes, I have already set it .
![image](https://user-images.githubusercontent.com/70566996/106718201-02a06a80-6601-11eb-97e6-ca7e9128525b.png)

**Comment by ahmlouati** [comment]
Yes I have already set it :) 
![image](https://user-images.githubusercontent.com/70566996/106718418-527f3180-6601-11eb-9daf-7e229a602313.png)

**Comment by iammattmartin** [comment]
If that is the value, may not be valid.

Try generating a better looking key ;) 

https://stackoverflow.com/questions/29187296/rails-production-how-to-set-secret-key-base

**Comment by ahmlouati** [comment]
Thanks @iammattmartin
