### ISSUE TITLE
Validation failed: Phone number should be in e164 format

### ISSUE THREAD

**Issue by HunterNyan** [chatwoot/chatwoot#2378]
**Describe the bug**

Can't handle SMS's sent in with a Text based Number/Shortcode

**To Reproduce**

Twilio integration, recieve an SMS which uses TEXT eg: Support as the sender.

**Expected behavior**

webhook fails and a http 500 is returned

**Server logs**

rails_1     | I, [2021-06-04T04:31:48.226866 #1]  INFO -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f] Started POST "/twilio/callback" for 3.93.186.56 at 2021-06-04 04:31:48 +0000
rails_1     | I, [2021-06-04T04:31:48.227921 #1]  INFO -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f] Processing by Twilio::CallbackController#create as */*
rails_1     | I, [2021-06-04T04:31:48.228001 #1]  INFO -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f]   Parameters: {"ApiVersion"=>"2010-04-01", "SmsSid"=>"**REDACTED**", "SmsStatus"=>"received", "SmsMessageSid"=>"**REDACTED**", "NumSegments"=>"1", "ToState"=>"", "From"=>"SUPPORT", "MessageSid"=>"**REDACTED**", "AccountSid"=>"**REDACTED**", "ToCity"=>"", "ToZip"=>"", "To"=>"+61**REDACTED**", "ToCountry"=>"AU", "Body"=>"You have a new Support Reply From **REDACTED**", "NumMedia"=>"0"}
rails_1     | W, [2021-06-04T04:31:48.228360 #1]  WARN -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f] Can't verify CSRF token authenticity.
rails_1     | I, [2021-06-04T04:31:48.236722 #1]  INFO -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f] Validation failed: Phone number should be in e164 format
rails_1     | I, [2021-06-04T04:31:48.238449 #1]  INFO -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f] Completed 500 Internal Server Error in 10ms (ActiveRecord: 1.8ms | Allocations: 3464)
rails_1     | F, [2021-06-04T04:31:48.239161 #1] FATAL -- : [2f31a77a-fde2-49ce-976c-7247d0899c1f]
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] NoMethodError (undefined method `contact' for true:TrueClass):
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f]
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/services/twilio/incoming_message_service.rb:53:in `set_contact'
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/services/twilio/incoming_message_service.rb:7:in `perform'
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/controllers/twilio/callback_controller.rb:3:in `create'
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/controllers/application_controller.rb:18:in `handle_with_exception'
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | [2f31a77a-fde2-49ce-976c-7247d0899c1f] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

**Environment**

SelfHosted using Docker.

**Comment by pranavrajs** [comment]
@HunterNyan Just to clarify here. Are you sending a message from a number that is a shortcode? `"From"=>"SUPPORT"` seems like you are sending from a short code number. Could you please share the use case here?

**Comment by HunterNyan** [comment]
Hey @pranavrajs

Currently, this is just incoming from 3rd party into Chatwoot.

I have set up several a numbers in twilio/ported exisiting ones so that the team could see the SMS's coming in and reply/action them.

With the "From"=>"SUPPORT" I apparantly had the number set up with one of our "Providers Ticketing System" so when their " Support" replied it would send an SMS notification to the number. This same thing is also set up on other providers for billing alerts and such some who use shortcodes and others than don't.

I'm also looking into the options around using a ShortCode directly ourselves but the countries we're in don't allow replies to Text based short codes yet.

I hope that explains it for you :)

Thanks

**Comment by stonecharioteer** [comment]
This issue is being closed due to lack of activity for over a year. [For more details, visit this discussion.](https://github.com/orgs/chatwoot/discussions/12810)
