### ISSUE TITLE
Redis 6 on Heroku Premium breaks ActionCable config

### ISSUE THREAD

**Issue by aniravi24** [chatwoot/chatwoot#2420]
**Describe the bug**

Heroku made some SSL/TLS changes with Redis 6, but there's a library called ActionCable which has a config file in the chatwoot project (cable.yml) where I needed to add this same verify mode config that was missing. We've already fixed this issue, but I wanted to put this issue up because it would be great to document this somewhere so other people don't run into this. Heroku upgraded our Redis instance automatically last night and inadvertently took down our service.

To fix this, add the ssl_params/verify_mode part of this config to your cable.yml

```ruby
adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://127.0.0.1:6379') %>
  password: <%= ENV.fetch('REDIS_PASSWORD', nil).presence %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  channel_prefix: <%= "chatwoot_#{Rails.env}_action_cable"  %>
```
and add 

```ruby
ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
```
to your base_config in config.rb for redis after the URL, password, timeout, etc.

References are down below.

**To Reproduce**

1. Deploy with a premium instance of Redis on Heroku, and app will go down completely.

**Expected behavior**

Not crash.

**Server logs**

```
2021-06-12T16:09:33.327038+00:00 app[web.2]: #<Thread:0x000055dae3744280 /app/vendor/bundle/ruby/2.7.0/gems/actioncable-6.0.3.7/lib/action_cable/subscription_adapter/redis.rb:151 run> terminated with exception (report_on_exception is true):
2021-06-12T16:09:33.327151+00:00 app[web.2]: /app/vendor/bundle/ruby/2.7.0/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (OpenSSL::SSL::SSLError)
```

**Environment**
self-hosted installation of Chatwoot on Heroku

**Additional context**

https://help.heroku.com/HC0F8CUS/redis-connection-issues

https://github.com/rails/rails/issues/42036#issuecomment-824613214

https://ogirginc.github.io/en/heroku-redis-ssl-error

**Comment by sojan-official** [comment]
@aniravi24  Thanks a lot for adding this. We will take this up as a documentation task or an ENV variable configuration since Heroku is a popular option in our community for deployments.

**Comment by crhonox** [comment]
@aniravi24 did you manage to get it to work on heroku?

Now i get an error with ssl when i try to broadcast a message.
`/app/vendor/ruby-3.0.1/lib/ruby/3.0.0/openssl/ssl.rb:140:in `merge': no implicit conversion of Integer into Hash (TypeError)`

Any ideas?

**Comment by aniravi24** [comment]
@crhonox yes it's working if you do what I described above. Is it because you're using Ruby 3? We're using 2.7

**Comment by romariolopezc** [comment]
For me, the fix described didn't work. I had to create a version 5 redis and attach it to chatwoot and now is working

```bash
heroku addons:create heroku-redis:premium-0 --version 5
```

**Comment by sojan-official** [comment]
@caseyprovost  ref: https://ogirginc.github.io/en/heroku-redis-ssl-error
