### ISSUE TITLE
Error in installing Chatwoot via Linux VM Script

### ISSUE THREAD

**Issue by hanzala-sohrab** [chatwoot/chatwoot#2493]
**Describe the bug**

The script fails to setup a Chatwoot instance on an Ubuntu VPS.

**To Reproduce**

Follow the instructions mentioned here : https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm
**Expected behavior**

Chatwoot Installation should be accessible at http://{your_ip_address}:3000

**Screenshots**

![image](https://user-images.githubusercontent.com/40603380/122975556-16cae580-d3b1-11eb-9f88-252b8454509c.png)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

- Linux VM installation
- Ubuntu VPS (20.04)
- RAM : 4 GB

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Browser firefox

**Additional context**

Seems like there are some dependency issues.

**Comment by sojan-official** [comment]
Could you share the logs from your rails server? 

ref: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#viewing-logs

**Comment by hanzala-sohrab** [comment]
```shell
-- Logs begin at Fri 2021-06-18 08:30:15 CEST. --
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:41:in `db_fallback'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:32:in `load_from_cache'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:12:in `block in get'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:11:in `each'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:11:in `get'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] app/controllers/dashboard_controller.rb:15:in `set_global_config'
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: 2021-06-23 06:30:34 +0200: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: ---
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: 2021-06-23 06:30:34 +0200: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: ---
```

**Comment by hanzala-sohrab** [comment]
> Could you share the logs from your rails server?
> 
> ref: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#viewing-logs

```shell
-- Logs begin at Fri 2021-06-18 08:30:15 CEST. --
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:41:in `db_fallback'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:32:in `load_from_cache'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:12:in `block in get'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:11:in `each'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] lib/global_config.rb:11:in `get'
Jun 23 01:46:47 vmi491368.contaboserver.net chatwoot-web.1[761298]: [4688b5a2-9bac-4f4b-a2ff-74bbc60cad36] app/controllers/dashboard_controller.rb:15:in `set_global_config'
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: 2021-06-23 06:30:34 +0200: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: ---
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: 2021-06-23 06:30:34 +0200: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
Jun 23 06:30:34 vmi491368.contaboserver.net chatwoot-web.1[761298]: ---
```

**Comment by sojan-official** [comment]
@hanzala-sohrab We tested the installation scripts on  Ubuntu 20.04, and it seems to be working. Could you check again on a new VM? 

Could you also let us know the following information: 

do you have any other services already running in your VM?
How much memory is allocated to the VM?

**Comment by uzziwizzle** [comment]
I had the same issue. I have tried with 4 VMs so far.

**Comment by sojan-official** [comment]
> I had the same issue. I have tried with 4 VMs so far.

Could you share the logs ?

**Comment by TheCrott** [comment]
@sojan-official I'm facing same issue on ubuntu 20.04
Here are logs from rails server and sidekiq

```sh
chatwoot@chatwoot:~/chatwoot$ journalctl -u chatwoot-web.1.service -f
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Fri 2021-07-02 14:55:22 UTC. --
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]     4:     <title>SuperAdmin | Chatwoot</title>
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]     5:     <%= javascript_pack_tag 'superadmin' %>
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]     6:     <%= stylesheet_pack_tag 'superadmin' %>
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]     7:   </head>
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]     8:   <body data-gr-c-s-loaded="true">
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c]
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c] app/views/installation/onboarding/index.html.erb:5
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c] app/controllers/application_controller.rb:18:in `handle_with_exception'
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Jul 03 08:15:12 chatwoot chatwoot-web.1[620]: [a1fbf9db-3045-4eda-b87d-c418e0976a6c] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

```sh
chatwoot@chatwoot:~/chatwoot$ journalctl -u chatwoot-worker.1.service -f
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Fri 2021-07-02 14:55:22 UTC. --
Jul 03 06:42:41 chatwoot chatwoot-worker.1[622]: DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from <top (required)> at /home/chatwoot/chatwoot/config/application.rb:9)
Jul 03 06:42:51 chatwoot chatwoot-worker.1[622]: I, [2021-07-03T06:42:51.550655 #622]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
Jul 03 06:42:51 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:42:51.552Z pid=622 tid=8s6 INFO: Booting Sidekiq 6.1.1 with redis options {:url=>"redis://localhost:6379", :password=>nil, :reconnect_attempts=>2, :network_timeout=>5, :size=>25}
Jul 03 06:42:51 chatwoot chatwoot-worker.1[622]: `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/usr/local/rvm/gems/ruby-2.7.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:464:in `block in save')
Jul 03 06:42:51 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:42:51.597Z pid=622 tid=8s6 INFO: Cron Jobs - add job with name: internal_check_new_versions_job
Jul 03 06:42:58 chatwoot chatwoot-worker.1[622]: W, [2021-07-03T06:42:58.447795 #622]  WARN -- : Creating scope :open. Overwriting existing method Conversation.open.
Jul 03 06:43:00 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:43:00.313Z pid=622 tid=8s6 INFO: Booted Rails 6.0.3.7 application in production environment
Jul 03 06:43:00 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:43:00.313Z pid=622 tid=8s6 INFO: Running in ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
Jul 03 06:43:00 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:43:00.314Z pid=622 tid=8s6 INFO: See LICENSE and the LGPL-3.0 for licensing details.
Jul 03 06:43:00 chatwoot chatwoot-worker.1[622]: 2021-07-03T06:43:00.314Z pid=622 tid=8s6 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
```

**Comment by sojan-official** [comment]
Hi everyone, I have checked the Linux install script on our master, and it seems like there are some breakages. 
for the moment, please use the script on develop branch

```
wget https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_20.04.sh -O setup.sh
chmod 755 setup.sh
./setup.sh develop
```

ref: https://github.com/chatwoot/chatwoot/issues/2565#issuecomment-874685460
we will update the script on master with our upcoming release.

**Comment by TheCrott** [comment]
Sweet

**Comment by sojan-official** [comment]
This should be fixed in our latest release.
