### ISSUE TITLE
Rails server fails to start when installing via Linux helper script - rvm gpg key issue

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#2508]
**Describe the bug**

Rails server is not able to start up when set up via the Linux installation script. Upon checking the chatwoot `systemd` service log, it seems the issue is because of ruby version mismatch. Debugging further it seems `rvm` installation is failing and the script fails to install the required `ruby` version `2.7.2`.

Root cause for rvm installation failure is  `gpg` key import issue. 

**To Reproduce**

1. Follow self-hosted Ubuntu installation
2. Complete setup
3. Browse to https://chatwoot.mydomain.com

**Expected behavior**
Chatwoot login page is displayed. 

**Screenshots**

![image](https://user-images.githubusercontent.com/3526167/123261142-fff0d400-d513-11eb-8aa7-7cbda22c4f89.png)

**Browser logs**
n/a

**Server logs**
```
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: Started chatwoot-web.1.service.                                                                                                                          
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]: /usr/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.7.0, but your Gemfile specified 2.7.2 (Bundler::Ruby
VersionMismatch)                                                                                                                                                                                                   
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler/definition.rb:470:in `validate_runtime!'                                                             
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler.rb:143:in `setup'                                                                                    
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'                                                           
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'                                                                      
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'                                                                          
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'                                                                    
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'                                                          
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'                                                          
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from /home/chatwoot/chatwoot/config/boot.rb:3:in `<top (required)>'                                                                   
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from bin/rails:3:in `require_relative'
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 chatwoot-web.1[32264]:         from bin/rails:3:in `<main>'
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: chatwoot-web.1.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 09:18:21 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: chatwoot-web.1.service: Failed with result 'exit-code'.
Jun 24 09:18:22 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: chatwoot-web.1.service: Scheduled restart job, restart counter is at 5.
Jun 24 09:18:22 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: Stopped chatwoot-web.1.service.
Jun 24 09:18:22 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: chatwoot-web.1.service: Start request repeated too quickly.
Jun 24 09:18:22 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: chatwoot-web.1.service: Failed with result 'exit-code'.
Jun 24 09:18:22 vn-ubuntu-s-2vcpu-4gb-blr1-01 systemd[1]: Failed to start chatwoot-web.1.service.

```

```
root@vn-ubuntu-s-2vcpu-4gb-blr1-01:~# ./setup.sh
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri Jan 15 18:46:22 2021 UTC
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Can't check signature: No public key
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.12.tgz' - 'https://github.com/rvm/
rvm/releases/download/1.29.12/1.29.12.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D
2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security

```

**Environment**
Self Hosted - Linux - Ubuntu 20.04

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
 n/a
 
**Additional context**

**Comment by sojan-official** [comment]
ref : #2493

**Comment by vishnu-narayanan** [comment]
![image](https://user-images.githubusercontent.com/3526167/123433844-80353900-d5e9-11eb-8274-a594e8f09593.png)
