### ISSUE TITLE
Unable to start chatwoot due to PGConnectionBad Error

### ISSUE THREAD

**Issue by mp051998** [chatwoot/chatwoot#2590]
I have been running chatwoot on a server for the past 3 days. When trying to make some API calls to it today I kept getting Internal Server Errors. So thought I'd restart the server, which I did. But after this, I was unable to start it again. This is the error I keep getting when trying to run chatwoot_prepare or reset or create. 

```
Creating chatwoot-production_rails_run ... done
+ rm -rf /app/tmp/pids/server.pid
+ rm -rf /app/tmp/cache/assets /app/tmp/cache/bootsnap-compile-cache /app/tmp/cache/bootsnap-load-path-cache /app/tmp/cache/webpacker
+ echo 'Waiting for postgres to become ready....'
Waiting for postgres to become ready....
+ docker/entrypoints/helpers/pg_database_url.sh
+ export 'POSTGRES_PORT=5432'
+ PG_READY='pg_isready -h postgres -p 5432 -U postgres'
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - accepting connections
+ echo 'Database ready to accept connections.'
Database ready to accept connections.
+ bundle install
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using i18n 1.8.10
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using zeitwerk 2.4.2
Using activesupport 6.0.3.7
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.5.1
Using racc 1.5.2
Using nokogiri 1.11.6 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.9.1
Using rails-html-sanitizer 1.3.0
Using actionview 6.0.3.7
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.0.3.7
Using nio4r 2.5.7
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Using actioncable 6.0.3.7
Using globalid 0.4.2
Using activejob 6.0.3.7
Using activemodel 6.0.3.7
Using activerecord 6.0.3.7
Using marcel 1.0.1
Using activestorage 6.0.3.7
Using mini_mime 1.1.0
Using mail 2.7.1
Using actionmailbox 6.0.3.7
Using actionmailer 6.0.3.7
Using actiontext 6.0.3.7
Using activerecord-import 1.0.7
Using acts-as-taggable-on 6.5.0
Using public_suffix 4.0.6
Using addressable 2.7.0
Using method_source 1.0.0
Using thor 1.1.0
Using railties 6.0.3.7
Using momentjs-rails 2.20.1
Using datetime_picker_rails 0.0.7
Using jquery-rails 4.4.0
Using kaminari-core 1.2.1
Using kaminari-actionview 1.2.1
Using kaminari-activerecord 1.2.1
Using kaminari 1.2.1
Using ffi 1.15.0
Using sassc 2.4.0
Using sprockets 3.7.2
Using sprockets-rails 3.2.2
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using selectize-rails 0.12.6
Using administrate 0.16.0
Using ast 2.4.1
Using attr_extras 6.2.4
Using aws-eventstream 1.1.0
Using aws-partitions 1.360.0
Using aws-sigv4 1.2.2
Using jmespath 1.4.0
Using aws-sdk-core 3.105.0
Using aws-sdk-kms 1.37.0
Using aws-sdk-s3 1.79.1
Using descendants_tracker 0.0.4
Using ice_nine 0.11.2
Using axiom-types 0.1.1
Using multipart-post 2.1.1
Using faraday 1.0.1
Using faraday_middleware 1.0.0
Using connection_pool 2.2.3
Using net-http-persistent 4.0.0
Using azure-storage-common 2.0.2
Using azure-storage-blob 2.0.1
Using multi_json 1.15.0
Using statsd-ruby 1.4.0
Using barnes 0.0.8
Using bcrypt 3.1.16
Using msgpack 1.3.3
Using bootsnap 1.4.8
Using brakeman 4.9.0
Using browser 5.3.1
Using bundler 2.2.16
Using coercible 1.0.0
Using ruby-enum 0.9.0
Using commonmarker 0.21.1
Using declarative 0.0.20
Using declarative-option 0.1.0
Using orm_adapter 0.5.0
Using responders 3.0.1
Using warden 1.2.9
Using devise 4.8.0
Using devise-secure_password 2.0.1
Using rails 6.0.3.7
Using devise_token_auth 1.1.4
Using digest-crc 0.6.1
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.6
Using dotenv-rails 2.7.6
Using regexp_parser 1.7.1
Using ecma-re-validator 0.2.1
Using equalizer 0.0.11
Using et-orbi 1.2.4
Using execjs 2.7.0
Using mime-types-data 3.2021.0225
Using mime-types 3.3.1
Using multi_xml 0.6.0
Using httparty 0.18.1
Using facebook-messenger 2.0.1
Using fcm 1.0.2
Using flag_shih_tzu 0.3.23
Using foreman 0.87.2
Using raabro 1.4.0
Using fugit 1.4.1
Using google-protobuf 3.15.8 (x86_64-linux)
Using googleapis-common-protos-types 1.0.6
Using grpc 1.37.1 (x86_64-linux)
Using googleapis-common-protos 1.3.11
Using jwt 2.2.3
Using memoist 0.16.2
Using os 1.1.1
Using signet 0.15.0
Using googleauth 0.16.2
Using gapic-common 0.3.4
Using geocoder 1.6.3
Using gli 2.19.2
Using httpclient 2.8.3
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.43.0
Using google-cloud-env 1.5.0
Using google-cloud-errors 1.1.0
Using google-cloud-core 1.6.0
Using google-cloud-dialogflow-v2 0.6.4
Using google-cloud-dialogflow 1.2.0
Using google-cloud-storage 1.28.0
Using groupdate 5.2.2
Using haikunator 1.1.0
Using parallel 1.19.2
Using parser 2.7.1.4
Using rainbow 3.0.0
Using rexml 3.2.5
Using rubocop-ast 0.3.0
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.7.0
Using rubocop 0.89.1
Using sexp_processor 4.15.1
Using ruby_parser 3.15.0
Using ruby2ruby 2.4.4
Using hairtrigger 0.2.23
Using hana 1.3.7
Using hashie 4.1.0
Using hkdf 0.3.0
Using http-accept 1.7.0
Using http-cookie 1.0.3
Using inflecto 0.0.2
Using jbuilder 2.10.0
Using json 2.3.1
Using uri_template 0.7.0
Using json_schemer 0.2.16
Using koala 3.0.0
Using liquid 4.0.3
Using maxminddb 0.1.22
Using mini_magick 4.10.1
Using netrc 0.11.0
Using oauth 0.5.6
Using pg 1.2.3
Using procore-sift 0.15.0
Using puma 4.3.8
Using pundit 2.1.0
Using rack-cache 1.12.0
Using rack-cors 1.1.1
Using rack-proxy 0.6.5
Using redis 4.2.1
Using redis-namespace 1.8.0
Using redis-store 1.9.0
Using redis-rack-cache 2.2.1
Using rest-client 2.1.0
Using scout_apm 2.6.9
Using semantic_range 2.3.0
Using sentry-raven 3.0.3
Using sidekiq 6.1.1
Using sidekiq-cron 1.2.0
Using slack-ruby-client 0.15.0
Using virtus 1.0.5
Using telegram-bot-ruby 0.12.0
Using telephone_number 1.4.9
Using time_diff 0.3.0
Using twilio-ruby 5.32.0
Using twitty 0.1.1
Using tzinfo-data 1.2020.1
Using uglifier 4.2.0
Using valid_email2 3.3.1
Using webpacker 5.2.1
Using webpush 1.0.0
Using wisper 2.0.0
Bundle complete! 88 Gemfile dependencies, 202 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
+ BUNDLE='bundle check'
+ bundle check
The Gemfile's dependencies are satisfied
+ exec bundle exec rails db:create
DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from block (2 levels) in require at /usr/local/bundle/gems/bundler-2.2.16/lib/bundler/runtime.rb:66)
I, [2021-07-07T23:11:46.463964 #1]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
FATAL:  password authentication failed for user "postgres"
Couldn't create 'chatwoot_production' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  password authentication failed for user "postgres"
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:189:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:126:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:476:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:475:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/command.rb:48:in `invoke'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'

Caused by:
PG::ConnectionBad: FATAL:  password authentication failed for user "postgres"
/gems/ruby/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/gems/ruby/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/gems/ruby/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_handling.rb:189:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:126:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:476:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:475:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/command.rb:48:in `invoke'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
ERROR: 1
```

Not sure why this happened. On trying to run it locally, I get the same error. Any idea what's wrong?
This is my .env file. I havent set redis password. I've only set postgres and it's added in the docker-compose file as well.

```
# Used to verify the integrity of signed cookies. so ensure a secure value is set
SECRET_KEY_BASE=replace_with_lengthy_secure_hex

# Replace with the URL you are planning to use for your app
FRONTEND_URL=########

# If the variable is set, all non-authenticated pages would fallback to the default locale.
# Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en
# DEFAULT_LOCALE=en

# If you plan to use CDN for your assets, set Asset CDN Host
ASSET_CDN_HOST=

# Force all access to the app over SSL, default is set to false
FORCE_SSL=false

# This lets you control new sign ups on your chatwoot installation
# true : default option, allows sign ups
# false : disables all the end points related to sign ups
# api_only: disables the UI for signup, but you can create sign ups via the account apis
ENABLE_ACCOUNT_SIGNUP=false

# Redis config
REDIS_URL=redis://redis:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=
# Redis Sentinel can be used by passing list of sentinel host and ports e,g. sentinel_host1:port1,sentinel_host2:port2
REDIS_SENTINELS=
# Redis sentinel master name is required when using sentinel, default value is "mymaster".
# You can find list of master using "SENTINEL masters" command
REDIS_SENTINEL_MASTER_NAME=

# Postgres Database config variables
POSTGRES_HOST=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=password
RAILS_ENV=development
RAILS_MAX_THREADS=5

# The email from which all outgoing emails are sent
# could user either  `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
MAILER_SENDER_EMAIL=Chatwoot <accounts@chatwoot.com>


#SMTP domain key is set up for HELO checking
SMTP_DOMAIN=chatwoot.com
# the default value is set "mailhog" and is used by docker-compose for development environments,
# Set the value as "localhost" or your SMTP address in other environments
SMTP_ADDRESS=mailhog
SMTP_PORT=1025
SMTP_USERNAME=
SMTP_PASSWORD=
# plain,login,cram_md5
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=true
# Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
SMTP_OPENSSL_VERIFY_MODE=peer

# Mail Incoming
# This is the domain set for the reply emails when conversation continuity is enabled
MAILER_INBOUND_EMAIL_DOMAIN=
# Set this to appropriate ingress channel with regards to incoming emails
# Possible values are :
# relay for Exim, Postfix, Qmail
# mailgun for Mailgun
# mandrill for Mandrill
# postmark for Postmark
# sendgrid for Sendgrid
RAILS_INBOUND_EMAIL_SERVICE=
# Use one of the following based on the email ingress service
# Ref: https://edgeguides.rubyonrails.org/action_mailbox_basics.html
RAILS_INBOUND_EMAIL_PASSWORD=
MAILGUN_INGRESS_SIGNING_KEY=
MANDRILL_INGRESS_API_KEY=

# Storage
ACTIVE_STORAGE_SERVICE=local

# Amazon S3
# documentation: https://www.chatwoot.com/docs/configuring-s3-bucket-as-cloud-storage
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=

# Sentry
SENTRY_DSN=

# Log settings
# Disable if you want to write logs to a file
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
LOG_SIZE=500

### This environment variables are only required if you are setting up social media channels

# Facebook
# documentation: https://www.chatwoot.com/docs/facebook-setup
FB_VERIFY_TOKEN=
FB_APP_SECRET=
FB_APP_ID=

# Twitter
# documentation: https://www.chatwoot.com/docs/twitter-app-setup
TWITTER_APP_ID=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ENVIRONMENT=

#slack integration
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=

### Change this env variable only if you are using a custom build mobile app
## Mobile app env variables
IOS_APP_ID=6C953F3RX2.com.chatwoot.app
ANDROID_BUNDLE_ID=com.chatwoot.app

# https://developers.google.com/android/guides/client-auth (use keytool to print the fingerprint in the first section)
ANDROID_SHA256_CERT_FINGERPRINT=AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8


### Smart App Banner
# https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
# You can find your app-id in https://itunesconnect.apple.com
#IOS_APP_IDENTIFIER=1495796682

## Push Notification
## generate a new key value here : https://d3v.one/vapid-key-generator/
# VAPID_PUBLIC_KEY=
# VAPID_PRIVATE_KEY=
#
# for mobile apps
# FCM_SERVER_KEY=

## Bot Customizations
USE_INBOX_AVATAR_FOR_BOT=true



## IP look up configuration
## ref https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md
## works only on accounts with ip look up feature enabled
# IP_LOOKUP_SERVICE=geoip2
# maxmindb api key to use geoip2 service
# IP_LOOKUP_API_KEY=


## Running chatwoot as an API only server
## setting this value to true will disable the frontend dashboard endpoints
# CW_API_ONLY_SERVER=false

## Development Only Config
# if you want to use letter_opener for local emails
# LETTER_OPENER=true
```

**Comment by mp051998** [comment]
The first thing I'm sure you'll tell will be that there's a password mismatch so I'll attach the docker-compose file as well.

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    restart: always
    #ports:
    #  - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/redis:/data
    #ports:
    #  - '6379:6379'
```

**Comment by srameshr** [comment]
This happens to me all the time.  If I just run foreman from a new terminal it starts to work fine.

**Comment by mp051998** [comment]
Oh, I run it in docker, Im not sure this fix applies to me.

**Comment by mp051998** [comment]
I did a clean install again. It worked.

Not sure but I believe leaving the postgres port open allowed someone to modify the database credentials. 
Chatwoot doesnt require exposing redis and postgres ports. It invites unnecessary trouble, my server ended up getting a crypto miner installed by a hacker lol.

**Comment by sojan-official** [comment]
> I did a clean install again. It worked.
> 
> Not sure but I believe leaving the postgres port open allowed someone to modify the database credentials.
> Chatwoot doesnt require exposing redis and postgres ports. It invites unnecessary trouble, my server ended up getting a crypto miner installed by a hacker lol.

Yeah, there isn't a need to expose both those ports publically. We will revisit and update the documentation accordingly.

**Comment by gerardbrunoquantion** [comment]
I got a related problem. I'm doing a fresh install in my local machine according to this documentation: https://www.chatwoot.com/docs/self-hosted/deployment/docker and it ends up with the same error.

The only modification I'm doing to the docker-compose.yml and .env files is the postgres password. Any suggestion?

**Comment by mp051998** [comment]
What worked for me was a fresh installation where I wget the docker-compose and .env files again. Don't reuse those files. Not sure why, but this is what worked for me.

**Comment by gerardbrunoquantion** [comment]
Already done that several times but got the same result. Thanks anyway for the quick response.

**Comment by mp051998** [comment]
> I got a related problem. I'm doing a fresh install in my local machine according to this documentation: https://www.chatwoot.com/docs/self-hosted/deployment/docker and, when executing step 4, it ends up with the same error.
> 
> The only modification I'm doing to the docker-compose.yml and .env files is the postgres password. Any suggestion?

Also you don't need to expose the ports on redis and postgres.

**Comment by mp051998** [comment]
> Already done that several times but got the same result. Thanks anyway for the quick response.

Was it working before? Have you successfully set it up once before?

**Comment by gerardbrunoquantion** [comment]
I did in previous versions of Chatwoot, some months ago.

**Comment by mp051998** [comment]
> I got a related problem. I'm doing a fresh install in my local machine according to this documentation: https://www.chatwoot.com/docs/self-hosted/deployment/docker and, when executing step 4, it ends up with the same error.
> 
> The only modification I'm doing to the docker-compose.yml and .env files is the postgres password. Any suggestion?

You may also need to change HOST in the .env file

**Comment by gerardbrunoquantion** [comment]
You mean the postgres host? I'm using the postgres service in docker-compose and the database connection is not resulting in a time out, so I guess the 'postgres' host is alright.

**Comment by gerardbrunoquantion** [comment]
It seems to be a problem related to my machine. I changed the postgres password to the one that I used when I first installed Chatwoot and it is working. I am pruning my docker system but I can't still use another password.

Anyway, this problem does not seem to be related with this repository. Thanks and I apologize for the inconvenience.

**Comment by mp051998** [comment]
> You mean the postgres host? I'm using the postgres service in docker-compose and the database connection is not resulting in a time out, so I guess the 'postgres' host is alright.

I meant the main host but I think it wasnt your issue.

You may have mounted the previously used volume. Might be because of that. In that case why dont you try resetting the database?

docker-compose run --rm rails bundle exec rails db:reset

**Comment by mp051998** [comment]
> It seems to be a problem related to my machine. I changed the postgres password to the one that I used when I first installed Chatwoot and it is working. I am pruning my docker system but I can't still use another password.
> 
> Anyway, this problem does not seem to be related with this repository. Thanks and I apologize for the inconvenience.

in the docker-compose file, the volumes being mounted are actually from root, so no matter which folder you docker-compose up from, it'll mount the same volume. 

A better thing to do would be to mount it from the current directory. You can do this by adding a full-stop (period, '.') before the volume. Something like this:

Replace `/data/postgres:/var/lib/postgresql/data` with `./data/postgres:/var/lib/postgresql/data`

**Comment by gerardbrunoquantion** [comment]
I moved the machine volume to a docker volume and got it working now. Thanks!
