### ISSUE TITLE
Edit translations from dashboard

### ISSUE THREAD

**Issue by benbehringer** [chatwoot/chatwoot#2704]
**Is your feature request related to a problem? Please describe.**
It is currently not possible for admins to easily update translations from the dashboard. For instance, they cannot switch from formal to non-formal communication in languages such as German ("Sie" vs. "du").

**Describe the solution you'd like**
It would suffice to be able to edit yml and json files of different languages straight from the dashboard and add custom translations (e.g., by uploading them via the dashboard).

**Comment by benbehringer** [comment]
Is there a workaround to change the translations? I deploy using CapRover and tried to override translation files for the web container like that:

```
{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM chatwoot/chatwoot:latest",
    "ADD https://example.com/de.json /app/app/javascript/widget/i18n/locale/de.json",
    "RUN chmod 644 /app/app/javascript/widget/i18n/locale/de.json",
    "ADD https://example.com/de.yml /app/config/locales/de.yml",
    "RUN chmod 644 /app/config/locales/de.yml",
    "RUN chmod +x docker/entrypoints/rails.sh",
    "ENTRYPOINT [\"docker/entrypoints/rails.sh\"]",
    "CMD bundle exec rake db:chatwoot_prepare; bundle exec rails s -b 0.0.0.0 -p 3000",
  ]
}
```

Works for de.yml but not for de.json. Any ideas?

**Comment by pranavrajs** [comment]
@vishnu-narayanan Would you please help @benbehringer to build a custom docker image from the official Chatwoot instance to update the translations?

**Comment by vishnu-narayanan** [comment]
Hey @benbehringer, 

These localization assets are compiled and packed into the base image at an early stage. This is why this change you are attempting will not be possible with `chatwoot` base image.

For you to have an image with custom translations, please follow the steps.

1. Clone the repo
2. Replace/Add the translation files you need
3. Build the docker image
4. Use that image in Caprover


Or you could contribute the translations upstream and have them in the official image. Check out
1. https://translate.chatwoot.com/ 
2. https://www.chatwoot.com/docs/contributing-guide/translation-guidelines

**Comment by vishnu-narayanan** [comment]
Closing this for now. Please reopen if you have more questions.

**Comment by benbehringer** [comment]
Hey @vishnu-narayanan 

Thanks for the infos. I followed the steps and built a custom docker image: https://hub.docker.com/r/taptreeben/chatwoot

Yet, I'm failing to use that image:

```
2021-09-27T20:05:45.487777627Z I, [2021-09-27T20:05:45.487533 #1] INFO -- : source=rack-timeout id=c093c461-395e-4587-a8f1-7f2e26dfc2ee timeout=15000ms state=ready
2021-09-27T20:05:45.488494237Z I, [2021-09-27T20:05:45.488314 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Started GET "/app/accounts/1/profile/settings" for 84.183.31.29 at 2021-09-27 20:05:45 +0000
2021-09-27T20:05:45.491138882Z I, [2021-09-27T20:05:45.490931 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Processing by DashboardController#index as HTML
2021-09-27T20:05:45.491161791Z I, [2021-09-27T20:05:45.491037 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Parameters: {"params"=>"accounts/1/profile/settings"}
2021-09-27T20:05:45.502552427Z I, [2021-09-27T20:05:45.502477 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.2ms | Allocations: 151)
2021-09-27T20:05:45.504781678Z I, [2021-09-27T20:05:45.504693 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Rendered layout layouts/vueapp.html.erb (Duration: 2.5ms | Allocations: 2820)
2021-09-27T20:05:45.504974936Z I, [2021-09-27T20:05:45.504904 #1] INFO -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee] Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.0ms | Allocations: 5646)
2021-09-27T20:05:45.505691733Z F, [2021-09-27T20:05:45.505595 #1] FATAL -- : [c093c461-395e-4587-a8f1-7f2e26dfc2ee]
2021-09-27T20:05:45.505699057Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] ActionView::Template::Error (Webpacker can't find application.js in /app/public/packs/manifest.json. Possible causes:
2021-09-27T20:05:45.505701872Z 1. You want to set webpacker.yml value of compile to true for your environment
2021-09-27T20:05:45.505704159Z unless you are using the `webpack -w` or the webpack-dev-server.
2021-09-27T20:05:45.505706435Z 2. webpack has not yet re-run to reflect updates.
2021-09-27T20:05:45.505708630Z 3. You have misconfigured Webpacker's config/webpacker.yml file.
2021-09-27T20:05:45.505710886Z 4. Your webpack configuration is not creating a manifest.
2021-09-27T20:05:45.505713058Z Your manifest contains:
2021-09-27T20:05:45.505715183Z {
2021-09-27T20:05:45.505717225Z }
2021-09-27T20:05:45.505719244Z ):
2021-09-27T20:05:45.505722601Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 56: }
2021-09-27T20:05:45.505724796Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 57: </script>
2021-09-27T20:05:45.505736262Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 58: <% end %>
2021-09-27T20:05:45.505738543Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 59: <%= javascript_pack_tag 'application' %>
2021-09-27T20:05:45.505740769Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 60: <%= stylesheet_pack_tag 'application' %>
2021-09-27T20:05:45.505742954Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 61: </head>
2021-09-27T20:05:45.505745063Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] 62: <body>
2021-09-27T20:05:45.505747346Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee]
2021-09-27T20:05:45.505749415Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] app/views/layouts/vueapp.html.erb:59
2021-09-27T20:05:45.505751578Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2021-09-27T20:05:45.505753759Z [c093c461-395e-4587-a8f1-7f2e26dfc2ee] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
2021-09-27T20:05:45.505942582Z I, [2021-09-27T20:05:45.505798 #1] INFO -- : source=rack-timeout id=c093c461-395e-4587-a8f1-7f2e26dfc2ee timeout=15000ms service=18ms state=completed
2021-09-27T20:05:45.575369549Z I, [2021-09-27T20:05:45.575215 #1] INFO -- : Finished "/cable/" [WebSocket] for 84.183.31.29 at 2021-09-27 20:05:45 +0000
```
