### ISSUE TITLE
Webpacker can't find superadmin.css 

### ISSUE THREAD

**Issue by farooqch11** [chatwoot/chatwoot#2814]
**Describe the bug**

Aug 13 18:19:51 ip-172-31-27-146 chatwoot-web.1[2870]: [85533391-7bb7-4c4f-a4d9-445a947a25d5] ActionView::Template::Error (Webpacker can't find superadmin.css in /home/chatwoot/chatwood/public/packs/manifest.json. Possible causes:
Aug 13 18:19:51 ip-172-31-27-146 chatwoot-web.1[2870]: 1. You want to set webpacker.yml value of compile to true for your environment
Aug 13 18:19:51 ip-172-31-27-146 chatwoot-web.1[2870]:    unless you are using the `webpack -w` or the webpack-dev-server.
Aug 13 18:19

**To Reproduce**

we just took a new pull from the master branch and this error is coming from the cahtwood.

**Comment by pranavrajs** [comment]
@farooqch11 Can you please share whether you are try to deploy this in production or development?

**Comment by farooqch11** [comment]
development works tottaly fine. its happening in production.

**Comment by farooqch11** [comment]
this happened after taking latest pull.

**Comment by pranavrajs** [comment]
@farooqch11 Can you please try this command and compile it again? https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

**Comment by farooqch11** [comment]
this error is coming when i run

RAILS_ENV=production rake assets:clean assets:clobber assets:precompile



ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module ***@***.***/plugin-transform-runtime'
Require stack:
-
***@***.***/core/lib/config/files/plugins.js
- ***@***.***/core/lib/config/files/index.js
- ***@***.***/core/lib/index.js
- /home/chatwoot/chatwood/node_modules/babel-loader/lib/index.js
- /home/chatwoot/chatwood/node_modules/loader-runner/lib/loadLoader.js
- /home/chatwoot/chatwood/node_modules/loader-runner/lib/LoaderRunner.js
- /home/chatwoot/chatwood/node_modules/webpack/lib/NormalModule.js
- /home/chatwoot/chatwood/node_modules/webpack/lib/NormalModuleFactory.js
- /home/chatwoot/chatwood/node_modules/webpack/lib/Compiler.js
- /home/chatwoot/chatwood/node_modules/webpack/lib/webpack.js
-
/home/chatwoot/chatwood/node_modules/webpack-cli/bin/utils/validate-options.js
- /home/chatwoot/chatwood/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/chatwoot/chatwood/node_modules/webpack-cli/bin/cli.js
- /home/chatwoot/chatwood/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:815:15)
    at resolve
(/home/chatwoot/chatwood/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at resolveStandardizedName
***@***.***/core/lib/config/files/plugins.js:96:7)
    at resolvePlugin
***@***.***/core/lib/config/files/plugins.js:40:10)
    at loadPlugin
***@***.***/core/lib/config/files/plugins.js:48:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor
***@***.***/core/lib/config/config-descriptors.js:179:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/chatwoot/chatwood/node_modules/gensync/index.js:261:32)
    at evaluateAsync
(/home/chatwoot/chatwood/node_modules/gensync/index.js:291:5)
    at /home/chatwoot/chatwood/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async
(/home/chatwoot/chatwood/node_modules/gensync/index.js:43:15)
    at Function.all
(/home/chatwoot/chatwood/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors
***@***.***/core/lib/config/config-descriptors.js:134:38)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors
***@***.***/core/lib/config/config-descriptors.js:130:17)
    at createPluginDescriptors.next (<anonymous>)
    at plugins
***@***.***/core/lib/config/config-descriptors.js:57:26)
    at plugins.next (<anonymous>)
    at mergeChainOpts
***@***.***/core/lib/config/config-chain.js:405:34)
    at mergeChainOpts.next (<anonymous>)
    at
***@***.***/core/lib/config/config-chain.js:364:14
    at Generator.next (<anonymous>)
    at loadFileChain
***@***.***/core/lib/config/config-chain.js:218:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain
***@***.***/core/lib/config/config-chain.js:81:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig
***@***.***/core/lib/config/partial.js:85:62)

**Comment by sojan-official** [comment]
@farooqch11 are there any customizations done over the chatwoot code?  could you share the spec of the environment where you are running chatwoot ?

**Comment by pranavrajs** [comment]
Closing as there is no activity for a long time, please feel free to reopen the issue if this is still an issue.
