### ISSUE TITLE
Unable to process inbound emails due to 'ActiveStorage::FileNotFoundError'

### ISSUE THREAD

**Issue by jabelone** [chatwoot/chatwoot#2824]
**Describe the bug**
Chatwoot cannot process incoming emails from send grid.

**To Reproduce**

1. configure incoming emails via sendgrid as per the [documentation](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/setup).
2. Send an email to the configured address.
3. Email never arrives to the chatwoot inbox and the below error is logged.

**Expected behavior**

I expect the email to be delivered correctly

**Server logs**

From the worker docker container:

```
2021-08-15T18:25:22.689Z pid=1 tid=3409 class=ActionMailbox::RoutingJob jid=c4e416964d83ae43fcdd2e05 INFO: start
I, [2021-08-15T18:25:22.705250 #1]  INFO -- : [ActiveJob] [ActionMailbox::RoutingJob] [8a2c8c2c-099b-4122-92b7-d493efc8ef3f] Performing ActionMailbox::RoutingJob (Job ID: 8a2c8c2c-099b-4122-92b7-d493efc8ef3f) from Sidekiq(action_mailbox_routing) enqueued at 2021-08-15T18:23:25Z with arguments: #<GlobalID:0x00007f60d31424f0 @uri=#<URI::GID gid://chatwoot/ActionMailbox::InboundEmail/6>>
I, [2021-08-15T18:25:22.711478 #1]  INFO -- : [ActiveJob] [ActionMailbox::RoutingJob] [8a2c8c2c-099b-4122-92b7-d493efc8ef3f]   Disk Storage (0.6ms) Downloaded file from key: kjybzg2thipdsbpfsvwv21gdky7s
E, [2021-08-15T18:25:22.711757 #1] ERROR -- : [ActiveJob] [ActionMailbox::RoutingJob] [8a2c8c2c-099b-4122-92b7-d493efc8ef3f] Error performing ActionMailbox::RoutingJob (Job ID: 8a2c8c2c-099b-4122-92b7-d493efc8ef3f) from Sidekiq(action_mailbox_routing) in 6.16ms: ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:34:in `rescue in block in download'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:32:in `block in download'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service.rb:126:in `instrument'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:31:in `download'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/app/models/active_storage/blob.rb:202:in `download'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email.rb:40:in `source'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email.rb:36:in `mail'
/app/app/mailboxes/application_mailbox.rb:9:in `block in reply_mail?'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router/route.rb:25:in `match?'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `block in match_to_mailbox'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `each'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `detect'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `match_to_mailbox'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:24:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/routing.rb:18:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email/routable.rb:22:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/jobs/action_mailbox/routing_job.rb:10:in `perform'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:40:in `block in perform_now'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/sentry-raven-3.0.3/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/i18n-1.8.8/lib/i18n.rb:314:in `with_locale'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:45:in `block in tag_logger'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:80:in `tagged'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:45:in `tag_logger'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:139:in `run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:39:in `perform_now'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:25:in `block in execute'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:84:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:139:in `run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:23:in `execute'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:196:in `execute_job'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/gems/ruby/2.7.0/gems/sentry-raven-3.0.3/lib/raven/integrations/sidekiq.rb:9:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:163:in `block in process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:111:in `local'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:14:in `block in call'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:13:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:257:in `stats'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:13:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:78:in `global'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/logger.rb:10:in `with'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:123:in `dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:162:in `process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:78:in `process_one'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:68:in `run'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:15:in `watchdog'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2021-08-15T18:25:22.713Z pid=1 tid=3409 class=ActionMailbox::RoutingJob jid=c4e416964d83ae43fcdd2e05 elapsed=0.024 INFO: fail
2021-08-15T18:25:22.713Z pid=1 tid=3409 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"action_mailbox_routing","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailbox::RoutingJob","args":[{"job_class":"ActionMailbox::RoutingJob","job_id":"8a2c8c2c-099b-4122-92b7-d493efc8ef3f","provider_job_id":null,"queue_name":"action_mailbox_routing","priority":null,"arguments":[{"_aj_globalid":"gid://chatwoot/ActionMailbox::InboundEmail/6"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2021-08-15T18:23:25Z"}],"jid":"c4e416964d83ae43fcdd2e05","created_at":1629051805.6046445,"enqueued_at":1629051922.6882768,"error_message":"ActiveStorage::FileNotFoundError","error_class":"ActiveStorage::FileNotFoundError","failed_at":1629051805.6315615,"retry_count":0,"retried_at":1629051897.850394},"jobstr":"{\"retry\":true,\"queue\":\"action_mailbox_routing\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailbox::RoutingJob\",\"args\":[{\"job_class\":\"ActionMailbox::RoutingJob\",\"job_id\":\"8a2c8c2c-099b-4122-92b7-d493efc8ef3f\",\"provider_job_id\":null,\"queue_name\":\"action_mailbox_routing\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/ActionMailbox::InboundEmail/6\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-08-15T18:23:25Z\"}],\"jid\":\"c4e416964d83ae43fcdd2e05\",\"created_at\":1629051805.6046445,\"enqueued_at\":1629051922.6882768,\"error_message\":\"ActiveStorage::FileNotFoundError\",\"error_class\":\"ActiveStorage::FileNotFoundError\",\"failed_at\":1629051805.6315615,\"retry_count\":0,\"retried_at\":1629051897.850394}"}
2021-08-15T18:25:22.713Z pid=1 tid=3409 WARN: ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError
2021-08-15T18:25:22.713Z pid=1 tid=3409 WARN: /gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:34:in `rescue in block in download'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:32:in `block in download'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service.rb:126:in `instrument'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/lib/active_storage/service/disk_service.rb:31:in `download'
/gems/ruby/2.7.0/gems/activestorage-6.0.3.5/app/models/active_storage/blob.rb:202:in `download'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email.rb:40:in `source'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email.rb:36:in `mail'
/app/app/mailboxes/application_mailbox.rb:9:in `block in reply_mail?'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router/route.rb:25:in `match?'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `block in match_to_mailbox'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `each'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `detect'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:37:in `match_to_mailbox'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/router.rb:24:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/lib/action_mailbox/routing.rb:18:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/models/action_mailbox/inbound_email/routable.rb:22:in `route'
/gems/ruby/2.7.0/gems/actionmailbox-6.0.3.5/app/jobs/action_mailbox/routing_job.rb:10:in `perform'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:40:in `block in perform_now'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/sentry-raven-3.0.3/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/i18n-1.8.8/lib/i18n.rb:314:in `with_locale'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:45:in `block in tag_logger'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/tagged_logging.rb:80:in `tagged'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:45:in `tag_logger'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:139:in `run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:39:in `perform_now'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:25:in `block in execute'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:84:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `instance_exec'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:139:in `run_callbacks'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/execution.rb:23:in `execute'
/gems/ruby/2.7.0/gems/activejob-6.0.3.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:196:in `execute_job'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
/gems/ruby/2.7.0/gems/sentry-raven-3.0.3/lib/raven/integrations/sidekiq.rb:9:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:163:in `block in process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:111:in `local'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:14:in `block in call'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/rails.rb:13:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:257:in `stats'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:13:in `call'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_retry.rb:78:in `global'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/logger.rb:10:in `with'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/job_logger.rb:33:in `prepare'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:123:in `dispatch'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:162:in `process'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:78:in `process_one'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/processor.rb:68:in `run'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:15:in `watchdog'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Environment**
Self hosted via caprover on ubuntu 20.04 server and using s3 as the cloud storage provider.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari

**Comment by pranavrajs** [comment]
@jabelone Have you configured storage as described here? https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

The docker images need external storage to be added for the attachments/inbound emails to work.

**Comment by jabelone** [comment]
> @jabelone Have you configured storage as described here? https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers
> 
> The docker images need external storage to be added for the attachments/inbound emails to work.

Thanks for your reply. Yeah I’ve configured S3 storage and confirmed that chatwoot uploads files, by the looks of it, whenever it tries to process an inbound email.

**Comment by pranavrajs** [comment]
@jabelone Can you please confirm whether adding the storage fixed this issue?

**Comment by sojan-official** [comment]
Closing the issue since there hasn't been any recent activity. Let's reopen in case the problem persists.
