### ISSUE TITLE
foreman can't run

### ISSUE THREAD

**Issue by abraham-azzam** [chatwoot/chatwoot#2848]
abraham@Abrahams-MacBook-Pro chatwoot-develop % foreman start -f Procfile.dev
```
08:39:22 backend.1  | started with pid 7571
08:39:22 frontend.1 | started with pid 7572
08:39:22 worker.1   | started with pid 7573
08:39:28 frontend.1 | ℹ ｢wds｣: Project is running at http://0.0.0.0:3035/
08:39:28 frontend.1 | ℹ ｢wds｣: webpack output is served from /packs/
08:39:28 frontend.1 | ℹ ｢wds｣: Content not from webpack is served from /Users/abraham/Desktop/chatwoot-develop/public/packs
08:39:28 frontend.1 | ℹ ｢wds｣: 404s will fallback to /index.html
08:39:29 backend.1  | => Booting Puma
08:39:29 backend.1  | => Rails 6.1.4 application starting in development 
08:39:29 backend.1  | => Run `bin/rails server --help` for more startup options
08:39:32 backend.1  | Puma starting in single mode...
08:39:32 backend.1  | * Puma version: 5.4.0 (ruby 3.0.2-p107) ("Super Flight")
08:39:32 backend.1  | *  Min threads: 5
08:39:32 backend.1  | *  Max threads: 5
08:39:32 backend.1  | *  Environment: development
08:39:32 backend.1  | *          PID: 7571
08:39:32 backend.1  | * Listening on http://127.0.0.1:3000
08:39:32 backend.1  | * Listening on http://[::1]:3000
08:39:32 backend.1  | Use Ctrl-C to stop
08:39:33 worker.1   | 2021-08-22T06:39:33.363Z pid=7573 tid=1b9 INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://redis:6379", :password=>nil, :reconnect_attempts=>2, :network_timeout=>5}
08:39:33 worker.1   | 2021-08-22T06:39:33.376Z pid=7573 tid=1b9 WARN: Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)
08:39:33 worker.1   | 2021-08-22T06:39:33.376Z pid=7573 tid=1b9 WARN: /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:384:in `rescue in establish_connection'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:365:in `establish_connection'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:117:in `block in connect'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:330:in `with_reconnect'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:116:in `connect'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:403:in `ensure_connected'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis/client.rb:148:in `call'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis.rb:2242:in `block in hget'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/monitor.rb:202:in `synchronize'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/redis-4.4.0/lib/redis.rb:2241:in `hget'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:361:in `block in status_from_redis'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-6.2.1/lib/sidekiq.rb:98:in `block in redis'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-6.2.1/lib/sidekiq.rb:95:in `redis'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:360:in `status_from_redis'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:272:in `initialize'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `new'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `block in load_from_array'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `each'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `load_from_array'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:157:in `load_from_hash'
08:39:33 worker.1   | /Users/abraham/Desktop/chatwoot-develop/config/initializers/sidekiq.rb:14:in `<main>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:326:in `block in load'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:326:in `load'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/engine.rb:681:in `block in load_config_initializer'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/notifications.rb:205:in `instrument'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/engine.rb:680:in `load_config_initializer'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/engine.rb:633:in `each'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/engine.rb:633:in `block in <class:Engine>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `instance_exec'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `run'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:61:in `block in run_initializers'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:50:in `each'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:50:in `tsort_each_child'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `call'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
08:39:33 worker.1   | /Users/abraham/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/initializable.rb:60:in `run_initializers'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/railties-6.1.4/lib/rails/application.rb:391:in `initialize!'
08:39:33 worker.1   | /Users/abraham/Desktop/chatwoot-develop/config/environment.rb:5:in `<top (required)>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:265:in `boot_application'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:37:in `run'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/gems/sidekiq-6.2.1/bin/sidekiq:31:in `<top (required)>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/bin/sidekiq:23:in `load'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/bin/sidekiq:23:in `<main>'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
08:39:33 worker.1   | /Users/abraham/.rvm/gems/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
08:39:33 worker.1   | exited with code 1
08:39:33 system     | sending SIGTERM to all processes
08:39:33 backend.1  | - Gracefully stopping, waiting for requests to finish
08:39:33 backend.1  | Exiting
08:39:33 backend.1  | terminated by SIGTERM
08:39:38 system     | sending SIGKILL to all processes

 - OS: [macOS Big Sur 11.3]
```

**Comment by sojan-official** [comment]
Please check the error message : "Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)" 

- ensure you have redis installed in your machine
- ensure you have the correct credentials configured in your `.env` file. 

if you are following any of our documentation and the instructions are not clear, do let us know and we will have it updated.

**Comment by sojan-official** [comment]
Please check the error message : "Redis::CannotConnectError: Error connecting to Redis on redis:6379 (SocketError)" 

- ensure you have redis installed in your machine
- ensure you have the correct credentials configured in your `.env` file. 

if you are following any of our documentation and the instructions are not clear, do let us know and we will have it updated.

**Comment by jatinvinkumar** [comment]
@abraham-azzam  i am having the same issue. Were you able to resolve? If so, could you please share steps? Thanks

**Comment by sojan-official** [comment]
@jatinvinkumar  Did you check your redis configurations in your local machine?

**Comment by pranavrajs** [comment]
Closing this as there was no activity for a couple of months.
