### ISSUE TITLE
Building chatwoot in docker is broken

### ISSUE THREAD

**Issue by kolaente** [chatwoot/chatwoot#289]
**Describe the bug**

**To Reproduce**

1. Try build the docker image from a clean checkout of the repo (with the fix from #288 already applied)
2. Step 8 (Frontend) fails:
```
Step 8/13 : RUN bundle exec rake assets:precompile
 ---> Running in 57b8673d76d2
yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.83s.
yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.82s.
rake aborted!
Sprockets::ArgumentError: link_directory argument must be a directory
/app/app/assets/config/manifest.js:3
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:389:in `expand_relative_dirname'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:325:in `process_link_directory_directive'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:189:in `block in process_directives'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:187:in `each'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:187:in `process_directives'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:84:in `_call'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/directive_processor.rb:65:in `call'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/bundle.rb:27:in `call'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:59:in `block in load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:335:in `fetch_asset_from_dependency_cache'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/loader.rb:43:in `load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/cached_environment.rb:44:in `load'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/base.rb:81:in `find_asset'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/usr/local/bundle/gems/sprockets-4.0.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/promise.rb:563:in `block in realize'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
ERROR: Service 'server' failed to build: The command '/bin/sh -c bundle exec rake assets:precompile' returned a non-zero code: 1
```

After digging into it a little, it looks like it expects a folder (presumably with css files in it) under `app/assets/stylesheets` which does not exist. Not knowing much about ruby or the build process here, I don't really know where this should come from. I would expect the files to just "sit there" but apparently they are created by a previous build step or so.

I assume during normal development, this does not happen because these files are already built and the folder exists, which is why this has not been noted until now.

**Expected behavior**

The docker image builds without issues.

**Comment by pranavrajs** [comment]
@kolaente Could you please specify the OS and docker version you are using?

**Comment by kolaente** [comment]
@pranavrajs sure, I'm on Nixos 19.09 with docker 19.03. May I ask how the host OS is relevant? This is docker, it should work regardless of the host os.

**Comment by kolaente** [comment]
@sojan-official why was this closed? Because of the PR? This issue is not resolved.

**Comment by sojan-official** [comment]
@kolaente I thought the PR fixed it. My bad. let me reopen this

**Comment by pranavrajs** [comment]
@kolaente It should work regardless of OS. We are not using rails asset pipeline, instead, we are using webpacker. sprockets should not through an error in this case. I was just trying to figure out if we missed any commands.

**Comment by sojan-official** [comment]
@kolaente  we just merged in a fix. let us know if you face anymore issues.

**Comment by kolaente** [comment]
@sojan-official Thanks, it seems to work now.
