### ISSUE TITLE
Old Campaigns Disappeared

### ISSUE THREAD

**Issue by aw-0** [chatwoot/chatwoot#3113]
**Describe the bug**

Campaigns that my team created prior to the new Campaigns tab (where you would create campaigns via the Inbox) do not appear in the new Campaigns tab and are unable to be edited in the UI. This is due to a 500 server error when trying to render the old campaigns.

**To Reproduce**

1. Create campaigns on a version of Chatwoot prior to 1.19.0
2. Update to 1.19.0+
3. Visit the new campaigns tab
4. See error in logs & visually

**Expected behavior**

All of your campaigns that were previously created in a specific Inbox will show up in the tab.

**Server logs**

```
2021-09-30T02:55:23.823164+00:00 app[web.1]: I, [2021-09-30T02:55:23.823133 #4]  INFO -- : [db696c10-ca21-4c8e-86a4-b3816b99c286] Completed 500 Internal Server Error in 70ms (ActiveRecord: 37.5ms | Allocations: 26980)
2021-09-30T02:55:23.824126+00:00 app[web.1]: F, [2021-09-30T02:55:23.824090 #4] FATAL -- : [db696c10-ca21-4c8e-86a4-b3816b99c286]   
2021-09-30T02:55:23.824127+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] ActionView::Template::Error (undefined method `id' for nil:NilClass):
2021-09-30T02:55:23.824127+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286]     1: json.account_id resource.account.id
2021-09-30T02:55:23.824128+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286]     2: json.availability_status resource.availability_status
2021-09-30T02:55:23.824128+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286]     3: json.confirmed resource.confirmed?
2021-09-30T02:55:23.824129+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286]     4: json.email resource.email
2021-09-30T02:55:23.824129+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286]   
2021-09-30T02:55:23.824129+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/views/api/v1/models/_agent.json.jbuilder:1
2021-09-30T02:55:23.824130+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/views/api/v1/models/_campaign.json.jbuilder:9
2021-09-30T02:55:23.824130+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/views/api/v1/models/_campaign.json.jbuilder:8
2021-09-30T02:55:23.824130+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/views/api/v1/accounts/campaigns/index.json.jbuilder:2
2021-09-30T02:55:23.824131+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/views/api/v1/accounts/campaigns/index.json.jbuilder:1
2021-09-30T02:55:23.824131+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2021-09-30T02:55:23.824131+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
2021-09-30T02:55:23.824132+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
2021-09-30T02:55:23.824132+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2021-09-30T02:55:23.824132+00:00 app[web.1]: [db696c10-ca21-4c8e-86a4-b3816b99c286] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

**Environment**

Self-hosted via Heroku on-click.

**Additional context**

Can provide additional information as needed.

**Comment by pranavrajs** [comment]
@aw-0 Can you please try upgrading to v1.20.0 and see if the error is still there? https://www.chatwoot.com/blog/v1-20-0/

**Comment by aw-0** [comment]
Thanks for the speedy response! We've already been running v1.20.0 for a while and the bug is still prevalent there.

**Comment by pranavrajs** [comment]
@aw-0 This should be closed by https://github.com/chatwoot/chatwoot/pull/3123
