### ISSUE TITLE
After update version v1.20.0 chatwoot and sidekiq service not working

### ISSUE THREAD

**Issue by vishnuv1995** [chatwoot/chatwoot#3218]
Hi,

I have updated my chatwoot version to v1.20.0 . After that  chatwoot and sidekiq service not working.

Redis password we have given in .env file.

**Logs:**
```
DEPRECATION WARNING: Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION is deprecated! Use Devise::Models::Authenticatable::UNSAFE_ATTRIBUTES_FOR_SERIALIZATION instead. (called from block (2 levels) in require at /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/runtime.rb:64)
I, [2021-10-14T13:34:28.548799 #1]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
2021-10-14T13:34:28.549Z pid=1 tid=4l1 INFO: Booting Sidekiq 6.1.1 with redis options {:url=>"redis://redis:6379", :password=>"REDACTED", :reconnect_attempts=>2, :network_timeout=>5}
2021-10-14T13:34:28.550Z pid=1 tid=4l1 WARN: Redis::CommandError: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
2021-10-14T13:34:28.550Z pid=1 tid=4l1 WARN: /gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:127:in `call'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:108:in `block in connect'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:2192:in `block in hget'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:2191:in `hget'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:361:in `block in status_from_redis'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq.rb:98:in `block in redis'
/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'
/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'
/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq.rb:95:in `redis'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:360:in `status_from_redis'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:272:in `initialize'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `new'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `block in load_from_array'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `each'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `load_from_array'
/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:157:in `load_from_hash'
/app/config/initializers/sidekiq.rb:14:in `<main>'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `block in load'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `load'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:666:in `block in load_config_initializer'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:182:in `instrument'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:665:in `load_config_initializer'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:624:in `each'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:624:in `block in <class:Engine>'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:32:in `instance_exec'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:32:in `run'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:50:in `each'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/lib/ruby/2.7.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:60:in `run_initializers'
/gems/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:252:in `boot_application'
```

**Comment by pranavrajs** [comment]
@vishnu-narayanan / @sojan-official Can you please take a look?

**Comment by rahulmr** [comment]
You need to login to `redis-server` using `redis-cli` and perform `requirepass` or `AUTH`
modify the `.env` to have `REDIS_PASSWORD=RedisAdminPwd`

then
`redis-cli` (make sure `redis-server` is running)
```
redis-cli> AUTH RedisAdminPwd
OK
```

**Comment by sojan-official** [comment]
closing this because of the lack of recent activity. please feel free to reopen if the issue persists.
