### ISSUE TITLE
Bug: Clean Chatwoot v2.0.0 on Caprover fatal error

### ISSUE THREAD

**Issue by aaron5670** [chatwoot/chatwoot#3589]
## Clean Chatwoot v2.0.0 on Caprover fatal error
I installed the latest v2.0.0 version on Caprover from one-click-apps and get the following error.

I can't get new conversations, it's always loading...
![image](https://user-images.githubusercontent.com/17295145/146243808-2f93080f-02c1-47dd-8fde-2194bf76fc21.png)

The network tab returns a 500 error on the request URL: https://support-web.my-caprover-dev.nl/api/v1/accounts/1/conversations?status=open&assignee_type=me&page=1

![image](https://user-images.githubusercontent.com/17295145/146243899-8ccd2271-28b1-4b18-b9ef-aaa437f9a88a.png)

### Error log from Caprover (chatwoot-web)

```
2021-12-15T18:20:52.535252671Z I, [2021-12-15T18:20:52.534656 #1] INFO -- : [374cb74d-e403-4d52-968a-be344472b485] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
2021-12-15T18:20:52.591511967Z I, [2021-12-15T18:20:52.591197 #1] INFO -- : source=rack-timeout id=374cb74d-e403-4d52-968a-be344472b485 timeout=15000ms service=271ms state=completed
2021-12-15T18:20:52.784668140Z I, [2021-12-15T18:20:52.784330 #1] INFO -- : [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 376.1ms | Allocations: 58609)
2021-12-15T18:20:52.785183515Z I, [2021-12-15T18:20:52.785027 #1] INFO -- : [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] Completed 500 Internal Server Error in 489ms (ActiveRecord: 177.7ms | Allocations: 76355)
2021-12-15T18:20:52.788364195Z F, [2021-12-15T18:20:52.786979 #1] FATAL -- : [2eb85f06-b145-4f4d-a096-02a27c4d1ae4]
2021-12-15T18:20:52.788401114Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
2021-12-15T18:20:52.788405422Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 22: elsif conversation.unread_incoming_messages.count.zero?
2021-12-15T18:20:52.788408748Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 23: json.messages [conversation.messages.includes([{ attachments: [{ file_attachment: [:blob] }] }]).last.try(:push_event_data)]
2021-12-15T18:20:52.788412044Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 24: else
2021-12-15T18:20:52.788415229Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 25: json.messages conversation.unread_messages.includes([:user, { attachments: [{ file_attachment: [:blob] }] }]).last(10).map(&:push_event_data)
2021-12-15T18:20:52.788419036Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 26: end
2021-12-15T18:20:52.788422322Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 27:
2021-12-15T18:20:52.788425308Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] 28: json.account_id conversation.account_id
2021-12-15T18:20:52.788428434Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4]
2021-12-15T18:20:52.788431189Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/models/attachment.rb:36:in `file_url'
2021-12-15T18:20:52.788434074Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/models/attachment.rb:52:in `file_metadata'
2021-12-15T18:20:52.788456166Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/models/attachment.rb:32:in `push_event_data'
2021-12-15T18:20:52.788459442Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/models/message.rb:104:in `map'
2021-12-15T18:20:52.788462618Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/models/message.rb:104:in `push_event_data'
2021-12-15T18:20:52.788465843Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25:in `map'
2021-12-15T18:20:52.788469330Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25
2021-12-15T18:20:52.788472716Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
2021-12-15T18:20:52.788476293Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
2021-12-15T18:20:52.788479679Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
2021-12-15T18:20:52.788484177Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
2021-12-15T18:20:52.788487624Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2021-12-15T18:20:52.788490780Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
2021-12-15T18:20:52.788494206Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
2021-12-15T18:20:52.788497613Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2021-12-15T18:20:52.788500819Z [2eb85f06-b145-4f4d-a096-02a27c4d1ae4] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
2021-12-15T18:20:52.788504876Z I, [2021-12-15T18:20:52.787415 #1] INFO -- : source=rack-timeout id=2eb85f06-b145-4f4d-a096-02a27c4d1ae4 timeout=15000ms service=558ms state=completed
```

**Comment by apitel** [comment]
I am having the same issue. Also clean Chatwoot v2.0.0 install on CapRover.

**Comment by vishnu-narayanan** [comment]
@aaron5670 @apitel Could you please ssh into your `caprover` instance and share the output of following ?

```
docker version
docker info
```

**Comment by vishnu-narayanan** [comment]
Tried a fresh install of `caprover` and then deployed chatwoot from the marketplace. Installation went fine and then was able to create a website inbox and verified its working.

https://chatwoot-web.cap.chatwoot.dev/api

@aaron5670 @apitel Not able to reproduce this issue from my end. Could you share more details?
1. Are you using a  fresh caprover install?
2. Could you share your caprover version ?

**Comment by vishnu-narayanan** [comment]
@sojan-official Not sure if it's related but I'm getting web socket disconnections events in the console.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3526167/146372797-4b3d069a-7b8c-44d9-aedb-5bf9c312de2b.png">

**Comment by apitel** [comment]
@vishnu-narayanan I am also seeing the web socket disconnects.

CapRover 1.10.1

It was a fresh install of both CapRover and Chatwoot.

**Comment by sojan-official** [comment]
@vishnu-narayanan  did you enable the web socket support from the UI? 
ref: https://medium.com/rommels-software-development-perspective/enabling-web-sockets-wss-websocket-secure-802ad5ae000f 

if we don't have this in the docs, let's have it updated.

**Comment by vishnu-narayanan** [comment]
@apitel Could you confirm your docker version?

ref: https://github.com/chatwoot/chatwoot/issues/2845

**Comment by aaron5670** [comment]
@vishnu-narayanan 

**Docker version:**
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 14
  Running: 12
  Paused: 0
  Stopped: 2
 Images: 275
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: xxx
  Is Manager: true
  ClusterID: xxx
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-134-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.66GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by sojan-official** [comment]
@aaron5670 Could you check and confirm the following? 

Configured a `FRONTEND_URL` env variable ( domain where you access chatwoot instance )
Configured environment variables for storage 


ref: https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-frontend-url

**Comment by aaron5670** [comment]
Thank you! I added the ``FRONTEND_URL`` variable to my chatwoot-web application on Caprover, updated Docker to the latest version and reinstalled Chatwoot on it. Now it all works fine :).

**Comment by apitel** [comment]
Resolved for me as well.
