### ISSUE TITLE
TLS1.2 support for SMTP outgoing emails

### ISSUE THREAD

**Issue by piotrpelica** [chatwoot/chatwoot#3590]
**Describe the bug**

When using Office 365 to send outgoing mail, following error shows up in the logs. Microsoft uses STARTTLS for the SMTP (see [here](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353)).

```
sidekiq_1   | WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number
sidekiq_1   | b:46:in `ssl_socket_connect'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:624:in `tlsconnect'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:591:in `do_start'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:557:in `start'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
sidekiq_1   | /gems/ruby/3.0.0/gems/actionmailer-6.1.4.1/lib/action_mailer/base.rb:559:in `block in deliver_mail'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/actionmailer-6.1.4.1/lib/action_mailer/base.rb:557:in `deliver_mail'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
```

The web UI shows e-mail as sent correctly.

**To Reproduce**

1. Set up mail with Office 365 account.
2. Attempt to send an e-mail through e-mail inbox or by creating a new agent.
3. In the logs above error shows up once the Sidekiq picks up the job.

**Expected behavior**

E-mail to be sent.

**Environment**

Self-hosted Chatwoot v. 2.0.0 in Docker

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04

**Comment by piotrpelica** [comment]
I've resolved the issue by reinstalling without Docker
