### ISSUE TITLE
Could not save SMTP settings for an inbox

### ISSUE THREAD

**Issue by TimoKoessler** [chatwoot/chatwoot#3631]
**Describe the bug**

SMTP settings for an e-mail inbox cannot be saved.

**To Reproduce**

Go to the Configuration-Tab of the Inbox-Settings of an Email-Inbox and try to save the SMTP-Settings.

**Browser logs**
Request: _/api/v1/accounts/1/inboxes/2_
```
{
  "channel": {
    "smtp_enabled": true,
    "smtp_address": "smtp.strato.de",
    "smtp_port": "465",
    "smtp_email": "email@domain.de",
    "smtp_password": "password",
    "smtp_domain": "domain.de"
  }
}
```
Response:
```
{"status":500,"error":"Internal Server Error"}
```
  
**Server logs**
```
rails_1     | I, [2021-12-20T15:53:41.524667 #1]  INFO -- : [a290a155-8bac-4996-88c6-eb688e38ae13] Started PATCH "/api/v1/accounts/1/inboxes/2" for IP at 2021-12-20 15:53:41 +0000
rails_1     | I, [2021-12-20T15:53:41.526739 #1]  INFO -- : [a290a155-8bac-4996-88c6-eb688e38ae13] Processing by Api::V1::Accounts::InboxesController#update as JSON
rails_1     | I, [2021-12-20T15:53:41.526818 #1]  INFO -- : [a290a155-8bac-4996-88c6-eb688e38ae13]   Parameters: {"channel"=>{"smtp_enabled"=>true, "smtp_address"=>"smtp.strato.de", "smtp_port"=>"465", "smtp_email"=>"email@domain.de", "smtp_password"=>"[FILTERED]", "smtp_domain"=>"domain.de"}, "account_id"=>"1", "id"=>"2", "inbox"=>{}}
rails_1     | E, [2021-12-20T15:53:56.524673 #1] ERROR -- : source=rack-timeout id=a290a155-8bac-4996-88c6-eb688e38ae13 timeout=15000ms service=15000ms state=timed_out
rails_1     | I, [2021-12-20T15:53:56.526056 #1]  INFO -- : [a290a155-8bac-4996-88c6-eb688e38ae13] Completed 500 Internal Server Error in 14999ms (ActiveRecord: 4.3ms | Allocations: 5489)
rails_1     | F, [2021-12-20T15:53:56.526759 #1] FATAL -- : [a290a155-8bac-4996-88c6-eb688e38ae13]
rails_1     | [a290a155-8bac-4996-88c6-eb688e38ae13] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
```

**Environment**

Selfhosted with Docker (using the provided docker-compose.yml and the latest images) on Debian 11.

Same behavior using different browsers or doing a request with an api client.

Thank you very much for your help,
Timo

**Comment by ncr4development** [comment]
I was able to solve this by making address and domain the same value (in my case smtp.gmail.com) seems that the error handling isn't very accurate. 
However, after I Get the success response, the settings don't seem to persist. 

Also using selfhosted on docker

**Comment by TimoKoessler** [comment]
Hello,
I could not reproduce the wrong success response @ncr4development observed.

Any updates on that issue?

Thanks and greetings,
Timo

**Comment by sojan-official** [comment]
@aswindevps  could you take a look ?

**Comment by aswindevps** [comment]
@sojan-official sure, let me check.

**Comment by ncr4development** [comment]
An upgrade to the 2.0.2 image solved the issue for me today

**Comment by aswindevps** [comment]
@TimoKoessler Could you try "smtp_port": "587"? Please share the server logs.

**Comment by TimoKoessler** [comment]
I can confirm that it is working with port 587.

I have not tried this port because Strato does not list it in its [support documents](https://www.strato.de/faq/mail/so-lauten-die-strato-e-mail-server/) and there has never been a case where SMTP has not worked over port 465.
We use this port in numerous applications and in our own projects, for example with Nodemailer or Phpmailer.

Thanks for your help.

**Comment by TimoKoessler** [comment]
Unfortunately, I was a bit too hasty in closing this issue.

Saving the e-mail settings works without any error, but **no** outgoing messages can be sent from this mailbox.
It is currently not possible to change advanced settings like SMTP_OPENSSL_VERIFY_MODE=none for a mailbox, is it?

```sidekiq_1   | 2022-01-05T09:24:09.356Z pid=1 tid=2bzd WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"mailers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"d23fdd2a-76f3-4369-a213-53aeb3192ff0","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["ConversationReplyMailer","email_reply","deliver_now",{"params":{"account":{"_aj_globalid":"gid://chatwoot/Account/1"},"_aj_symbol_keys":["account"]},"args":[{"_aj_globalid":"gid://chatwoot/Message/14"}],"_aj_ruby2_keywords":["params","args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-01-05T09:23:51Z"}],"jid":"8c489c89f415c0ce96a43b00","created_at":1641374631.998279,"enqueued_at":1641374649.2495496,"error_message":"SSL_connect returned=1 errno=0 state=error: wrong version number","error_class":"OpenSSL::SSL::SSLError","failed_at":1641374632.0931177,"retry_count":0},"jobstr":"{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"d23fdd2a-76f3-4369-a213-53aeb3192ff0\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"ConversationReplyMailer\",\"email_reply\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/1\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/Message/14\"}],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-01-05T09:23:51Z\"}],\"jid\":\"8c489c89f415c0ce96a43b00\",\"created_at\":1641374631.998279,\"enqueued_at\":1641374649.2495496,\"error_message\":\"SSL_connect returned=1 errno=0 state=error: wrong version number\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1641374632.0931177,\"retry_count\":0}"}
sidekiq_1   | 2022-01-05T09:24:09.356Z pid=1 tid=2bzd WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"mailers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"d23fdd2a-76f3-4369-a213-53aeb3192ff0","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["ConversationReplyMailer","email_reply","deliver_now",{"params":{"account":{"_aj_globalid":"gid://chatwoot/Account/1"},"_aj_symbol_keys":["account"]},"args":[{"_aj_globalid":"gid://chatwoot/Message/14"}],"_aj_ruby2_keywords":["params","args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-01-05T09:23:51Z"}],"jid":"8c489c89f415c0ce96a43b00","created_at":1641374631.998279,"enqueued_at":1641374649.2495496,"error_message":"SSL_connect returned=1 errno=0 state=error: wrong version number","error_class":"OpenSSL::SSL::SSLError","failed_at":1641374632.0931177,"retry_count":0},"jobstr":"{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"d23fdd2a-76f3-4369-a213-53aeb3192ff0\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"ConversationReplyMailer\",\"email_reply\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/1\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/Message/14\"}],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-01-05T09:23:51Z\"}],\"jid\":\"8c489c89f415c0ce96a43b00\",\"created_at\":1641374631.998279,\"enqueued_at\":1641374649.2495496,\"error_message\":\"SSL_connect returned=1 errno=0 state=error: wrong version number\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1641374632.0931177,\"retry_count\":0}"}
sidekiq_1   | 2022-01-05T09:24:09.356Z pid=1 tid=2bzd WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number
sidekiq_1   | 2022-01-05T09:24:09.357Z pid=1 tid=2bzd WARN: /usr/local/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:624:in `tlsconnect'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:591:in `do_start'
sidekiq_1   | /usr/local/lib/ruby/3.0.0/net/smtp.rb:557:in `start'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
sidekiq_1   | /gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
sidekiq_1   | /gems/ruby/3.0.0/gems/actionmailer-6.1.4.3/lib/action_mailer/base.rb:559:in `block in deliver_mail'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/notifications.rb:203:in `block in instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/notifications.rb:203:in `instrument'
sidekiq_1   | /gems/ruby/3.0.0/gems/actionmailer-6.1.4.3/lib/action_mailer/base.rb:557:in `deliver_mail'
...
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/job_retry.rb:79:in `global'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/logger.rb:11:in `with'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/job_logger.rb:33:in `prepare'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:123:in `dispatch'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:162:in `process'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:78:in `process_one'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:68:in `run'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
sidekiq_1   | /gems/ruby/3.0.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:52:in `block in safe_thread'
sidekiq_1   | I, [2022-01-05T09:24:09.368807 #1]  INFO -- : [ActiveJob] [EventDispatcherJob] [785be088-5ef0-4167-8e76-c20dc109fdb6] Performed EventDispatcherJob (Job ID: 785be088-5ef0-4167-8e76-c20dc109fdb6) from Sidekiq(events) in 27.79ms
sidekiq_1   | 2022-01-05T09:24:09.369Z pid=1 tid=2ckh class=EventDispatcherJob jid=0a970ab9297e8ee630440beb elapsed=0.066 INFO: done```

**Comment by pranavrajs** [comment]
@aswindevps Since #3700 is completed, can we close this as well?

**Comment by TimoKoessler** [comment]
Yes, that should fix it, thank you. Looking forward to the release.
