### ISSUE TITLE
RoomChannel#update_presence - Could not execute command 

### ISSUE THREAD

**Issue by mtrofimiuk** [chatwoot/chatwoot#3695]
Repeating error logs:

Install version v2.0.2

**Expected behavior**
No errors in logs.

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

```
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: I, [2022-01-05T11:47:45.373703 #583688]  INFO -- : RoomChannel#update_presence
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: E, [2022-01-05T11:47:45.377646 #583688] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"tsezEc8hwqkiyYKwPbXH9cWq\"}", "data"=>"{\"action\":\"update_presence\"}"}) [NoMethodError - undefined method `id' for nil:NilClass]: /home/chatwoot/
chatwoot/app/channels/room_channel.rb:29:in `update_subscription' | /home/chatwoot/chatwoot/app/channels/room_channel.rb:11:in `update_presence' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `public_send' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `dispatch
_action' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:170:in `block in perform_action'
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: I, [2022-01-05T11:47:45.583327 #583688]  INFO -- : RoomChannel#update_presence
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: E, [2022-01-05T11:47:45.586470 #583688] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"qvLrQRq1Y5fpXt1bwBF4PU8U\"}", "data"=>"{\"action\":\"update_presence\"}"}) [NoMethodError - undefined method `id' for nil:NilClass]: /home/chatwoot/
chatwoot/app/channels/room_channel.rb:29:in `update_subscription' | /home/chatwoot/chatwoot/app/channels/room_channel.rb:11:in `update_presence' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `public_send' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `dispatch
_action' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:170:in `block in perform_action'
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: I, [2022-01-05T11:47:45.602801 #583688]  INFO -- : RoomChannel#update_presence
Jan  5 11:47:45 mautic chatwoot-web.1[583688]: E, [2022-01-05T11:47:45.606438 #583688] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"cKAFKSfBvHpUmdCDML4Etfn3\"}", "data"=>"{\"action\":\"update_presence\"}"}) [NoMethodError - undefined method `id' for nil:NilClass]: /home/chatwoot/
chatwoot/app/channels/room_channel.rb:29:in `update_subscription' | /home/chatwoot/chatwoot/app/channels/room_channel.rb:11:in `update_presence' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `public_send' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:270:in `dispatch
_action' | /usr/local/rvm/gems/ruby-3.0.2/gems/actioncable-6.1.4.3/lib/action_cable/channel/base.rb:170:in `block in perform_action'
```

**Environment**
Self hosted on linux VM

**Comment by mtrofimiuk** [comment]
As a workaround, I have silenced these logs with this little hack, for some reason @current_account is not set:

```
diff --git a/app/channels/room_channel.rb b/app/channels/room_channel.rb
index b3c59777..58035301 100644
--- a/app/channels/room_channel.rb
+++ b/app/channels/room_channel.rb
@@ -15,9 +15,10 @@ class RoomChannel < ApplicationCable::Channel
   private
 
   def broadcast_presence
-    data = { account_id: @current_account.id, users: ::OnlineStatusTracker.get_available_users(@current_account.id) }
-    data[:contacts] = ::OnlineStatusTracker.get_available_contacts(@current_account.id) if @current_user.is_a? User
-    ActionCable.server.broadcast(@pubsub_token, { event: 'presence.update', data: data })
+    if @current_account.id
+      data = { account_id: @current_account.id, users: ::OnlineStatusTracker.get_available_users(@current_account.id) }
+      data[:contacts] = ::OnlineStatusTracker.get_available_contacts(@current_account.id) if @current_user.is_a? User
+      ActionCable.server.broadcast(@pubsub_token, { event: 'presence.update', data: data })
   end
 
   def ensure_stream
@@ -26,7 +27,8 @@ class RoomChannel < ApplicationCable::Channel
   end
 
   def update_subscription
-    ::OnlineStatusTracker.update_presence(@current_account.id, @current_user.class.name, @current_user.id)
+    logger.info "Updating subscription"
+    ::OnlineStatusTracker.update_presence(@current_account.id, @current_user.class.name, @current_user.id) if @current_user
   end
 
   def current_user
```

**Comment by sojan-official** [comment]
@mtrofimiuk
- is it a new installation or an existing installation that was recently updated ?
- did you delete/merge any contacts recently?

**Comment by mtrofimiuk** [comment]
The existing installation was updated from v1. I did not merge any contacts.
