### ISSUE TITLE
Unable to send mails using SES: "SocketError: getaddrinfo"

### ISSUE THREAD

**Issue by Christilut** [chatwoot/chatwoot#3767]
**Describe the bug**

Chatwoot is unable to send mails over SMTP using Amazon SES. It looks like it has trouble resolving the SES domain.

**To Reproduce**

docker-compose env vars:

```
services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: chatwoot/.env
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    container_name: chatwoot
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:3000
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SMTP_ADDRESS=email-smtp.eu-central-1.amazonaws.com
      - SMTP_AUTHENTICATION=plain
      - SMTP_USERNAME=abc
      - SMTP_PASSWORD=123
      - SMTP_ENABLE_STARTTLS_AUTO=true
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
```

Send transcript email. Check Sidekiq logs, the error appears.

**Expected behavior**

Should send email

**Server logs**

Sidekiq logs:
```
2022-01-13T09:39:48.607Z pid=1 tid=2c4d class=ActionMailer::MailDeliveryJob jid=f0ed6aca37bc989906880c11 elapsed=5.04 INFO: fail
2022-01-13T09:39:48.608Z pid=1 tid=2c4d WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"mailers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"02b49153-66ac-4797-8cd9-f0f45548be60","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["ConversationReplyMailer","conversation_transcript","deliver_now",{"params":{"account":{"_aj_globalid":"gid://chatwoot/Account/1"},"_aj_symbol_keys":["account"]},"args":[{"_aj_globalid":"gid://chatwoot/Conversation/1"},"test@example.com"],"_aj_ruby2_keywords":["params","args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-01-13T09:39:43Z"}],"jid":"f0ed6aca37bc989906880c11","created_at":1642066783.5669825,"enqueued_at":1642066783.567171},"jobstr":"{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"02b49153-66ac-4797-8cd9-f0f45548be60\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"ConversationReplyMailer\",\"conversation_transcript\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/1\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/Conversation/1\"},\"test@example.com\"],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-01-13T09:39:43Z\"}],\"jid\":\"f0ed6aca37bc989906880c11\",\"created_at\":1642066783.5669825,\"enqueued_at\":1642066783.567171}"}
2022-01-13T09:39:48.608Z pid=1 tid=2c4d WARN: SocketError: getaddrinfo: Try again
2022-01-13T09:39:48.608Z pid=1 tid=2c4d WARN: /usr/local/lib/ruby/3.0.0/net/smtp.rb:578:in `initialize'
/usr/local/lib/ruby/3.0.0/net/smtp.rb:578:in `open'
/usr/local/lib/ruby/3.0.0/net/smtp.rb:578:in `tcp_socket'
/usr/local/lib/ruby/3.0.0/net/smtp.rb:588:in `block in do_start'
/usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
/usr/local/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
/usr/local/lib/ruby/3.0.0/net/smtp.rb:587:in `do_start'
/usr/local/lib/ruby/3.0.0/net/smtp.rb:557:in `start'
/gems/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
```

**Environment**

Self hosted on bare metal machine using docker-compose from the Chatwoot documentation website.

Chatwoot 2.1.0

**Desktop (please complete the following information):**
 - OS: Ubuntu server 20.04

**Additional context**

I ran telnet from the host machine and from inside the docker container, both were able to connect to the SMTP server.

**Comment by sojan-official** [comment]
@vishnu-narayanan  could you take a look ?

**Comment by Christilut** [comment]
Anything I can try? Would like to start using Chatwoot but no emails is blocking that

**Comment by sojan-official** [comment]
@Christilut  The emails are sent from sidekiq. looking at the docker-compose I can see that the environment variables are only made available to the rails server.  You would want to expose them to sidekiq as well .

**Comment by Christilut** [comment]
Thanks! That was exactly it. That wasn't clear for me from the docs :)
