### ISSUE TITLE
dockerhub builds failing on develop

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#4045]
**Describe the bug**

dockerhub builds failing on develop after the version update of gems.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to dockerhub.
2. Click on chatwoot builds.
3. See error.

https://hub.docker.com/repository/docker/chatwoot/chatwoot/builds

**Expected behaviour**

Builds should pass.

**Screenshots**

![image](https://user-images.githubusercontent.com/3526167/155156679-ec2b952f-0350-44e8-8eed-99d6a2b4428a.png)

**Browser logs**

n/a

**Server logs**

n/a

**Environment**

n/a

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by vishnu-narayanan** [comment]
# logs from docker build

<details>
  <summary>Click to expand!</summary>
  
```
Fetching kaminari-core 1.2.2
Installing thor 1.2.1
Installing kaminari-core 1.2.2
Fetching ffi 1.15.5
Fetching tilt 2.0.10
Installing tilt 2.0.10
Fetching selectize-rails 0.12.6
Installing ffi 1.15.5 with native extensions
Installing selectize-rails 0.12.6
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching attr_extras 6.2.5
Installing attr_extras 6.2.5
Fetching aws-eventstream 1.2.0
Installing aws-eventstream 1.2.0
Fetching aws-partitions 1.556.0
Installing aws-partitions 1.556.0
Fetching jmespath 1.6.0
Installing jmespath 1.6.0
Fetching multipart-post 2.1.1
Fetching connection_pool 2.2.5
Installing multipart-post 2.1.1
Installing connection_pool 2.2.5
Fetching multi_json 1.15.0
Fetching statsd-ruby 1.5.0
Installing multi_json 1.15.0
Installing statsd-ruby 1.5.0
Fetching bcrypt 3.1.16
Fetching msgpack 1.4.5
Installing bcrypt 3.1.16 with native extensions
Installing msgpack 1.4.5 with native extensions
Fetching brakeman 5.2.1
Installing brakeman 5.2.1
Fetching browser 5.3.1
Installing browser 5.3.1
Using bundler 2.3.7
Fetching commonmarker 0.23.2
Installing commonmarker 0.23.2 with native extensions
Fetching debase-ruby_core_source 0.10.14
Installing debase-ruby_core_source 0.10.14
Fetching declarative 0.0.20
Installing declarative 0.0.20
Fetching orm_adapter 0.5.0
Installing orm_adapter 0.5.0
Fetching digest-crc 0.6.4
Installing digest-crc 0.6.4 with native extensions
Fetching unf_ext 0.0.8
Installing unf_ext 0.0.8 with native extensions
Fetching dotenv 2.7.6
Installing dotenv 2.7.6
Fetching regexp_parser 2.2.1
Installing regexp_parser 2.2.1
Fetching email_reply_trimmer 0.1.13
Installing email_reply_trimmer 0.1.13
Fetching execjs 2.8.1
Installing execjs 2.8.1
Fetching mime-types-data 3.2022.0105
Installing mime-types-data 3.2022.0105
Fetching multi_xml 0.6.0
Installing multi_xml 0.6.0
Fetching flag_shih_tzu 0.3.23
Installing flag_shih_tzu 0.3.23
Fetching foreman 0.87.2
Installing foreman 0.87.2
Fetching raabro 1.4.0
Installing raabro 1.4.0
Fetching google-protobuf 3.19.4
Installing google-protobuf 3.19.4 with native extensions
Fetching jwt 2.3.0
Installing jwt 2.3.0
Fetching memoist 0.16.2
Installing memoist 0.16.2
Fetching os 1.1.4
Installing os 1.1.4
Fetching geocoder 1.7.3
Installing geocoder 1.7.3
Fetching gli 2.21.0
Installing gli 2.21.0
Fetching httpclient 2.8.3
Installing httpclient 2.8.3
Fetching trailblazer-option 0.1.2
Installing trailblazer-option 0.1.2
Fetching uber 0.1.0
Installing uber 0.1.0
Fetching retriable 3.1.2
Installing retriable 3.1.2
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching google-cloud-errors 1.2.0
Installing google-cloud-errors 1.2.0
Fetching haikunator 1.1.1
Installing haikunator 1.1.1
Fetching sexp_processor 4.16.0
Installing sexp_processor 4.16.0
Fetching hana 1.3.7
Installing hana 1.3.7
Fetching hashie 5.0.0
Installing hashie 5.0.0
Fetching hkdf 0.3.0
Installing hkdf 0.3.0
Fetching http-accept 1.7.0
Installing http-accept 1.7.0
Fetching mini_magick 4.11.0
Installing mini_magick 4.11.0
Fetching json 2.6.1
Installing json 2.6.1 with native extensions
Fetching uri_template 0.7.0
Installing uri_template 0.7.0
Fetching line-bot-api 1.23.0
Installing line-bot-api 1.23.0
Fetching liquid 5.1.0
Installing liquid 5.1.0
Fetching maxminddb 0.1.22
Installing maxminddb 0.1.22
Fetching netrc 0.11.0
Installing netrc 0.11.0
Fetching newrelic_rpm 8.4.0
Installing newrelic_rpm 8.4.0
Fetching oauth 0.5.8
Installing oauth 0.5.8
Fetching pg 1.3.2
Installing pg 1.3.2 with native extensions
Fetching rack-timeout 0.6.0
Installing rack-timeout 0.6.0
Fetching redis 4.6.0
Installing redis 4.6.0
Fetching semantic_range 3.0.0
Installing semantic_range 3.0.0
Fetching telephone_number 1.4.13
Installing telephone_number 1.4.13
Fetching wisper 2.0.0
Fetching rack-test 1.1.0
Installing wisper 2.0.0
Fetching warden 1.2.9
Installing rack-test 1.1.0
Fetching rack-attack 6.6.0
Installing warden 1.2.9
Fetching rack-cors 1.1.1
Installing rack-attack 6.6.0
Fetching rack-proxy 0.7.2
Installing rack-cors 1.1.1
Fetching i18n 1.10.0
Installing rack-proxy 0.7.2
Fetching tzinfo 2.0.4
Installing i18n 1.10.0
Installing tzinfo 2.0.4
Fetching sprockets 4.0.2
Fetching sentry-ruby-core 5.1.0
Installing sprockets 4.0.2
Installing sentry-ruby-core 5.1.0
Fetching websocket-driver 0.7.5
Fetching mail 2.7.1
Installing websocket-driver 0.7.5 with native extensions
Installing mail 2.7.1
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching parser 3.1.1.0
Fetching aws-sigv4 1.4.0
Installing parser 3.1.1.0
Installing aws-sigv4 1.4.0
Fetching nokogiri 1.13.3
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Fetching faraday 1.0.1
Installing nokogiri 1.13.3 with native extensions
Installing faraday 1.0.1
Fetching barnes 0.0.9
Installing barnes 0.0.9
Fetching puma 5.6.2
Installing puma 5.6.2 with native extensions
Fetching bootsnap 1.10.3
Installing bootsnap 1.10.3 with native extensions
Fetching ddtrace 0.54.2
Installing ddtrace 0.54.2 with native extensions
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching ecma-re-validator 0.4.0
Installing ecma-re-validator 0.4.0
Fetching uglifier 4.2.0
Installing uglifier 4.2.0
Fetching mime-types 3.4.1
Installing mime-types 3.4.1
Fetching sassc 2.4.0
Installing sassc 2.4.0 with native extensions
Fetching ruby-vips 2.1.4
Installing ruby-vips 2.1.4
Fetching representable 3.1.1
Installing representable 3.1.1
Fetching ruby_parser 3.18.1
Installing ruby_parser 3.18.1
Fetching webpush 1.1.0
Installing webpush 1.1.0
Fetching twitty 0.1.4
Installing twitty 0.1.4
Fetching redis-namespace 1.8.1
Installing redis-namespace 1.8.1
Fetching sidekiq 6.4.1
Installing sidekiq 6.4.1
Fetching googleapis-common-protos-types 1.3.0
Installing googleapis-common-protos-types 1.3.0
Fetching activesupport 6.1.4.6
Installing activesupport 6.1.4.6
Fetching et-orbi 1.2.6
Installing et-orbi 1.2.6
Fetching tzinfo-data 1.2021.5
Fetching sentry-ruby 5.1.0
Installing tzinfo-data 1.2021.5
Installing sentry-ruby 5.1.0
Fetching down 5.3.0
Installing down 5.3.0
Fetching aws-sdk-core 3.126.2
Installing aws-sdk-core 3.126.2
Fetching scout_apm 5.1.1
Fetching faraday_middleware 1.2.0
Installing scout_apm 5.1.1 with native extensions
Installing faraday_middleware 1.2.0
Fetching fcm 1.0.5
Installing fcm 1.0.5
Fetching signet 0.16.0
Installing signet 0.16.0
Fetching google-cloud-env 1.5.0
Installing google-cloud-env 1.5.0
Fetching koala 3.1.0
Installing koala 3.1.0
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching json_schemer 0.2.19
Installing json_schemer 0.2.19
Fetching httparty 0.20.0
Installing httparty 0.20.0
Fetching image_processing 1.12.1
Installing image_processing 1.12.1
Fetching ruby2ruby 2.4.4
Installing ruby2ruby 2.4.4
Fetching sentry-sidekiq 5.1.0
Installing sentry-sidekiq 5.1.0
Fetching grpc 1.43.1
Fetching fugit 1.5.2
Installing fugit 1.5.2
Fetching globalid 1.0.0
Installing globalid 1.0.0
Fetching activemodel 6.1.4.6
Installing activemodel 6.1.4.6
Fetching groupdate 6.0.1
Installing groupdate 6.0.1
Fetching pundit 2.2.0
Installing pundit 2.2.0
Installing grpc 1.43.1 with native extensions
Fetching time_diff 0.3.0
Installing time_diff 0.3.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /gems/ruby/3.0.0/gems/nokogiri-1.13.3/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.0.0 -r
./siteconf20220223-1-2iud90.rb extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS...
yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.0
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.9.13.
Configuration options: --host\=x86_64-pc-linux-musl --enable-static
--disable-shared
--libdir\=/gems/ruby/3.0.0/gems/nokogiri-1.13.3/ports/x86_64-linux-musl/libxml2/2.9.13/lib
--with-iconv\=yes --disable-dependency-tracking --without-python
--without-readline --with-c14n --with-debug --with-threads --disable-shared
--enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0008-htmlParseComment-handle-abruptly-closed-comments.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

[{:url=>
"https://mirror.csclub.uwaterloo.ca/gnome/sources/libxml2/2.9/libxml2-2.9.13.tar.xz",
  :sha256=>"276130602d12fe484ecc03447ee5e759d0465558fbc9d6bd144e3745306ebf0e"}]
Extracting libxml2-2.9.13.tar.xz into
tmp/x86_64-pc-linux-musl/ports/libxml2/2.9.13... ERROR, review
'/gems/ruby/3.0.0/gems/nokogiri-1.13.3/ext/nokogiri/tmp/x86_64-pc-linux-musl/ports/libxml2/2.9.13/extract.log'
to see what happened. Last lines are:
========================================================================
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--prevent-strip
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--enable-cross-build
	--disable-cross-build
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-source-dir
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:460:in
`block in execute': Failed to complete extract task (RuntimeError)
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in
`chdir'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in
`execute'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:413:in
`extract_file'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:90:in
`block in extract'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in
`each'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in
`extract'
from
/gems/ruby/3.0.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:183:in
`cook'
	from extconf.rb:528:in `block (2 levels) in process_recipe'
	from extconf.rb:309:in `chdir'
	from extconf.rb:309:in `chdir_for_build'
	from extconf.rb:528:in `block in process_recipe'
	from <internal:kernel>:90:in `tap'
	from extconf.rb:427:in `process_recipe'
	from extconf.rb:781:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /gems/ruby/3.0.0/extensions/x86_64-linux-musl/3.0.0/nokogiri-1.13.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /gems/ruby/3.0.0/gems/nokogiri-1.13.3 for
inspection.
Results logged to
/gems/ruby/3.0.0/extensions/x86_64-linux-musl/3.0.0/nokogiri-1.13.3/gem_make.out

  /usr/local/lib/ruby/3.0.0/rubygems/ext/builder.rb:91:in `run'
/usr/local/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:48:in `block in
build'
  /usr/local/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/local/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /usr/local/lib/ruby/3.0.0/rubygems/ext/builder.rb:157:in `build_extension'
/usr/local/lib/ruby/3.0.0/rubygems/ext/builder.rb:191:in `block in
build_extensions'
  /usr/local/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `each'
  /usr/local/lib/ruby/3.0.0/rubygems/ext/builder.rb:188:in `build_extensions'
  /usr/local/lib/ruby/3.0.0/rubygems/installer.rb:828:in `build_extensions'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/source/rubygems.rb:204:in
`install'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/worker.rb:62:in `apply_func'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/worker.rb:57:in `block in
process_queue'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in `loop'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing nokogiri (1.13.3), and Bundler cannot
continue.

In Gemfile:
  devise_token_auth was resolved to 1.2.0, which depends on
    rails was resolved to 6.1.4.6, which depends on
      actioncable was resolved to 6.1.4.6, which depends on
        actionpack was resolved to 6.1.4.6, which depends on
          actionview was resolved to 6.1.4.6, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri
The command '/bin/sh -c if [ "$RAILS_ENV" = "production" ]; then   bundle config set without 'development test'; bundle install -j 4 -r 3;   else bundle install -j 4 -r 3;   fi' returned a non-zero code: 5
```
</details>

**Comment by pranavrajs** [comment]
@vishnu-narayanan @sojan-official Removed the Gemfile.lock and regenerated the file in #4059. Let us see if this works, otherwise close the PR.

**Comment by vishnu-narayanan** [comment]
@pranavrajs I also have raised one. I think this should fix it.

**Comment by vishnu-narayanan** [comment]
tar (child): xz: Cannot exec: No such file or directory[¶](https://nokogiri.org/tutorials/installing_nokogiri.html#tar-child-xz-cannot-exec-no-such-file-or-directory)

From the docs

> Starting in v1.13.2, the source archive used for libxml2 and libxslt is compressed with xz (previous versions were compressed with gzip. As a result, when compiling from source, your system will need to have xz installed in order to extract the source code for these libraries.


ref: https://nokogiri.org/tutorials/installing_nokogiri.html#tar-child-xz-cannot-exec-no-such-file-or-directory
