### ISSUE TITLE
bug: Docker build fails during yarn install with ENOENT

### ISSUE THREAD

**Issue by jordan-brough** [chatwoot/chatwoot#4091]
### Summary

I tried to build the docker image from `v2.2.1` on my MacBook and the `yarn install` step fails.

### Context
```
$ /usr/bin/arch
arm64

$ system_profiler SPHardwareDataType | grep "Model Identifier" 
      Model Identifier: MacBookPro18,2

$ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62

$ docker --version
Docker version 20.10.12, build e91ed57
```

### Repro

```
$ git checkout v2.2.1
HEAD is now at ed2772dd Merge branch 'release/2.2.1'

$ docker build . \
  --file docker/Dockerfile \
  --build-arg BUNDLE_WITHOUT='' \
  --build-arg EXECJS_RUNTIME='Node' \
  --build-arg RAILS_ENV='development' \
  --build-arg RAILS_SERVE_STATIC_FILES='false'

...

#15 48.03 [5/5] Building fresh packages...
#15 51.26 error /app/node_modules/deasync: Command failed.
#15 51.26 Exit code: 1
#15 51.26 Command: node ./build.js

...

#15 51.26 Error: spawn node-gyp ENOENT
```

### Full logs
<details><summary>click here</summary>

```
$ docker build . \
  --file docker/Dockerfile \
  --build-arg BUNDLE_WITHOUT='' \
  --build-arg EXECJS_RUNTIME='Node' \
  --build-arg RAILS_ENV='development' \
  --build-arg RAILS_SERVE_STATIC_FILES='false'

[+] Building 66.2s (15/22)                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 37B                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 35B                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ruby:3.0.2-alpine                                                                                                     0.0s
 => [internal] load build context                                                                                                                                        0.1s
 => => transferring context: 284.81kB                                                                                                                                    0.1s
 => [pre-builder  1/13] FROM docker.io/library/ruby:3.0.2-alpine                                                                                                         0.0s
 => CACHED [stage-1 2/6] RUN apk add --update --no-cache     openssl     tzdata     postgresql-client     imagemagick     git   && gem install bundler                   0.0s
 => CACHED [stage-1 3/6] RUN if [ "development" != "production" ]; then   apk add nodejs yarn;   fi                                                                      0.0s
 => CACHED [pre-builder  2/13] RUN apk update   && apk add     openssl     tar     build-base     tzdata     postgresql-dev     postgresql-client     nodejs     yarn    0.0s
 => CACHED [pre-builder  3/13] WORKDIR /app                                                                                                                              0.0s
 => CACHED [pre-builder  4/13] COPY Gemfile Gemfile.lock ./                                                                                                              0.0s
 => CACHED [pre-builder  5/13] RUN apk add --no-cache musl ruby-full ruby-dev gcc make musl-dev openssl openssl-dev g++ linux-headers xz                                 0.0s
 => CACHED [pre-builder  6/13] RUN bundle config set --local force_ruby_platform true                                                                                    0.0s
 => CACHED [pre-builder  7/13] RUN if [ "development" = "production" ]; then   bundle config set without 'development test'; bundle install -j 4 -r 3;   else bundle in  0.0s
 => CACHED [pre-builder  8/13] COPY package.json yarn.lock ./                                                                                                            0.0s
 => ERROR [pre-builder  9/13] RUN yarn install                                                                                                                          66.0s
------                                                                                                                                                                        
 > [pre-builder  9/13] RUN yarn install:                                                                                                                                      
#15 0.339 yarn install v1.22.10                                                                                                                                               
#15 0.416 [1/5] Validating package.json...                                                                                                                                    
#15 0.419 [2/5] Resolving packages...                                                                                                                                         
#15 0.928 [3/5] Fetching packages...                                                                                                                                          
#15 34.39 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#15 34.39 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#15 34.40 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
#15 34.40 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
#15 34.42 [4/5] Linking dependencies...
#15 34.42 warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
#15 34.42 warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
#15 34.42 warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
#15 34.42 warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
#15 34.42 warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
#15 34.42 warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
#15 34.42 warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
#15 34.42 warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
#15 34.42 warning " > @storybook/addons@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning " > @storybook/addons@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/api@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/api@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/client-api@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/client-api@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
#15 34.42 warning "@storybook/addon-links > @storybook/router@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-links > @storybook/router@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
#15 34.42 warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > markdown-to-jsx@7.1.2" has unmet peer dependency "react@>= 0.14.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-colorful@5.1.4" has unmet peer dependency "react@>=16.8.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-colorful@5.1.4" has unmet peer dependency "react-dom@>=16.8.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@13.5.3" has unmet peer dependency "react@>= 0.14.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize@8.3.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip > react-popper@2.2.5" has unmet peer dependency "react@^16.8.0 || ^17".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-composed-ref@1.1.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
#15 34.42 warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest > use-isomorphic-layout-effect@1.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/builder-webpack4@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/builder-webpack4@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/core@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/core@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/source-loader@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.42 warning "@storybook/addon-docs > @storybook/source-loader@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
#15 34.43 warning "@storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.43 warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/core > @storybook/core-client@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/core > @storybook/core-client@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/core > @storybook/core-client@6.2.9" has unmet peer dependency "webpack@*".
#15 34.43 warning "@storybook/addon-docs > @storybook/core > @storybook/core-server@6.2.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/core > @storybook/core-server@6.2.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > downshift@6.1.3" has unmet peer dependency "react@>=16.12.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > markdown-to-jsx@6.11.4" has unmet peer dependency "react@>= 0.14.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-helmet-async@1.0.9" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-helmet-async@1.0.9" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-sizeme@3.0.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".
#15 34.43 warning "@storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-sizeme@3.0.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".
#15 34.43 warning " > @storybook/vue@6.2.9" has unmet peer dependency "css-loader@*".
#15 34.43 warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@*".
#15 34.43 warning "@storybook/vue > vue-docgen-api > @vue/compiler-sfc@3.0.11" has incorrect peer dependency "vue@3.0.11".
#15 34.43 warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
#15 34.43 warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
#15 47.54 [5/5] Building fresh packages...
#15 50.72 error /app/node_modules/deasync: Command failed.
#15 50.72 Exit code: 1
#15 50.72 Command: node ./build.js
#15 50.72 Arguments: 
#15 50.72 Directory: /app/node_modules/deasync
#15 50.72 Output:
#15 50.72 events.js:377
#15 50.72       throw er; // Unhandled 'error' event
#15 50.72       ^
#15 50.72 
#15 50.72 Error: spawn node-gyp ENOENT
#15 50.72     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
#15 50.72     at onErrorNT (internal/child_process.js:469:16)
#15 50.72     at processTicksAndRejections (internal/process/task_queues.js:82:21)
#15 50.72 Emitted 'error' event on ChildProcess instance at:
#15 50.72     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
#15 50.72     at onErrorNT (internal/child_process.js:469:16)
#15 50.72     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
#15 50.72   errno: -2,
#15 50.72   code: 'ENOENT',
#15 50.72   syscall: 'spawn node-gyp',
#15 50.72   path: 'node-gyp',
#15 50.72   spawnargs: [ 'rebuild' ]
#15 50.72 }
#15 50.72 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
```
</details>

**Comment by sojan-official** [comment]
@vishnu-narayanan  could you take a look ?

**Comment by u4d3rc0v3r** [comment]
any update on this? having same issue

**Comment by ahmedshabib** [comment]
The problem seems to be with the vue-jest package depending on desync. 
I removed vue-jest from package.json file and it worked !!

**Comment by sojan-official** [comment]
@ahmedshabib  thanks a lot for reporting back. We will take a look.

**Comment by elassadi** [comment]
any update on this one ? Docker production build failed with the deasync error  mentioned above with for master branch 
<pre><code>
docker production build -f docker/Dockerfile 
#15 64.65 error /app/node_modules/deasync: Command failed.

#15 64.65 Exit code: 1
#15 64.65 Command: node ./build.js
#15 64.65 Arguments:
#15 64.65 Directory: /app/node_modules/deasync
</code></pre>

**Comment by jordan-brough** [comment]
#4693 fixes the issue! Thank you!
