### ISSUE TITLE
Emails are created multiple times when fetchIMAP email jobs returns an error

### ISSUE THREAD

**Issue by sagararyal** [chatwoot/chatwoot#4130]
<img width="1246" alt="Screen Shot 2022-03-08 at 12 13 33 PM" src="https://user-images.githubusercontent.com/5401575/157227683-2d11603d-b626-42cd-a9ac-580863d77f5d.png">

Every single time the cron runs, the same emails are fetched over and over again flooding the inbox.

I removed some dead jobs before taking the screenshots, but these pile up very soon.

Log from Papertrail
```
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482793&selected=1437743768250482793) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482793&selected=1437743768250482793)  pid=4 tid=4lcmk WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"low","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Inboxes::FetchImapEmailsJob","args":[{"job_class":"Inboxes::FetchImapEmailsJob","job_id":"[7153b2f2-7bbe-4881-812d-981cbefcb0a8](https://my.papertrailapp.com/systems/planetchat/events?q=%227153b2f2-7bbe-4881-812d-981cbefcb0a8%22&focus=1437743768250482793&selected=1437743768250482793)","provider_job_id":null,"queue_name":"low","priority":null,"arguments":[{"_aj_globalid":"gid://chatwoot/Channel::Email/4"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-03-08T06:45:15Z"}],"jid":"129e2ddb2fd7377577f116ce","created_at":1646721915.9312048,"enqueued_at":1646722018.6931486,"error_message":"wrong number of arguments (given 0, expected 1..2)","error_class":"ArgumentError","failed_at":1646721948.7379751,"retry_count":1,"retried_at":1646721998.302071},"jobstr":"{\"retry\":true,\"queue\":\"low\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Inboxes::FetchImapEmailsJob\",\"args\":[{\"job_class\":\"Inboxes::FetchImapEmailsJob\",\"job_id\":\"[7153b2f2-7bbe-4881-812d-981cbefcb0a8](https://my.papertrailapp.com/systems/planetchat/events?q=%227153b2f2-7bbe-4881-812d-981cbefcb0a8%22&focus=1437743768250482793&selected=1437743768250482793)\",\"provider_job_id\":null,\"queue_name\":\"low\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/Channel::Email/4\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-03-08T06:45:15Z\"}],\"jid\":\"129e2ddb2fd7377577f116ce\",\"created_at\":1646721915.9312048,\"enqueued_at\":1646722018.6931486,\"error_message\":\"wrong number of arguments (given 0, expected 1..2)\",\"error_class\":\"ArgumentError\",\"failed_at\":1646721948.7379751,\"retry_count\":1,\"retried_at\":1646721998.302071}"}
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482794&selected=1437743768250482794) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482794&selected=1437743768250482794) pid=4 tid=4lcmk WARN: ArgumentError: wrong number of arguments (given 0, expected 1..2)
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482795&selected=1437743768250482795) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482795&selected=1437743768250482795) pid=4 tid=4lcmk WARN: /app/vendor/bundle/ruby/3.0.0/gems/activemodel-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482795&selected=1437743768250482795)/lib/active_model/errors.rb:404:in `add'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482796&selected=1437743768250482796) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482796&selected=1437743768250482796) /app/app/models/message.rb:236:in `validate_attachments_limit'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482797&selected=1437743768250482797) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482797&selected=1437743768250482797) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482797&selected=1437743768250482797)/lib/active_record/associations/builder/collection_association.rb:40:in `block (2 levels) in define_callback'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482798&selected=1437743768250482798) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482798&selected=1437743768250482798) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482798&selected=1437743768250482798)/lib/active_record/associations/collection_association.rb:478:in `block in callback'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482799&selected=1437743768250482799) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482799&selected=1437743768250482799) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482799&selected=1437743768250482799)/lib/active_record/associations/collection_association.rb:477:in `each'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482800&selected=1437743768250482800) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482800&selected=1437743768250482800) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482800&selected=1437743768250482800)/lib/active_record/associations/collection_association.rb:477:in `callback'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482801&selected=1437743768250482801) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482801&selected=1437743768250482801) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482801&selected=1437743768250482801)/lib/active_record/associations/collection_association.rb:453:in `block in replace_on_target'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768250482802&selected=1437743768250482802) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768250482802&selected=1437743768250482802) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768250482802&selected=1437743768250482802)/lib/active_record/associations/collection_association.rb:452:in `catch'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676992&selected=1437743768254676992) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676992&selected=1437743768254676992) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254676992&selected=1437743768254676992)/lib/active_record/associations/collection_association.rb:452:in `replace_on_target'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676993&selected=1437743768254676993) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676993&selected=1437743768254676993) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254676993&selected=1437743768254676993)/lib/active_record/associations/collection_association.rb:285:in `add_to_target'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676994&selected=1437743768254676994) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676994&selected=1437743768254676994) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254676994&selected=1437743768254676994)/lib/active_record/associations/collection_association.rb:108:in `build'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676995&selected=1437743768254676995) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676995&selected=1437743768254676995) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254676995&selected=1437743768254676995)/lib/active_record/associations/collection_proxy.rb:317:in `build'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676996&selected=1437743768254676996) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676996&selected=1437743768254676996) /app/app/mailboxes/mailbox_helper.rb:23:in `block in add_attachments_to_message'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676997&selected=1437743768254676997) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676997&selected=1437743768254676997) /app/app/mailboxes/mailbox_helper.rb:22:in `each'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676998&selected=1437743768254676998) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676998&selected=1437743768254676998) /app/app/mailboxes/mailbox_helper.rb:22:in `add_attachments_to_message'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254676999&selected=1437743768254676999) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254676999&selected=1437743768254676999) /app/app/mailboxes/imap/imap_mailbox.rb:19:in `block in process'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254677000&selected=1437743768254677000) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254677000&selected=1437743768254677000) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254677000&selected=1437743768254677000)/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254677002&selected=1437743768254677002) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254677002&selected=1437743768254677002) /app/vendor/bundle/ruby/3.0.0/gems/activerecord-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254677002&selected=1437743768254677002)/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254677003&selected=1437743768254677003) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254677003&selected=1437743768254677003) /app/vendor/bundle/ruby/3.0.0/gems/activesupport-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254677003&selected=1437743768254677003)/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254677004&selected=1437743768254677004) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254677004&selected=1437743768254677004) /app/vendor/bundle/ruby/3.0.0/gems/activesupport-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254677004&selected=1437743768254677004)/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
Mar 07 22:47:28 [planetchat](https://my.papertrailapp.com/systems/planetchat/events?focus=1437743768254677005&selected=1437743768254677005) [app/worker.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fworker.1&focus=1437743768254677005&selected=1437743768254677005) /app/vendor/bundle/ruby/3.0.0/gems/activesupport-[6.1.4.6](https://my.papertrailapp.com/systems/planetchat/events?q=%226.1.4.6%22&focus=1437743768254677005&selected=1437743768254677005)/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
```

**Comment by sojan-official** [comment]
notes:
>  to debug, create an email with a non-supported attachment type.

**Comment by sagararyal** [comment]
@sojan-official 
new case today. Same behavior seen for an emails that contains:

Content-Transfer-Encoding: base64 I've forwarded the email to hello@chat.. email.

**Comment by sojan-official** [comment]
We have added for this in the latest releases. Please try on v3.5.2 .
