### ISSUE TITLE
Get error in sentry

### ISSUE THREAD

**Issue by skyblue** [chatwoot/chatwoot#4306]
![image](https://user-images.githubusercontent.com/248937/160350359-68d762d4-debe-4c2b-ae00-a3b8de4f3ddb.png)

```
NoMethodError: undefined method `webhook_data' for nil:NilClass
  from app/models/message.rb:127:in `webhook_data'
  from app/listeners/webhook_listener.rb:48:in `message_updated'
  from wisper (2.0.0) lib/wisper/broadcasters/send_broadcaster.rb:5:in `public_send'
  from wisper (2.0.0) lib/wisper/broadcasters/send_broadcaster.rb:5:in `broadcast'
  from wisper (2.0.0) lib/wisper/registration/object.rb:18:in `broadcast'
  from wisper (2.0.0) lib/wisper/publisher.rb:43:in `block in broadcast'
  from set.rb:344:in `each_key'
  from set.rb:344:in `each'
  from wisper (2.0.0) lib/wisper/publisher.rb:42:in `broadcast'
  from app/dispatchers/async_dispatcher.rb:8:in `publish_event'
  from app/jobs/event_dispatcher_job.rb:5:in `perform'
  from activejob (6.1.4.7) lib/active_job/execution.rb:48:in `block in perform_now'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from i18n (1.10.0) lib/i18n.rb:328:in `with_locale'
  from activejob (6.1.4.7) lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.4.7) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
  from activejob (6.1.4.7) lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.4.7) lib/active_job/instrumentation.rb:21:in `block in instrument'
  from activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `block in instrument'
  from activesupport (6.1.4.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `instrument'
  from activejob (6.1.4.7) lib/active_job/instrumentation.rb:31:in `instrument'
  from activejob (6.1.4.7) lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activejob (6.1.4.7) lib/active_job/logging.rb:22:in `block in tag_logger'
  from activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
  from activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:37:in `tagged'
  from activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `tagged'
  from activejob (6.1.4.7) lib/active_job/logging.rb:22:in `tag_logger'
  from activejob (6.1.4.7) lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.4.7) lib/active_job/execution.rb:47:in `perform_now'
  from sentry-rails (5.1.0) lib/sentry/rails/active_job.rb:6:in `perform_now'
  from activejob (6.1.4.7) lib/active_job/execution.rb:25:in `block in execute'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  from activejob (6.1.4.7) lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  from activesupport (6.1.4.7) lib/active_support/execution_wrapper.rb:91:in `wrap'
  from activesupport (6.1.4.7) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.4.7) lib/active_support/execution_wrapper.rb:87:in `wrap'
  from activesupport (6.1.4.7) lib/active_support/reloader.rb:71:in `wrap'
  from activejob (6.1.4.7) lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  from activesupport (6.1.4.7) lib/active_support/callbacks.rb:137:in `run_callbacks'
  from activejob (6.1.4.7) lib/active_job/execution.rb:23:in `execute'
  from activejob (6.1.4.7) lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:196:in `execute_job'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq (6.4.1) lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  from sentry-sidekiq (5.1.0) lib/sentry/sidekiq/sentry_context_middleware.rb:24:in `call'
  from sidekiq (6.4.1) lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq (6.4.1) lib/sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:163:in `block in process'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/job_retry.rb:114:in `local'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/rails.rb:14:in `block in call'
  from activesupport (6.1.4.7) lib/active_support/execution_wrapper.rb:91:in `wrap'
  from activesupport (6.1.4.7) lib/active_support/reloader.rb:72:in `block in wrap'
  from activesupport (6.1.4.7) lib/active_support/execution_wrapper.rb:91:in `wrap'
  from activesupport (6.1.4.7) lib/active_support/reloader.rb:71:in `wrap'
  from sidekiq (6.4.1) lib/sidekiq/rails.rb:13:in `call'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:257:in `stats'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/job_logger.rb:13:in `call'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/job_retry.rb:81:in `global'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq (6.4.1) lib/sidekiq/job_logger.rb:39:in `prepare'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:123:in `dispatch'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:162:in `process'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:78:in `process_one'
  from sidekiq (6.4.1) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.4.1) lib/sidekiq/util.rb:56:in `watchdog'
  from sidekiq (6.4.1) lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by sojan-official** [comment]
@skyblue  could you include the chatwoot version?

**Comment by skyblue** [comment]
docker image : v2.3.1

**Comment by sojan-official** [comment]
@skyblue  I looked into our sentry and wasn't able to find an instance of this error. 
Could you also look into the arguments that were passed into the job?

also is this error event occurring consistently ?
