### ISSUE TITLE
Couldn't save IMAP/SMTP settings for an inbox

### ISSUE THREAD

**Issue by dmpanch** [chatwoot/chatwoot#4329]
**Describe the bug**

IMAP/SMTP settings for an e-mail inbox cannot be saved.

**To Reproduce**

Go to the Configuration-Tab of the Inbox-Settings of an Email-Inbox and try to save the IMAP or SMTP Settings.

Domain/email/password changed for security purposes.

**IMAP Browser logs**

Request: `PATCH /api/v1/accounts/2/inboxes/2`
```
{
    "channel": {
        "imap_enabled": true,
        "imap_address": "imap.gmail.com",
        "imap_port": "993",
        "imap_email": "support@example",
        "imap_password": "password",
        "imap_enable_ssl": true,
        "imap_inbox_synced_at": "2022-03-29T16:26:35.221Z"
    }
}
```

Response: `{"status":500,"error":"Internal Server Error"}`

**IMAP Server logs**

```
rails_1         | I, [2022-03-29T16:23:54.418710 #1]  INFO -- : [89c1df58-cd0d-49fa-96b7-dc536dedb22d] Started PATCH "/api/v1/accounts/2/inboxes/2" for 10.10.10.10 at 2022-03-29 16:23:54 +0000
rails_1         | I, [2022-03-29T16:23:54.424572 #1]  INFO -- : [89c1df58-cd0d-49fa-96b7-dc536dedb22d] Processing by Api::V1::Accounts::InboxesController#update as JSON
rails_1         | I, [2022-03-29T16:23:54.425873 #1]  INFO -- : [89c1df58-cd0d-49fa-96b7-dc536dedb22d]   Parameters: {"channel"=>{"imap_enabled"=>true, "imap_address"=>"imap.gmail.com", "imap_port"=>"993", "imap_email"=>"support@example.com", "imap_password"=>"[FILTERED]", "imap_enable_ssl"=>true, "imap_inbox_synced_at"=>"2022-03-29T16:23:54.342Z"}, "account_id"=>"2", "id"=>"2", "inbox"=>{}}
rails_1         | I, [2022-03-29T16:24:01.178178 #1]  INFO -- : RoomChannel#update_presence
rails_1         | E, [2022-03-29T16:24:09.418145 #1] ERROR -- : source=rack-timeout id=89c1df58-cd0d-49fa-96b7-dc536dedb22d timeout=15000ms service=15002ms state=timed_out
rails_1         | I, [2022-03-29T16:24:09.420944 #1]  INFO -- : [89c1df58-cd0d-49fa-96b7-dc536dedb22d] Completed 500 Internal Server Error in 14994ms (ActiveRecord: 5.4ms | Allocations: 6503)
rails_1         | F, [2022-03-29T16:24:09.423329 #1] FATAL -- : [89c1df58-cd0d-49fa-96b7-dc536dedb22d]
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d]
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/helpers/api/v1/inboxes_helper.rb:22:in `validate_imap'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/helpers/api/v1/inboxes_helper.rb:5:in `validate_email_channel'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/api/v1/accounts/inboxes_controller.rb:52:in `update'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [89c1df58-cd0d-49fa-96b7-dc536dedb22d] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
rails_1         | I, [2022-03-29T16:24:09.426854 #1]  INFO -- : source=rack-timeout id=89c1df58-cd0d-49fa-96b7-dc536dedb22d timeout=15000ms service=15011ms state=completed
```

**SMTP Browser logs**
```
{
    "channel": {
        "smtp_enabled": true,
        "smtp_address": "smtp.gmail.com",
        "smtp_port": "587",
        "smtp_email": "support@example.com",
        "smtp_password": "password",
        "smtp_domain": "smtp.gmail.com",
        "smtp_enable_ssl_tls": false,
        "smtp_enable_starttls_auto": true,
        "smtp_openssl_verify_mode": "peer"
    }
}
```
Response: `{"status":500,"error":"Internal Server Error"}`

**SMTP Server logs**

```
rails_1         | I, [2022-03-29T16:36:28.374045 #1]  INFO -- : [ae50aaf7-7c54-46c1-968d-520542bde737] Started PATCH "/api/v1/accounts/2/inboxes/2" for 91.201.234.188 at 2022-03-29 16:36:28 +0000
rails_1         | I, [2022-03-29T16:36:28.376906 #1]  INFO -- : [ae50aaf7-7c54-46c1-968d-520542bde737] Processing by Api::V1::Accounts::InboxesController#update as JSON
rails_1         | I, [2022-03-29T16:36:28.377076 #1]  INFO -- : [ae50aaf7-7c54-46c1-968d-520542bde737]   Parameters: {"channel"=>{"smtp_enabled"=>true, "smtp_address"=>"smtp.gmail.com", "smtp_port"=>"587", "smtp_email"=>"support@example.com", "smtp_password"=>"[FILTERED]", "smtp_domain"=>"smtp.gmail.com", "smtp_enable_ssl_tls"=>false, "smtp_enable_starttls_auto"=>true, "smtp_openssl_verify_mode"=>"peer"}, "account_id"=>"2", "id"=>"2", "inbox"=>{}}
rails_1         | I, [2022-03-29T16:36:37.224067 #1]  INFO -- : RoomChannel#update_presence
rails_1         | I, [2022-03-29T16:36:41.257202 #1]  INFO -- : RoomChannel#update_presence
rails_1         | E, [2022-03-29T16:36:43.373710 #1] ERROR -- : source=rack-timeout id=ae50aaf7-7c54-46c1-968d-520542bde737 timeout=15000ms service=15006ms state=timed_out
rails_1         | I, [2022-03-29T16:36:43.376012 #1]  INFO -- : [ae50aaf7-7c54-46c1-968d-520542bde737] Completed 500 Internal Server Error in 14999ms (ActiveRecord: 12.0ms | Allocations: 7554)
rails_1         | F, [2022-03-29T16:36:43.378006 #1] FATAL -- : [ae50aaf7-7c54-46c1-968d-520542bde737]
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737]
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/helpers/api/v1/inboxes_helper.rb:33:in `validate_smtp'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/helpers/api/v1/inboxes_helper.rb:6:in `validate_email_channel'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/api/v1/accounts/inboxes_controller.rb:52:in `update'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [ae50aaf7-7c54-46c1-968d-520542bde737] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
rails_1         | I, [2022-03-29T16:36:43.380304 #1]  INFO -- : source=rack-timeout id=ae50aaf7-7c54-46c1-968d-520542bde737 timeout=15000ms service=15012ms state=completed
```

**Environment**

Selfhosted with Docker, using the provided docker-compose.yml and the latest images (v.2.3.2) + https-portal as NGINX and Letsencrypt provider on Ubuntu 20.04.3 LTS as DigitalOcean droplet 1VCPU 2GB RAM.

Same behavior using different browsers.

[docker-compose.yml example](https://pastebin.com/TkZ4X6ZH)
[.env example](https://pastebin.com/Bm6WTk4C)

Thanks!

**Comment by dmpanch** [comment]
Same when trying to create Telegram bot

```
rails_1         | I, [2022-03-29T17:02:35.029862 #1]  INFO -- : source=rack-timeout id=e9d81f14-25e2-4758-8be2-377480b70cf4 timeout=15000ms state=ready
rails_1         | I, [2022-03-29T17:02:35.031838 #1]  INFO -- : [e9d81f14-25e2-4758-8be2-377480b70cf4] Started POST "/api/v1/accounts/2/inboxes" for 91.201.234.188 at 2022-03-29 17:02:35 +0000
rails_1         | I, [2022-03-29T17:02:35.036425 #1]  INFO -- : [e9d81f14-25e2-4758-8be2-377480b70cf4] Processing by Api::V1::Accounts::InboxesController#create as JSON
rails_1         | I, [2022-03-29T17:02:35.038116 #1]  INFO -- : [e9d81f14-25e2-4758-8be2-377480b70cf4]   Parameters: {"channel"=>{"type"=>"telegram", "bot_token"=>"[FILTERED]"}, "account_id"=>"2", "inbox"=>{}}
rails_1         | I, [2022-03-29T17:02:41.201254 #1]  INFO -- : RoomChannel#update_presence
rails_1         | E, [2022-03-29T17:02:50.031645 #1] ERROR -- : source=rack-timeout id=e9d81f14-25e2-4758-8be2-377480b70cf4 timeout=15000ms service=15002ms state=timed_out
rails_1         | I, [2022-03-29T17:02:50.035126 #1]  INFO -- : [e9d81f14-25e2-4758-8be2-377480b70cf4] Completed 500 Internal Server Error in 14996ms (ActiveRecord: 3.0ms | Allocations: 5015)
rails_1         | F, [2022-03-29T17:02:50.037814 #1] FATAL -- : [e9d81f14-25e2-4758-8be2-377480b70cf4]
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4]
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/models/channel/telegram.rb:62:in `ensure_valid_bot_token'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/api/v1/accounts/inboxes_controller.rb:100:in `create_channel'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/api/v1/accounts/inboxes_controller.rb:30:in `block in create'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/api/v1/accounts/inboxes_controller.rb:29:in `create'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1         | [e9d81f14-25e2-4758-8be2-377480b70cf4] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
rails_1         | I, [2022-03-29T17:02:50.041651 #1]  INFO -- : source=rack-timeout id=e9d81f14-25e2-4758-8be2-377480b70cf4 timeout=15000ms service=15012ms state=completed
```

Is the issue somewhere in the data storage area?

**Comment by dmpanch** [comment]
My fault, wrong network config, adding rails container to the external network fixed the issue.

[Working docker-compose.yml.](https://pastebin.com/MqdWFaUY)
