### ISSUE TITLE
Configure agent and inbox limit

### ISSUE THREAD

**Issue by MaoBueno** [chatwoot/chatwoot#4611]
**Describe the bug**

When I enter the super administrator in the "accounts" option in limits and define a limit for agents or inboxes I get the error "The change you wanted was rejected."

**To Reproduce**

1. Go to 'https://{installation-domain}/super_admin'
2. Click on 'accounts'
3. Click on 'edit'
4. //configure limit of agents or inboxes//
5. Click on 'Update account'
6. See error

**Expected behavior**

Confirmation message expected when setting limits

**Environment**

Heroku
Version 2.4.1
![error-limites](https://user-images.githubusercontent.com/50222850/166493343-152d7251-4d2c-4729-8e74-7ceee1c34862.JPG)

**Comment by sojan-official** [comment]
could you provide logs from the rails server?

**Comment by MaoBueno** [comment]
> could you provide logs from the rails server?
2022-05-21T19:45:42.324444+00:00 app[web.1]: I, [2022-05-21T19:45:42.324327 #9]  INFO -- : RoomChannel#update_presence
2022-05-21T19:45:48.003659+00:00 app[web.1]: I, [2022-05-21T19:45:48.003562 #9]  INFO -- : RoomChannel#update_presence
2022-05-21T19:45:48.004283+00:00 app[web.1]: I, [2022-05-21T19:45:48.004229 #9]  INFO -- : RoomChannel#update_presence
2022-05-21T19:45:50.481745+00:00 app[web.1]: I, [2022-05-21T19:45:50.481668 #9]  INFO -- : source=rack-timeout id=5ed82a4e-7aa0-4108-a582-ee6f90671437 wait=3ms timeout=15000ms state=ready
2022-05-21T19:45:50.482176+00:00 app[web.1]: I, [2022-05-21T19:45:50.482143 #9]  INFO -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437] Started PATCH "/super_admin/accounts/2" for 141.101.110.200 at 2022-05-21 19:45:50 +0000
2022-05-21T19:45:50.484064+00:00 app[web.1]: I, [2022-05-21T19:45:50.484020 #9]  INFO -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437] Processing by SuperAdmin::AccountsController#update as HTML
2022-05-21T19:45:50.484113+00:00 app[web.1]: I, [2022-05-21T19:45:50.484083 #9]  INFO -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437]   Parameters: {"authenticity_token"=>"[FILTERED]", "account"=>{"name"=>"Empresa1", "locale"=>"en", "limits"=>{"agents"=>"4", "inboxes"=>""}}, "commit"=>"Update Account", "id"=>"2"}
2022-05-21T19:45:50.485108+00:00 app[web.1]: W, [2022-05-21T19:45:50.485063 #9]  WARN -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437] HTTP Origin header (https://web.chatia.app) didn't match request.base_url (http://web.chatia.app)
2022-05-21T19:45:50.485503+00:00 app[web.1]: I, [2022-05-21T19:45:50.485467 #9]  INFO -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437] Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 953)
2022-05-21T19:45:50.486301+00:00 app[web.1]: F, [2022-05-21T19:45:50.486253 #9] FATAL -- : [5ed82a4e-7aa0-4108-a582-ee6f90671437]
2022-05-21T19:45:50.486303+00:00 app[web.1]: [5ed82a4e-7aa0-4108-a582-ee6f90671437] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
2022-05-21T19:45:50.486304+00:00 app[web.1]: [5ed82a4e-7aa0-4108-a582-ee6f90671437]2022-05-21T19:45:50.486304+00:00 app[web.1]: [5ed82a4e-7aa0-4108-a582-ee6f90671437] actionpack (6.1.5.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
2022-05-21T19:45:50.486304+00:00 app[web.1]: [5ed82a4e-7aa0-4108-a582-ee6f90671437] actionpack (6.1.5.1) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'

**Comment by mxsxs2** [comment]
This happens for us for all form submission in the super_admin area. The log is also very similar. We have the WARN line where the website is HTTPS but the request comes from HTTP. Which i think leads to the InvalidAuthenticityToken Error:
```

{"log":"[36b2419e-69fb-43d2-abd2-6bdf58f07e36] actionpack (6.1.5.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'\n","stream":"stdout","time":"2022-06-07T14:12:31.058403433Z"}
{"log":"[36b2419e-69fb-43d2-abd2-6bdf58f07e36]   \n","stream":"stdout","time":"2022-06-07T14:12:31.058395164Z"}
{"log":"[36b2419e-69fb-43d2-abd2-6bdf58f07e36] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):\n","stream":"stdout","time":"2022-06-07T14:12:31.058385446Z"}
{"log":"F, [2022-06-07T14:12:31.058106 #14] FATAL -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36]   \n","stream":"stdout","time":"2022-06-07T14:12:31.05836363Z"}
{"log":"I, [2022-06-07T14:12:31.055784 #14]  INFO -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36] Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms \| Allocations: 428)\n","stream":"stdout","time":"2022-06-07T14:12:31.055925894Z"}
{"log":"W, [2022-06-07T14:12:31.055194 #14]  WARN -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36] HTTP Origin header (https://private.com) didn't match request.base_url (http://private.com)\n","stream":"stdout","time":"2022-06-07T14:12:31.055319287Z"}
{"log":"I, [2022-06-07T14:12:31.053970 #14]  INFO -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36]   Parameters: {\"authenticity_token\"=\u003e\"[FILTERED]\", \"account_user\"=\u003e{\"account_id\"=\u003e\"1\", \"user_id\"=\u003e\"6\", \"role\"=\u003e\"agent\"}, \"commit\"=\u003e\"Create Account user\"}\n","stream":"stdout","time":"2022-06-07T14:12:31.05409423Z"}
{"log":"I, [2022-06-07T14:12:31.053850 #14]  INFO -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36] Processing by SuperAdmin::AccountUsersController#create as HTML\n","stream":"stdout","time":"2022-06-07T14:12:31.054016901Z"}
{"log":"I, [2022-06-07T14:12:31.050779 #14]  INFO -- : [36b2419e-69fb-43d2-abd2-6bdf58f07e36] Started POST \"/super_admin/account_users\" for 193.120.250.225 at 2022-06-07 14:12:31 +0000\n","stream":"stdout","time":"2022-06-07T14:12:31.050975206Z"}
{"log":"I, [2022-06-07T14:12:31.049971 #14]  INFO -- : source=rack-timeout id=36b2419e-69fb-43d2-abd2-6bdf58f07e36 timeout=15000ms state=ready\n","stream":"stdout","time":"2022-06-07T14:12:31.050206467Z"}
```

**Comment by sojan-official** [comment]
@mxsxs2 @MaoBueno  could you check the FRONTEND_URL environment configuration and see if you have configured the https version?

**Comment by MaoBueno** [comment]
> @mxsxs2 @MaoBueno could you check the FRONTEND_URL environment configuration and see if you have configured the https version?

Yes, the FRONTEND_URL variable is set to https

**Comment by pranavrajs** [comment]
```
HTTP Origin header (https://web.chatia.app/) didn't match request.base_url (http://web.chatia.app/)
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

It seems like this is an issue in the configuration. You cannot access the Chatwoot super_admin in any other URL than the configured FRONTEND_URL.

Please feel free to reopen with more information if it is not the case.
