### ISSUE TITLE
chatwoot fails to start if I enable s3_compatible with minio

### ISSUE THREAD

**Issue by beeyev** [chatwoot/chatwoot#4642]
I followed [this ](https://github.com/chatwoot/chatwoot/issues/1596) instruction to configure working with `minio`
```
# Storage
ACTIVE_STORAGE_SERVICE=s3_compatible
STORAGE_BUCKET_NAME=app
STORAGE_REGION=us-east-1
STORAGE_ACCESS_KEY_ID=admin
STORAGE_SECRET_ACCESS_KEY=12345678
STORAGE_ENDPOINT=http://minio:9000
STORAGE_FORCE_PATH_STYLE=true
```
Everything seems correct, but unfortunately, chatwoot  fails to start with this messages:

```
Bundle complete! 100 Gemfile dependencies, 201 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
+ BUNDLE='bundle check'
+ bundle check
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.8). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.8`.
+ exec bundle exec rails s -p 3000 -b 0.0.0.0
The Gemfile's dependencies are satisfied
=> Booting Puma
=> Rails 6.1.4.7 application starting in production 
=> Run `bin/rails server --help` for more startup options
W, [2022-05-08T09:40:42.761979 #1]  WARN -- : Creating scope :open. Overwriting existing method Conversation.open.

Exiting

/gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/credentials.rb:35:in `set?': undefined method `empty?' for 12345678:Integer (NoMethodError)
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/credential_provider_chain.rb:14:in `block in resolve'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
fom /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/plugins/credentials_configuration.rb:72:in `block in <class:CredentialsConfiguration>'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:72:in `call'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:219:in `block in resolve_defaults'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:59:in `each'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:59:in `each'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:218:in `resolve_defaults'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:211:in `value_at'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:191:in `block in resolve'
from /usr/local/lib/ruby/3.0.0/set.rb:344:in `each_key'
from /usr/local/lib/ruby/3.0.0/set.rb:344:in `each'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:191:in `resolve'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/configuration.rb:152:in `build!'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/base.rb:65:in `build_config'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/base.rb:22:in `initialize'
from /gems/ruby/3.0.0/gems/aws-sdk-s3-1.112.0/lib/aws-sdk-s3/client.rb:431:in `initialize'
from /gems/ruby/3.0.0/gems/aws-sdk-core-3.126.2/lib/seahorse/client/base.rb:102:in `new'
from /gems/ruby/3.0.0/gems/aws-sdk-s3-1.112.0/lib/aws-sdk-s3/resource.rb:28:in `initialize'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/s3_service.rb:16:in `new'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/s3_service.rb:16:in `initialize'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service.rb:61:in `new'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service.rb:61:in `build'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/configurator.rb:17:in `build'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/registry.rb:13:in `block in fetch'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/registry.rb:11:in `fetch'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/service/registry.rb:11:in `fetch'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/lib/active_storage/engine.rb:147:in `block (2 levels) in <class:Engine>'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:51:in `each'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
from /gems/ruby/3.0.0/gems/activestorage-6.1.4.7/app/models/active_storage/blob.rb:354:in `<main>'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
from /app/config/environment.rb:5:in `<main>'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /gems/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
from /gems/ruby/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
from config.ru:3:in `block in <main>'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
from /gems/ruby/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:39:in `start'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
from <internal:kernel>:90:in `tap'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:135:in `perform'
from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
from /gems/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/command/base.rb:69:in `perform'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/command.rb:48:in `invoke'
from /gems/ruby/3.0.0/gems/railties-6.1.4.7/lib/rails/commands.rb:18:in `<main>'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from /gems/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
from bin/rails:4:in `<main>'
```

**Comment by sojan-official** [comment]
@vishnu-narayanan  could you take a look ?

**Comment by vishnu-narayanan** [comment]
@beeyev I see that you are setting `STORAGE_ENDPOINT=http://minio:9000`.

Is `minio` resolvable from chatwoot web/worker containers? Could you confirm?

**Comment by pranavrajs** [comment]
Closing this issue as there was no response for more than 2 weeks. @beeyev Please feel free to reopen if the issue is still there and you can provide more information.
