### ISSUE TITLE
Pre-chat options not saving

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#4770]
Pre-chat field options do not save.

This was reported by another user in #4735 and we too are seeing this.

Running `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile` as directed works but fails:

```
Compilation failed:

warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
    node_modules/foundation-sites/scss/util/_flex.scss 43:7        flex-align()
    app/javascript/dashboard/assets/scss/widgets/_modal.scss 88:5  @import
    app/javascript/dashboard/assets/scss/_woot.scss 34:9           @import
    app/javascript/dashboard/assets/scss/app.scss 1:9              root stylesheet

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
    node_modules/foundation-sites/scss/util/_flex.scss 43:7        flex-align()
    app/javascript/dashboard/assets/scss/widgets/_modal.scss 88:5  @import
    app/javascript/dashboard/assets/scss/_woot.scss 34:9           @import
    app/javascript/dashboard/assets/scss/app.scss 1:9              @import
    app/javascript/dashboard/App.vue 104:9                         root stylesheet

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
    node_modules/foundation-sites/scss/util/_flex.scss 43:7        flex-align()
    app/javascript/dashboard/assets/scss/widgets/_modal.scss 88:5  @import
    app/javascript/dashboard/assets/scss/_woot.scss 34:9           @import
    app/javascript/dashboard/components/ChatList.vue 523:9         root stylesheet

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
    node_modules/foundation-sites/scss/util/_flex.scss 43:7                            flex-align()
    app/javascript/dashboard/assets/scss/widgets/_modal.scss 88:5                      @import
    app/javascript/dashboard/assets/scss/_woot.scss 34:9                               @import
    app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue 88:9  root stylesheet

WARNING: flex-grid-row-align(): flex-start is not a valid value for horizontal alignment. Use left, right, center, justify, or spaced.
    node_modules/foundation-sites/scss/util/_flex.scss 43:7                            flex-align()
    app/javascript/dashboard/assets/scss/widgets/_modal.scss 88:5                      @import
    app/javascript/dashboard/assets/scss/_woot.scss 34:9                               @import
    app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue 180:9  root stylesheet


```

**Comment by iammattmartin** [comment]
after doing this, CW does not load.

```
May 31 11:49:04 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:04.115257 #2250689]  INFO -- : RoomChannel#update_presence
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.237106 #2250689]  INFO -- : source=rack-timeout id=630e5610-776e-43bd-9b6e-d54397c63de3 timeout=15000ms state=ready
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.237743 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3] Started GET "/app/accounts/2/settings/inboxes/list" for x at 2022-05-31 11:49:05 +0000
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.242532 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3] Processing by DashboardController#index as HTML
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.242686 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3]   Parameters: {"params"=>"accounts/2/settings/inboxes/list"}
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.251664 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.1ms | Allocations: 4)
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.255077 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3]   Rendered layout layouts/vueapp.html.erb (Duration: 3.5ms | Allocations: 1587)
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.255481 #2250689]  INFO -- : [630e5610-776e-43bd-9b6e-d54397c63de3] Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms | Allocations: 3778)
May 31 11:49:05 messenger chatwoot-web.1[2250689]: F, [2022-05-31T11:49:05.257143 #2250689] FATAL -- : [630e5610-776e-43bd-9b6e-d54397c63de3]
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3] ActionView::Template::Error (Webpacker can't find application.js in /home/chatwoot/chatwoot/public/packs/manifest.json. Possible causes:
May 31 11:49:05 messenger chatwoot-web.1[2250689]: 1. You want to set webpacker.yml value of compile to true for your environment
May 31 11:49:05 messenger chatwoot-web.1[2250689]:    unless you are using the `webpack -w` or the webpack-dev-server.
May 31 11:49:05 messenger chatwoot-web.1[2250689]: 2. webpack has not yet re-run to reflect updates.
May 31 11:49:05 messenger chatwoot-web.1[2250689]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
May 31 11:49:05 messenger chatwoot-web.1[2250689]: 4. Your webpack configuration is not creating a manifest.
May 31 11:49:05 messenger chatwoot-web.1[2250689]: Your manifest contains:
May 31 11:49:05 messenger chatwoot-web.1[2250689]: {
May 31 11:49:05 messenger chatwoot-web.1[2250689]: }
May 31 11:49:05 messenger chatwoot-web.1[2250689]: ):
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     57:       }
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     58:     </script>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     59:     <% end %>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     60:     <%= javascript_pack_tag 'application' %>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     61:     <%= stylesheet_pack_tag 'application' %>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     62:   </head>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]     63:   <body>
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3]
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3] app/views/layouts/vueapp.html.erb:60
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
May 31 11:49:05 messenger chatwoot-web.1[2250689]: [630e5610-776e-43bd-9b6e-d54397c63de3] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
May 31 11:49:05 messenger chatwoot-web.1[2250689]: I, [2022-05-31T11:49:05.257616 #2250689]  INFO -- : source=rack-timeout id=630e5610-776e-43bd-9b6e-d54397c63de3 timeout=15000ms service=20ms state=comple
```

**Comment by iammattmartin** [comment]
Further update. This was largely due to the assets very large memory use when compiling. I know this was raised some years ago now that to compile requires such a large amount of RAM for such a basic process.

So for the other poster of the referenced case, that could be related and closing for now  along with #4578 which this resolved.
