### ISSUE TITLE
Error 500 on /api/v1/accounts/3/conversations - Caprover

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#4916]
I'm using Chatwoot 2.6.0 on caprover and I'm currently unable to load conversations.
It occurred suddenly.
I answered a conversation, and then I was unable to load unassigned conversations.

**Comment by sojan-official** [comment]
@jean-philippeansel  could you share the logs for the request?

**Comment by jean-philippeansel** [comment]
Thanks @sojan-official, here is the log:

`2022-06-26T07:38:09.209632661Z I, [2022-06-26T07:38:09.209514 #19] INFO -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] Started GET "/api/v1/accounts/3/conversations?status=open&assignee_type=unassigned&page=1" for 82.66.76.119 at 2022-06-26 07:38:09 +0000

2022-06-26T07:38:09.217136112Z I, [2022-06-26T07:38:09.216652 #19] INFO -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] Processing by Api::V1::Accounts::ConversationsController#index as JSON

2022-06-26T07:38:09.229149382Z I, [2022-06-26T07:38:09.217228 #19] INFO -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] Parameters: {"status"=>"open", "assignee_type"=>"unassigned", "page"=>"1", "account_id"=>"3"}

2022-06-26T07:38:09.330457106Z I, [2022-06-26T07:38:09.330239 #19] INFO -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 81.1ms | Allocations: 13662)

2022-06-26T07:38:09.330914067Z I, [2022-06-26T07:38:09.330821 #19] INFO -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] Completed 500 Internal Server Error in 113ms (ActiveRecord: 27.9ms | Allocations: 17699)

2022-06-26T07:38:09.333035429Z F, [2022-06-26T07:38:09.332925 #19] FATAL -- : [35ca8ce6-7d25-4de8-883d-e29453eac66e] 

2022-06-26T07:38:09.333048009Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"active_storage/blobs/redirect", :filename=>#<ActiveStorage::Filename:0x00007f73e78f3308 @filename="">, :signed_id=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYTQ9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e2f16a573729daff3d2258e40cd379018743d592"}, possible unmatched constraints: [:filename]

2022-06-26T07:38:09.333053946Z Did you mean? rails_service_blob_path

2022-06-26T07:38:09.333077267Z rails_service_blob_proxy_url

2022-06-26T07:38:09.333082052Z rails_service_blob_proxy_path):

2022-06-26T07:38:09.333085476Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 22: elsif conversation.unread_incoming_messages.count.zero?

2022-06-26T07:38:09.333088932Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 23: json.messages [conversation.messages.includes([{ attachments: [{ file_attachment: [:blob] }] }]).last.try(:push_event_data)]

2022-06-26T07:38:09.333092458Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 24: else

2022-06-26T07:38:09.333095670Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 25: json.messages conversation.unread_messages.includes([:user, { attachments: [{ file_attachment: [:blob] }] }]).last(10).map(&:push_event_data)

2022-06-26T07:38:09.333099601Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 26: end

2022-06-26T07:38:09.333102710Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 27: 

2022-06-26T07:38:09.333105839Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 28: json.account_id conversation.account_id

2022-06-26T07:38:09.333109033Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] 

2022-06-26T07:38:09.333112185Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/models/attachment.rb:48:in `file_url'

2022-06-26T07:38:09.333115353Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/models/attachment.rb:70:in `file_metadata'

2022-06-26T07:38:09.333118504Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/models/attachment.rb:43:in `push_event_data'

2022-06-26T07:38:09.333135688Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/models/message.rb:107:in `map'

2022-06-26T07:38:09.333139210Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/models/message.rb:107:in `push_event_data'

2022-06-26T07:38:09.333142433Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25:in `map'

2022-06-26T07:38:09.333156853Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25

2022-06-26T07:38:09.333161330Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/accounts/conversations/index.json.jbuilder:10

2022-06-26T07:38:09.333164674Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/accounts/conversations/index.json.jbuilder:9

2022-06-26T07:38:09.333167848Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/accounts/conversations/index.json.jbuilder:8

2022-06-26T07:38:09.333171033Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/views/api/v1/accounts/conversations/index.json.jbuilder:1

2022-06-26T07:38:09.333174179Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'

2022-06-26T07:38:09.333177311Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'

2022-06-26T07:38:09.333180513Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'

2022-06-26T07:38:09.333183782Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/controllers/concerns/switch_locale.rb:24:in `set_locale'

2022-06-26T07:38:09.333186942Z [35ca8ce6-7d25-4de8-883d-e29453eac66e] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

2022-06-26T07:38:09.333659482Z I, [2022-06-26T07:38:09.333565 #19] INFO -- : source=rack-timeout id=35ca8ce6-7d25-4de8-883d-e29453eac66e timeout=15000ms service=130ms state=completed

2022-06-26T07:38:10.244591683Z I, [2022-06-26T07:38:10.244369 #19] INFO -- : Finished "/cable/" [WebSocket] for 92.89.169.23 at 2022-06-26 07:38:10 +0000

2022-06-26T07:38:10.245705074Z I, [2022-06-26T07:38:10.245326 #19] INFO -- : RoomChannel stopped streaming from 9kKjsM3SVRfn3B7eaMmcGNEY

2022-06-26T07:38:11.304830146Z I, [2022-06-26T07:38:11.304542 #19] INFO -- : source=rack-timeout id=59acf531-2e79-4899-9f96-16cf3af394ed timeout=15000ms state=ready
`

**Comment by jean-philippeansel** [comment]
Hi @sojan-official, any news on this ?
I had to stop using Chatwoot because no message can be loaded.

**Comment by pranavrajs** [comment]
@jean-philippeansel It seems like there is not enough to debug the issue. Would it be possible to share the following as well?

- What is the storage you are using? Did you make any recent changes?
- Did you make any customizations in code?
- Have tried rebooting the container? 

If this doesn't help, we would be happy to understand the issue, please schedule a call here. https://calendly.com/chatwoot/support

**Comment by jean-philippeansel** [comment]
Hi @pranavrajs !
I investigated further, and the error 500 is because of a particular conversation that Chatwoot is not able to load. I was able to export the conversation for you as insert queries:

```
INSERT INTO "public"."conversations" ("id", "account_id", "inbox_id", "status", "assignee_id", "created_at", "updated_at", "contact_id", "display_id", "contact_last_seen_at", "agent_last_seen_at", "additional_attributes", "contact_inbox_id", "uuid", "identifier", "last_activity_at", "team_id", "campaign_id", "snoozed_until", "custom_attributes", "assignee_last_seen_at", "first_reply_created_at") VALUES (565, 3, 42, 0, NULL, '2022-06-22 17:25:05.916873', '2022-06-22 17:25:05.953093', 24423, 532, NULL, NULL, '{"source": "email", "in_reply_to": null, "initiated_at": {"timestamp": "2022-06-22T17:25:05.912Z"}, "mail_subject": "FALTA Knowleagework ---- entao eu tenho a solucao ----- antonio campanico ----- professor de primeira classe ao mestrado"}', 24454, '623ddfe8-4948-4ccc-88ad-e9b92254f4ad', NULL, '2022-06-22 17:25:05.909417', NULL, NULL, NULL, '{}', NULL, NULL);

INSERT INTO "public"."messages" ("id", "content", "account_id", "inbox_id", "conversation_id", "message_type", "created_at", "updated_at", "private", "status", "source_id", "content_type", "content_attributes", "sender_type", "sender_id", "external_source_ids", "additional_attributes") VALUES (1638, '[]', 3, 42, 565, 0, '2022-06-22 17:25:05.950261', '2022-06-22 17:25:05.950261', 'f', 0, 'd94ec98b8d4d184a858c74e7e6eda7a9@PC', 8, '"{\"email\":{\"bcc\":null,\"cc\":null,\"content_type\":\"multipart/related; boundary=\\\"----=_NextPart_000_0001_A0D9A647.BC85C041\\\"\",\"date\":\"2022-06-22T18:15:01+01:00\",\"from\":[\"explicacoesddmaterias@yahoo.com\"],\"html_content\":{\"full\":\"\u003c!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.0 Transitional//EN\\\"\u003e\\r\\n\u003cHTML\u003e\u003cHEAD\u003e\\r\\n\u003cMETA content=\\\"text/html; charset=iso-8859-1\\\" http-equiv=Content-Type\u003e\\r\\n\u003cMETA name=GENERATOR content=\\\"MSHTML 9.00.8112.16448\\\"\u003e\u003c/HEAD\u003e\\r\\n\u003cBODY\u003e\\r\\n\u003cP align=center\u003e\u003cIMG border=0 hspace=0 alt=\\\"\\\" align=baseline src=\\\"cid:26e74fee03f0294e8119eaee079607d1@PC\\\"\u003e\u003c/P\u003e\u003c/BODY\u003e\u003c/HTML\u003e\\r\\n\",\"reply\":\"[]\",\"quoted\":\"[]\"},\"in_reply_to\":null,\"message_id\":\"d94ec98b8d4d184a858c74e7e6eda7a9@PC\",\"multipart\":true,\"number_of_attachments\":1,\"subject\":\"FALTA Knowleagework ---- entao eu tenho a solucao ----- antonio campanico ----- professor de primeira classe ao mestrado\",\"text_content\":{},\"to\":[\"info@mydomain.com\"]},\"cc_email\":null,\"bcc_email\":null}"', 'Contact', 24423, '{}', '{}');
```

Is there something here that can cause an error ? account_id, inbox_id, assignee_id and contact_id do exist in the database.

**Comment by uhlhosting** [comment]
I also got issues in latest release using it from caprover with minio. I just upgraded to latest release and managed to finally make minio work. So it works well when I send images from within the mobile app. Yet it fails with 422 when I try ti send it from web browser widget.

**Comment by CraniumAdamantium** [comment]
Facing this issue, if you send images thorugh chat AND if you don't set your storage IN caprover, it simply crashes
>app/models/attachment.rb:53:in `file_url'

**Comment by pranavrajs** [comment]
Closing this as there was no activity on this thread for some time. Please feel free to reopen if it is still an issue.
