### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by Askeshine** [chatwoot/chatwoot#5217]
![image](https://user-images.githubusercontent.com/37356127/183341291-68cf67e3-3f39-4281-ac9f-0499556f7a32.png)

I post last part of log if any want full log i can post i think.

![image](https://user-images.githubusercontent.com/37356127/183341348-16f6f02d-5741-4f13-9694-46db1313d7e0.png)

SO: Ubuntu 20.04.

FULL LOG WHEN START ERRORS:
```

Installing faraday_middleware 1.2.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/racc-1.6.0/ext/racc/cparse
/usr/local/rvm/rubies/ruby-3.0.4/bin/ruby -I /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r ./siteconf20220808-27629-esu7t5.rb extconf.rb
checking for rb_block_call()... yes
checking for rb_ary_subseq()... yes
creating Makefile

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/racc-1.6.0/ext/racc/cparse
make DESTDIR\= clean

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/racc-1.6.0/ext/racc/cparse
make DESTDIR\=
compiling cparse.c
linking shared-object racc/cparse.so

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/racc-1.6.0/ext/racc/cparse
make DESTDIR\= install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.-.racc.time] Error 127

make install failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-3.0.4/gems/racc-1.6.0 for inspection.
Results logged to /usr/local/rvm/gems/ruby-3.0.4/extensions/x86_64-linux/3.0.0/racc-1.6.0/gem_make.out

  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:44:in `block in make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing racc (1.6.0), and Bundler cannot continue.

In Gemfile:
  devise_token_auth was resolved to 1.2.0, which depends on
    rails was resolved to 6.1.6.1, which depends on
      actioncable was resolved to 6.1.6.1, which depends on
        actionpack was resolved to 6.1.6.1, which depends on
          actionview was resolved to 6.1.6.1, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri was resolved to 1.13.7, which depends on
                racc


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bcrypt-3.1.18/ext/mri
/usr/local/rvm/rubies/ruby-3.0.4/bin/ruby -I /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r ./siteconf20220808-27629-wcxa69.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bcrypt-3.1.18/ext/mri
make DESTDIR\= clean

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bcrypt-3.1.18/ext/mri
make DESTDIR\=
compiling bcrypt_ext.c
compiling crypt_blowfish.c
gcc  -D__SKIP_GNU     -c -o x86.o x86.S
compiling crypt_gensalt.c
compiling wrapper.c
wrapper.c:182:60: warning: 'struct crypt_data' declared inside parameter list will not be visible outside of this definition or declaration
  182 | char *crypt_r(const char *key, const char *setting, struct crypt_data *data)
      |                                                            ^~~~~~~~~~
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
linking shared-object bcrypt_ext.so

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bcrypt-3.1.18/ext/mri
make DESTDIR\= install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.time] Error 127

make install failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-3.0.4/gems/bcrypt-3.1.18 for inspection.
Results logged to /usr/local/rvm/gems/ruby-3.0.4/extensions/x86_64-linux/3.0.0/bcrypt-3.1.18/gem_make.out

  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:44:in `block in make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing bcrypt (3.1.18), and Bundler cannot continue.

In Gemfile:
  devise-secure_password was resolved to 2.0.1, which depends on
    devise was resolved to 4.8.1, which depends on
      bcrypt


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bindex-0.8.1/ext/skiptrace
/usr/local/rvm/rubies/ruby-3.0.4/bin/ruby -I /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r ./siteconf20220808-27629-vv3qtw.rb extconf.rb
creating Makefile

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bindex-0.8.1/ext/skiptrace
make DESTDIR\= clean

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bindex-0.8.1/ext/skiptrace
make DESTDIR\=
compiling cruby.c
linking shared-object skiptrace/internal/cruby.so

current directory: /usr/local/rvm/gems/ruby-3.0.4/gems/bindex-0.8.1/ext/skiptrace
make DESTDIR\= install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.-.skiptrace.-.internal.time] Error 127

make install failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-3.0.4/gems/bindex-0.8.1 for inspection.
Results logged to /usr/local/rvm/gems/ruby-3.0.4/extensions/x86_64-linux/3.0.0/bindex-0.8.1/gem_make.out

  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:44:in `block in make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:36:in `make'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing bindex (0.8.1), and Bundler cannot continue.

In Gemfile:
  web-console was resolved to 4.2.0, which depends on
    bindex
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 0.61s.
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.16). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.16`.
rake aborted!
Bundler::GemNotFound: Could not find rails-6.1.6.1, bootsnap-1.12.0, acts-as-taggable-on-9.0.1, jbuilder-2.11.5, kaminari-1.2.2, responders-3.0.1, rest-client-2.1.0, valid_email2-4.0.3, commonmarker-0.23.5, aws-sdk-s3-1.114.0, azure-storage-blob-2.0.3, google-cloud-storage-1.37.0, image_processing-1.12.2, pg-1.4.1, activerecord-import-1.4.0, dotenv-rails-2.7.6, puma-5.6.4, webpacker-5.4.3, devise-4.8.1, devise_token_auth-1.2.0, administrate-0.17.0, facebook-messenger-2.0.1, twilio-ruby-5.68.0, koala-3.2.0, slack-ruby-client-1.0.0, google-cloud-dialogflow-1.5.0, ddtrace-1.2.0, scout_apm-5.2.0, sentry-rails-5.3.1, sidekiq-cron-1.6.0, fcm-1.0.8, hairtrigger-0.2.25, procore-sift-0.16.0, html2text-0.2.1, pg_search-2.3.6, annotate-3.2.0, web-console-4.2.0, database_cleaner-2.0.1, byebug-11.1.3, factory_bot_rails-6.2.0, listen-3.7.1, rspec-rails-5.0.3, rubocop-1.31.2, rubocop-performance-1.14.2, rubocop-rails-2.15.2, rubocop-rspec-2.12.1, seed_dump-3.3.1, simplecov-0.17.1, spring-watcher-listen-2.0.1, actioncable-6.1.6.1, actionmailbox-6.1.6.1, actionmailer-6.1.6.1, actionpack-6.1.6.1, actiontext-6.1.6.1, actionview-6.1.6.1, activejob-6.1.6.1, activerecord-6.1.6.1, activestorage-6.1.6.1, railties-6.1.6.1, sprockets-rails-3.4.2, msgpack-1.5.3, kaminari-actionview-1.2.2, kaminari-activerecord-1.2.2, http-cookie-1.0.5, azure-storage-common-2.0.4, nokogiri-1.13.7-x86_64-linux, google-apis-iamcredentials_v1-0.13.0, google-apis-storage_v1-0.18.0, google-cloud-core-1.6.0, googleauth-1.2.0, ruby-vips-2.1.4, nio4r-2.5.8, bcrypt-3.1.18, datetime_picker_rails-0.0.7, jquery-rails-4.5.0, momentjs-rails-2.29.1.1, sassc-rails-2.1.2, json-2.6.2, websocket-driver-0.7.5, google-cloud-dialogflow-v2-0.17.0, libddwaf-1.3.0.2.0-x86_64-linux, bindex-0.8.1, database_cleaner-active_record-2.0.1, rb-inotify-0.10.1, rails-dom-testing-2.0.3, rails-html-sanitizer-1.4.3, domain_name-0.5.20190701, racc-1.6.0, google-apis-core-0.7.0, ffi-1.15.5, sassc-2.4.0, gapic-common-0.10.0, google-cloud-location-0.2.0, loofah-2.18.0, unf-0.1.4, unf_ext-0.0.8.2 in any of the sources
<internal:/usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/chatwoot/chatwoot/config/boot.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/config/application.rb:3:in `require_relative'
/home/chatwoot/chatwoot/config/application.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/Rakefile:4:in `require_relative'
/home/chatwoot/chatwoot/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'
(See full trace by running task with --trace)


```

**Comment by vishnu-narayanan** [comment]
Could you try running the below command and then rerunning the installer?
```sudo ln -s /bin/mkdir /usr/bin/mkdir```

```
./install.sh --install
```

**Comment by msindisi** [comment]
Im getting the same error.

**Comment by vishnu-narayanan** [comment]
@msindisi the above solution worked for @Askeshine. Could you please try that?

**Comment by vishnu-narayanan** [comment]
@msindisi Please reopen this issue if it is not working for you.
