### ISSUE TITLE
Push notification failing for web/mobile

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#5471]
Both web and chatwoot app notification doesn't work anymore and i see the following error in console (at least for web push) and i don't get mobile push notification as well when it used to work previously. I am unsure what has changed on my side. I don't think i've changed anything significantly that could effect this.

Any help to point to the right direction for troubleshooting would be much appreciated.

CW version: 2.8.1
Type: Self hosted
OS: Ubuntu 20.04
Mobile version: 1.6.5
Browser: Edge 105

The following log is generated when push is enabled on browser. I also do not receive any, it seem to crash rails and a restart happens.

Logs:
```
2022-09-21T02:16:04.962Z pid=62303 tid=1o3b WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Notification::PushNotificationJob","args":[{"job_class":"Notification::PushNotificationJob","job_id":"e9731992-ef8e-4b65-a6bc-83e888b05607","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://chatwoot/Notification/411"}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2022-09-21T02:16:04Z"}],"jid":"ee351005ad7a299a0c5d3a96","created_at":1663726564.858791,"enqueued_at":1663726564.8589768},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Notification::PushNotificationJob\",\"args\":[{\"job_class\":\"Notification::PushNotificationJob\",\"job_id\":\"e9731992-ef8e-4b65-a6bc-83e888b05607\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/Notification/411\"}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2022-09-21T02:16:04Z\"}],\"jid\":\"ee351005ad7a299a0c5d3a96\",\"created_at\":1663726564.858791,\"enqueued_at\":1663726564.8589768}"}
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: 2022-09-21T02:16:04.962Z pid=62303 tid=1o3b WARN: Webpush::Unauthorized: host: wns2-sg2p.notify.windows.com, #<Net::HTTPUnauthorized 401 Unauthorized readbody=true>
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: body:
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: 2022-09-21T02:16:04.962Z pid=62303 tid=1o3b WARN: /usr/local/rvm/gems/ruby-3.0.4/gems/webpush-1.1.0/lib/webpush/request.rb:175:in `verify_response'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/webpush-1.1.0/lib/webpush/request.rb:34:in `perform'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/webpush-1.1.0/lib/webpush.rb:44:in `payload_send'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /home/chatwoot/chatwoot/app/services/notification/push_notification_service.rb:52:in `send_browser_push'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /home/chatwoot/chatwoot/app/services/notification/push_notification_service.rb:10:in `block in perform'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/delegation.rb:88:in `each'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/delegation.rb:88:in `each'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /home/chatwoot/chatwoot/app/services/notification/push_notification_service.rb:9:in `perform'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /home/chatwoot/chatwoot/app/jobs/notification/push_notification_job.rb:5:in `perform'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/execution.rb:48:in `block in perform_now'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/i18n-1.11.0/lib/i18n.rb:322:in `with_locale'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:21:in `block in instrument'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:31:in `instrument'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `block in tag_logger'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:37:in `tagged'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `tagged'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `tag_logger'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/execution.rb:47:in `perform_now'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sentry-rails-5.3.1/lib/sentry/rails/active_job.rb:6:in `perform_now'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/execution.rb:25:in `block in execute'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:72:in `block in wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:71:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/execution.rb:23:in `execute'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activejob-6.1.6.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:196:in `execute_job'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sentry-sidekiq-5.3.1/lib/sentry/sidekiq/sentry_context_middleware.rb:24:in `call'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:163:in `block in process'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:114:in `local'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:72:in `block in wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:71:in `wrap'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:257:in `stats'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:13:in `call'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:81:in `global'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:39:in `prepare'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:123:in `dispatch'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:162:in `process'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:78:in `process_one'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:68:in `run'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
Sep 21 02:16:04 sg01 chatwoot-worker.1[62303]: /usr/local/rvm/gems/ruby-3.0.4/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by ankwad** [comment]
Any update on this one.. 
This is an essential feature..
Without notification how can we support customers immediately

**Comment by mariusa** [comment]
I'm using the https://app.chatwoot.com/ version and also don't get browser notifications, nor sound notifications. I've checked profile settings and browser site settings. 
The only indicator I get is the changed favicon with a red dot -- good, but easy to miss.

I get mobile app notifications.

**Comment by DblK** [comment]
Any update on it?

**Comment by pavlotsyhanok** [comment]
Any updtate?

**Comment by juliomac** [comment]
any update?

**Comment by sojan-official** [comment]
@DblK @pavlotsyhanok @juliomac  could you add your environment details?

**Comment by sojan-official** [comment]
If anybody is experiencing issues on Chatwoot Cloud, please use the in-app support to reach out so that we can take a look at the account

**Comment by stonecharioteer** [comment]
This issue is being closed due to lack of activity for over a year. [For more details, visit this discussion.](https://github.com/orgs/chatwoot/discussions/12810)
