### ISSUE TITLE
Deployment behind SSL terminating proxy

### ISSUE THREAD

**Issue by mxsxs2** [chatwoot/chatwoot#5506]
**Describe the bug**

We have an installation where HAProxy is terminating SSL in front of Kubernetes with (Nginx inc ingress controller) where Chatwoot is deployed. Chatwoot superadmin checks whether the request is coming from the `FRONTEND_URL` or not. This fails as my `FRONTEND_URL` is HTTPS and the request URL is not. 

A possible solution could be to allow the HTTP version of the URL or to allow us to define a list of alternative URLs similar how [Grafana's allowed_origins](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allowed_origins) works.

**To Reproduce**

1. Install Chatwoot behind a proxy/ingress that terminates SSL
2. Configure `FRONTEND_URL` to HTTPS
2. Try to create an account in superadmin area

**Expected behavior**

Can use superadmin area

**Screenshots**

![image](https://user-images.githubusercontent.com/13612429/192541296-7f223626-2834-492c-b296-df8ae37b99f4.png)

**Browser logs**

```
accounts:1          POST https://mydomain.com/super_admin/accounts 422
```

**Server logs**

```
I, [2022-09-27T13:31:24.439024 #1]  INFO -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf] Started POST "/super_admin/accounts" for xxx.xxx.xxx.xxx at 2022-09-27 13:31:24 +0000
I, [2022-09-27T13:31:24.440814 #1]  INFO -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf] Processing by SuperAdmin::AccountsController#create as HTML
I, [2022-09-27T13:31:24.440904 #1]  INFO -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf]   Parameters: {"authenticity_token"=>"[FILTERED]", "account"=>{"name"=>"My Account", "locale"=>"en", "status"=>"active", "limits"=>{"agents"=>"0", "inboxes"=>""}}, "commit"=>"Create Account"}
W, [2022-09-27T13:31:24.441519 #1]  WARN -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf] HTTP Origin header (https://mydomain.com) didn't match request.base_url (http://mydomain.com)
I, [2022-09-27T13:31:24.442012 #1]  INFO -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf] Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 429)
F, [2022-09-27T13:31:24.443462 #1] FATAL -- : [411d1a56-28f5-4517-b005-3a29a5dd8faf]
[411d1a56-28f5-4517-b005-3a29a5dd8faf] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[411d1a56-28f5-4517-b005-3a29a5dd8faf]
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] devise (4.8.1) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:199:in `block in halting'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:512:in `each'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:512:in `invoke_before'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actiontext (6.1.6.1) lib/action_text/rendering.rb:20:in `with_renderer'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actiontext (6.1.6.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:126:in `instance_exec'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/notifications.rb:203:in `block in instrument'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/notifications.rb:203:in `instrument'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activerecord (6.1.6.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/abstract_controller/base.rb:165:in `process'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionview (6.1.6.1) lib/action_view/rendering.rb:39:in `process'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal.rb:190:in `dispatch'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_controller/metal.rb:254:in `dispatch'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] scout_apm (5.2.0) lib/scout_apm/middleware.rb:17:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/etag.rb:27:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/head.rb:12:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-rails (5.3.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:26:in `block (2 levels) in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry/hub.rb:199:in `with_session_tracking'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry-ruby.rb:351:in `with_session_tracking'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:17:in `block in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry/hub.rb:59:in `with_scope'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry-ruby.rb:331:in `with_scope'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:16:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] railties (6.1.6.1) lib/rails/rack/logger.rb:37:in `call_app'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] railties (6.1.6.1) lib/rails/rack/logger.rb:26:in `block in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/tagged_logging.rb:37:in `tagged'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/tagged_logging.rb:99:in `tagged'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] railties (6.1.6.1) lib/rails/rack/logger.rb:26:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/method_override.rb:24:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/runtime.rb:22:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] activesupport (6.1.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/static.rb:24:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] actionpack (6.1.6.1) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] railties (6.1.6.1) lib/rails/engine.rb:539:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
[411d1a56-28f5-4517-b005-3a29a5dd8faf] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Environment**

Deployed into self hosted Kubernetes with helm as described in [the documentation](https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 105.0.5195.127 (Official Build) (64-bit)

**Additional context**

This issue was partially discussed at https://github.com/chatwoot/chatwoot/issues/4611 without resolution.

**Comment by vishnu-narayanan** [comment]
@mxsxs2 Could you try adding `proxy_set_header X-Forwarded-Proto https;` config to your nginx ingress controller?

**Comment by mxsxs2** [comment]
> @mxsxs2 Could you try adding `proxy_set_header X-Forwarded-Proto https;` config to your nginx ingress controller?

Unfortunatelly that is not something that one can set on the controller. It is described at: https://github.com/nginxinc/kubernetes-ingress/issues/1284

Therefore, I added it to the ingress itself in the `values.yaml` file i used to install the chart with:
```
ingress:
  enabled: ture
  ingressClassName: nginx
  annotations:
    nginx.org/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    nginx.org/location-snippets: |
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Proto https;
  hosts: 
    - host: mydomain.com
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: chatwoot
            port:
              number: 3000
```

This generates the following nginx config:
```
# configuration for chatwoot/chatwoot

upstream chatwoot-chatwoot-chat.mydomain.com-chatwoot-3000 {
        zone chatwoot-chatwoot-chat.mydomain.com-chatwoot-3000 256k;
        random two least_conn;

        server 10.244.0.121:3000 max_fails=1 fail_timeout=10s max_conns=0;

}


server {


        listen 80 proxy_protocol;
        listen [::]:80 proxy_protocol;








        server_tokens on;

        server_name mydomain.com;

        set $resource_type "ingress";
        set $resource_name "chatwoot";
        set $resource_namespace "chatwoot";







        location / {
                set $service "chatwoot";


                proxy_http_version 1.1;


                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-Proto https;


                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 100m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering on;

                proxy_pass http://chatwoot-chatwoot-mydomain.com-chatwoot-3000;


        }


}
```

You can see the above referenced bug adds the `proxy_set_header X-Forwarded-Proto $scheme;` line. Anyhow, it still works. I assume the specified `https` takes precedence over a variable.

Thanks for pointing to the right direction!

**Comment by sojan-official** [comment]
@vishnu-narayanan can we add this to our docs ?

**Comment by vishnu-narayanan** [comment]
@mxsxs2 Happy that you got it working, and thank you for sharing the solution that worked for you.
