### ISSUE TITLE
problems accessing chatwoot Caprover

### ISSUE THREAD

**Issue by walderfranco** [chatwoot/chatwoot#5707]
Hi,
I have installed Chatwoot on Caprover using AWS Lightsail.
After installation everything works fine using the subdomain that caprover generates but after activating https and Websocket Support the application (chatwoot) gives me the following error.

![image](https://user-images.githubusercontent.com/49401126/197227601-0c33b2f8-5092-4521-a8b5-9220e66e6b01.png)

I don't know what could be happening.

```
Logs:
2022-10-21T15:03:14.224558826Z + rm -rf /app/tmp/pids/server.pid
2022-10-21T15:03:14.225285039Z + rm -rf '/app/tmp/cache/*'
2022-10-21T15:03:14.225990914Z + echo 'Waiting for postgres to become ready....'
2022-10-21T15:03:14.225998808Z Waiting for postgres to become ready....
2022-10-21T15:03:14.226007191Z + docker/entrypoints/helpers/pg_database_url.rb
2022-10-21T15:03:14.342848271Z + export 'POSTGRES_PORT=5432'
2022-10-21T15:03:14.342878882Z + PG_READY='pg_isready -h srv-captain--aceinternational-chatwoot-postgres -p 5432 -U chatwoot'
2022-10-21T15:03:14.342885836Z + pg_isready -h srv-captain--aceinternational-chatwoot-postgres -p 5432 -U chatwoot
2022-10-21T15:03:14.347997337Z + echo 'Database ready to accept connections.'
2022-10-21T15:03:14.348015686Z srv-captain--aceinternational-chatwoot-postgres:5432 - accepting connections
2022-10-21T15:03:14.348033686Z Database ready to accept connections.
2022-10-21T15:03:14.348018326Z + bundle install
2022-10-21T15:03:14.840660133Z Using rake 13.0.6
2022-10-21T15:03:14.841210947Z Using concurrent-ruby 1.1.10
2022-10-21T15:03:14.841668714Z Using i18n 1.11.0
2022-10-21T15:03:14.842275802Z Using minitest 5.16.2
2022-10-21T15:03:14.842846218Z Using tzinfo 2.0.4
2022-10-21T15:03:14.843335309Z Using zeitwerk 2.6.0
2022-10-21T15:03:14.843913045Z Using activesupport 6.1.6.1
2022-10-21T15:03:14.844400806Z Using builder 3.2.4
2022-10-21T15:03:14.844903681Z Using erubi 1.10.0
2022-10-21T15:03:14.845438153Z Using mini_portile2 2.8.0
2022-10-21T15:03:14.845608619Z Using racc 1.6.0
2022-10-21T15:03:14.845759462Z Using nokogiri 1.13.7
2022-10-21T15:03:14.846271740Z Using rails-dom-testing 2.0.3
2022-10-21T15:03:14.846834448Z Using crass 1.0.6
2022-10-21T15:03:14.847492879Z Using loofah 2.18.0
2022-10-21T15:03:14.848046079Z Using rails-html-sanitizer 1.4.3
2022-10-21T15:03:14.848601126Z Using actionview 6.1.6.1
2022-10-21T15:03:14.849268389Z Using rack 2.2.4
2022-10-21T15:03:14.849814482Z Using rack-test 2.0.2
2022-10-21T15:03:14.850446049Z Using actionpack 6.1.6.1
2022-10-21T15:03:14.850596456Z Using nio4r 2.5.8
2022-10-21T15:03:14.851123802Z Using websocket-extensions 0.1.5
2022-10-21T15:03:14.851301120Z Using websocket-driver 0.7.5
2022-10-21T15:03:14.851978856Z Using actioncable 6.1.6.1
2022-10-21T15:03:14.852422383Z Using globalid 1.0.0
2022-10-21T15:03:14.852929189Z Using activejob 6.1.6.1
2022-10-21T15:03:14.853344851Z Using activemodel 6.1.6.1
2022-10-21T15:03:14.853830298Z Using activerecord 6.1.6.1
2022-10-21T15:03:14.854461354Z Using marcel 1.0.2
2022-10-21T15:03:14.854993043Z Using mini_mime 1.1.2
2022-10-21T15:03:14.855533338Z Using activestorage 6.1.6.1
2022-10-21T15:03:14.856135088Z Using mail 2.7.1
2022-10-21T15:03:14.856719206Z Using actionmailbox 6.1.6.1
2022-10-21T15:03:14.857294724Z Using actionmailer 6.1.6.1
2022-10-21T15:03:14.857813000Z Using actiontext 6.1.6.1
2022-10-21T15:03:14.858251249Z Using activerecord-import 1.4.0
2022-10-21T15:03:14.858850052Z Using acts-as-taggable-on 9.0.1
2022-10-21T15:03:14.859358744Z Using public_suffix 4.0.7
2022-10-21T15:03:14.859818982Z Using addressable 2.8.0
2022-10-21T15:03:14.860325938Z Using method_source 1.0.0
2022-10-21T15:03:14.860845431Z Using thor 1.2.1
2022-10-21T15:03:14.861506051Z Using railties 6.1.6.1
2022-10-21T15:03:14.861991766Z Using momentjs-rails 2.29.1.1
2022-10-21T15:03:14.862465513Z Using datetime_picker_rails 0.0.7
2022-10-21T15:03:14.864577563Z Using jquery-rails 4.5.0
2022-10-21T15:03:14.865135526Z Using kaminari-core 1.2.2
2022-10-21T15:03:14.865713727Z Using kaminari-actionview 1.2.2
2022-10-21T15:03:14.866274187Z Using kaminari-activerecord 1.2.2
2022-10-21T15:03:14.867228133Z Using kaminari 1.2.2
2022-10-21T15:03:14.867385095Z Using ffi 1.15.5
2022-10-21T15:03:14.867625484Z Using sassc 2.4.0
2022-10-21T15:03:14.868598477Z Using sprockets 4.1.1
2022-10-21T15:03:14.869208085Z Using sprockets-rails 3.4.2
2022-10-21T15:03:14.869892538Z Using tilt 2.0.10
2022-10-21T15:03:14.870479782Z Using sassc-rails 2.1.2
2022-10-21T15:03:14.871020944Z Using selectize-rails 0.12.6
2022-10-21T15:03:14.871651861Z Using administrate 0.17.0
2022-10-21T15:03:14.872431621Z Using ast 2.4.2
2022-10-21T15:03:14.872931187Z Using attr_extras 6.2.5
2022-10-21T15:03:14.873371722Z Using aws-eventstream 1.2.0
2022-10-21T15:03:14.873791889Z Using aws-partitions 1.605.0
2022-10-21T15:03:14.874284475Z Using aws-sigv4 1.5.0
2022-10-21T15:03:14.874715369Z Using jmespath 1.6.1
2022-10-21T15:03:14.875478719Z Using aws-sdk-core 3.131.2
2022-10-21T15:03:14.876012625Z Using aws-sdk-kms 1.57.0
2022-10-21T15:03:14.876533354Z Using aws-sdk-s3 1.114.0
2022-10-21T15:03:14.877224888Z Using faraday-em_http 1.0.0
2022-10-21T15:03:14.878083142Z Using faraday-em_synchrony 1.0.0
2022-10-21T15:03:14.878761282Z Using faraday-excon 1.1.0
2022-10-21T15:03:14.879403442Z Using faraday-httpclient 1.0.1
2022-10-21T15:03:14.880137930Z Using multipart-post 2.2.3
2022-10-21T15:03:14.880639687Z Using faraday-multipart 1.0.4
2022-10-21T15:03:14.881284345Z Using faraday-net_http 1.0.1
2022-10-21T15:03:14.881899534Z Using faraday-net_http_persistent 1.2.0
2022-10-21T15:03:14.882698610Z Using faraday-patron 1.0.0
2022-10-21T15:03:14.883348980Z Using faraday-rack 1.0.0
2022-10-21T15:03:14.883772682Z Using faraday-retry 1.0.3
2022-10-21T15:03:14.884288807Z Using ruby2_keywords 0.0.5
2022-10-21T15:03:14.885093029Z Using faraday 1.10.0
2022-10-21T15:03:14.885514180Z Using faraday_middleware 1.2.0
2022-10-21T15:03:14.886005130Z Using connection_pool 2.2.5
2022-10-21T15:03:14.886589980Z Using net-http-persistent 4.0.1
2022-10-21T15:03:14.887432140Z Using azure-storage-common 2.0.4
2022-10-21T15:03:14.888032914Z Using azure-storage-blob 2.0.3
2022-10-21T15:03:14.888527530Z Using multi_json 1.15.0
2022-10-21T15:03:14.889141829Z Using statsd-ruby 1.5.0
2022-10-21T15:03:14.890614547Z Using barnes 0.0.9
2022-10-21T15:03:14.890762193Z Using bcrypt 3.1.18
2022-10-21T15:03:14.890950542Z Using msgpack 1.5.3
2022-10-21T15:03:14.891062128Z Using bootsnap 1.12.0
2022-10-21T15:03:14.891676892Z Using browser 5.3.1
2022-10-21T15:03:14.891910982Z Using bundler 2.3.24
2022-10-21T15:03:14.892067314Z Using commonmarker 0.23.6
2022-10-21T15:03:14.892581479Z Using debase-ruby_core_source 0.10.16
2022-10-21T15:03:14.893235578Z Using libddprof 0.6.0.1.0
2022-10-21T15:03:14.893716862Z Using libddwaf 1.3.0.2.0
2022-10-21T15:03:14.893851078Z Using ddtrace 1.2.0
2022-10-21T15:03:14.894347261Z Using declarative 0.0.20
2022-10-21T15:03:14.895013799Z Using orm_adapter 0.5.0
2022-10-21T15:03:14.895711052Z Using responders 3.0.1
2022-10-21T15:03:14.896255404Z Using warden 1.2.9
2022-10-21T15:03:14.896802106Z Using devise 4.8.1
2022-10-21T15:03:14.897005209Z Using devise-secure_password 2.0.1 from https://github.com/chatwoot/devise-secure_password
2022-10-21T15:03:14.924119762Z Using rails 6.1.6.1
2022-10-21T15:03:14.924950705Z Using devise_token_auth 1.2.0
2022-10-21T15:03:14.925113996Z Using digest-crc 0.6.4
2022-10-21T15:03:14.925317238Z Using unf_ext 0.0.8.2
2022-10-21T15:03:14.925851903Z Using unf 0.1.4
2022-10-21T15:03:14.926376438Z Using domain_name 0.5.20190701
2022-10-21T15:03:14.926843825Z Using dotenv 2.7.6
2022-10-21T15:03:14.927527359Z Using dotenv-rails 2.7.6
2022-10-21T15:03:14.928150668Z Using down 5.3.1
2022-10-21T15:03:14.928622287Z Using regexp_parser 2.5.0
2022-10-21T15:03:14.929198997Z Using ecma-re-validator 0.4.0
2022-10-21T15:03:14.930013232Z Using http-cookie 1.0.5
2022-10-21T15:03:14.930408742Z Using http-form_data 2.3.0
2022-10-21T15:03:14.930963283Z Using ffi-compiler 1.0.1
2022-10-21T15:03:14.931160017Z Using llhttp-ffi 0.4.0
2022-10-21T15:03:14.931718748Z Using http 5.1.0
2022-10-21T15:03:14.932234926Z Using elastic-apm 4.5.1
2022-10-21T15:03:14.932968766Z Using email_reply_trimmer 0.1.13
2022-10-21T15:03:14.933453351Z Using et-orbi 1.2.7
2022-10-21T15:03:14.933926195Z Using execjs 2.8.1
2022-10-21T15:03:14.934602301Z Using mime-types-data 3.2022.0105
2022-10-21T15:03:14.935602791Z Using mime-types 3.4.1
2022-10-21T15:03:14.936087270Z Using multi_xml 0.6.0
2022-10-21T15:03:14.936560629Z Using httparty 0.20.0
2022-10-21T15:03:14.937180161Z Using facebook-messenger 2.0.1
2022-10-21T15:03:14.938028395Z Using faker 2.21.0
2022-10-21T15:03:14.938591181Z Using jwt 2.4.1
2022-10-21T15:03:14.939175735Z Using memoist 0.16.2
2022-10-21T15:03:14.945737164Z Using os 1.1.4
2022-10-21T15:03:14.950033952Z Using signet 0.17.0
2022-10-21T15:03:14.957865962Z Using googleauth 1.2.0
2022-10-21T15:03:14.958353172Z Using fcm 1.0.8
2022-10-21T15:03:14.958940564Z Using flag_shih_tzu 0.3.23
2022-10-21T15:03:14.959422686Z Using foreman 0.87.2
2022-10-21T15:03:14.959916993Z Using raabro 1.4.0
2022-10-21T15:03:14.960663158Z Using fugit 1.5.3
2022-10-21T15:03:14.960835508Z Using google-protobuf 3.21.7
2022-10-21T15:03:14.961331803Z Using googleapis-common-protos-types 1.3.2
2022-10-21T15:03:14.961516032Z Using grpc 1.47.0
2022-10-21T15:03:14.962015734Z Using googleapis-common-protos 1.3.12
2022-10-21T15:03:14.962995697Z Using gapic-common 0.10.0
2022-10-21T15:03:14.963535196Z Using geocoder 1.8.0
2022-10-21T15:03:14.964147857Z Using gli 2.21.0
2022-10-21T15:03:14.964567287Z Using httpclient 2.8.3
2022-10-21T15:03:14.965111991Z Using trailblazer-option 0.1.2
2022-10-21T15:03:14.965600497Z Using uber 0.1.0
2022-10-21T15:03:14.966393005Z Using representable 3.2.0
2022-10-21T15:03:14.966939031Z Using retriable 3.1.2
2022-10-21T15:03:14.967478296Z Using rexml 3.2.5
2022-10-21T15:03:14.968047554Z Using webrick 1.7.0
2022-10-21T15:03:14.968802825Z Using google-apis-core 0.7.0
2022-10-21T15:03:14.969325706Z Using google-apis-iamcredentials_v1 0.13.0
2022-10-21T15:03:14.969845697Z Using google-apis-storage_v1 0.18.0
2022-10-21T15:03:14.970520209Z Using google-cloud-env 1.6.0
2022-10-21T15:03:14.971331725Z Using google-cloud-errors 1.2.0
2022-10-21T15:03:14.972047136Z Using google-cloud-core 1.6.0
2022-10-21T15:03:14.972667540Z Using google-cloud-location 0.2.0
2022-10-21T15:03:14.973525077Z Using google-cloud-dialogflow-v2 0.17.0
2022-10-21T15:03:14.974143883Z Using google-cloud-dialogflow 1.5.0
2022-10-21T15:03:14.974873050Z Using google-cloud-storage 1.37.0
2022-10-21T15:03:14.975343865Z Using groupdate 6.1.0
2022-10-21T15:03:14.975854245Z Using haikunator 1.1.1
2022-10-21T15:03:14.976537189Z Using sexp_processor 4.16.1
2022-10-21T15:03:14.977261403Z Using ruby_parser 3.19.1
2022-10-21T15:03:14.977957133Z Using ruby2ruby 2.4.4
2022-10-21T15:03:14.978541313Z Using hairtrigger 0.2.25
2022-10-21T15:03:14.979127934Z Using hana 1.3.7
2022-10-21T15:03:14.979668173Z Using hashie 5.0.0
2022-10-21T15:03:14.980274215Z Using hkdf 0.3.0
2022-10-21T15:03:14.980870708Z Using html2text 0.2.1
2022-10-21T15:03:14.981404861Z Using http-accept 1.7.0
2022-10-21T15:03:14.982092974Z Using mini_magick 4.11.0
2022-10-21T15:03:14.982785740Z Using ruby-vips 2.1.4
2022-10-21T15:03:14.983478776Z Using image_processing 1.12.2
2022-10-21T15:03:14.984172569Z Using jbuilder 2.11.5
2022-10-21T15:03:14.984419218Z Using json 2.6.2
2022-10-21T15:03:14.985046351Z Using uri_template 0.7.0
2022-10-21T15:03:14.985714057Z Using json_schemer 0.2.21
2022-10-21T15:03:14.986383595Z Using koala 3.2.0
2022-10-21T15:03:14.986992827Z Using line-bot-api 1.25.0
2022-10-21T15:03:14.987604162Z Using liquid 5.3.0
2022-10-21T15:03:14.988225611Z Using maxminddb 0.1.22
2022-10-21T15:03:14.988780121Z Using netrc 0.11.0
2022-10-21T15:03:14.989741285Z Using newrelic_rpm 8.9.0
2022-10-21T15:03:14.990506098Z Using oauth 0.5.10
2022-10-21T15:03:14.991243159Z Using parser 3.1.2.0
2022-10-21T15:03:14.991488166Z Using pg 1.4.1
2022-10-21T15:03:14.992277692Z Using pg_search 2.3.6
2022-10-21T15:03:14.992900710Z Using procore-sift 0.16.0
2022-10-21T15:03:14.993118175Z Using puma 5.6.4
2022-10-21T15:03:14.993821108Z Using pundit 2.2.0
2022-10-21T15:03:14.994633916Z Using rack-attack 6.6.1
2022-10-21T15:03:14.995283303Z Using rack-cors 1.1.1
2022-10-21T15:03:14.995821138Z Using rack-proxy 0.7.2
2022-10-21T15:03:14.996434436Z Using rack-timeout 0.6.3
2022-10-21T15:03:14.997057047Z Using redis 4.7.1
2022-10-21T15:03:14.997725487Z Using redis-namespace 1.8.2
2022-10-21T15:03:14.998465588Z Using rest-client 2.1.0
2022-10-21T15:03:14.998703627Z Using scout_apm 5.2.0
2022-10-21T15:03:14.999256688Z Using semantic_range 3.0.0
2022-10-21T15:03:14.999882240Z Using sentry-ruby-core 5.3.1
2022-10-21T15:03:15.000482091Z Using sentry-rails 5.3.1
2022-10-21T15:03:15.001098128Z Using sentry-ruby 5.3.1
2022-10-21T15:03:15.001729460Z Using sidekiq 6.4.2
2022-10-21T15:03:15.002341687Z Using sentry-sidekiq 5.3.1
2022-10-21T15:03:15.003058825Z Using sidekiq-cron 1.6.0
2022-10-21T15:03:15.003854646Z Using slack-ruby-client 1.0.0
2022-10-21T15:03:15.004480965Z Using stripe 6.5.0
2022-10-21T15:03:15.005186952Z Using telephone_number 1.4.16
2022-10-21T15:03:15.005843850Z Using time_diff 0.3.0
2022-10-21T15:03:15.006615897Z Using twilio-ruby 5.68.0
2022-10-21T15:03:15.007243279Z Using twitty 0.1.4
2022-10-21T15:03:15.007880991Z Using tzinfo-data 1.2022.1
2022-10-21T15:03:15.008575564Z Using uglifier 4.2.0
2022-10-21T15:03:15.009274424Z Using valid_email2 4.0.3
2022-10-21T15:03:15.009978869Z Using webpacker 5.4.3
2022-10-21T15:03:15.010672276Z Using webpush 1.1.0
2022-10-21T15:03:15.011169371Z Using wisper 2.0.0
2022-10-21T15:03:15.011838126Z Using working_hours 1.4.1
2022-10-21T15:03:15.032933309Z Bundle complete! 102 Gemfile dependencies, 222 gems now installed.
2022-10-21T15:03:15.032957702Z Gems in the groups 'development' and 'test' were not installed.
2022-10-21T15:03:15.033051386Z Bundled gems are installed into `/gems`
2022-10-21T15:03:15.039757727Z + BUNDLE='bundle check'
2022-10-21T15:03:15.039775538Z + bundle check
2022-10-21T15:03:15.400527307Z The Gemfile's dependencies are satisfied
2022-10-21T15:03:15.403567622Z + exec /bin/sh -c 'bundle exec rails db:chatwoot_prepare; bundle exec rails s -b 0.0.0.0 -p 3000'
2022-10-21T15:03:22.733006278Z Loading Installation config
2022-10-21T15:03:25.443545533Z => Booting Puma
2022-10-21T15:03:25.443570704Z => Rails 6.1.6.1 application starting in production
2022-10-21T15:03:25.443576485Z => Run `bin/rails server --help` for more startup options
2022-10-21T15:03:29.797549358Z W, [2022-10-21T15:03:28.444654 #1] WARN -- : Creating scope :open. Overwriting existing method Conversation.open.
2022-10-21T15:03:29.797575605Z W, [2022-10-21T15:03:28.500516 #1] WARN -- : Creating scope :latest. Overwriting existing method Mention.latest.
2022-10-21T15:03:29.797581662Z Puma starting in single mode...
2022-10-21T15:03:29.797586622Z * Puma version: 5.6.4 (ruby 3.0.4-p208) ("Birdie's Version")
2022-10-21T15:03:29.797591693Z * Min threads: 5
2022-10-21T15:03:29.797596345Z * Max threads: 5
2022-10-21T15:03:29.797601015Z * Environment: production
2022-10-21T15:03:29.797620005Z * PID: 1
2022-10-21T15:03:29.797681531Z * Listening on http://0.0.0.0:3000
2022-10-21T15:03:29.800911789Z Use Ctrl-C to stop
2022-10-21T15:03:56.676681893Z I, [2022-10-21T15:03:56.676478 #1] INFO -- : source=rack-timeout id=e4c18649-2f2d-427d-9a8d-264a286a41f9 timeout=15000ms state=ready
2022-10-21T15:03:56.677433515Z I, [2022-10-21T15:03:56.677268 #1] INFO -- : [e4c18649-2f2d-427d-9a8d-264a286a41f9] Started POST "/auth/sign_in" for 186.7.163.69 at 2022-10-21 15:03:56 +0000
2022-10-21T15:03:56.682243486Z I, [2022-10-21T15:03:56.682104 #1] INFO -- : [e4c18649-2f2d-427d-9a8d-264a286a41f9] Processing by DeviseOverrides::SessionsController#create as HTML
2022-10-21T15:03:56.682257898Z I, [2022-10-21T15:03:56.682179 #1] INFO -- : [e4c18649-2f2d-427d-9a8d-264a286a41f9] Parameters: {"email"=>"walder.franco@gmail.com", "password"=>"[FILTERED]", "sso_auth_token"=>"[FILTERED]"}
2022-10-21T15:03:57.046620786Z I, [2022-10-21T15:03:57.046392 #1] INFO -- : [e4c18649-2f2d-427d-9a8d-264a286a41f9] Completed 500 Internal Server Error in 364ms (ActiveRecord: 32.0ms | Allocations: 58114)
2022-10-21T15:03:57.047934943Z F, [2022-10-21T15:03:57.047719 #1] FATAL -- : [e4c18649-2f2d-427d-9a8d-264a286a41f9]
2022-10-21T15:03:57.047956119Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
2022-10-21T15:03:57.047965857Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 1: json.access_token resource.access_token.token
2022-10-21T15:03:57.047971036Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 2: json.account_id resource.active_account_user&.account_id
2022-10-21T15:03:57.047976589Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 3: json.available_name resource.available_name
2022-10-21T15:03:57.047981444Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 4: json.avatar_url resource.avatar_url
2022-10-21T15:03:57.047986402Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 5: json.confirmed resource.confirmed?
2022-10-21T15:03:57.047991022Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 6: json.display_name resource.display_name
2022-10-21T15:03:57.047995772Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] 7: json.message_signature resource.message_signature
2022-10-21T15:03:57.048000467Z [e4c18649-2f2d-427d-9a8d-264a286a41f9]
2022-10-21T15:03:57.048005116Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/models/concerns/avatarable.rb:14:in `avatar_url'
2022-10-21T15:03:57.048009808Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/views/api/v1/models/_user.json.jbuilder:4
2022-10-21T15:03:57.048014528Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/views/devise/_auth.json.jbuilder:2
2022-10-21T15:03:57.048019210Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/views/devise/_auth.json.jbuilder:1
2022-10-21T15:03:57.048023936Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/controllers/devise_overrides/sessions_controller.rb:19:in `render_create_success'
2022-10-21T15:03:57.048028685Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/controllers/devise_overrides/sessions_controller.rb:14:in `create'
2022-10-21T15:03:57.048048265Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2022-10-21T15:03:57.048053252Z [e4c18649-2f2d-427d-9a8d-264a286a41f9] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
2022-10-21T15:03:57.048193183Z I, [2022-10-21T15:03:57.048089 #1] INFO -- : source=rack-timeout id=e4c18649-2f2d-427d-9a8d-264a286a41f9 timeout=15000ms service=372ms state=completed
2022-10-21T15:04:04.113991430Z I, [2022-10-21T15:04:04.113753 #1] INFO -- : source=rack-timeout id=b55ce24c-8c5a-4a35-b0ee-0da51fabe729 timeout=15000ms state=ready
2022-10-21T15:04:04.114322165Z I, [2022-10-21T15:04:04.114210 #1] INFO -- : [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] Started POST "/auth/sign_in" for 186.7.163.69 at 2022-10-21 15:04:04 +0000
2022-10-21T15:04:04.116890387Z I, [2022-10-21T15:04:04.116732 #1] INFO -- : [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] Processing by DeviseOverrides::SessionsController#create as HTML
2022-10-21T15:04:04.116905270Z I, [2022-10-21T15:04:04.116800 #1] INFO -- : [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] Parameters: {"email"=>"walder.franco@gmail.com", "password"=>"[FILTERED]", "sso_auth_token"=>"[FILTERED]"}
2022-10-21T15:04:04.345422577Z I, [2022-10-21T15:04:04.345208 #1] INFO -- : [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] Completed 500 Internal Server Error in 228ms (ActiveRecord: 4.4ms | Allocations: 5559)
2022-10-21T15:04:04.346670016Z F, [2022-10-21T15:04:04.346524 #1] FATAL -- : [b55ce24c-8c5a-4a35-b0ee-0da51fabe729]
2022-10-21T15:04:04.346682692Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
2022-10-21T15:04:04.346687890Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 1: json.access_token resource.access_token.token
2022-10-21T15:04:04.346692802Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 2: json.account_id resource.active_account_user&.account_id
2022-10-21T15:04:04.346697968Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 3: json.available_name resource.available_name
2022-10-21T15:04:04.346702478Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 4: json.avatar_url resource.avatar_url
2022-10-21T15:04:04.346706950Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 5: json.confirmed resource.confirmed?
2022-10-21T15:04:04.346711466Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 6: json.display_name resource.display_name
2022-10-21T15:04:04.346715726Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] 7: json.message_signature resource.message_signature
2022-10-21T15:04:04.346720041Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729]
2022-10-21T15:04:04.346724293Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/models/concerns/avatarable.rb:14:in `avatar_url'
2022-10-21T15:04:04.346728530Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/views/api/v1/models/_user.json.jbuilder:4
2022-10-21T15:04:04.346732799Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/views/devise/_auth.json.jbuilder:2
2022-10-21T15:04:04.346737028Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/views/devise/_auth.json.jbuilder:1
2022-10-21T15:04:04.346741332Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/controllers/devise_overrides/sessions_controller.rb:19:in `render_create_success'
2022-10-21T15:04:04.346760146Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/controllers/devise_overrides/sessions_controller.rb:14:in `create'
2022-10-21T15:04:04.346765216Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
2022-10-21T15:04:04.346769748Z [b55ce24c-8c5a-4a35-b0ee-0da51fabe729] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
2022-10-21T15:04:04.346875188Z I, [2022-10-21T15:04:04.346744 #1] INFO -- : source=rack-timeout id=b55ce24c-8c5a-4a35-b0ee-0da51fabe729 timeout=15000ms service=233ms state=completed
```

**Comment by pranavrajs** [comment]
@walderfranco It seems there is a missing env variable. Can you please make sure that you have set the FRONTEND_URL config? Please see the documentation [here](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables/#configure-frontend-url-domain). 

```
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host],
```

**Comment by walderfranco** [comment]
> @walderfranco It seems there is a missing env variable. Can you please make sure that you have set the FRONTEND_URL config? Please see the documentation [here](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables/#configure-frontend-url-domain).
> 
> ```
> ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host],
> ```
I'm going to check, thanks

**Comment by walderfranco** [comment]
indeed, problem solved, I'm already inside the application. thank you.
