### ISSUE TITLE
Production Deployment Error

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5938]
Due to one of these 4 commits the production deployment on Heroku is broken 

86ca7f4a8d5e2b7d45033e85d5e100870ed0bfa0, 8b659de73d3813489489b249a9b3f8e95dbd2999, f2753df8df424b5b9137cad0da2e3f6da7ad2dda, c121b44df419696cd44601468e36064c680356d9

`REDIS_OPENSSL_VERIFY_MODE` is not working with these changes.

### Error message
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self-signed certificate in certificate chain)

```
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/connection/ruby.rb:264:in `connect_nonblock'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/connection/ruby.rb:264:in `connect'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/connection/ruby.rb:306:in `connect'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:385:in `establish_connection'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:115:in `block in connect'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:344:in `with_reconnect'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:114:in `connect'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:20:in `block in connect'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:30:in `block in connect_with_tracing'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `block in with_tracing'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/tracer.rb:351:in `capture_segment_error'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:45:in `with_tracing'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/instrumentation.rb:30:in `connect_with_tracing'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/redis/prepend.rb:20:in `connect'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:417:in `ensure_connected'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:269:in `block in process'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:356:in `logging'
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:78:in `block in logging'
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:17:in `block in instrument'
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:28:in `record_span'
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:16:in `instrument'
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/redis.rb:77:in `logging'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:268:in `process'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:233:in `call_pipelined'
/app/vendor/bundle/ruby/3.0.0/gems/redis-4.7.1/lib/redis/client.rb:200:in `block in call_pipeline'
<truncated 93 additional frames>
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/ssl.rb:77:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/engine.rb:539:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
/app/vendor/bundle/ruby/3.0.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by pranavrajs** [comment]
As a workaround, I've reverted these commits for now on one of our production instances.

**Comment by sojan-official** [comment]
## Debugging commits

- [ ] 86ca7f4a8d5e2b7d45033e85d5e100870ed0bfa0
- [ ] 8b659de73d3813489489b249a9b3f8e95dbd2999
- [ ] f2753df8df424b5b9137cad0da2e3f6da7ad2dda
- [ ] c121b44df419696cd44601468e36064c680356d9

**Comment by sojan-official** [comment]
Identified the breakage to be stemming from https://github.com/chatwoot/chatwoot/commit/86ca7f4a8d5e2b7d45033e85d5e100870ed0bfa0  . will be looking to debug further.
