### ISSUE TITLE
Couldn't Deploying to Linux VM self-hosted

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#6246]
**Describe the bug**

Couldn't Deploying to Linux VM self-hosted , using this guide :
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

**To Reproduce**

1. wget https://get.chatwoot.app/linux/install.sh
2. chmod +x install.sh
3. sudo ./install.sh --install
4. See the error

./install.sh: line 466: curl: command not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Some error has occured. Check '/var/log/chatwoot-setup.log' for details.

**Expected behavior**

Installation Complete

**Server logs**

'/var/log/chatwoot-setup.log' is Empty

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ x] Self-hosted
- - [ x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Additional context**

OS : ubuntu-20.04.5-desktop-amd64

**Comment by vishnu-narayanan** [comment]
It looks like `curl` is not present in your OS.

Try installing curl first and then runnning the script.
```
sudo apt update
sudo ap install curl
```

**Comment by Double-Click-ERP** [comment]
@vishnu-narayanan 
Thank You
