### ISSUE TITLE
Docker container build failing on logging related issue

### ISSUE THREAD

**Issue by sony-mathew** [chatwoot/chatwoot#632]
**Describe the bug**
When you build a chatwoot docker container for production, it's failing. There build log in docker hub supporting this.

**To Reproduce**
Remove the `app/log/production.log` and build a docker container for production.

**Expected behavior**
This shouldn't throw any error.

**Screenshots**
Failure logs:
```
Removing intermediate container ae075e956f34
---> f200bb8bf77f
Step 17/35 : COPY . /app
---> 9467186a6f0c
Step 18/35 : RUN if [ "$RAILS_ENV" = "production" ]; then SECRET_KEY_BASE=precompile_placeholder bundle exec rake assets:precompile; fi
---> Running in 3921449df3db
[91mrake aborted!
[0m
[91mErrno::ENOENT: No such file or directory @ rb_sysopen - /app/log/production.log
[0m
[91m/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/logger.rb:81:in `initialize'
/app/config/environments/production.rb:87:in `new'
/app/config/environments/production.rb:87:in `block in <main>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:216:in `instance_eval'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:216:in `configure'
/app/config/environments/production.rb:1:in `<main>'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/gems/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:611:in `each'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/gems/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:339:in `require_environment!'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/gems/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/gems/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
[0m
[91m
Caused by:
[0m
[91mErrno::ENOENT: No such file or directory @ rb_sysopen - /app/log/production.log
[0m
[91m/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/logger.rb:81:in `initialize'
/app/config/environments/production.rb:87:in `new'
/app/config/environments/production.rb:87:in `block in <main>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:216:in `instance_eval'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/railtie.rb:216:in `configure'
/app/config/environments/production.rb:1:in `<main>'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/gems/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:611:in `each'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/gems/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/gems/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:339:in `require_environment!'
/gems/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/gems/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/gems/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
[0m
[91mTasks: TOP => environment
[0m
[91m(See full trace by running task with --trace)
[0m
Removing intermediate container 3921449df3db
The command '/bin/sh -c if [ "$RAILS_ENV" = "production" ]; then SECRET_KEY_BASE=precompile_placeholder bundle exec rake assets:precompile; fi' returned a non-zero code: 1
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Catalina

**Additional context**
This is possibly due to this changes  : https://github.com/chatwoot/chatwoot/compare/71d48854..f69eb7e5

**Comment by pranavrajs** [comment]
Closed via #637
