### ISSUE TITLE
Getting error while installation

### ISSUE THREAD

**Issue by Rohit-Mondal** [chatwoot/chatwoot#6560]
[5/5] Building fresh packages...
Done in 21.45s.
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/chatwoot/chatwoot/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chatwoot/chatwoot/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by tejaswinichile** [comment]
@Rohit-Mondal What process and guide are you following currently?
Which version are you using?

**Comment by pranavrajs** [comment]
Closing this as there is no activity for a long time.
