### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by jhonnyrampoon** [chatwoot/chatwoot#6578]
I am getting an error while installing on Linode, Ubuntu - Using https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm this guide and the error is 

warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
Done in 11.91s.
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/chatwoot/chatwoot/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chatwoot/chatwoot/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0

The file log is bigger, i can provide that.

**Comment by jhonnyrampoon** [comment]
Thank you for the amazing Support, It was fixed, without you even saying anything. Never mind.
