### ISSUE TITLE
Email inbox error 500 in console - Filter: All+Open=Internal Server Error

### ISSUE THREAD

**Issue by avardo** [chatwoot/chatwoot#6723]
**Describe the bug**
The problem is that letters in the email inbox stop loading with the "Open" status, their number is not displayed correctly.

**To Reproduce**
To reproduce the problem, you need to go to the inbox with a large number of letters (9000+ in my case), and select the "All" tab + filter by "Open"

**Screenshots**
1. Email inbox with All + Open 
![image](https://user-images.githubusercontent.com/7565817/226588540-148a15d9-2d02-47e1-89cb-d89329989f63.png)

2. At this point, you can see a 500 error in the console when accessing: `/api/v1/accounts/2/conversations?inbox_id=1&status=open&assignee_type=all&page=1`
![image](https://user-images.githubusercontent.com/7565817/226589000-de7efaa5-4daf-4ad5-9c60-f27fbe44e1fd.png)
responce from api:
`{"status":500,"error":"Internal Server Error"}`

Now if i change filter from "Open" to "All" -  I can see all messages in this inbox
![image](https://user-images.githubusercontent.com/7565817/226590182-3791522f-d5bc-4794-b045-d9a2acea3ede.png)
I can see all messages in this email inbox.

**Browser logs**
`/api/v1/accounts/2/conversations?inbox_id=1&status=open&assignee_type=all&page=1` 
returns
`{"status":500,"error":"Internal Server Error"}`

**Server logs**

```
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"active_storage/blobs/redirect", :filename=>#<ActiveStorage::Filename:0x00007f8aa6e42ec8 @filename="">, :signed_id=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnB1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbd6ade7b32b881b090fbc06f7df2551b9638e67"}, possible unmatched constraints: [:filename]
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: Did you mean?  rails_service_blob_path
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]:                rails_service_blob_proxy_url
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]:                rails_service_blob_proxy_path):
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     22: elsif conversation.unread_incoming_messages.count.zero?
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     23:   json.messages [conversation.messages.includes([{ attachments: [{ file_attachment: [:blob] }] }]).last.try(:push_event_data)]
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     24: else
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     25:   json.messages conversation.unread_messages.includes([:user, { attachments: [{ file_attachment: [:blob] }] }]).last(10).map(&:push_event_data)
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     26: end
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     27:
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]     28: json.account_id conversation.account_id
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16]
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/models/attachment.rb:54:in `file_url'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/models/attachment.rb:76:in `file_metadata'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/models/attachment.rb:49:in `push_event_data'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/models/message.rb:122:in `map'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/models/message.rb:122:in `push_event_data'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25:in `map'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Mar 21 12:00:20 chatwoot chatwoot-web.1[2771329]: [0e19e7b4-6b51-4018-98a1-3567a0437c16] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

**Environment**

- [x] Self-hosted
- - [x] Linux VM (Ubuntu 20.04.5 LTS)

**Desktop (please complete the following information)** (If applicable)
 - OS: Windows
 - Browser: chrome
 - Version: 111.0.5563.65

**Chatwoot version**
v2.15.0

**Comment by pranavrajs** [comment]
@avardo It seems like a file is missing. Have configured any storage provider?

**Comment by andrsharov** [comment]
Hi, there

I also have same error.

When I try to select Opened Tickets progress bar will never stops.

![image](https://user-images.githubusercontent.com/44819772/231004749-b0321ab3-9aab-4bd9-b0cf-1b58d34609ef.png)

Environment:

- Virtual Machine Ubuntu 20.04 LTS
- Docker-compose file 
- Chatwoot v2.15.0

I use S3 Compatiblity Storage Yandex.S3
Part of  `.evn` config file here:
```
STORAGE_BUCKET_NAME=my-rails-data
STORAGE_ACCESS_KEY_ID=My_Access_Key_ID
STORAGE_SECRET_ACCESS_KEY=My_Secret_Key
STORAGE_REGION=ru-central1
STORAGE_ENDPOINT=https://storage.yandexcloud.net
```

Main error is 
```
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"active_storage/blobs/redirect", :filename=>#<ActiveStorage::Filename:0x00007fa5b025e538 @filename="">, :signed_id=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHNaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--692b813cf6febef88e46eb4768fb18f01d56f9bb"}, possible unmatched constraints: [:filename]
```
Full log down below
```
chatwoot-rails-1    | I, [2023-04-10T21:16:25.709542 #1]  INFO -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] Started GET "/api/v1/accounts/1/conversations?inbox_id=8&status=open&assignee_type=unassigned&page=1" for 1.1.1.1 at 2023-04-10 21:16:25 +0000
chatwoot-rails-1    | I, [2023-04-10T21:16:25.711790 #1]  INFO -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] Processing by Api::V1::Accounts::ConversationsController#index as JSON
chatwoot-rails-1    | I, [2023-04-10T21:16:25.711841 #1]  INFO -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]   Parameters: {"inbox_id"=>"8", "status"=>"open", "assignee_type"=>"unassigned", "page"=>"1", "account_id"=>"1"}
chatwoot-rails-1    | I, [2023-04-10T21:16:26.156043 #1]  INFO -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]   Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 437.1ms | Allocations: 220642)
chatwoot-rails-1    | I, [2023-04-10T21:16:26.156463 #1]  INFO -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] Completed 500 Internal Server Error in 445ms (ActiveRecord: 75.2ms | Allocations: 224020)
chatwoot-rails-1    | F, [2023-04-10T21:16:26.157526 #1] FATAL -- : [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]   
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"active_storage/blobs/redirect", :filename=>#<ActiveStorage::Filename:0x00007fa5b025e538 @filename="">, :signed_id=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHNaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--692b813cf6febef88e46eb4768fb18f01d56f9bb"}, possible unmatched constraints: [:filename]
chatwoot-rails-1    | Did you mean?  rails_service_blob_path
chatwoot-rails-1    |                rails_service_blob_proxy_url
chatwoot-rails-1    |                rails_service_blob_proxy_path):
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     22: elsif conversation.unread_incoming_messages.count.zero?
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     23:   json.messages [conversation.messages.includes([{ attachments: [{ file_attachment: [:blob] }] }]).last.try(:push_event_data)]
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     24: else
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     25:   json.messages conversation.unread_messages.includes([:user, { attachments: [{ file_attachment: [:blob] }] }]).last(10).map(&:push_event_data)
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     26: end
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     27: 
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]     28: json.account_id conversation.account_id
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2]   
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/models/attachment.rb:54:in `file_url'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/models/attachment.rb:76:in `file_metadata'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/models/attachment.rb:49:in `push_event_data'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/models/message.rb:116:in `map'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/models/message.rb:116:in `push_event_data'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25:in `map'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:25
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
chatwoot-rails-1    | [b06ecc2b-91b4-4892-b231-ba8f14f9a5e2] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

I know why this happened in my case. I have some experience with Yandex.S3 cloud storage. Sometimes uploads fails some objects, not more one object from 10000.

But this is not should broke all the service, only one post(attachment in the post) in the tiket. Why this broken attach broken all the service? It's horrible.

@pranavrajs , Please answer to me ASAP, what I need to do, to reparie my service?
P.S.: May be I need to do some manual database modifications?

**Comment by andrsharov** [comment]
I am diveded to situation. 

1. I was enable debug level log rails service in `.env` file  `LOG_LEVEL=debug` 
2. I was  starting to testing. I was find next one sql requests
```
chatwoot-rails-1    | D, [2023-04-10T21:54:29.077272 #1] DEBUG -- : [de3daede-3f37-4be5-af3a-1b7323b420f5]   ActiveStorage::Blob Load (0.2ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1  [["id", 6491]]
```
When I was go to the database and was finded this record 

```
id  |key                         |filename|content_type|metadata           |byte_size|checksum                |created_at             |service_name |
----+----------------------------+--------+------------+-------------------+---------+------------------------+-----------------------+-------------+
6491|ghr2epyws3us9jlg54hekn8667zb|        |image/png   |{"identified":true}|      372|TN6/VPfbWM/NiBAsDaED9w==|2023-04-10 14:48:05.089|s3_compatible|
```

I think the main mistake was the `filename` column was empty. 
Next one I am  was guessed that `key` column this object name in S3 Storage. 
And I was tried to find this object in the Yandex.S3 cloud interface, i failed. 
And I decided to upload this png picture by myself. 

Solution to resolve:

1. Fill the empty column `filename`. 
2. Upload `ghr2epyws3us9jlg54hekn8667zb` object diretly in the bucket.

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
