### ISSUE TITLE
ActionView::Template::Error: undefined method `additional_attributes' for nil:NilClass

### ISSUE THREAD

**Issue by creatorrr** [chatwoot/chatwoot#6879]
**Describe the bug**

We recently deployed chatwoot using docker-compose, external postgres dashboard. Unfortunately the conversations page keeps loading. Notes:

- docker image version: `2.15.0`
- the js console shows that a request failed with 500 (attached screenshots)
- request: [/api/v1/accounts/1/conversations?status=open&assignee_type=me&page=1](/#)
- response: `{status: 500, error: "Internal Server Error"}`
- logs show `ActionView::Template::Error: undefined method `additional_attributes' for nil:NilClass`

Possibly related to: #4620 

**To Reproduce**

1. Deploy using docker-compose
2. Log in to dashboard
3. Messages keep loading
4. See the error in the js console

**Screenshots**

![Screenshot from 2023-04-11 13-08-27](https://user-images.githubusercontent.com/931887/231090027-cc922ac9-b196-4e5f-9b3a-8d4b1e663698.png)
![Screenshot from 2023-04-11 13-01-20](https://user-images.githubusercontent.com/931887/231090039-0c1b179e-9fcc-4157-8de6-65951e284607.png)

**Browser logs**

- request: /api/v1/accounts/1/conversations?status=open&assignee_type=me&page=1
- response: `{status: 500, error: "Internal Server Error"}`

**Server logs**

- logs show `ActionView::Template::Error: undefined method `additional_attributes' for nil:NilClass`

**Comment by creatorrr** [comment]
More logs:

```
D, [2023-04-11T07:40:39.415695 #1] DEBUG -- : [d753921e-c88b-4a83-a3a9-9efb233642f0]   Rendered api/v1/models/_contact.json.jbuilder (Duration: 1.8ms | Allocations: 957)
D, [2023-04-11T07:40:39.415767 #1] DEBUG -- : [d753921e-c88b-4a83-a3a9-9efb233642f0]   Rendered api/v1/conversations/partials/_conversation.json.jbuilder (Duration: 2.0ms | Allocations: 1044)
I, [2023-04-11T07:40:39.415852 #1]  INFO -- : [d753921e-c88b-4a83-a3a9-9efb233642f0]   Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 264.3ms | Allocations: 104847)
I, [2023-04-11T07:40:39.416302 #1]  INFO -- : [d753921e-c88b-4a83-a3a9-9efb233642f0] Completed 500 Internal Server Error in 515ms (ActiveRecord: 78.4ms | Allocations: 164441)
F, [2023-04-11T07:40:39.418004 #1] FATAL -- : [d753921e-c88b-4a83-a3a9-9efb233642f0]
[d753921e-c88b-4a83-a3a9-9efb233642f0] ActionView::Template::Error (undefined method `additional_attributes' for nil:NilClass):
[d753921e-c88b-4a83-a3a9-9efb233642f0]     1: json.additional_attributes resource.additional_attributes
[d753921e-c88b-4a83-a3a9-9efb233642f0]     2: json.availability_status resource.availability_status
[d753921e-c88b-4a83-a3a9-9efb233642f0]     3: json.email resource.email
[d753921e-c88b-4a83-a3a9-9efb233642f0]     4: json.id resource.id
[d753921e-c88b-4a83-a3a9-9efb233642f0]
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/models/_contact.json.jbuilder:1
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:3
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:2
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:1
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/accounts/conversations/index.json.jbuilder:10
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/accounts/conversations/index.json.jbuilder:9
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/accounts/conversations/index.json.jbuilder:8
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/views/api/v1/accounts/conversations/index.json.jbuilder:1
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[d753921e-c88b-4a83-a3a9-9efb233642f0] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

**Comment by creatorrr** [comment]
cc/ @philipbalbas

**Comment by creatorrr** [comment]
Strange but maybe related behaviour:
- switching Status to "All" works
- [api/v1/accounts/1/conversations?status=all&assignee_type=all&page=1](/#) seems to work

### Screenshot

![Screenshot from 2023-04-11 13-18-06](https://user-images.githubusercontent.com/931887/231092410-3d09bccd-fbe4-4448-aa2d-17e5a3e13bbc.png)

**Comment by creatorrr** [comment]
@vishnu-narayanan can you please help out with this?

**Comment by pranavrajs** [comment]
@creatorrr It seems like one of the conversations has an errored payload for some reason. The best bet is to find the conversation which has a missing contact. Just to confirm, did you make any changes in the code?

**Comment by pranavrajs** [comment]
Closing this as there is no activity for a long time.
