### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by nlkocx** [chatwoot/chatwoot#6935]
Can't install on a Hetzner VPS with Ubuntu 20.04.

Error is: 

➥ 1/9 Installing dependencies. This takes a while.
➥ 2/9 Installing databases.
➥ 3/9 Installing webserver.
➥ 4/9 Setting up Ruby
➥ 5/9 Setting up the database.
➥ 6/9 Installing Chatwoot. This takes a long while.

Some error has occured. Check '/var/log/chatwoot-setup.log' for details.

```
`rake aborted!
Bundler::GemNotFound: Could not find rack-cors-1.1.1, rails-6.1.7.3, bootsnap-1.12.0, attr_extras-6.2.5, bro                                                                                                                                 wser-5.3.1, hashie-5.0.0, jbuilder-2.11.5, responders-3.0.1, rest-client-2.1.0, telephone_number-1.4.16, tim                                                                                                                                 e_diff-0.3.0, tzinfo-data-1.2022.1, valid_email2-4.0.3, uglifier-4.2.0, flag_shih_tzu-0.3.23, haikunator-1.1                                                                                                                                 .1, liquid-5.3.0, commonmarker-0.23.9, json_schemer-0.2.21, rack-attack-6.6.1, down-5.3.1, gmail_xoauth-0.4.                                                                                                                                 2, csv-safe-3.1.1, google-cloud-translate-3.3.0, aws-sdk-s3-1.114.0, azure-storage-blob-2.0.3, google-cloud-                                                                                                                                 storage-1.37.0, image_processing-1.12.2, groupdate-6.1.0, pg-1.4.1, redis-4.7.1, redis-namespace-1.8.2, dote                                                                                                                                 nv-rails-2.7.6, foreman-0.87.2, puma-5.6.4, webpacker-5.4.3, barnes-0.0.9, devise-4.8.1, devise_token_auth-1                                                                                                                                 .2.0, jwt-2.5.0, pundit-2.2.0, administrate-0.17.0, wisper-2.0.0, facebook-messenger-2.0.1, line-bot-api-1.2                                                                                                                                 5.0, twilio-ruby-5.68.0, twitty-0.1.5, koala-3.2.0, slack-ruby-client-1.0.0, google-cloud-dialogflow-1.5.0,                                                                                                                                  ddtrace-1.2.0, elastic-apm-4.5.1, newrelic_rpm-8.15.0, newrelic-sidekiq-metrics-1.6.1, scout_apm-5.2.0, sent                                                                                                                                 ry-rails-5.3.1, sentry-ruby-5.3.1, sentry-sidekiq-5.3.1, sidekiq-6.4.2, sidekiq-cron-1.6.0, fcm-1.0.8, web-p                                                                                                                                 ush-3.0.0, geocoder-1.8.0, maxminddb-0.1.22, hairtrigger-0.2.25, procore-sift-0.16.0, email_reply_trimmer-0.                                                                                                                                 1.13, html2text-0.2.1, working_hours-1.4.1, pg_search-2.3.6, stripe-6.5.0, faker-2.21.0, lograge-0.12.0, omn                                                                                                                                 iauth-oauth2-1.8.0, audited-5.2.0, omniauth-2.1.0, omniauth-google-oauth2-1.1.1, omniauth-rails_csrf_protect                                                                                                                                 ion-1.0.1, rack-timeout-0.6.3, annotate-3.2.0, bullet-7.0.2, letter_opener-1.8.1, web-console-4.2.0, json_re                                                                                                                                 fs-0.1.7, squasher-0.6.2, rack-mini-profiler-3.0.0, stackprof-0.2.24, cypress-on-rails-1.13.1, database_clea                                                                                                                                 ner-2.0.1, webmock-3.18.1, test-prof-1.0.11, brakeman-5.2.3, bundle-audit-0.1.0, byebug-11.1.3, climate_cont                                                                                                                                 rol-1.1.1, factory_bot_rails-6.2.0, listen-3.7.1, mock_redis-0.32.0, pry-rails-0.3.9, rspec_junit_formatter-                                                                                                                                 0.6.0, rspec-rails-5.0.3, rubocop-1.31.2, rubocop-performance-1.14.2, rubocop-rails-2.15.2, rubocop-rspec-2.                                                                                                                                 12.1, seed_dump-3.3.1, shoulda-matchers-5.1.0, simplecov-0.17.1, spring-2.1.1, spring-watcher-listen-2.0.1,                                                                                                                                  sprockets-rails-3.4.2, msgpack-1.5.3, http-accept-1.7.0, http-cookie-1.0.5, mime-types-3.4.1, netrc-0.11.0,                                                                                                                                  execjs-2.8.1, ecma-re-validator-0.4.0, hana-1.3.7, regexp_parser-2.5.0, uri_template-0.7.0, oauth-0.5.10, go                                                                                                                                 ogle-cloud-core-1.6.0, google-cloud-translate-v2-0.4.0, google-cloud-translate-v3-0.5.0, aws-sdk-core-3.131.                                                                                                                                 2, aws-sdk-kms-1.57.0, aws-sigv4-1.5.0, azure-storage-common-2.0.4, digest-crc-0.6.4, google-apis-iamcredent                                                                                                                                 ials_v1-0.13.0, google-apis-storage_v1-0.18.0, googleauth-1.2.0, mini_magick-4.11.0, ruby-vips-2.1.4, dotenv                                                                                                                                 -2.7.6, rack-proxy-0.7.2, semantic_range-3.0.0, multi_json-1.15.0, statsd-ruby-1.5.0, bcrypt-3.1.18, orm_ada                                                                                                                                 pter-0.5.0, warden-1.2.9, sassc-rails-2.1.2, selectize-rails-0.12.6, httparty-0.21.0, faraday-1.10.0, json-2                                                                                                                                 .6.2, faraday_middleware-1.2.0, gli-2.21.0, google-cloud-dialogflow-v2-0.17.0, debase-ruby_core_source-0.10.                                                                                                                                 16, libddprof-0.6.0.1.0-x86_64-linux, libddwaf-1.3.0.2.0-x86_64-linux, http-5.1.0, parser-3.1.2.0, sentry-ru                                                                                                                                 by-core-5.3.1, connection_pool-2.2.5, fugit-1.5.3, hkdf-1.0.0, openssl-3.1.0, ruby2ruby-2.4.4, ruby_parser-3                                                                                                                                 .19.1, request_store-1.5.1, oauth2-2.0.9, rack-protection-3.0.5, uniform_notifier-1.16.0, launchy-2.5.0, bin                                                                                                                                 dex-0.8.1, database_cleaner-active_record-2.0.1, crack-0.4.5, hashdiff-1.0.1, bundler-audit-0.9.1, factory_b                                                                                                                                 ot-6.2.1, rb-fsevent-0.11.1, rb-inotify-0.10.1, pry-0.14.1, rspec-core-3.11.0, rspec-expectations-3.11.0, rs                                                                                                                                 pec-mocks-3.11.1, rspec-support-3.11.0, parallel-1.22.1, rainbow-3.1.1, rubocop-ast-1.19.1, ruby-progressbar                                                                                                                                 -1.11.0, unicode-display_width-2.2.0, docile-1.4.0, simplecov-html-0.10.2, sprockets-4.2.0, domain_name-0.5.                                                                                                                                 20190701, mime-types-data-3.2022.0105, google-cloud-env-1.6.0, google-cloud-errors-1.2.0, googleapis-common-                                                                                                                                 protos-1.3.12, googleapis-common-protos-types-1.3.2, gapic-common-0.10.0, aws-eventstream-1.2.0, aws-partiti                                                                                                                                 ons-1.605.0, jmespath-1.6.1, net-http-persistent-4.0.1, google-apis-core-0.7.0, memoist-0.16.2, os-1.1.4, si                                                                                                                                 gnet-0.17.0, sassc-2.4.0, tilt-2.0.10, multi_xml-0.6.0, faraday-em_http-1.0.0, faraday-em_synchrony-1.0.0, f                                                                                                                                 araday-excon-1.1.0, faraday-httpclient-1.0.1, faraday-multipart-1.0.4, faraday-net_http-1.0.1, faraday-net_h                                                                                                                                 ttp_persistent-1.2.0, faraday-patron-1.0.0, faraday-rack-1.0.0, faraday-retry-1.0.3, google-cloud-location-0                                                                                                                                 .2.0, http-form_data-2.3.0, llhttp-ffi-0.4.0, ast-2.4.2, et-orbi-1.2.7, raabro-1.4.0, sexp_processor-4.16.1,                                                                                                                                  snaky_hash-2.0.1, version_gem-1.1.1, database_cleaner-core-2.0.1, coderay-1.1.3, diff-lcs-1.5.0, unf-0.1.4,                                                                                                                                  google-protobuf-3.21.7-x86_64-linux, grpc-1.47.0-x86_64-linux, httpclient-2.8.3, representable-3.2.0, retri                                                                                                                                 able-3.1.2, webrick-1.7.0, multipart-post-2.2.3, ffi-compiler-1.0.1, unf_ext-0.0.8.2, declarative-0.0.20, tr                                                                                                                                 ailblazer-option-0.1.2, uber-0.1.0 in locally installed gems
<internal:/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `requir                                                                                                                                 e'
<internal:/usr/local/rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `requir                                                                                                                                 e'
/home/chatwoot/chatwoot/config/boot.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/config/application.rb:3:in `require_relative'
/home/chatwoot/chatwoot/config/application.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/Rakefile:4:in `require_relative'
/home/chatwoot/chatwoot/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by nlkocx** [comment]
Solved. Increased RAM to 10GB.

I’m migrating from [Tawk.to](http://tawk.to/) and there’s couple of problems…

First, I can’t seem to offer “consent” mode of GDPR for users… So, if I don’t offer I’m liable for GDPR fines…

Second is that there’s no cross-domain support… User lands on [lander.domain.com](http://lander.domain.com/) and goes to [shop.domain.com](http://shop.domain.com/) and the chat history is not there…

Third is that no “sounds” are made when someone messages me “I’ve set it on my profile”

Fourth, there is no kind of trigger for example… After 5 minutes of visitor on the page send a “x” welcome message…

**Comment by jochenstu** [comment]
If you want issues to be investigated (and they will if you follow form), you should a) search for existing tickets and b) create separate tickets for separate issues.
