### ISSUE TITLE
V2.16 Messages wont send and chats wont resolve

### ISSUE THREAD

**Issue by OllyJack** [chatwoot/chatwoot#6950]
**Describe the bug**

Upgraded to version 2.16 and when replying to livechats, the agents messages do not always go through.

Console error is:
```
TypeError: Cannot read properties of undefined (reading 'useInboxAvatarForBot')
    at u.useInboxAvatarForBot (configMixin.js:4:44)
    at dn.get (vue.common.prod.js:1445:21)
    at dn.evaluate (vue.common.prod.js:1495:21)
    at u.useInboxAvatarForBot (vue.common.prod.js:1607:32)
    at u.avatarUrl (AgentMessage.vue:133:1)
    at dn.get (vue.common.prod.js:1445:21)
    at dn.evaluate (vue.common.prod.js:1495:21)
    at u.avatarUrl (vue.common.prod.js:1607:32)
    at u.<anonymous> (AgentMessage.vue?ed24:1:403)
    at e._render (vue.common.prod.js:1880:21)

```
We're using Linux self-hosted.

**To Reproduce**

1. Raise a livechat
2. Reply to livechat
3. End user does not get a message
4. Send multiple messages, end user will recieve the message before. 

**Expected behavior**

Send a message to a user, and they receive it without issues.  Since upgrading to 2.16 this issue has been occurring without fail.

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X ] Self-hosted
- - [ X] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Additional context**

When closing chats as a user, this also triggers the above error.

**Comment by vishnu-narayanan** [comment]
@OllyJack Was the upgrade process successful?

**Comment by GrygorievEvgeniy** [comment]
Have the same issue, upgrade was succesful.
Messages do not always go through, only agent side. From clients is all okey.

**Comment by GrygorievEvgeniy** [comment]
> Have the same issue, upgrade was succesful. Messages do not always go through, only agent side. From clients is all okey.

Problem resolved on manual upgrade with RAILS_ENV=production rake assets:clean assets:clobber assets:precompile

**Comment by arladmin** [comment]
Facing the same issue on my Cloudron instance.

Need an urgent fix.

**Comment by GrygorievEvgeniy** [comment]
> Facing the same issue on my Cloudron instance.
> 
> Need an urgent fix.


Do you make local changes?

**Comment by arladmin** [comment]
@GrygorievEvgeniy none

**Comment by GrygorievEvgeniy** [comment]
> @GrygorievEvgeniy none

Do you try manual upgrade?

**Comment by arladmin** [comment]
> > @GrygorievEvgeniy none
> 
> Do you try manual upgrade?

I tried this:
> RAILS_ENV=production rake assets:clean assets:clobber assets:precompile

but seems like Cloudron users can't perform manual upgrades.

**Comment by nebulade** [comment]
On Cloudron the apps run in a read-only environment, so rebuilding assets will not work. However for each version/app package we build all assets fresh, so I am not sure how rebuilding them will fix this issue, unless some runtime configuration requires that?

**Comment by scysys** [comment]
Same here after upgrading to 2.17.1 on Ubuntu 20.04. The upgrade process was working with a successful message. I realized after a few days that messages on the agent and user side are not arriving.

**The console log shows**

```
js:659  TypeError: Cannot read properties of undefined (reading 'useInboxAvatarForBot')
    at u.useInboxAvatarForBot (configMixin.js:4:44)
    at dn.get (vue.common.prod.js:1445:21)
    at dn.evaluate (vue.common.prod.js:1495:21)
    at u.useInboxAvatarForBot (vue.common.prod.js:1607:32)
    at u.avatarUrl (AgentMessage.vue:133:1)
    at dn.get (vue.common.prod.js:1445:21)
    at dn.evaluate (vue.common.prod.js:1495:21)
    at u.avatarUrl (vue.common.prod.js:1607:32)
    at u.<anonymous> (AgentMessage.vue:1:403)
    at e._render (vue.common.prod.js:1880:21)
```

The solution from @GrygorievEvgeniy is also working here! 🥇 

----

If needed, I also tried to do the upgrade process again. This was the output every time. At first, I thought maybe doing the upgrade process one more time would fix the missing things.

```
root@cs:~# ./setup.sh -u
Upgrading Chatwoot to v2.17.1
Upgrading Redis to v7+ for Rails 7 support(Chatwoot v2.17+)
File '/usr/share/keyrings/redis-archive-keyring.gpg' exists. Overwrite? (y/N) y
deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb focal main
Hit:1 https://deb.nodesource.com/node_16.x focal InRelease
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                              
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu focal InRelease                          
Hit:4 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 https://packages.redis.io/deb focal InRelease
Get:6 http://nova.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:8 http://repo.zabbix.com/zabbix/5.0/ubuntu focal InRelease
Fetched 239 kB in 1s (173 kB/s)                               
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
redis-server is already the newest version (6:7.0.11-1rl1~focal1).
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libmagickcore-6.q16-6-extra sntp imagemagick libhdf5-103
  libmagickwand-6.q16-6 libcgraph6 ntp imagemagick-6.q16 libmatio9 libcdt5
  libpathplan4 libopenexr24 libmagickcore-6.q16-6 libgvc6 imagemagick-6-common
Learn more about Ubuntu Pro at https://ubuntu.com/pro
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libvips42' instead of 'libvips'
libvips42 is already the newest version (8.9.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Already installed ruby-3.2.2.
To reinstall use:

    rvm reinstall ruby-3.2.2

Using /usr/local/rvm/gems/ruby-3.2.2
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using i18n 1.13.0
Using minitest 5.18.0
Using tzinfo 2.0.6
Using activesupport 7.0.4.3
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.6.2
Using nokogiri 1.14.3 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.20.0
Using rails-html-sanitizer 1.5.0
Using actionview 7.0.4.3
Using rack 2.2.7
Using rack-test 2.1.0
Using actionpack 7.0.4.3
Using nio4r 2.5.9
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 7.0.4.3
Using globalid 1.1.0
Using activejob 7.0.4.3
Using activemodel 7.0.4.3
Using activerecord 7.0.4.3
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 7.0.4.3
Using date 3.3.3
Using timeout 0.3.2
Using net-protocol 0.2.1
Using net-imap 0.3.4
Using net-pop 0.1.2
Using net-smtp 0.3.3
Using mail 2.8.1
Using actionmailbox 7.0.4.3
Using actionmailer 7.0.4.3
Using actiontext 7.0.4.3
Using active_record_query_trace 1.8
Using activerecord-import 1.4.1
Using acts-as-taggable-on 9.0.1
Using public_suffix 5.0.1
Using addressable 2.8.4
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.6.8
Using railties 7.0.4.3
Using jquery-rails 4.5.1
Using kaminari-core 1.2.2
Using kaminari-actionview 1.2.2
Using kaminari-activerecord 1.2.2
Using kaminari 1.2.2
Using ffi 1.15.5
Using sassc 2.4.0
Using sprockets 4.2.0
Using sprockets-rails 3.4.2
Using tilt 2.1.0
Using sassc-rails 2.1.2
Using selectize-rails 0.12.6
Using administrate 0.18.0
Using annotate 3.2.0
Using ast 2.4.2
Using attr_extras 7.1.0
Using request_store 1.5.1
Using audited 5.3.3
Using aws-eventstream 1.2.0
Using aws-partitions 1.760.0
Using aws-sigv4 1.5.2
Using jmespath 1.6.2
Using aws-sdk-core 3.171.1
Using aws-sdk-kms 1.64.0
Using aws-sdk-s3 1.122.0
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using faraday 2.7.4
Using faraday-follow_redirects 0.3.0
Using connection_pool 2.4.0
Using net-http-persistent 4.0.2
Using faraday-net_http_persistent 2.1.0
Using azure-storage-common 2.0.4 from https://github.com/chatwoot/azure-storage-ruby (at chatwoot@9957cf8)
Using azure-storage-blob 2.0.3 from https://github.com/chatwoot/azure-storage-ruby (at chatwoot@9957cf8)
Using multi_json 1.15.0
Using statsd-ruby 1.5.0
Using barnes 0.0.9
Using bcrypt 3.1.18
Using bindex 0.8.1
Using msgpack 1.7.0
Using bootsnap 1.16.0
Using brakeman 5.4.1
Using browser 5.3.1
Using uniform_notifier 1.16.0
Using bullet 7.0.7
Using bundler 2.4.10
Using bundler-audit 0.9.1
Using bundle-audit 0.1.0
Using byebug 11.1.3
Using climate_control 1.2.0
Using coderay 1.1.3
Using commonmarker 0.23.9
Using rexml 3.2.5
Using crack 0.4.5
Using csv-safe 3.2.1
Using cypress-on-rails 1.13.1
Using database_cleaner-core 2.0.1
Using database_cleaner-active_record 2.1.0
Using database_cleaner 2.0.2
Using debase-ruby_core_source 3.2.0
Using libdatadog 2.0.0.1.0 (x86_64-linux)
Using libddwaf 1.8.2.0.0 (x86_64-linux)
Using ddtrace 1.11.1
Using declarative 0.0.20
Using orm_adapter 0.5.0
Using responders 3.1.0
Using warden 1.2.9
Using devise 4.9.2
Using devise-secure_password 2.0.1 from https://github.com/chatwoot/devise-secure_password (at chatwoot@adcc85f)
Using rails 7.0.4.3
Using devise_token_auth 1.2.1
Using diff-lcs 1.5.0
Using digest-crc 0.6.4
Using docile 1.4.0
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.8.1
Using dotenv-rails 2.8.1
Using down 5.4.0
Using regexp_parser 2.8.0
Using ecma-re-validator 0.4.0
Using http-cookie 1.0.5
Using http-form_data 2.3.0
Using ffi-compiler 1.0.1
Using llhttp-ffi 0.4.0
Using http 5.1.1
Using elastic-apm 4.6.2
Using email_reply_trimmer 0.1.13
Using et-orbi 1.2.7
Using execjs 2.8.1
Using multi_xml 0.6.0
Using httparty 0.21.0
Using facebook-messenger 2.0.1
Using factory_bot 6.2.1
Using factory_bot_rails 6.2.0
Using faker 3.2.0
Using hashie 5.0.0
Using faraday-mashify 0.1.1
Using multipart-post 2.3.0
Using faraday-multipart 1.0.4
Using faraday-retry 2.1.0
Using jwt 2.7.0
Using memoist 0.16.2
Using os 1.1.4
Using signet 0.17.0
Using googleauth 1.5.2
Using fcm 1.0.8
Using flag_shih_tzu 0.3.23
Using foreman 0.87.2
Using raabro 1.4.0
Using fugit 1.8.1
Using google-protobuf 3.22.3 (x86_64-linux)
Using googleapis-common-protos-types 1.6.0
Using grpc 1.54.0 (x86_64-linux)
Using googleapis-common-protos 1.4.0
Using gapic-common 0.18.0
Using geocoder 1.8.1
Using gli 2.21.0
Using version_gem 1.1.2
Using oauth-tty 1.0.5
Using snaky_hash 2.0.1
Using oauth 1.1.0
Using gmail_xoauth 0.4.2
Using httpclient 2.8.3
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using representable 3.2.0
Using retriable 3.1.2
Using webrick 1.8.1
Using google-apis-core 0.11.0
Using google-apis-iamcredentials_v1 0.17.0
Using google-apis-storage_v1 0.19.0
Using google-cloud-env 1.6.0
Using google-cloud-errors 1.3.1
Using google-cloud-core 1.6.0
Using google-cloud-location 0.4.0
Using google-cloud-dialogflow-v2 0.23.0
Using google-cloud-storage 1.44.0
Using google-cloud-translate-v3 0.6.0
Using groupdate 6.2.1
Using haikunator 1.1.1
Using sexp_processor 4.17.0
Using ruby_parser 3.20.0
Using ruby2ruby 2.5.0
Using hairtrigger 1.0.0
Using hana 1.3.7
Using hashdiff 1.0.1
Using hkdf 1.0.0
Using html2text 0.3.1 from https://github.com/chatwoot/html2text_ruby (at chatwoot@cdbdbbb)
Using http-accept 1.7.0
Using mini_magick 4.12.0
Using ruby-vips 2.1.4
Using image_processing 1.12.2
Using jbuilder 2.11.5
Using json 2.6.3
Using json_refs 0.1.8
Using uri_template 0.7.0
Using json_schemer 0.2.24
Using koala 3.4.0
Using launchy 2.5.2
Using letter_opener 1.8.1
Using line-bot-api 1.28.0
Using liquid 5.4.0
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.8.0
Using lograge 0.12.0
Using maxminddb 0.1.22
Using mime-types-data 3.2023.0218.1
Using mime-types 3.4.1
Using mock_redis 0.36.0
Using netrc 0.11.0
Using newrelic_rpm 8.16.0
Using redis-client 0.14.1
Using sidekiq 7.1.0
Using newrelic-sidekiq-metrics 1.6.1
Using oauth2 2.0.9
Using rack-protection 3.0.6
Using omniauth 2.1.1
Using omniauth-oauth2 1.8.0
Using omniauth-google-oauth2 1.1.1
Using omniauth-rails_csrf_protection 1.0.1
Using openssl 3.1.0
Using parallel 1.23.0
Using parser 3.2.2.1
Using pg 1.5.3
Using pg_search 2.3.6
Using procore-sift 1.0.0
Using pry 0.14.2
Using pry-rails 0.3.9
Using puma 6.2.2
Using pundit 2.3.0
Using rack-attack 6.6.1
Using rack-cors 2.0.1
Using rack-mini-profiler 3.1.0
Using rack-proxy 0.7.6
Using rack-timeout 0.6.3
Using rainbow 3.1.1
Using redis 5.0.6
Using redis-namespace 1.10.0
Using rest-client 2.1.0
Using rspec-support 3.12.0
Using rspec-core 3.12.2
Using rspec-expectations 3.12.3
Using rspec-mocks 3.12.5
Using rspec-rails 6.0.2
Using rspec_junit_formatter 0.6.0
Using rubocop-ast 1.28.1
Using ruby-progressbar 1.13.0
Using unicode-display_width 2.4.2
Using rubocop 1.50.2
Using rubocop-capybara 2.18.0
Using rubocop-performance 1.17.1
Using rubocop-rails 2.19.1
Using rubocop-rspec 2.21.0
Using sass-listen 4.0.0
Using sass 3.7.4
Using scout_apm 5.3.3
Using scss_lint 0.60.0
Using seed_dump 3.3.1
Using semantic_range 3.0.0
Using sentry-ruby 5.9.0
Using sentry-rails 5.9.0
Using sentry-sidekiq 5.9.0
Using shoulda-matchers 5.3.0
Using sidekiq-cron 1.10.0
Using simplecov-html 0.10.2
Using simplecov 0.17.1
Using slack-ruby-client 2.0.0
Using spring 4.1.1
Using spring-watcher-listen 2.1.0
Using squasher 0.7.2
Using stackprof 0.2.25
Using stripe 8.5.0
Using telephone_number 1.4.20
Using test-prof 1.2.1
Using time_diff 0.3.0
Using twilio-ruby 5.77.0
Using twitty 0.1.5
Using tzinfo-data 1.2023.3
Using uglifier 4.2.0
Using valid_email2 4.0.6
Using web-console 4.2.0
Using web-push 3.0.0
Using webmock 3.18.1
Using webpacker 5.4.4
Using wisper 2.0.0
Using working_hours 1.4.1
Bundle complete! 117 Gemfile dependencies, 297 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 1.59s.
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 1.74s.
Everything's up-to-date. Nothing to do
Loading Installation config
```

**Comment by sojan-official** [comment]
- closing this issue since its from 2.16
