### ISSUE TITLE
Chatwoot Error In Prod.

### ISSUE THREAD

**Issue by dhwaj1902** [chatwoot/chatwoot#6974]
Getting this error on the website
![image](https://user-images.githubusercontent.com/57860123/234083287-fa7ecf24-eb74-48e5-af92-efca638ff90b.png)

Logs:
```
Apr 24 18:16:23 ip-172-31-43-40 chatwoot-web.1[452]: I, [2023-04-24T18:16:23.570431 #452]  INFO -- : RoomChannel#update_presence
Apr 24 18:16:23 ip-172-31-43-40 chatwoot-web.1[452]: E, [2023-04-24T18:16:23.571102 #452] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"TfRibVPWS5Y6aN2cvkQBeLdZ\",\"account_id\":1,\"user_id\":1}", "data"=>"{\"action\":\"update_presence\"}"}) [Redis::CommandError - MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.]: /usr/local/rvm/gems/ruby-3.1.3/gems/redis-4.7.1/lib/redis/client.rb:162:in `call' | /usr/local/rvm/gems/ruby-3.1.3/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command' | /usr/local/rvm/gems/ruby-3.1.3/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize' | /usr/local/rvm/gems/ruby-3.1.3/gems/redis-4.7.1/lib/redis.rb:268:in `send_command' | /usr/local/rvm/gems/ruby-3.1.3/gems/redis-4.7.1/lib/redis/commands/sorted_sets.rb:70:in `zadd'
```

I Using a self-hosted instance(with linux installation)

Please help me solve the issue because it is running in production.

**Comment by vishnu-narayanan** [comment]
@dhwaj1902  Could you please share the following?

```
**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)


**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, firefox, safari]
 - Version [e.g. 22]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

Add any other context about the problem here.

```

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
