### ISSUE TITLE
Backend test failure

### ISSUE THREAD

**Issue by mesutrk95** [chatwoot/chatwoot#7109]
### Describe the bug

I attempted to execute the backend test workflow [run_foss_spec.yml](https://github.com/chatwoot/chatwoot/blob/develop/.github/workflows/run_foss_spec.yml), but unfortunately, it failed and returned 14 errors. I would like to note that I did not modify the file in question prior to running the test.

```
Failures:

  1) Platform Accounts API GET /platform/api/v1/accounts/{account_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/accounts_controller_spec.rb:103:in `block (4 levels) in <top (required)>'

  2) Platform Accounts API PATCH /platform/api/v1/accounts/{account_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/accounts_controller_spec.rb:141:in `block (4 levels) in <top (required)>'

  3) Platform Accounts API DELETE /platform/api/v1/accounts/{account_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/accounts_controller_spec.rb:190:in `block (4 levels) in <top (required)>'

  4) Platform Agent Bot API GET /platform/api/v1/agent_bots/{agent_bot_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/agent_bots_controller_spec.rb:65:in `block (4 levels) in <top (required)>'

  5) Platform Users API GET /platform/api/v1/users/{user_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/users_controller_spec.rb:27:in `block (4 levels) in <top (required)>'

  6) Platform Users API PATCH /platform/api/v1/users/{user_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/users_controller_spec.rb:161:in `block (4 levels) in <top (required)>'

  7) Platform Users API DELETE /platform/api/v1/users/{user_id} when it is an authenticated platform app returns unauthorized when its not a permissible object
     Failure/Error: expect(response).to have_http_status(:unauthorized)
       expected the response to have status code :unauthorized (401) but it was :ok (200)
     # ./spec/controllers/platform/api/v1/users_controller_spec.rb:201:in `block (4 levels) in <top (required)>'

  8) Public Portals API GET /public/api/v1/portals/{portal_slug} Throws unauthorised error for unknown domain
     Failure/Error: expect(json_response['error']).to eql "Domain: www.example.com is not registered with us. \

       expected: "Domain: www.example.com is not registered with us.       Please send us an email at support@chatwoot.com with the custom domain name and account API key"
            got: "Domain: www.example.com is not registered with us.       Please send us an email at support@hoory.com with the custom domain name and account API key"

       (compared using eql?)
     # ./spec/controllers/public/api/v1/portals_controller_spec.rb:28:in `block (3 levels) in <top (required)>'

  9) SupportMailbox when a chatwoot notification email is received shouldnt create a conversation in the channel
     Failure/Error: expect(conversation.present?).to be(false)

       expected false
            got true
     # ./spec/mailboxes/support_mailbox_spec.rb:15:in `block (3 levels) in <top (required)>'

  10) ConversationReplyMailer reply when inbox email address is available set reply to email address as inbox email address
      Failure/Error: expect(mail.from).to eq([inbox.email_address])

        expected: ["noreply@chatwoot.com"]
             got: ["support@test.com"]

        (compared using ==)
      # ./spec/mailers/conversation_reply_mailer_spec.rb:243:in `block (4 levels) in <top (required)>'

  11) ConversationReplyMailer reply when the custom domain emails are enabled sets reply to email to be based on the domain
      Failure/Error: return @channel.email if @channel.email

      NoMethodError:
        undefined method `email' for #<Channel::WebWidget id: 823, website_url: "https://example-821.com/", account_id: 1525, created_at: "2023-05-17 10:38:58.648225000 +0000", updated_at: "2023-05-17 10:38:58.648225000 +0000", website_token: "yP9rEEF4PcDNFvN89HJ78x2X", widget_color: "821", welcome_title: nil, welcome_tagline: nil, feature_flags: 7, reply_time: "in_a_few_minutes", hmac_token: "1GYqb2oz8xZYV9gcThh7Qju2", pre_chat_form_enabled: false, pre_chat_form_options: {"pre_chat_fields"=>[{"name"=>"emailAddress", "type"=>"email", "label"=>"Email Id", "enabled"=>false, "required"=>true, "field_type"=>"standard"}, {"name"=>"fullName", "type"=>"text", "label"=>"Full name", "enabled"=>false, "required"=>false, "field_type"=>"standard"}, {"name"=>"phoneNumber", "type"=>"text", "label"=>"Phone number", "enabled"=>false, "required"=>false, "field_type"=>"standard"}], "pre_chat_message"=>"Share your queries or comments here."}, hmac_mandatory: false, continuity_via_email: true>
      # ./app/mailers/conversation_reply_mailer.rb:133:in `inbox_from_email_address'
      # ./app/mailers/conversation_reply_mailer.rb:110:in `from_email_with_name'
      # ./app/mailers/conversation_reply_mailer_helper.rb:75:in `email_from'
      # ./app/mailers/conversation_reply_mailer_helper.rb:5:in `prepare_mail'
      # ./app/mailers/conversation_reply_mailer.rb:16:in `reply_with_summary'
      # ./app/mailers/application_mailer.rb:81:in `switch_locale'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:253:in `block (4 levels) in <top (required)>'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:266:in `block (4 levels) in <top (required)>'

  12) ConversationReplyMailer reply when the custom domain emails are enabled sets the from email to be the support email
      Failure/Error: return @channel.email if @channel.email

      NoMethodError:
        undefined method `email' for #<Channel::WebWidget id: 824, website_url: "https://example-822.com/", account_id: 1526, created_at: "2023-05-17 10:38:58.829179000 +0000", updated_at: "2023-05-17 10:38:58.829179000 +0000", website_token: "E8sYLS7ZfjtQukF32yHGS99h", widget_color: "822", welcome_title: nil, welcome_tagline: nil, feature_flags: 7, reply_time: "in_a_few_minutes", hmac_token: "TEs1THp3SxRacEYmKjrHoaC5", pre_chat_form_enabled: false, pre_chat_form_options: {"pre_chat_fields"=>[{"name"=>"emailAddress", "type"=>"email", "label"=>"Email Id", "enabled"=>false, "required"=>true, "field_type"=>"standard"}, {"name"=>"fullName", "type"=>"text", "label"=>"Full name", "enabled"=>false, "required"=>false, "field_type"=>"standard"}, {"name"=>"phoneNumber", "type"=>"text", "label"=>"Phone number", "enabled"=>false, "required"=>false, "field_type"=>"standard"}], "pre_chat_message"=>"Share your queries or comments here."}, hmac_mandatory: false, continuity_via_email: true>
      # ./app/mailers/conversation_reply_mailer.rb:133:in `inbox_from_email_address'
      # ./app/mailers/conversation_reply_mailer.rb:110:in `from_email_with_name'
      # ./app/mailers/conversation_reply_mailer_helper.rb:75:in `email_from'
      # ./app/mailers/conversation_reply_mailer_helper.rb:5:in `prepare_mail'
      # ./app/mailers/conversation_reply_mailer.rb:16:in `reply_with_summary'
      # ./app/mailers/application_mailer.rb:81:in `switch_locale'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:253:in `block (4 levels) in <top (required)>'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:271:in `block (4 levels) in <top (required)>'

  13) ConversationReplyMailer reply when the custom domain emails are enabled sets the correct custom message id
      Failure/Error: return @channel.email if @channel.email

      NoMethodError:
        undefined method `email' for #<Channel::WebWidget id: 825, website_url: "https://example-823.com/", account_id: 1527, created_at: "2023-05-17 10:38:59.005470000 +0000", updated_at: "2023-05-17 10:38:59.005470000 +0000", website_token: "psuDNJsstVhj5ooaWiRQ75FE", widget_color: "823", welcome_title: nil, welcome_tagline: nil, feature_flags: 7, reply_time: "in_a_few_minutes", hmac_token: "MBENkfheNEAWG5RrBpBWjzTf", pre_chat_form_enabled: false, pre_chat_form_options: {"pre_chat_fields"=>[{"name"=>"emailAddress", "type"=>"email", "label"=>"Email Id", "enabled"=>false, "required"=>true, "field_type"=>"standard"}, {"name"=>"fullName", "type"=>"text", "label"=>"Full name", "enabled"=>false, "required"=>false, "field_type"=>"standard"}, {"name"=>"phoneNumber", "type"=>"text", "label"=>"Phone number", "enabled"=>false, "required"=>false, "field_type"=>"standard"}], "pre_chat_message"=>"Share your queries or comments here."}, hmac_mandatory: false, continuity_via_email: true>
      # ./app/mailers/conversation_reply_mailer.rb:133:in `inbox_from_email_address'
      # ./app/mailers/conversation_reply_mailer.rb:110:in `from_email_with_name'
      # ./app/mailers/conversation_reply_mailer_helper.rb:75:in `email_from'
      # ./app/mailers/conversation_reply_mailer_helper.rb:5:in `prepare_mail'
      # ./app/mailers/conversation_reply_mailer.rb:16:in `reply_with_summary'
      # ./app/mailers/application_mailer.rb:81:in `switch_locale'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:253:in `block (4 levels) in <top (required)>'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:276:in `block (4 levels) in <top (required)>'

  14) ConversationReplyMailer reply when the custom domain emails are enabled sets the correct in reply to id
      Failure/Error: return @channel.email if @channel.email

      NoMethodError:
        undefined method `email' for #<Channel::WebWidget id: 826, website_url: "https://example-824.com/", account_id: 1528, created_at: "2023-05-17 10:38:59.184531000 +0000", updated_at: "2023-05-17 10:38:59.184531000 +0000", website_token: "GTyPj6tg54W7dQbvAPb6HyAc", widget_color: "824", welcome_title: nil, welcome_tagline: nil, feature_flags: 7, reply_time: "in_a_few_minutes", hmac_token: "bHce4GrMkV6gGe3PLXGjXwt3", pre_chat_form_enabled: false, pre_chat_form_options: {"pre_chat_fields"=>[{"name"=>"emailAddress", "type"=>"email", "label"=>"Email Id", "enabled"=>false, "required"=>true, "field_type"=>"standard"}, {"name"=>"fullName", "type"=>"text", "label"=>"Full name", "enabled"=>false, "required"=>false, "field_type"=>"standard"}, {"name"=>"phoneNumber", "type"=>"text", "label"=>"Phone number", "enabled"=>false, "required"=>false, "field_type"=>"standard"}], "pre_chat_message"=>"Share your queries or comments here."}, hmac_mandatory: false, continuity_via_email: true>
      # ./app/mailers/conversation_reply_mailer.rb:133:in `inbox_from_email_address'
      # ./app/mailers/conversation_reply_mailer.rb:110:in `from_email_with_name'
      # ./app/mailers/conversation_reply_mailer_helper.rb:75:in `email_from'
      # ./app/mailers/conversation_reply_mailer_helper.rb:5:in `prepare_mail'
      # ./app/mailers/conversation_reply_mailer.rb:16:in `reply_with_summary'
      # ./app/mailers/application_mailer.rb:81:in `switch_locale'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:253:in `block (4 levels) in <top (required)>'
      # ./spec/mailers/conversation_reply_mailer_spec.rb:280:in `block (4 levels) in <top (required)>'
```

### To Reproduce

1. test environment
2. when push and pull request 

### Expected behavior

Successfully pass all tests with no errors.

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

ubuntu-20.04

**Comment by pranavrajs** [comment]
@mesutrk95 Did you change any code?  As I can see we have Github action running FOSS only tests and it is green.

**Comment by mesutrk95** [comment]
Today, I cloned the project and set up the environment variables in my local machine running Ubuntu 20.02. However, when I ran the workflow commands, I encountered 27 error messages.

```
  1) /app/login without DEFAULT_LOCALE renders the dashboard
     Failure/Error: raise response.body

     # ./spec/controllers/dashboard_controller_spec.rb:7:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) /app/login with DEFAULT_LOCALE renders the dashboard
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./spec/controllers/dashboard_controller_spec.rb:16:in `block (4 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:24:in `block in modify'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `synchronize'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `modify'
     # ./spec/spec_helper.rb:19:in `with_modified_env'
     # ./spec/controllers/dashboard_controller_spec.rb:14:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  3) DeviseOverrides::OmniauthCallbacksController #omniauth_sucess blocks personal accounts signup
     Failure/Error: expect(response).to redirect_to(%r{/app/login\?error=business-account-only$})
       Expected response to be a <3XX: redirect>, but was a <500: Internal Server Error>
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:55:in `block (4 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:24:in `block in modify'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `synchronize'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `modify'
     # ./spec/spec_helper.rb:19:in `with_modified_env'
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:46:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  4) DeviseOverrides::OmniauthCallbacksController #omniauth_sucess blocks signup if ENV disabled
     Failure/Error: expect(response).to redirect_to(%r{/app/login\?error=no-account-found$})
       Expected response to be a <3XX: redirect>, but was a <500: Internal Server Error>
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:71:in `block (4 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:24:in `block in modify'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `synchronize'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `modify'
     # ./spec/spec_helper.rb:19:in `with_modified_env'
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  5) DeviseOverrides::OmniauthCallbacksController #omniauth_sucess allows login
     Failure/Error: expect(response).to redirect_to(%r{/app/login\?email=.+&sso_auth_token=.+$})
       Expected response to be a <3XX: redirect>, but was a <500: Internal Server Error>
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:84:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  6) DeviseOverrides::OmniauthCallbacksController #omniauth_sucess allows personal account login
     Failure/Error: expect(response).to redirect_to(%r{/app/login\?email=.+&sso_auth_token=.+$})
       Expected response to be a <3XX: redirect>, but was a <500: Internal Server Error>
     # ./spec/controllers/devise/omniauth_callbacks_controller_spec.rb:103:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  7) Installation::Onboarding API GET /installation/onboarding when CHATWOOT_INSTALLATION_ONBOARDING redis key is set returns onboarding page
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./spec/controllers/installation/onboarding_controller_spec.rb:19:in `block (4 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  8) Public Articles API GET /public/api/v1/portals/:slug/articles Fetch all articles in the portal
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./spec/controllers/public/api/v1/portals/articles_controller_spec.rb:23:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  9) Public Articles API GET /public/api/v1/portals/:slug/articles get all articles with searched text query
     Failure/Error: expect(response).to have_http_status(:success)
       expected the response to have a success status code (2xx) but it was 500
     # ./spec/controllers/public/api/v1/portals/articles_controller_spec.rb:38:in `block (3 levels) in <top (required)>'
     # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  10) Public Articles API GET /public/api/v1/portals/:slug/articles/:id Fetch article with the id
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/public/api/v1/portals/articles_controller_spec.rb:45:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  11) Public Articles API GET /public/api/v1/portals/:slug/articles/:id returns the article with the id with a different locale
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/public/api/v1/portals/articles_controller_spec.rb:52:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  12) Public Categories API GET /public/api/v1/portals/:portal_slug/categories Fetch all categories in the portal
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/public/api/v1/portals/categories_controller_spec.rb:19:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  13) Public Categories API GET /public/api/v1/portals/:portal_slug/categories/:slug Fetch category with the slug
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/public/api/v1/portals/categories_controller_spec.rb:29:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  14) Public Portals API GET /public/api/v1/portals/{portal_slug} Show portal and categories belonging to the portal
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/public/api/v1/portals_controller_spec.rb:16:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  15) /survey/response GET survey/responses/{uuid} renders the page correctly when called
      Failure/Error: expect(response).to be_successful
        expected `#<ActionDispatch::TestResponse:0x00007f1acb5270a0 @mon_data=#<Monitor:0x00007f1accceb510>, @mon_data_...st GET "http://localhost:3000/survey/responses/1cd114f9-2a46-496d-a840-6b42007f98f9" for 127.0.0.1>>.successful?` to be truthy, got false
      # ./spec/controllers/service/responses_controller_spec.rb:8:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  16) Super Admin access tokens API GET /super_admin/access_tokens when it is an authenticated super admin shows the list of access tokens
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/access_tokens_controller_spec.rb:19:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  17) Super Admin Account Users API GET /super_admin/account_users/new when it is an authenticated super admin shows the account user create page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/account_users_controller_spec.rb:18:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  18) Super Admin accounts API GET /super_admin/accounts when it is an authenticated user shows the list of accounts
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/accounts_controller_spec.rb:23:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  19) Super Admin agent-bots API GET /super_admin/agent_bots when it is an authenticated super admin shows the list of users
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/agent_bots_controller_spec.rb:20:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  20) Super Admin Application Config API GET /super_admin/app_config when it is an authenticated super admin shows the app_config page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/app_config_controller_spec.rb:20:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  21) Super Admin /super_admin renders the login page
      Failure/Error: expect(response).to have_http_status(:ok)
        expected the response to have status code :ok (200) but it was :internal_server_error (500)
      # ./spec/controllers/super_admin/devise/sessions_controller_spec.rb:8:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:24:in `block in modify'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `synchronize'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/climate_control-1.2.0/lib/climate_control.rb:15:in `modify'
      # ./spec/spec_helper.rb:19:in `with_modified_env'
      # ./spec/controllers/super_admin/devise/sessions_controller_spec.rb:6:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  22) Super Admin Installation Config API GET /super_admin/installation_configs/new when it is an authenticated super admin shows the installation_configs create page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/installation_configs_controller_spec.rb:24:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  23) Super Admin Installation Config API GET /super_admin/installation_configs/new when it is an authenticated super admin shows the installation_configs edit page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/installation_configs_controller_spec.rb:31:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  24) Super Admin Installation Config API GET /super_admin/installation_configs/new when it is an authenticated super admin shows the installation_configs list page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/installation_configs_controller_spec.rb:37:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  25) Super Admin Instance health GET /super_admin/instance_status when it is an authenticated super admin shows the instance_status page
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/instance_statuses_controller_spec.rb:18:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  26) Super Admin platform app API GET /super_admin/platform_apps when it is an authenticated super admin shows the list of users
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/platform_apps_controller_spec.rb:20:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  27) Super Admin Users API GET /super_admin/users when it is an authenticated super admin shows the list of users
      Failure/Error: expect(response).to have_http_status(:success)
        expected the response to have a success status code (2xx) but it was 500
      # ./spec/controllers/super_admin/users_controller_spec.rb:30:in `block (4 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  28) /widget GET /widget renders the page correctly when called with website_token
      Failure/Error: expect(response).to be_successful
        expected `#<ActionDispatch::TestResponse:0x00007f1acb3732b8 @mon_data=#<Monitor:0x00007f1accbef080>, @mon_data_...h::Request GET "http://localhost:3000/widget?website_token=wimsmChiGg5UButtEKMobV1b" for 127.0.0.1>>.successful?` to be truthy, got false
      # ./spec/controllers/widgets_controller_spec.rb:14:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  29) /widget GET /widget renders the page correctly when called with website_token and cw_conversation
      Failure/Error: expect(response).to be_successful
        expected `#<ActionDispatch::TestResponse:0x00007f1acb68fe60 @mon_data=#<Monitor:0x00007f1accabcc08>, @mon_data_....ITH8Mjvalwy3t5Gfw5bt-73pfkYwm77VKI_QDOU_92g&website_token=yVqErAg1PKLAfMZyYH4sNKqi" for 127.0.0.1>>.successful?` to be truthy, got false
      # ./spec/controllers/widgets_controller_spec.rb:20:in `block (3 levels) in <top (required)>'
      # /usr/share/rvm/gems/ruby-3.2.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
 
Finished in 8 minutes 19 seconds (files took 4.82 seconds to load)
2113 examples, 29 failures

```

**Comment by sojan-official** [comment]
@mesutrk95  The tests don't expect a .env file to be present in the environment. Please try removing the .env file and running the tests.  Setting specific values in .environment could affect how the specs are run, 

also it expects the database and redis to be accessible by the default config in the test environment, so please ensure that they are as well. 

```
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_test') %>"
  username: "<%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD', '') %>"
```

```
   url: ENV.fetch('REDIS_URL', 'redis://127.0.0.1:6379'),
    password: ENV.fetch('REDIS_PASSWORD', nil).presence,
```

------

Closing this as the tests are running fine in GitHub actions.
