### ISSUE TITLE
Increase Timeout for OpenAI Integration Requests

### ISSUE THREAD

**Issue by noremac09** [chatwoot/chatwoot#7111]
### Is your feature or enhancement related to a problem? Please describe.

Currently, the timeout for requests in the OpenAI integration is set to 15 seconds. However, when engaging in a dialogue with users in languages other than English or when dealing with large conversations, the response generation often takes longer than 15 seconds. As a result, the requests fail with a timeout error, preventing a successful completion of the conversation.

### Describe the solution you'd like

I would like to request an increase in the timeout duration for OpenAI integration requests. It would be beneficial to have a longer timeout, allowing the model sufficient time to generate responses, especially in scenarios involving non-English dialogues and large conversations. A reasonable increase in the timeout duration, such as 30 seconds or more, would greatly improve the reliability and usability of the integration.

### Additional context

The current timeout of 15 seconds is insufficient for certain use cases, leading to errors as shown in the log snippet provided. By extending the timeout, developers integrating OpenAI would have more flexibility and improved performance when working with the API. Considering the growing demand for multilingual support and the need to handle complex conversations, an extended timeout would greatly enhance the overall experience and functionality of the OpenAI integration.

```
May 17 20:06:21 E, [2023-05-17T20:06:21.352017 #21199] ERROR -- : source=rack-timeout id=e601b177-ed22-433c-a3dd-f201d7a2d33a timeout=15000ms service=15000ms state=timed_out
May 17 20:06:21 I, [2023-05-17T20:06:21.353016 #21199]  INFO -- : [e601b177-ed22-433c-a3dd-f201d7a2d33a] Completed 500 Internal Server Error in 14998ms (ActiveRecord: 2.3ms | Allocations: 1356851)
May 17 20:06:21 F, [2023-05-17T20:06:21.353583 #21199] FATAL -- : [e601b177-ed22-433c-a3dd-f201d7a2d33a]
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a]
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] lib/integrations/openai/processor_service.rb:132:in `make_api_call'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] lib/integrations/openai/processor_service.rb:115:in `reply_suggestion_message'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] lib/integrations/openai/processor_service.rb:17:in `perform'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/models/integrations/hook.rb:53:in `process_event'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/api/v1/accounts/integrations/hooks_controller.rb:14:in `process_event'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
May 17 20:06:21 [e601b177-ed22-433c-a3dd-f201d7a2d33a] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
May 17 20:06:21 I, [2023-05-17T20:06:21.353937 #21199]  INFO -- : source=rack-timeout id=e601b177-ed22-433c-a3dd-f201d7a2d33a timeout=15000ms service=15002ms state=completed
```

**Comment by jiacheo** [comment]
I always set the timeout to more than 3 minutes when pretending large input context or output.
