### ISSUE TITLE
Error while upgrading

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#7149]
### Describe the bug

chatwoot@chatwoot-volty:~/chatwoot$ RAILS_ENV=production bundle exec rake db:migrate
I, [2023-05-21T14:37:42.656219 #83412]  INFO -- : Migrating to AddIndexForSearchOperations (20230224124632)
== 20230224124632 AddIndexForSearchOperations: migrating ======================
-- enable_extension("pg_trgm")
   -> 0.0120s
2023-05-21T14:37:42.671Z pid=83412 tid=1ylk INFO: Sidekiq 7.1.0 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379", :password=>nil, :reconnect_attempts=>2, :timeout=>1}
E, [2023-05-21T14:37:42.673191 #83412] ERROR -- : [ActiveJob] Failed enqueuing Migration::AddSearchIndexesJob to Sidekiq(scheduled_jobs): RedisClient::UnsupportedServer (redis-client requires Redis 6+ with HELLO command available (redis://localhost:6379/0))
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

redis-client requires Redis 6+ with HELLO command available (redis://localhost:6379/0)
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:706:in `rescue in connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:662:in `connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:657:in `raw_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:624:in `ensure_connected'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:359:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:51:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:225:in `block in raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:222:in `raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:92:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:171:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:22:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:67:in `block in enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:35:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:9:in `block (2 levels) in <module:Instrumentation>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:25:in `tag_logger'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:63:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:30:in `perform_later'
/home/chatwoot/chatwoot/db/migrate/20230224124632_add_index_for_search_operations.rb:4:in `change'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:870:in `exec_migration'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1411:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1447:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1117:in `up'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1092:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `load'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `<main>'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
RedisClient::UnsupportedServer: redis-client requires Redis 6+ with HELLO command available (redis://localhost:6379/0)
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:706:in `rescue in connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:662:in `connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:657:in `raw_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:624:in `ensure_connected'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:359:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:51:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:225:in `block in raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:222:in `raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:92:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:171:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:22:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:67:in `block in enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:35:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:9:in `block (2 levels) in <module:Instrumentation>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:25:in `tag_logger'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:63:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:30:in `perform_later'
/home/chatwoot/chatwoot/db/migrate/20230224124632_add_index_for_search_operations.rb:4:in `change'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:870:in `exec_migration'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1411:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1447:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1117:in `up'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1092:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `load'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `<main>'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
RedisClient::CommandError: ERR unknown command `HELLO`, with args beginning with: `3`, 
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client/connection_mixin.rb:61:in `call_pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:696:in `block in connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client/middlewares.rb:16:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:695:in `connect'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:657:in `raw_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:624:in `ensure_connected'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client.rb:359:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/redis-client-0.14.1/lib/redis_client/decorator.rb:51:in `pipelined'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:225:in `block in raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:107:in `block (2 levels) in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:106:in `block in with'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/connection_pool-2.4.0/lib/connection_pool.rb:103:in `with'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:222:in `raw_push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:92:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.0/lib/sidekiq/client.rb:171:in `push'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:22:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:67:in `block in enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:35:in `instrument'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:9:in `block (2 levels) in <module:Instrumentation>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:25:in `tag_logger'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:63:in `enqueue'
/usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.4.3/lib/active_job/enqueuing.rb:30:in `perform_later'
/home/chatwoot/chatwoot/db/migrate/20230224124632_add_index_for_search_operations.rb:4:in `change'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:870:in `exec_migration'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1411:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1447:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1117:in `up'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1092:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.4.3/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `load'
/usr/local/rvm/rubies/ruby-3.2.2/bin/bundle:31:in `<main>'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

### To Reproduce

Upgrade manually

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by mattiamarras** [comment]
I made the try to upgrade with cwctl --upgrade but without success, trying to upgrade manually there is this errore. I am stuck with this problem now.

**Comment by mattiamarras** [comment]
Solved with 
sudo apt-get purge --auto-remove redis-server
