### ISSUE TITLE
[CW-2037] 500 error on /rails/active_storage/representations/redirect/... on ActiveStorage::FileNotFoundError

### ISSUE THREAD

**Issue by bradtgmurray** [chatwoot/chatwoot#7229]
### Describe the bug

Self-hosted v2.17.1

Seeing this fairly frequently in our logs. Not sure why the file isn't there, but 500 doesn't seem like the right status code.

```
2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.682846 #1]  INFO -- : source=rack-timeout id=c6a11c7bdb3d67a1ebf3b080eccc3245 timeout=15000ms service=8ms state=completed

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/server.rb:233:in `block in run'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/server.rb:431:in `process_client'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/request.rb:97:in `handle_request'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/request.rb:98:in `block in handle_request'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] puma (6.2.2) lib/puma/configuration.rb:270:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] railties (7.0.4.3) lib/rails/engine.rb:530:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/sendfile.rb:110:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/runtime.rb:22:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/method_override.rb:24:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `tagged'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:37:in `tagged'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `block in call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] railties (7.0.4.3) lib/rails/rack/logger.rb:40:in `call_app'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:99:in `run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/middleware/cookies.rb:704:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/head.rb:12:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/etag.rb:27:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] warden (1.2.9) lib/warden/manager.rb:34:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] warden (1.2.9) lib/warden/manager.rb:34:in `catch'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal.rb:251:in `dispatch'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal.rb:188:in `dispatch'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionview (7.0.4.3) lib/action_view/rendering.rb:39:in `process'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/abstract_controller/base.rb:151:in `process'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/action_controller/metal/rescue.rb:22:in `process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:233:in `process_action'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:138:in `run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `instance_exec'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actiontext (7.0.4.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actiontext (7.0.4.3) lib/action_text/rendering.rb:20:in `with_renderer'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] audited (5.3.3) lib/audited/sweeper.rb:16:in `around'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] audited (5.3.3) lib/audited/sweeper.rb:16:in `around'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:116:in `block in run_callbacks'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `invoke_before'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `each'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `block in invoke_before'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:200:in `block in halting'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/callbacks.rb:400:in `block in make_lambda'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:14:in `processed'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:19:in `process'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) app/models/active_storage/blob.rb:301:in `open'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service.rb:90:in `open'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/downloader.rb:12:in `open'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/downloader.rb:24:in `open_tempfile'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/downloader.rb:13:in `block in open'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/downloader.rb:32:in `download'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service/disk_service.rb:28:in `download'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service.rb:163:in `instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service/disk_service.rb:29:in `block in download'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service/disk_service.rb:143:in `stream'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] activestorage (7.0.4.3) lib/active_storage/service/disk_service.rb:150:in `rescue in stream'

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245]   

2023-05-31T11:53:11Z	[c6a11c7bdb3d67a1ebf3b080eccc3245] ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):

2023-05-31T11:53:11Z	F, [2023-05-31T11:53:11.682695 #1] FATAL -- : [c6a11c7bdb3d67a1ebf3b080eccc3245]   

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.681810 #1]  INFO -- : [c6a11c7bdb3d67a1ebf3b080eccc3245] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.9ms | Allocations: 1582)

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.681647 #1]  INFO -- : [c6a11c7bdb3d67a1ebf3b080eccc3245]   Disk Storage (0.2ms) Downloaded file from key: 2tn0j7zwvc8t4ltoe12zei4oywr7

2023-05-31T11:53:11Z	D, [2023-05-31T11:53:11.681167 #1] DEBUG -- : [c6a11c7bdb3d67a1ebf3b080eccc3245]   ActiveStorage::VariantRecord Load (0.4ms)  SELECT "active_storage_variant_records".* FROM "active_storage_variant_records" WHERE "active_storage_variant_records"."blob_id" = $1 AND "active_storage_variant_records"."variation_digest" = $2 LIMIT $3  [["blob_id", 1], ["variation_digest", "P5v6kS02U7Ei4rbw/mo/MWxXjvQ="], ["LIMIT", 1]]

2023-05-31T11:53:11Z	D, [2023-05-31T11:53:11.679784 #1] DEBUG -- : [c6a11c7bdb3d67a1ebf3b080eccc3245]   ActiveStorage::Blob Load (0.5ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.677535 #1]  INFO -- : [c6a11c7bdb3d67a1ebf3b080eccc3245]   Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d1425ecf49aac7a84fe8284f14ca665c3875a3a", "variation_key"=>"[FILTERED]", "filename"=>"eric headshot"}

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.677490 #1]  INFO -- : [c6a11c7bdb3d67a1ebf3b080eccc3245] Processing by ActiveStorage::Representations::RedirectController#show as PNG

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.675669 #1]  INFO -- : [c6a11c7bdb3d67a1ebf3b080eccc3245] Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d1425ecf49aac7a84fe8284f14ca665c3875a3a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJY0c1bkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--b704c8a8ee5b95b20e719aa3c4df3f4bd82729ef/eric%20headshot.png" for 94.5.250.198 at 2023-05-31 11:53:11 +0000

2023-05-31T11:53:11Z	D, [2023-05-31T11:53:11.675395 #1] DEBUG -- : source=rack-timeout id=c6a11c7bdb3d67a1ebf3b080eccc3245 timeout=15000ms service=0ms state=active

2023-05-31T11:53:11Z	I, [2023-05-31T11:53:11.675229 #1]  INFO -- : source=rack-timeout id=c6a11c7bdb3d67a1ebf3b080eccc3245 timeout=15000ms state=ready
```

### To Reproduce

Not sure how to reproduce, happy to debug further.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

<sub>[CW-2037](https://linear.app/chatwoot/issue/CW-2037/500-error-on-railsactive-storagerepresentationsredirect-on)</sub>

**Comment by vishnu-narayanan** [comment]
@bradtgmurray Could you share more details about your installation setup?

**Comment by vishnu-narayanan** [comment]
Also, are you using any cloud storage service for activestorage?

**Comment by bradtgmurray** [comment]
`ACTIVE_STORAGE_SERVICE=amazon`

Most storage is working, but for some reason this particular reference is dangling.

Hosted on EKS using RDS as the postgres database.

**Comment by vishnu-narayanan** [comment]
@bradtgmurray We are also seeing this in the logs. The error code should be 404 and not 500. We will prioritize this in the coming sprints.

**Comment by iwansyahp-rey** [comment]
I am not using active storage to handle upload and download, but I keep receiving this error. Can we avoid this error to be reported? in this case I want to not use active storage at all.

I see there is no option to disable according to this doc: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

thanks in advance
