### ISSUE TITLE
NoMethodError: 'processed_message_content' after upgrade

### ISSUE THREAD

**Issue by amplitudesxd** [chatwoot/chatwoot#7324]
### Describe the bug

Using cwctl to upgrade Chatwoot, after the upgrade I get the following error while trying to send a message:

```
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: F, [2023-06-16T06:27:40.934948 #410202] FATAL -- : [70702606-510d-4b34-a4b3-221d032d29f5]
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5] NoMethodError (undefined method `processed_message_content' for #<Message id: nil, content: "test", account_id: 1, inbox_id: 1, conversation_id: 68, message_type: "incoming", created_at: nil, updated_at: nil, private: false, status: "sent", source_id: nil, content_type: "text", content_attributes: {}, sender_type: "Contact", sender_id: 400, external_source_ids: {}, additional_attributes: {}>):
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5]
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5] app/controllers/api/v1/widget/messages_controller.rb:12:in `create'
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Jun 16 06:27:40 chatwoot chatwoot-web.1[410202]: [70702606-510d-4b34-a4b3-221d032d29f5] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

Additionally, messages in the dashboard do not load,

I've attempted to locate the cause of the issue but I'm not sure, so any help would be appreciated.

### To Reproduce

1. Upgrade Chatwoot from 2.17.1 to 2.18.0
2. Attempt to send message
3. Error

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by amplitudesxd** [comment]
The request to /api/v1/accounts/1/cache_keys returns 401 with the message `You need to sign in or sign up before continuing.`

**Comment by amplitudesxd** [comment]
Not sure what caused the issue, attempted to upgrade again and it fixed.
