### ISSUE TITLE
[CW-2374] OpenAI Integration 500 error

### ISSUE THREAD

**Issue by panaras10** [chatwoot/chatwoot#7586]
### Describe the bug

Everything is setup correctly but the cwctl logs show:

```
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: I, [2023-07-23T13:01:28.813257 #1159172]  INFO -- : [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] Completed 500 Internal Server Error in 162ms (ActiveRecord: 1.7ms | Allocations: 9277)
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: F, [2023-07-23T13:01:28.813661 #1159172] FATAL -- : [0ee07a71-a5bc-4b91-b5e1-dd63e5915925]
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] NoMethodError (undefined method `first' for nil:NilClass):
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925]
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] lib/integrations/openai_base_service.rb:78:in `make_api_call'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] lib/integrations/openai_base_service.rb:19:in `perform'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/models/integrations/hook.rb:53:in `process_event'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/api/v1/accounts/integrations/hooks_controller.rb:14:in `process_event'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
Jul 23 13:01:28 stablechat chatwoot-web.1[1159172]: [0ee07a71-a5bc-4b91-b5e1-dd63e5915925] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

```

I have 2 instances, one on 2.8 and one on the 3.0.0 and it's the same on both.

### To Reproduce

Brand new installation with API key from https://platform.openai.com/account/api-keys

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

<sub>[CW-2374](https://linear.app/chatwoot/issue/CW-2374/openai-integration-500-error)</sub>

**Comment by sojan-official** [comment]
will be fixed by https://github.com/chatwoot/chatwoot/commit/4c75bb68f442254155cd076ca418561a34f7d4a6
