### ISSUE TITLE
Error updating account on Super Admin

### ISSUE THREAD

**Issue by amplitudesxd** [chatwoot/chatwoot#7592]
### Describe the bug

When editing an account on the Super Admin using version 3.0.0-rc1, upon clicking save, I get an error page saying "We're sorry, but something went wrong."

Here's the log output:
```
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: I, [2023-07-24T13:39:49.460765 #109729]  INFO -- : [2d7a6930-36b4-4a45-839d-22d5aaacfe34] Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.7ms | Allocations: 1838)
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: F, [2023-07-24T13:39:49.461378 #109729] FATAL -- : [2d7a6930-36b4-4a45-839d-22d5aaacfe34]
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: [2d7a6930-36b4-4a45-839d-22d5aaacfe34] ArgumentError (wrong number of arguments (given 1, expected 0)):
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: [2d7a6930-36b4-4a45-839d-22d5aaacfe34]
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: [2d7a6930-36b4-4a45-839d-22d5aaacfe34] app/dashboards/account_dashboard.rb:89:in `permitted_attributes'
Jul 24 13:39:49 chatwoot chatwoot-web.1[109729]: [2d7a6930-36b4-4a45-839d-22d5aaacfe34] app/controllers/super_admin/accounts_controller.rb:37:in `resource_params'
```

### To Reproduce

1. Go on account in super admin panel
2. Click "Update Account"
3. See error

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
@amplitudesxd Could you post the full log, including the request parameters?

**Comment by amplitudesxd** [comment]
@sojan-official Of course, here it is:
```
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: I, [2023-07-24T18:17:25.806411 #112573]  INFO -- : [bd633e47-1331-4a66-a337-6528b60852bf] Started PATCH "/super_admin/accounts/1" for xx.xx.xx.xx at 2023-07-24 18:17:25 +0000
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: I, [2023-07-24T18:17:25.815525 #112573]  INFO -- : [bd633e47-1331-4a66-a337-6528b60852bf] Processing by SuperAdmin::AccountsController#update as HTML
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: I, [2023-07-24T18:17:25.815694 #112573]  INFO -- : [bd633e47-1331-4a66-a337-6528b60852bf]   Parameters: {"authenticity_token"=>"[FILTERED]", "account"=>{"name"=>"Dropmap", "locale"=>"en", "status"=>"active", "limits"=>{"agents"=>"", "inboxes"=>""}}, "enabled_features"=>{"feature_inbound_emails"=>"true", "feature_channel_email"=>"true", "feature_channel_facebook"=>"true", "feature_channel_twitter"=>"true", "feature_help_center"=>"true", "feature_macros"=>"true", "feature_agent_management"=>"true", "feature_team_management"=>"true", "feature_inbox_management"=>"true", "feature_labels"=>"true", "feature_custom_attributes"=>"true", "feature_automations"=>"true", "feature_canned_responses"=>"true", "feature_integrations"=>"true", "feature_voice_recorder"=>"true", "feature_channel_website"=>"true", "feature_campaigns"=>"true", "feature_reports"=>"true", "feature_crm"=>"true", "feature_auto_resolve_conversations"=>"true"}, "commit"=>"Update Account", "id"=>"1"}
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: I, [2023-07-24T18:17:25.821161 #112573]  INFO -- : [bd633e47-1331-4a66-a337-6528b60852bf] Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.9ms | Allocations: 1831)
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: F, [2023-07-24T18:17:25.821637 #112573] FATAL -- : [bd633e47-1331-4a66-a337-6528b60852bf]
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: [bd633e47-1331-4a66-a337-6528b60852bf] ArgumentError (wrong number of arguments (given 1, expected 0)):
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: [bd633e47-1331-4a66-a337-6528b60852bf]
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: [bd633e47-1331-4a66-a337-6528b60852bf] app/dashboards/account_dashboard.rb:89:in `permitted_attributes'
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: [bd633e47-1331-4a66-a337-6528b60852bf] app/controllers/super_admin/accounts_controller.rb:37:in `resource_params'
Jul 24 18:17:25 chatwoot chatwoot-web.1[112573]: I, [2023-07-24T18:17:25.821843 #112573]  INFO -- : source=rack-timeout id=bd633e47-1331-4a66-a337-6528b60852bf timeout=15000ms service=16ms state=completed
```

**Comment by sojan-official** [comment]
@amplitudesxd  Could you also provide the Chatwoot version which you are using?

**Comment by Hamzanael** [comment]
I have the same issue and I've installed the latest Chatwoot version

**Comment by Hamzanael** [comment]
```
F, [2023-07-28T12:53:30.377881 #1] FATAL -- : [8cc5334193c1f9a081a65e2c6e9240de]   
[8cc5334193c1f9a081a65e2c6e9240de] ArgumentError (wrong number of arguments (given 1, expected 0)):
[8cc5334193c1f9a081a65e2c6e9240de]   
[8cc5334193c1f9a081a65e2c6e9240de] app/dashboards/account_dashboard.rb:89:in `permitted_attributes'
[8cc5334193c1f9a081a65e2c6e9240de] app/controllers/super_admin/accounts_controller.rb:37:in `resource_params'
```

**Comment by amplitudesxd** [comment]
> @amplitudesxd Could you also provide the Chatwoot version which you are using?

I am using chatwoot v3.0.0-rc1

**Comment by LiamAshdown** [comment]
@sojan-official 

I can also replicate this in my local environment.

This only occurs in v3.0.0 of Chatwoot.

This is due to to bringing the latest version of `administrate`
[https://github.com/chatwoot/chatwoot/compare/v2.18.0...v3.0.0-rc1?diff=unified#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR77](url)

The latest version of `administrate` changes the way `permitted_attributes` work.
[https://github.com/thoughtbot/administrate/pull/2356/files#diff-4e220b661b88f9a19ac527c50d6f1577ef6ab7b0bed2bfdf048e22e6bfa74a05R204](url)

To rectify this we need to update the `permitted_attributes` function to accept parameters.

I will create a pull request to fix this.

**Comment by sojan-official** [comment]
@LiamAshdown  Thanks a lot for looking into this ❤️🚀
