### ISSUE TITLE
Fatal while compiling v3.0

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#7741]
### Describe the bug

After cwctl --upgrade failed on me, I resorted to `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile`

This is what I got:

```
Compiling...
Compilation failed:
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/chatwoot/chatwoot/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chatwoot/chatwoot/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

### To Reproduce

I assume this is not strictly reproducible.

1. cwctl --upgrade
2. RAILS_ENV=production rake assets:clean assets:clobber assets:precompile

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Additional context

Running on Hetzner CPX21 (3 core AMD, 4GB RAM, 80% free disk space)

**Comment by jochenstu** [comment]
Trying to run cwctl --upgrade again (after doing RAILS_ENV=production rake assets:clean assets:clobber assets:precompile) yields this:

```
root@chatwoot:/home/chatwoot/chatwoot# cwctl --upgrade
Upgrading Chatwoot to v3.0.0
public/assets/administrate/bot/avatar.png: needs update
public/assets/administrate/user/avatar.png: needs update
public/assets/images/auth/auth--bg.svg: needs update
public/assets/images/auth/bottom-right.svg: needs update
public/assets/images/auth/google.svg: needs update
public/assets/images/auth/top-left.svg: needs update
public/assets/images/dashboard/channels/api.png: needs update
public/assets/images/dashboard/channels/email.png: needs update
public/assets/images/dashboard/channels/facebook.png: needs update
public/assets/images/dashboard/channels/line.png: needs update
public/assets/images/dashboard/channels/microsoft.png: needs update
public/assets/images/dashboard/channels/sms.png: needs update
public/assets/images/dashboard/channels/telegram.png: needs update
public/assets/images/dashboard/channels/twilio.png: needs update
public/assets/images/dashboard/channels/twitter.png: needs update
public/assets/images/dashboard/channels/website.png: needs update
public/assets/images/dashboard/channels/whatsapp.png: needs update
public/assets/images/dashboard/editor/cmd-editor.png: needs update
public/assets/images/dashboard/editor/enter-editor.png: needs update
public/assets/images/dashboard/priority/high.svg: needs update
public/assets/images/dashboard/priority/low.svg: needs update
public/assets/images/dashboard/priority/medium.svg: needs update
public/assets/images/dashboard/priority/none.svg: needs update
public/assets/images/dashboard/priority/urgent.svg: needs update
public/assets/images/hc/grid.svg: needs update
Custom code changes detected. Aborting update.
Please proceed to update manually.
```

(There are no custom code changes that I am aware of)

**Comment by jochenstu** [comment]
Duplicate of https://github.com/chatwoot/chatwoot/issues/7626

**Comment by LiamAshdown** [comment]
This looks like node has somehow been updated on your machine.

If you run `node -v` what version does that output?

**Comment by jochenstu** [comment]
Node.js v18.16.0

I am fairly certain, that I did not upgrade this. I use this vhost solely for our chatwoot instance – but alas: After retrying right now with 16 the compilation is working. I do have at least one other major issue, which I will file separately. Thanks @LiamAshdown !
