### ISSUE TITLE
V3.0.0 - Unable to create website inbox

### ISSUE THREAD

**Issue by JordanBCX** [chatwoot/chatwoot#7763]
### Describe the bug

```
ons: 1436)
root-rails-1  | I, [2023-08-18T11:22:59.118492 #1]  INFO -- : [eb4ff8fd-738e-41db-993a-49b62f89ccec] Completed 500 Internal Server Error in 39ms (ActiveRecord: 21.7ms | Allocations: 14287)
root-rails-1  | F, [2023-08-18T11:22:59.119039 #1] FATAL -- : [eb4ff8fd-738e-41db-993a-49b62f89ccec]
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] ActionView::Template::Error (undefined method `business_name' for #<Inbox id: 13, channel_id: 10, account_id: 5, name: "Testing", created_at: "2023-08-18 11:22:59.086029327 +0000", updated_at: "2023-08-18 11:22:59.086029327 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: true, greeting_enabled: false, greeting_message: "", email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: false, allow_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, sender_name_type: nil>):
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     17: json.allow_messages_after_resolved resource.allow_messages_after_resolved
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     18: json.lock_to_single_conversation resource.lock_to_single_conversation
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     19: json.sender_name_type resource.sender_name_type
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     20: json.business_name resource.business_name
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     21:
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     22: if resource.portal.present?
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]     23:   json.help_center do
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec]
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/views/api/v1/models/_inbox.json.jbuilder:20
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/views/api/v1/accounts/inboxes/create.json.jbuilder:1
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
root-rails-1  | [eb4ff8fd-738e-41db-993a-49b62f89ccec] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
```

### To Reproduce

1. Fill out new inbox fields
2. Submit
3. Fail
![image](https://github.com/chatwoot/chatwoot/assets/9353117/a286e820-4c81-4b4b-a531-ba6aba1b3a00)

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Chrome 116

### Docker (if applicable)

```
Client: Docker Engine - Community
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        3e7cbfd
 Built:             Tue Apr  4 22:03:23 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       59118bf
  Built:            Tue Apr  4 22:03:23 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.4.157-1-pve
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4GiB
 Name: REDACTED
 ID: 964c0602-b1ec-4519-99b1-abdc76583781
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

`Docker Compose version v2.17.2`

**Comment by pranavrajs** [comment]
@JordanBCX Have you completed the DB migrations? It seems like the DB migrations are missing. Please see this guide. https://www.chatwoot.com/docs/self-hosted/deployment/upgrade/#docker

**Comment by JordanBCX** [comment]
> 

I have :) I did the migration when I was unable to load my conversation list. The installation works other than this minor issue

**Comment by JordanBCX** [comment]
I just retired and it does work, forgive me.
