### ISSUE TITLE
issue: Read Timeout on sending emails via smtp

### ISSUE THREAD

**Issue by zahidgu** [chatwoot/chatwoot#7802]
### Describe the bug

The emails sent out by chatwoot for user registration, password reset etc are not getting delivered most of the times and eventually a ReadTimeOut error is thrown. Upon digging it seems that ActionMailer has a default read timeout of 5 seconds with no Environment variable available to modify this behaviour.

Below is the log

```
I, [2023-08-17T11:34:00.281609 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [2e2dba32-63fb-4549-82c7-03a9141b41a0]   Rendered layout layouts/mailer/base.liquid (Duration: 4.5ms | Allocations: 462)
{"ts":"2023-08-17T11:34:03.194Z","pid":1,"tid":"2f45","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"05b0f7c23e0a6a87ac9bbb43"}}
I, [2023-08-17T11:34:03.195520 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1759fbc8-7c1e-4fc2-9d40-354e4177f4df] Performing Inboxes::FetchImapEmailInboxesJob (Job ID: 1759fbc8-7c1e-4fc2-9d40-354e4177f4df) from Sidekiq(scheduled_jobs) enqueued at 2023-08-17T11:34:03Z
I, [2023-08-17T11:34:03.197850 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1759fbc8-7c1e-4fc2-9d40-354e4177f4df] Performed Inboxes::FetchImapEmailInboxesJob (Job ID: 1759fbc8-7c1e-4fc2-9d40-354e4177f4df) from Sidekiq(scheduled_jobs) in 2.19ms
{"ts":"2023-08-17T11:34:03.198Z","pid":1,"tid":"2f45","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"05b0f7c23e0a6a87ac9bbb43","elapsed":0.003}}
I, [2023-08-17T11:34:05.326937 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [2e2dba32-63fb-4549-82c7-03a9141b41a0] Delivered mail 64de05a8450ae_11ba087464@chatwoot-worker-5df48f45d5-lfqps.mail (5044.5ms)
E, [2023-08-17T11:34:05.327202 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [2e2dba32-63fb-4549-82c7-03a9141b41a0] Error performing ActionMailer::MailDeliveryJob (Job ID: 2e2dba32-63fb-4549-82c7-03a9141b41a0) from Sidekiq(mailers) in 5054.7ms: Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):
/gems/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill'
/gems/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:199:in `readuntil'
/gems/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:209:in `readline'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1057:in `recv_response'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1051:in `get_response'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:854:in `block in auth_login'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1067:in `critical'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:851:in `auth_login'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:837:in `public_send'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:837:in `authenticate'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:670:in `do_start'
/gems/ruby/3.1.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'
/gems/ruby/3.1.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/gems/ruby/3.1.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/gems/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
/gems/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:559:in `block in deliver_mail'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:557:in `deliver_mail'
/gems/ruby/3.1.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/gems/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:48:in `block in perform_now'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:21:in `block in instrument'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:31:in `instrument'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:22:in `block in tag_logger'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:22:in `tag_logger'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:47:in `perform_now'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:25:in `block in execute'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:23:in `execute'
/gems/ruby/3.1.0/gems/activejob-6.1.7.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:196:in `execute_job'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:163:in `block in process'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:114:in `local'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/gems/ruby/3.1.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:257:in `stats'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:13:in `call'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:81:in `global'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:39:in `prepare'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:123:in `dispatch'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:162:in `process'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:78:in `process_one'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:68:in `run'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
/gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'
{"ts":"2023-08-17T11:34:05.328Z","pid":1,"tid":"2fbd","lvl":"INFO","msg":"fail","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"ab3784770ab2bc601a2bfeb2","elapsed":5.06}}
{"ts":"2023-08-17T11:34:05.328Z","pid":1,"tid":"2fbd","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"2e2dba32-63fb-4549-82c7-03a9141b41a0\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"Devise::Mailer\",\"reset_password_instructions\",\"deliver_now\",{\"params\":{\"account\":null,\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/SuperAdmin/2\"},\"wdmvpmGpEWtyWah6nRfU\",{\"client_config\":\"default\",\"_aj_symbol_keys\":[\"client_config\"]}],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2023-08-17T11:33:37Z\"}],\"jid\":\"ab3784770ab2bc601a2bfeb2\",\"created_at\":1692272017.0935266,\"enqueued_at\":1692272040.2680454,\"error_message\":\"Net::ReadTimeout with #<Socket:(closed)>\",\"error_class\":\"Net::ReadTimeout\",\"failed_at\":1692272022.1500747,\"retry_count\":0},\"jobstr\":\"{\\\"retry\\\":true,\\\"queue\\\":\\\"mailers\\\",\\\"class\\\":\\\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\\\",\\\"wrapped\\\":\\\"ActionMailer::MailDeliveryJob\\\",\\\"args\\\":[{\\\"job_class\\\":\\\"ActionMailer::MailDeliveryJob\\\",\\\"job_id\\\":\\\"2e2dba32-63fb-4549-82c7-03a9141b41a0\\\",\\\"provider_job_id\\\":null,\\\"queue_name\\\":\\\"mailers\\\",\\\"priority\\\":null,\\\"arguments\\\":[\\\"Devise::Mailer\\\",\\\"reset_password_instructions\\\",\\\"deliver_now\\\",{\\\"params\\\":{\\\"account\\\":null,\\\"_aj_symbol_keys\\\":[\\\"account\\\"]},\\\"args\\\":[{\\\"_aj_globalid\\\":\\\"gid://chatwoot/SuperAdmin/2\\\"},\\\"wdmvpmGpEWtyWah6nRfU\\\",{\\\"client_config\\\":\\\"default\\\",\\\"_aj_symbol_keys\\\":[\\\"client_config\\\"]}],\\\"_aj_ruby2_keywords\\\":[\\\"params\\\",\\\"args\\\"]}],\\\"executions\\\":0,\\\"exception_executions\\\":{},\\\"locale\\\":\\\"en\\\",\\\"timezone\\\":\\\"UTC\\\",\\\"enqueued_at\\\":\\\"2023-08-17T11:33:37Z\\\"}],\\\"jid\\\":\\\"ab3784770ab2bc601a2bfeb2\\\",\\\"created_at\\\":1692272017.0935266,\\\"enqueued_at\\\":1692272040.2680454,\\\"error_message\\\":\\\"Net::ReadTimeout with #<Socket:(closed)>\\\",\\\"error_class\\\":\\\"Net::ReadTimeout\\\",\\\"failed_at\\\":1692272022.1500747,\\\"retry_count\\\":0}\"}"}
```

### To Reproduce

With the default setting try sending email through a gateway that is slower.

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

### Additional context

Using Chatwoot Version 2.16, but I can see smtp_settings in chatwoot do not set any read_timeout value for config.action_mailer.smtp_settings.

**Comment by pranavrajs** [comment]
@zahidgu 

I found something similar on Discourse forums about read timeout. https://meta.discourse.org/t/smtp-net-readtimeout-without-relation-to-net-or-login-problems-smtp-host-is-just-slow/235727

The change here seems fine to me. Would you be able to contribute?

**Comment by imskr** [comment]
Can I work on this?

**Comment by prashanth-surya** [comment]
the same issue is also for me.
![image](https://github.com/chatwoot/chatwoot/assets/110809430/4f79258c-8561-4374-952a-3287d8687c7f)

**Comment by sojan-official** [comment]
@imskr  please go ahead

**Comment by jalberto** [comment]
any workaround?

**Comment by mona-chen** [comment]
so additionally, i'm getting the same issue when using Amazon SES, is it like a configuration thing or a bug.

**Comment by dorianmariecom** [comment]
Can confirm for Google/Gmail, switching from port 465 to port 587 fixed it

**Comment by NicksonYap** [comment]
Tested the fix to work:

This is for slow SMTP servers

default timeout I have also measured to be around 5 seconds

https://github.com/chatwoot/chatwoot/blob/v3.9.0/app/mailers/conversation_reply_mailer_helper.rb#L56


```diff
    smtp_settings = {
      address: @channel.smtp_address,
      port: @channel.smtp_port,
      user_name: @channel.smtp_login,
      password: @channel.smtp_password,
      domain: @channel.smtp_domain,
      tls: @channel.smtp_enable_ssl_tls,
      enable_starttls_auto: @channel.smtp_enable_starttls_auto,
      openssl_verify_mode: @channel.smtp_openssl_verify_mode,
+      open_timeout: 15,
+      read_timeout: 15,
      authentication: @channel.smtp_authentication
    }
 ```

**Comment by sojan-official** [comment]
@NicksonYap  are you interested in raising a PR for this?

**Comment by sojan-official** [comment]
We will take this forward over https://github.com/chatwoot/chatwoot/pull/10318
