### ISSUE TITLE
dev mode using helm chart

### ISSUE THREAD

**Issue by meMaipal** [chatwoot/chatwoot#7877]
### Describe the bug

i am unable to run chatwoot stack on k8s using helm chart in development mode

### To Reproduce

image:
    repository: chatwoot/chatwoot
    tag: v3.0.0
    pullPolicy: IfNotPresent

autoscaling:
    apiVersion: autoscaling/v2

services:
    name: chatwoot
    internalPort: 3000
    targetPort: 3000
    type: ClusterIP

serviceAccount:
    create: true

service:
    type: ClusterIP
    port: 80

postgresql:
    enabled: false
    auth:
        username: .........
        postgresPassword: ...............
        database: chatwoot_dev
    postgresqlHost:........................
    postgresqlPort: 5432

redis:
    enabled: true
    nameOverride: chatwoot-redis
    auth:
        password: redis
    master:
        persistence:
            enabled: false
    replica:
        replicaCount: 1

hooks:
    affinity: {}
    migrate:
        env: []
        resources:
            limits:
                memory: 100Mi
            requests:
                memory: 100Mi
        hookAnnotation: "post-install,post-upgrade"

env:
    ACTIVE_STORAGE_SERVICE: local
    ANDROID_BUNDLE_ID: com.chatwoot.app
    ANDROID_SHA256_CERT_FINGERPRINT: "AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8"
    ENABLE_ACCOUNT_SIGNUP: false
    FORCE_SSL: false
    FRONTEND_URL: "*..*.com"
    INSTALLATION_ENV: helm
    IOS_APP_ID: 6C953F3RX2.com.chatwoot.app
    LOG_LEVEL: info
    LOG_SIZE: 500
    RAILS_ENV: development
    RAILS_LOG_TO_STDOUT: true
    RAILS_MAX_THREADS: 5
    REDIS_TLS: false
    SECRET_KEY_BASE: 1vbpySIMyz720flTsnOELWVcFlZpjNGUw==

### Expected behavior

it is working if i switch RAILS_ENV  production 

& it should work if i switch back RAILS_ENV to devlopment

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

None

### Operating system

i am using custom k8s deployed on aws ec2

### Additional context

log of chatwoot-web pod

10566534Z Using web-push 3.0.0
2023-09-07T09:46:10.211475477Z Using webpacker 5.4.4
2023-09-07T09:46:10.212098375Z Using wisper 2.0.0
2023-09-07T09:46:10.212839615Z Using working_hours 1.4.1
2023-09-07T09:46:10.248566357Z Bundle complete! 123 Gemfile dependencies, 245 gems now installed.
2023-09-07T09:46:10.248684028Z Gems in the groups 'development' and 'test' were not installed.
2023-09-07T09:46:10.248767419Z Bundled gems are installed into `/gems`
2023-09-07T09:46:10.257619861Z + BUNDLE='bundle check'
2023-09-07T09:46:10.257667382Z + bundle check
2023-09-07T09:46:10.708885707Z The Gemfile's dependencies are satisfied
2023-09-07T09:46:10.712534957Z + exec bundle exec rails s -p 3000 -b 0.0.0.0
2023-09-07T09:46:16.778826349Z => Booting Puma
2023-09-07T09:46:16.778845299Z => Rails 7.0.5.1 application starting in development 
2023-09-07T09:46:16.778869579Z => Run `bin/rails server --help` for more startup options
2023-09-07T09:46:16.798705582Z Exiting
2023-09-07T09:46:16.869913691Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- listen (LoadError)
2023-09-07T09:46:16.869957472Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.869962112Z  from /gems/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
2023-09-07T09:46:16.869965652Z  from /gems/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
2023-09-07T09:46:16.869969222Z  from /gems/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/evented_file_update_checker.rb:6:in `<main>'
2023-09-07T09:46:16.869972442Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.869975032Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.869977692Z  from /gems/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-09-07T09:46:16.869980342Z  from /gems/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
2023-09-07T09:46:16.869983442Z  from /app/config/environments/development.rb:61:in `block in <main>'
2023-09-07T09:46:16.869986092Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/railtie.rb:257:in `instance_eval'
2023-09-07T09:46:16.869988742Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/railtie.rb:257:in `configure'
2023-09-07T09:46:16.869992042Z  from /app/config/environments/development.rb:1:in `<main>'
2023-09-07T09:46:16.869995052Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.869997822Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.870000442Z  from /gems/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-09-07T09:46:16.870003013Z  from /gems/ruby/3.2.0/gems/zeitwerk-2.6.9/lib/zeitwerk/kernel.rb:38:in `require'
2023-09-07T09:46:16.870006073Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:562:in `block (2 levels) in <class:Engine>'
2023-09-07T09:46:16.870008623Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:561:in `each'
2023-09-07T09:46:16.870019853Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:561:in `block in <class:Engine>'
2023-09-07T09:46:16.870022743Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `instance_exec'
2023-09-07T09:46:16.870025513Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:32:in `run'
2023-09-07T09:46:16.870028413Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-09-07T09:46:16.870030933Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
2023-09-07T09:46:16.870033543Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-09-07T09:46:16.870036273Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
2023-09-07T09:46:16.870038943Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-09-07T09:46:16.870041833Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
2023-09-07T09:46:16.870044733Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:50:in `each'
2023-09-07T09:46:16.870047363Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:50:in `tsort_each_child'
2023-09-07T09:46:16.870049973Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
2023-09-07T09:46:16.870055893Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
2023-09-07T09:46:16.870059363Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-09-07T09:46:16.870062073Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
2023-09-07T09:46:16.870065303Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
2023-09-07T09:46:16.870068313Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
2023-09-07T09:46:16.870071943Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
2023-09-07T09:46:16.870075114Z  from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
2023-09-07T09:46:16.870078444Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/initializable.rb:60:in `run_initializers'
2023-09-07T09:46:16.870081194Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/application.rb:372:in `initialize!'
2023-09-07T09:46:16.870084524Z  from /app/config/environment.rb:5:in `<main>'
2023-09-07T09:46:16.870087244Z  from config.ru:3:in `require_relative'
2023-09-07T09:46:16.870089864Z  from config.ru:3:in `block in <main>'
2023-09-07T09:46:16.870092944Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
2023-09-07T09:46:16.870095784Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
2023-09-07T09:46:16.870098634Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
2023-09-07T09:46:16.870101544Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
2023-09-07T09:46:16.870109494Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2023-09-07T09:46:16.870112694Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
2023-09-07T09:46:16.870115354Z  from /gems/ruby/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
2023-09-07T09:46:16.870118224Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
2023-09-07T09:46:16.870121474Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:36:in `start'
2023-09-07T09:46:16.870124174Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
2023-09-07T09:46:16.870131614Z  from <internal:kernel>:90:in `tap'
2023-09-07T09:46:16.870134534Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands/server/server_command.rb:134:in `perform'
2023-09-07T09:46:16.870137334Z  from /gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
2023-09-07T09:46:16.870140094Z  from /gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
2023-09-07T09:46:16.870142994Z  from /gems/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
2023-09-07T09:46:16.870145805Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/command/base.rb:87:in `perform'
2023-09-07T09:46:16.870148515Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/command.rb:48:in `invoke'
2023-09-07T09:46:16.870151425Z  from /gems/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/commands.rb:18:in `<main>'
2023-09-07T09:46:16.870154165Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.870156915Z  from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-09-07T09:46:16.870159605Z  from /gems/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-09-07T09:46:16.870162885Z  from bin/rails:4:in `<main>'

**Comment by sojan-official** [comment]
@meMaipal Could you give details about why you want to run helm with development mode? we recommend running it directly in your OS or  using docker-compose for development purposes 

https://www.chatwoot.com/docs/contributing-guide/environment-setup/mac-os

**Comment by maipal-oscoy** [comment]
I am running low spec host machine so i have to run it on cloud vm / kßs dev cluster. 
To do so even i tried to clone this repo and followed instructions from your docs on ubuntu VM but this one fails too (with some post install required node js 20.x version error) even i tried to swich node version to 20.x but still it fails. Some times permission errors to access /usr/share/rvm/....  and even docs doesn't mention that we need to use rvmsudo to install ruby. I don't know too much about ruby. 

Then i tried to use docker installation over aws ec2 (amazon linux 2023). But this one fails with building docker images and it says i am not authorized to pull image (i don't recall which images it was). 

Everything is failing but the simplest and easy setup will be using helm chart. To run it in dev mode. 

Even on running helm chart with production env give error code 429 (retry later) on calling /widget api by chatwoot web SDK with creds after using 4/5 different account. (When i see logs in pod it says request blocked) 

On frontend i am using next js and it's very hard to control popup rendering & by using your official guide on nextjs it is fetching a new script whenever i try to control mounting of chat bubble. Because detecting changes in window object can't be done in nextjs or reactjs. It will be better to have an react widget or if maybe just a javascript apis SDK to create clients & conversion & messages.

Thank you. But please make things developer friendly
