### ISSUE TITLE
visit help center portal error undefined method `locale' for nil:NilClass

### ISSUE THREAD

**Issue by adinovic** [chatwoot/chatwoot#8124]
### Describe the bug

i run chatwoot v2.18.0 Build e204fe1c1f5cb57499459f22d7a70885a7db4b3f using docker.
i have deployed chatwoot with 2 subdomain in 1 server
1. example.com : for the main chatwoot page
2. docs.example.com : for help center/knowledge base

example.com are working perfectly, and then i create help center in docs.example.com, i already setup the nginx vhost configuration. then i create some article to publish.
the homepage of docs.example.com is work, displaying several article that i've created. however, everytime i click the article link in docs.example.com, or preview the page in administrator user, it will show 'We're sorry, but something went wrong.'

docker-compose logs show these error when viewing the page

```
rails_1     | I, [2023-10-17T11:07:00.026510 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2] Started GET "/hc/techsupport/articles/1697537725-te
sting" for 167.205.0.228 at 2023-10-17 11:07:00 +0000                                                                                                 
rails_1     | I, [2023-10-17T11:07:00.030036 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2] Processing by Public::Api::V1::Portals::ArticlesCon
troller#show as HTML                                                                                                                                  
rails_1     | I, [2023-10-17T11:07:00.030148 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2]   Parameters: {"slug"=>"techsupport", "article_slug
"=>"1697537725-testing"}                                                                                                                              
rails_1     | I, [2023-10-17T11:07:00.043313 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2]   Rendered public/api/v1/portals/articles/show.html
.erb within layouts/portal (Duration: 0.7ms | Allocations: 161)                                                                                       
rails_1     | I, [2023-10-17T11:07:00.043526 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2]   Rendered layout layouts/portal.html.erb (Duration
: 1.0ms | Allocations: 190)                                                                                                                           
rails_1     | I, [2023-10-17T11:07:00.043943 #1]  INFO -- : [72947f28-f764-48df-9d06-1cf302ae0de2] Completed 500 Internal Server Error in 14ms (Active
Record: 4.5ms | Allocations: 1798)                                                                                                                    
rails_1     | F, [2023-10-17T11:07:00.045391 #1] FATAL -- : [72947f28-f764-48df-9d06-1cf302ae0de2]                                                    
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2] ActionView::Template::Error (undefined method `locale' for nil:NilClass):                        
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     17:     <div>                                                                                
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     18:       <a                                                                                 
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     19:         class="text-slate-700 hover:underline leading-8 text-sm font-semibold"           
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     20:         href="/hc/<%= @portal.slug %>/<%= @article.category.locale %>"                   
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     21:       >                                                                                  
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     22:         Home                                                                             
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]     23:       </a>                                                                               
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2]                                                                                                  
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2] app/views/public/api/v1/portals/articles/show.html.erb:20                                        
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2] app/controllers/public/api/v1/portals/base_controller.rb:35:in `switch_locale_with_article'      
rails_1     | [72947f28-f764-48df-9d06-1cf302ae0de2] app/controllers/public/api/v1/portals/base_controller.rb:8:in `set_locale'                
```

### To Reproduce

1. run chatwoot user docker (docker-compose) image chatwoot/chatwoot:latest
2. create help center portal, choose custom domain, different than the main chatwoot domain
3. create some article
4. choose preview the article > it will ommit above error, or
5. from the help center page, click one of article link, it will ommit above error.

### Expected behavior

i can read the article from the help center portal subdomain or from the preview button

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

CentOS 7

### Browser and version

firefox 118.0.2 (64-bit)

### Docker (if applicable)

docker version
```
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:44:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:43:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

 docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 20
  Running: 4
  Paused: 0
  Stopped: 16
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
```

docker-compose version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
````

**Comment by pranavrajs** [comment]
Closing this here as this issue is solved in the latest version. https://github.com/chatwoot/chatwoot/pull/7504

**Comment by adinovic** [comment]
i forgot to update the information, i've tried to upgrade to latest version, it still error, however it produce another error

```
rails_1     | I, [2023-10-17T11:59:29.858868 #1]  INFO -- : [d389d8f4-49d9-4a61-bda3-1f4d46f59c24] Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.0ms | Allocations: 1134)
rails_1     | F, [2023-10-17T11:59:29.859967 #1] FATAL -- : [d389d8f4-49d9-4a61-bda3-1f4d46f59c24]   
rails_1     | [d389d8f4-49d9-4a61-bda3-1f4d46f59c24] I18n::InvalidLocale ("id_ID" is not a valid locale):
rails_1     | [d389d8f4-49d9-4a61-bda3-1f4d46f59c24]   
rails_1     | [d389d8f4-49d9-4a61-bda3-1f4d46f59c24] app/controllers/public/api/v1/portals/base_controller.rb:41:in `switch_locale_with_article'
rails_1     | [d389d8f4-49d9-4a61-bda3-1f4d46f59c24] app/controllers/public/api/v1/portals/base_controller.rb:14:in `set_locale'
rails_1     | I, [2023-10-17T11:59:29.860281 #1]  INFO -- : source=rack-timeout id=d389d8f4-49d9-4a61-bda3-1f4d46f59c24 timeout=15000ms service=12ms state=completed
rails_1     | I, [2023-10-17T11:59:29.991769 #1]  INFO -- : RoomChannel#update_presence
rails_1     | I, [2023-10-17T11:59:30.157358 #1]  INFO -- : RoomChannel#update_presence
rails_1     | I, [2023-10-17T11:59:30.158052 #1]  INFO -- : RoomChannel#update_presence
rails_1     | I, [2023-10-17T11:59:30.194150 #1]  INFO -- : source=rack-timeout id=3be1a51d-9724-457c-8dcb-38326f4aa08e timeout=15000ms state=ready

```
`Apparently it was due to the saved articles are using locale id_ID, instead of locale ID, hence chatwoot doesn't recognize the id_ID locale. since when i create a new portal based on Bahasa Indonesia, the locale is ID, not id_ID. i don't know why the previous chatwoot use those locale. So, i managed to solve it by copied all the articles from id_ID to the new portal.
