### ISSUE TITLE
ActiveStorage::FileNotFoundError Bucket Google Cloud

### ISSUE THREAD

**Issue by jtayrone** [chatwoot/chatwoot#8164]
### Describe the bug

When sending and receiving media files this error is generated, in some cases the media arrives as a file on the recipient's WhatsApp.

Logs error

```bash
ct 22 10:20:20 app-dispzap chatwoot-web.1[3395321]: I, [2023-10-22T10:20:20.833949 #3395321]  INFO -- : RoomChannel#update_presence
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: I, [2023-10-22T10:20:21.259753 #3395321]  INFO -- : [78f2fbde-c812-43c5-b2f8-e2500ddc8568] [36m  GCS Storage (1325.8ms) [0m[34mDownloaded file from key: az6yw1gyunvb4uxfpumuxib65iry[0m
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: I, [2023-10-22T10:20:21.260333 #3395321]  INFO -- : [78f2fbde-c812-43c5-b2f8-e2500ddc8568] Completed 500 Internal Server Error in 1331ms (ActiveRecord: 0.7ms | Allocations: 41319)
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: F, [2023-10-22T10:20:21.262028 #3395321] FATAL -- : [78f2fbde-c812-43c5-b2f8-e2500ddc8568]
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568]
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/service/gcs_service.rb:181:in `stream'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/service/gcs_service.rb:35:in `block in download'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `block in instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/service.rb:163:in `instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/service/gcs_service.rb:34:in `download'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/downloader.rb:32:in `download'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/downloader.rb:13:in `block in open'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/downloader.rb:24:in `open_tempfile'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/downloader.rb:12:in `open'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) lib/active_storage/service.rb:90:in `open'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) app/models/active_storage/blob.rb:301:in `open'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) app/models/active_storage/variant_with_record.rb:19:in `process'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) app/models/active_storage/variant_with_record.rb:14:in `processed'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activestorage (7.0.8) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:400:in `block in make_lambda'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:200:in `block in halting'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:595:in `block in invoke_before'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:595:in `each'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:595:in `invoke_before'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] audited (5.4.0) lib/audited/sweeper.rb:16:in `around'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] audited (5.4.0) lib/audited/sweeper.rb:16:in `around'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actiontext (7.0.8) lib/action_text/rendering.rb:20:in `with_renderer'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actiontext (7.0.8) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `instance_exec'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-rails (5.12.0) lib/sentry/rails/controller_transaction.rb:28:in `block in sentry_around_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/hub.rb:102:in `with_child_span'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry-ruby.rb:476:in `with_child_span'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-rails (5.12.0) lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:138:in `run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/abstract_controller/callbacks.rb:233:in `process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal/rescue.rb:23:in `process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `block in instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `instrument'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activerecord (7.0.8) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/abstract_controller/base.rb:151:in `process'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionview (7.0.8) lib/action_view/rendering.rb:39:in `process'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal.rb:188:in `dispatch'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_controller/metal.rb:251:in `dispatch'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:32:in `serve'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:50:in `block in serve'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:32:in `each'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:32:in `serve'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:852:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] warden (1.2.9) lib/warden/manager.rb:34:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/etag.rb:27:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/head.rb:12:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/cookies.rb:704:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/callbacks.rb:99:in `run_callbacks'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-rails (5.12.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/hub.rb:251:in `with_session_tracking'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry-ruby.rb:387:in `with_session_tracking'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/hub.rb:59:in `with_scope'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry-ruby.rb:367:in `with_scope'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:18:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] railties (7.0.8) lib/rails/rack/logger.rb:40:in `call_app'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] railties (7.0.8) lib/rails/rack/logger.rb:25:in `block in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `block in tagged'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/tagged_logging.rb:37:in `tagged'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `tagged'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] railties (7.0.8) lib/rails/rack/logger.rb:25:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/request_id.rb:26:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/method_override.rb:24:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/runtime.rb:22:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/static.rb:23:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] actionpack (7.0.8) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] railties (7.0.8) lib/rails/engine.rb:530:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/configuration.rb:270:in `call'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/request.rb:100:in `block in handle_request'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/thread_pool.rb:344:in `with_force_shutdown'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/request.rb:99:in `handle_request'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/server.rb:443:in `process_client'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/server.rb:245:in `block in run'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: [78f2fbde-c812-43c5-b2f8-e2500ddc8568] puma (6.3.1) lib/puma/thread_pool.rb:151:in `block in spawn_thread'
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: I, [2023-10-22T10:20:21.278608 #3395321]  INFO -- sentry: [Transport] Sending envelope with items [event] 96b8b9fa8574438491dba0a7530cdb4a to Sentry
Oct 22 10:20:21 app-dispzap chatwoot-web.1[3395321]: I, [2023-10-22T10:20:21.278962 #3395321]  INFO -- : source=rack-timeout id=78f2fbde-c812-43c5-b2f8-e2500ddc8568 timeout=15000ms service=1354ms state=completed
```
### Audio sent from Chatwoot
![image](https://github.com/chatwoot/chatwoot/assets/34479816/97304060-775d-48d8-802e-7ac4f16f7cb8)

### Audio received on Whatsapp
![image](https://github.com/chatwoot/chatwoot/assets/34479816/9cc0bf89-bc11-4dd2-ad02-51dd994297d4)

### To Reproduce

1- Send any type of media
2- Have configured external Google Cloud storage
3- Monitor the logs

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Additional context

Issue report to #7229 

### .env settings

`DIRECT_UPLOADS_ENABLED=true`

### Bucket Settings 

```bash
ACTIVE_STORAGE_SERVICE=google
GCS_PROJECT=chatwoot
GCS_BUCKET=bucket
GCS_CREDENTIALS='{"type": "service_account",....'
```

### Installation information

Chatwoot version v3.2.0
Branch Develop #8147 
Node version v20.5.1

**Comment by pranavrajs** [comment]
@jtayrone The error logs seem unrelated. Can you reproduce this consistently, or does it happen randomly? I mean does it break if the audio message is long?

**Comment by jtayrone** [comment]
No! It happens randomly with some messages.
