### ISSUE TITLE
SMTP is not working

### ISSUE THREAD

**Issue by yoges24** [chatwoot/chatwoot#8226]
### Describe the bug

I setup an Azure APP and added the APP ID and Secret key to the .env file. The inbox is added. I receive mails to the chatwoot inbox channel. But my reply message is not to another end. Its failing. I am having an error like this. How to fix this? 
![278345252-24ed3f76-0a37-4944-901b-15333200282b](https://github.com/chatwoot/chatwoot/assets/148360361/15f76c5d-2c47-4821-a50e-b8f1423f5081)

### To Reproduce

Microsoft Inbox channel to configured and both send and receive should be work for the Office365 account.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Linux

### Browser and version

22.04

**Comment by pranavrajs** [comment]
@yoges24 There is no information to debug this error. Can you please add more logs or reproducible steps?

**Comment by yoges24** [comment]
Log


Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: I, [2023-10-27T12:40:34.537188 #150606]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0] Delivered mail conversation/23d2be61-16c8-4755-a678-69a58802dfc4/messages/140 (5077.0ms)
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: E, [2023-10-27T12:40:34.537610 #150606] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0] Error performing ActionMailer::MailDeliveryJob (Job ID: 86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0) from Sidekiq(default) in 5178.2ms: Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:229:in `rbuf_fill'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:199:in `readuntil'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:209:in `readline'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1057:in `recv_response'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1051:in `get_response'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/smtp_xoauth2_authenticator.rb:9:in `block in send_xoauth2'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1067:in `critical'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/smtp_xoauth2_authenticator.rb:8:in `send_xoauth2'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/smtp_xoauth2_authenticator.rb:25:in `auth_xoauth2'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:837:in `public_send'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:837:in `authenticate'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:670:in `do_start'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/base.rb:588:in `block in deliver_mail'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `block in instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/base.rb:586:in `deliver_mail'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/rescuable.rb:19:in `handle_exceptions'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/actionmailer-7.0.8/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/execution.rb:65:in `block in _perform_job'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/execution.rb:64:in `_perform_job'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:20:in `_perform_job'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/execution.rb:52:in `perform_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `block in perform_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:25:in `block in instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `block in instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:35:in `instrument'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `perform_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `block in perform_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/logging.rb:25:in `tag_logger'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `perform_now'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/execution.rb:30:in `block in execute'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/reloader.rb:72:in `block in wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:88:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/reloader.rb:71:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/execution.rb:28:in `execute'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activejob-7.0.8/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:210:in `execute_job'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:180:in `traverse'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/metrics/tracking.rb:26:in `track'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/metrics/tracking.rb:122:in `call'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:182:in `traverse'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/middleware/chain.rb:173:in `invoke'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/job_retry.rb:114:in `local'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/rails.rb:16:in `block in call'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/reloader.rb:72:in `block in wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.0.8/lib/active_support/reloader.rb:71:in `wrap'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/rails.rb:15:in `call'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:271:in `stats'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/job_logger.rb:13:in `call'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/job_retry.rb:81:in `global'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:128:in `block in dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/job_logger.rb:39:in `prepare'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:127:in `dispatch'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:177:in `handle_interrupt'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:177:in `block in process'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:176:in `handle_interrupt'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:176:in `process'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:82:in `process_one'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/processor.rb:72:in `run'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/component.rb:10:in `watchdog'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/component.rb:19:in `block in safe_thread'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: {"ts":"2023-10-27T07:10:34.537Z","pid":150606,"tid":"2cli","lvl":"INFO","msg":"Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job 2db39adcc049c8530db1e98a","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"2db39adcc049c8530db1e98a"}}
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: {"ts":"2023-10-27T07:10:34.538Z","pid":150606,"tid":"2cli","lvl":"INFO","msg":"fail","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"2db39adcc049c8530db1e98a","elapsed":5.181}}
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: {"ts":"2023-10-27T07:10:34.539Z","pid":150606,"tid":"2cli","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"ConversationReplyMailer\",\"email_reply\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/1\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/Message/140\"}],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2023-10-27T07:10:29Z\"}],\"jid\":\"2db39adcc049c8530db1e98a\",\"retry_for\":0,\"created_at\":1698390629.3578594,\"enqueued_at\":1698390629.357933},\"_config\":{\"labels\":\"#<Set: {}>\",\"require\":\".\",\"environment\":\"production\",\"concurrency\":10,\"timeout\":25,\"poll_interval_average\":null,\"average_scheduled_poll_interval\":5,\"on_complex_arguments\":\"raise\",\"error_handlers\":[\"#<Proc:0x00007f600bba89d0 /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/config.rb:37 (lambda)>\"],\"death_handlers\":[],\"lifecycle_events\":{\"startup\":[],\"quiet\":[],\"shutdown\":[],\"heartbeat\":[],\"beat\":[\"#<Proc:0x00007f600b5684a8 /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/metrics/tracking.rb:133>\"]},\"dead_max_jobs\":10000,\"dead_timeout_in_seconds\":15552000,\"reloader\":\"#<Sidekiq::Rails::Reloader @app=Chatwoot::Application>\",\"backtrace_cleaner\":\"#<Proc:0x00007f600ab55038 /usr/local/rvm/gems/ruby-3.2.2/gems/sidekiq-7.1.3/lib/sidekiq/rails.rb:59 (lambda)>\",\"verbose\":false,\"max_retries\":3,\"queues\":[\"critical\",\"high\",\"medium\",\"default\",\"mailers\",\"action_mailbox_routing\",\"low\",\"scheduled_jobs\",\"async_database_migration\",\"active_storage_analysis\",\"active_storage_purge\",\"action_mailbox_incineration\"],\"staging\":{\"concurrency\":10},\"config_file\":\"config/sidekiq.yml\",\"tag\":\"chatwoot\",\"identity\":\"ip-172-31-15-79:150606:dce1a85f0203\",\"cron_poll_interval\":30}}"}
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: {"ts":"2023-10-27T07:10:34.539Z","pid":150606,"tid":"2cli","lvl":"WARN","msg":"Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>"}
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: {"ts":"2023-10-27T07:10:34.540Z","pid":150606,"tid":"2cli","lvl":"WARN","msg":""}

**Comment by Placidina** [comment]
```
MAILER_SENDER_EMAIL: Example <no-reply@example.com>
SMTP_DOMAIN: example.com
SMTP_ADDRESS: email-smtp.REPLACE_FOR_YOUR_REGION.amazonaws.com
SMTP_PORT: "587"
SMTP_AUTHENTICATION: login
SMTP_USERNAME: REPLACE_FOR_YOUR_IAM_SMPT_USER_ACCESS_KEY
SMTP_PASSWORD: REPLACE_FOR_YOUR_IAM_SMPT_USER_SECRET_KEY_ID
SMTP_ENABLE_STARTTLS_AUTO: "true"
SMTP_OPENSSL_VERIFY_MODE: none
```

**Comment by juliomac** [comment]
Same problem...

**Comment by Calbo67** [comment]
I'm also getting this issue was there a fix?
