### ISSUE TITLE
Redis Sentinel Support broken in 3.2

### ISSUE THREAD

**Issue by m4ex** [chatwoot/chatwoot#8368]
### Describe the bug

Latest version(3.2) can't connect to redis using sentinel. Tested in docker setup.

sidekiq container crash with an error:
RedisClient::SentinelConfig requires either a name or an url with a host

looks like we need to add name parameter in redis config here: https://github.com/chatwoot/chatwoot/blob/develop/lib/redis/config.rb#L46

full log:
```
fatal: not a git repository (or any of the parent directories): .git
RedisClient::SentinelConfig requires either a name or an url with a host
/gems/ruby/3.2.0/gems/redis-client-0.17.0/lib/redis_client/sentinel_config.rb:37:in `initialize'
/gems/ruby/3.2.0/gems/redis-client-0.17.0/lib/redis_client.rb:148:in `new'
/gems/ruby/3.2.0/gems/redis-client-0.17.0/lib/redis_client.rb:148:in `sentinel'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/redis_client_adapter.rb:50:in `initialize'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/redis_connection.rb:22:in `new'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/redis_connection.rb:22:in `create'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/config.rb:139:in `new_redis_pool'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/config.rb:133:in `local_redis_pool'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/config.rb:127:in `redis_pool'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/config.rb:160:in `redis'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq.rb:73:in `redis'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:375:in `status_from_redis'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:285:in `initialize'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:200:in `new'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:200:in `block in load_from_array'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:199:in `each'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:199:in `load_from_array'
/gems/ruby/3.2.0/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:170:in `load_from_hash'
{"ts":"2023-11-17T13:36:58.764Z","pid":1,"tid":"5a1","lvl":"INFO","msg":"Sidekiq 7.1.6 connecting to Redis with options {:size=>10, :pool_name=>\"internal\", :url=>\"redis://mymaster\", :password=>\"REDACTED\", :reconnect_attempts=>2, :timeout=>1, :sentinels=>[{:host=>\"redis-sentinel\", :port=>\"26379\", :password=>\"REDACTED\"}]}"}
/app/config/initializers/sidekiq.rb:17:in `block in <main>'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `instance_exec'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `block in make_lambda'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `catch'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `block in default_terminator'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:200:in `block in halting'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `block in invoke_before'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `each'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `invoke_before'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:106:in `run_callbacks'
/gems/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:88:in `prepare!'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
/gems/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/cli.rb:303:in `boot_application'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/lib/sidekiq/cli.rb:42:in `run'
/gems/ruby/3.2.0/gems/sidekiq-7.1.6/bin/sidekiq:31:in `<top (required)>'
/gems/ruby/3.2.0/bin/sidekiq:25:in `load'
/gems/ruby/3.2.0/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

### To Reproduce

1) Install Docker on your VM
```
# example in ubuntu
apt-get update
apt-get upgrade
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
apt install docker-compose-plugin
```
1) Copy files:

```
# Download the env file template
wget -O .env https://raw.githubusercontent.com/m4ex/chatwoot/develop/.env.sentinel.example
# Download the Docker compose template
wget -O docker-compose.yaml https://raw.githubusercontent.com/m4ex/chatwoot/develop/docker-compose.sentinel.yaml
```

2) Prepare the database by running the migrations
```
docker compose run --rm rails bundle exec rails db:chatwoot_prepare
```
3) Get the service up and running
```
docker compose up -d
```
5) Check an error in sidekiq container

### Expected behavior

app starts and works with redis sentinel without errors

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by maipal-oscoy** [comment]
facing same issue , i think it could be password issue as there are no env vriable for setting sentinel password, however i am facing this issue on k8s with chatwoot official helm chart & bitnami redis chart with sentinel enabled

**Comment by ggualerz** [comment]
Hi, i'm on k3s and sentinel seem to still not work.
Is that issue is solved ?

**Comment by iahmad-khan** [comment]
I was able to fix it, i exec into the pod and did a name lookup on the endpoints, those were failing , then i provided the right endpoints that were able to resolve by dns , worked.
 example endpoint:

````

<pod-name>.<headless-service-name>.<namespace>.svc.cluster.local

**Comment by anabeto93** [comment]
I hope this gets approved https://github.com/redis-rb/redis-client/pull/283
