### ISSUE TITLE
Underfined Method 'icon' when viewing categories.

### ISSUE THREAD

**Issue by Wamy-Dev** [chatwoot/chatwoot#8383]
### Describe the bug

I don't know why this is happening and it just started today. I can access specific articles, but when viewing a category in the help center it fails.

```
[29ff945d-5a12-4f43-83c3-27de618989bf] ActionView::Template::Error (undefined method `icon' for #<Category id: 3, account_id: 1, portal_id: 1, name: "Account", description: "xxxxxxxxxxxxx", position: nil, created_at: "2023-09-27 01:19:16.190204000 +0000", updated_at: "2023-09-27 01:19:16.190204000 +0000", locale: "en", slug: "account", parent_category_id: nil, associated_category_id: nil>):
[29ff945d-5a12-4f43-83c3-27de618989bf]     11:   </div>
[29ff945d-5a12-4f43-83c3-27de618989bf]     12:   <div class="flex justify-start flex-col items-start w-full gap-2">
[29ff945d-5a12-4f43-83c3-27de618989bf]     13:     <div class="flex flex-col gap-2">
[29ff945d-5a12-4f43-83c3-27de618989bf]     14:       <% if category.icon.present? %>
[29ff945d-5a12-4f43-83c3-27de618989bf]     15:       <span class="text-4xl"><%= category.icon %></span>
[29ff945d-5a12-4f43-83c3-27de618989bf]     16:       <% end %>
[29ff945d-5a12-4f43-83c3-27de618989bf]     17:       <h1 class="text-3xl font-semibold leading-[52.5px] text-slate-900 dark:text-white">
[29ff945d-5a12-4f43-83c3-27de618989bf]   
[29ff945d-5a12-4f43-83c3-27de618989bf] app/views/public/api/v1/portals/categories/_category-hero.html.erb:14
[29ff945d-5a12-4f43-83c3-27de618989bf] app/views/public/api/v1/portals/categories/show.html.erb:11
[29ff945d-5a12-4f43-83c3-27de618989bf] app/controllers/public/api/v1/portals/base_controller.rb:42:in `switch_locale_with_portal'
[29ff945d-5a12-4f43-83c3-27de618989bf] app/controllers/public/api/v1/portals/base_controller.rb:26:in `set_locale'
```

### To Reproduce

Simply try and access the help center categories

### Expected behavior

For the help center articles to display.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by Wamy-Dev** [comment]
Ended up having to update the database. Didn't realize my image had updated thanks to watchtower.
