### ISSUE TITLE
Telegram "Lock to single conversation" flag

### ISSUE THREAD

**Issue by h4t0n** [chatwoot/chatwoot#8426]
### Is your feature or enhancement related to a problem? Please describe.

It is useful to add the "Lock to single conversation" flag also for the telegram channel. Now the default behaviour is to have a single telegram conversation. If you resolve one, and the user send a new message, the last conversation is reopened. But in a ticketing system, the user may have different conversations with the support team, so Chatwoot should allow to have multiple conversations each time the user has a problem.

### Describe the solution you'd like

Just have for Telegram what we have for the other channels like Whatsapp, the "Lock to single conversation" feature.

**Comment by pranavrajs** [comment]
@h4t0n This might be a miss from our end. We will add the support for this.

**Comment by h4t0n** [comment]
Thank you @pranavrajs do you have a plan or a roadmap for the feature? Just to understand when I could use it in my self hosted environments.

**Comment by hiagodotme** [comment]
Hi, @h4t0n and @pranavrajs I'm not a Ruby programmer. I've never done a hello world.

But I tried to analyze the source code and it seems like a relatively simple task. I made the local change and am testing it.

If it works, I'll make a pull request.

**Comment by hiagodotme** [comment]
Guys, I couldn't run chatwoot locally. I use Windows and docker containers don't seem to work very well. I followed a guide here but I couldn't run it.

The solution to this problem is simple, I'll leave it below:

> *File:* app\javascript\dashboard\routes\dashboard\settings\inbox\Settings.vue **from the line** 175

```javascript
    canLocktoSingleConversation() {
      return (
        this.isASmsInbox || this.isAWhatsAppChannel || this.isAFacebookInbox || this.isATelegramChannel
      );
    },
```

>*File:* app\services\telegram\incoming_message_service.rb **from the line** 65

```rb
  def set_conversation
    @conversation = if @inbox.lock_to_single_conversation
                      @contact_inbox.conversations.last
                    else
                      @contact_inbox.conversations
                                    .where.not(status: :resolved).last
                    end
    return if @conversation

    @conversation = ::Conversation.create!(conversation_params)
  end
```

Just these two changes should make Telegram behave as expected. I couldn't test this solution because I couldn't run the docker container on windows.

**Comment by sojan-official** [comment]
@hiagodotme Would you be interested in raising a PR for this?  You could try it in codespaces may be ?

**Comment by hiagodotme** [comment]
@sojan-official Try here... More in the creation of codespaces or the error below is presented:
```
failed to solve: process "/bin/sh -c yarn && gem install bundler && bundle install" did not complete successfully: exit code: 1
[539984 ms] Stop: Run: docker-compose --project-name chatwoot_devcontainer -f /var/lib/docker/codespacemount/workspace/chatwoot/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1724359931643.yml build
Error: Command failed: docker-compose --project-name chatwoot_devcontainer -f /var/lib/docker/codespacemount/workspace/chatwoot/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1724359931643.yml build
    at Rw (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:429:525)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:429:2496)
    at async x$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:409:3165)
    at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3833)
    at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
    at async xeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11265)
    at async UeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11006)
devcontainer process exited with exit code 1
{"outcome":"error","message":"Command failed: docker-compose --project-name chatwoot_devcontainer -f /var/lib/docker/codespacemount/workspace/chatwoot/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1724359931643.yml build","description":"An error occurred building the Docker Compose images."}
Failed to create container.
Error: Command failed: docker-compose --project-name chatwoot_devcontainer -f /var/lib/docker/codespacemount/workspace/chatwoot/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1724359931643.yml build
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```
I made the implementation here, in this branch if someone can validate if it works I will make the PR.

https://github.com/hiagodotme/chatwoot/tree/fix/cw-2820

**Comment by h4t0n** [comment]
@sojan-official are you going to add this feature for the next v4 release?

**Comment by macolym** [comment]
Hi my friend @h4t0n ,

The “Lock to single conversation” option for the Telegram channel has already been implemented as part of [CW-2661 – Enhancement for Resolved Conversations in Telegram Channel #8046](https://github.com/chatwoot/chatwoot/issues/8046)
 and merged in [PR #12367](https://github.com/chatwoot/chatwoot/pull/12367)
 
The code is merged and the issue is technically resolved, but we’re waiting for it to be included in an official release.

@sojan-official @pranavrajs @muhsin-k
Could you share if this fix is planned for the next Chatwoot release or provide any timeline for when it will be available?

**Comment by muhsin-k** [comment]
> Could you share if this fix is planned for the next Chatwoot release or provide any timeline for when it will be available?

@macolym You can expect this fix in release 4.7 (mid-October).

**Comment by muhsin-k** [comment]
Fixed via https://github.com/chatwoot/chatwoot/pull/12367
