### ISSUE TITLE
`cwctl --upgrade` has to be ran multiple times before actually starting well

### ISSUE THREAD

**Issue by pierrecorsini** [chatwoot/chatwoot#8485]
### Describe the bug

The update command gives unexpected output: first "nothing", then "an error", and the third time the expected result.

Does not seems to be blocking as the last call is as expected; but the first two fails might have caused or be caused by a damaged installation.

### To Reproduce

1. cwctl --upgrade

```
root@S05-chatwoot:/home/chatwoot# cwctl --upgrade
root@S05-chatwoot:/home/chatwoot# cwctl --upgrade
Checking for cwctl updates...
Your cwctl is up to date
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@S05-chatwoot:/home/chatwoot# cwctl --upgrade
Checking for cwctl updates...
Your cwctl is up to date
Upgrading Chatwoot to v3.3.1
Checking Redis availability...
Checking Redis version...
Redis is already version 7.2.2 (>= 7). Skipping Redis upgrade.
Upgrading nodejs version to v20.x
[...]
```

### Expected behavior

The 3rd cwctl call is the expected behavior.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu 20 04

**Comment by stonecharioteer** [comment]
This issue is being closed due to lack of activity for over a year. [For more details, visit this discussion.](https://github.com/orgs/chatwoot/discussions/12810)
