### ISSUE TITLE
V.1.4.2 fails the web widget fetch (500 error code)

### ISSUE THREAD

**Issue by whiteyhat** [chatwoot/chatwoot#868]
**Describe the bug**
When updating to the new version it fails to fetch the web inbox from the client.

**Expected behaviour**
It should fetch the web inox widget without any errors.

**Screenshots**
![Captura de pantalla 2020-05-16 a las 15 25 19](https://user-images.githubusercontent.com/31220861/82120899-7e176e80-9789-11ea-9425-3ec43e232ef0.png)

**Comment by whiteyhat** [comment]
LOGS
```
l1ju7ci => Booting Puma
l1ju7ci => Rails 6.0.2.2 application starting in production
l1ju7ci => Run `rails server --help` for more startup options
l1ju7ci /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
l1ju7ci /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
l1ju7ci /gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
l1ju7ci /gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
l1ju7ci /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
l1ju7ci /gems/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
l1ju7ci Error: Column "push_flags" doesn't exist on table "notification_settings". Did you forget to run migrations?
l1ju7ci FlagShihTzu says: Flag column push_flags appears to be missing!
l1ju7ci To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/notification_setting.rb:33:in `<class:NotificationSetting>'
l1ju7ci Error: Column "feature_flags" doesn't exist on table "accounts". Did you forget to run migrations?
l1ju7ci FlagShihTzu says: Flag column feature_flags appears to be missing!
l1ju7ci To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/concerns/features.rb:16:in `block in <module:Features>'
l1ju7ci Error: Column "settings_flags" doesn't exist on table "accounts". Did you forget to run migrations?
l1ju7ci FlagShihTzu says: Flag column settings_flags appears to be missing!
l1ju7ci To turn off this warning set check_for_column: false in has_flags definition here: /app/app/models/account.rb:50:in `<class:Account>'
l1ju7ci /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/store.rb:106: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
l1ju7ci /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/store.rb:109: warning: The called method `store_accessor' is defined here
l1ju7ci Puma starting in single mode...
l1ju7ci * Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
l1ju7ci * Min threads: 5, max threads: 5
l1ju7ci * Environment: production
l1ju7ci * Listening on tcp://0.0.0.0:3000
```

**Comment by whiteyhat** [comment]
It seems like the critical changes in the DB have taken place...

**Comment by whiteyhat** [comment]
## FIXED
`bundle exec rails migrate`

**Comment by agustinrudas** [comment]
This still hapenning on 2.1.1 . **Using production yaml.**
I made the test alot of times. The same error is showing up
![image](https://user-images.githubusercontent.com/78917059/151202144-7f2a21cc-caa0-472b-a019-255a2b7f8810.png)
