### ISSUE TITLE
Websocket failed in chrome/firefox with apache2 configuration

### ISSUE THREAD

**Issue by L1so** [chatwoot/chatwoot#8715]
### Describe the bug

Hello, I just recently installed this utility, it is working fine as my Whatsapp API solution, but to receive new message-- I must refresh it manually, upon seeing the issues here turns out this has to do with websocket configuration. Apparently mine was not configured properly, resulting in following error (taken from browser console):

Chrome.
```
logger-1.min.js:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
build.umd.js:4240 LogRocket: script could not load. Check that you have a valid network connection.
e.onerror @ build.umd.js:4240
Show 1 more frame
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
Show 1 more frame
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
action_cable.js:241 WebSocket connection to 'wss://chat.company.com/cable' failed: 
e.open @ action_cable.js:241
e.reopen @ action_cable.js:276
e.reconnectIfStale @ action_cable.js:154
(anonymous) @ action_cable.js:130
Show 4 more frames
Show less
```

Firefox.
```
Initializing bitwardenContentMessageHandler bootstrap-content-message-handler.js:229:13
Attaching message event listener. bootstrap-content-message-handler.js:217:17
Handling window message bootstrap-content-message-handler.js:167:21
Bad source or badly formatted message, skipping. bootstrap-content-message-handler.js:171:25
Handling window message bootstrap-content-message-handler.js:167:21
Bad source or badly formatted message, skipping. bootstrap-content-message-handler.js:171:25
Handling window message bootstrap-content-message-handler.js:167:21
Bad source or badly formatted message, skipping. bootstrap-content-message-handler.js:171:25
Some cookies are misusing the recommended “SameSite“ attribute 2
Loading failed for the <script> with source “https://cdn.lr-in-prod.com/logger-1.min.js”. dashboard:1:1
LogRocket: script could not load. Check that you have a valid network connection. build.umd.js:4240:22
Firefox can’t establish a connection to the server at wss://chat.company.com/cable. action_cable.js:241:25
GET
wss://chat.company.com/cable

Firefox can’t establish a connection to the server at wss://chat.company.com/cable. action_cable.js:241:25
GET
wss://chat.company.com/cable

Firefox can’t establish a connection to the server at wss://chat.company.com/cable. action_cable.js:241:25
```

I also get endlessly `WebSocket connection to 'wss://chat.company.com/cable' failed:` error from console in chrome. Can anyone tell me whats wrong with my configuration ?

### Apache2 config

```
<VirtualHost *:80>
    ServerName chat.company.com
    #Redirect permanent / https://chat.company.com/
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
    ProxyPass /cable http://127.0.0.1:3000/cable upgrade=websocket
</VirtualHost>

<VirtualHost *:443>
    SSLEngine On
    SSLProxyEngine on
    SSLProxyVerify none 
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ServerName chat.company.com
    
    ProxyPass /cable http://127.0.0.1:3000/cable upgrade=websocket
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
    <Location /cable>
       ProxyPass wss://127.0.0.1:3000/cable upgrade=websocket
    </Location>
    
    ProxyPreserveHost On
	RequestHeader set "Upgrade" "%{HTTP:Upgrade}s"
	RequestHeader set "Connection" "%{HTTP:Connection}s"
	RequestHeader set "Host" "%{HTTP:Host}s"
	RequestHeader set "X-Forwarded-Proto" "%{HTTP:X-Forwarded-Proto}s"
	RequestHeader set "X-Forwarded-Ssl" "on"

    RequestHeader set "X-Real-IP" "%{REMOTE_ADDR}s"
    RequestHeader set "X-Forwarded-For" "%{HTTP:X-Forwarded-For}s"
  
    SetEnvIfNoCase ^Accept.Encoding$ ^(.*)$ fix_accept_encoding=$1
    RequestHeader set Accept-Encoding %{fix_accept_encoding}e env=fix_accept_encoding
    SetEnv proxy-nokeepalive 1

    LimitRequestBody 0
    Timeout 36000

    SSLCertificateFile /opt/acme-cert/japati.net/cert.pem
    SSLCertificateKeyFile /opt/acme-cert/japati.net/site.key
    SSLCertificateChainFile /opt/acme-cert/japati.net/fullchain.cer
</VirtualHost>
```

### Additional environment variable
```
FRONTEND_URL=https://chat.company.com
FORCE_SSL=true
```

### To Reproduce

1. Login to chatwoot
2. Wait for new message to arrive
3. No new message are coming
4. Refresh to see new message loaded

### Expected behavior

Message are loaded realtime without the need for refreshing the web page

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu Server 20.04.6 LTS

### Browser and version

Chromium Version 120.0.6099.199 (Official Build) built on Debian 12.4, running on Debian 12.4 (64-bit)

### Docker (if applicable)

- `docker version`
```
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:12 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:12 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- `docker info`
```
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-169-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 11.68GiB
 Name: vps3-japati
 ID: 9222fe6b-f97d-4fcd-b8cc-299eeb455396
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- `docker-compose version`
```
Docker Compose version v2.22.0
```

### Additional context

My server only have apache2 at the moment and unfortunately it is currently not possible for me to install any other webserver. I hope anyone have a solution for this problem.

**Comment by si458** [comment]
i just discovered a similar bug but using traefik
you need to set `FORCE_SSL=false` to get the `/cable` to work correctly
thankfully i use traefik to force http to https
https://github.com/orgs/chatwoot/discussions/8528

**Comment by help-corretora** [comment]
Me too. 

Change the configuration to FORCE_SSL=false and test it.

**Comment by i9team** [comment]
@si458 Obrigado irmão, era isso mesmo!
