### ISSUE TITLE
Access to this endpoint is not authorized for bots

### ISSUE THREAD

**Issue by ozzyoss77** [chatwoot/chatwoot#8882]
### Describe the bug

I have a WhatsApp bot that uses the API endpoints. My instance is self-hosted on AWS.

Inbox created via API. Integration webhook configured with parameters: message created and contact updated.
Error prompt:
`
2024-02-08T00:41:10.950681026Z Error details: { error: 'Access to this endpoint is not authorized for bots' }
2024-02-08T00:41:11.047682332Z Error details: { error: 'Access to this endpoint is not authorized for bots' }
2024-02-08T00:41:11.047883147Z Error processing outgoing queue message: Error: Request failed with status code 401
2024-02-08T00:41:11.047914173Z at /app/Services/chatwoot.js:54:18
`
Chatwoot version: v3.5.1
This error does not exist in version v3.4.0.

### To Reproduce

Self hosted on AWS EC2 instance on t3.medium

### Expected behavior

No limitations on consuming API

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

Edge

### Additional context

Chatwoot version: v3.5.1
This error does not exist in version v3.4.0.
`
2024-02-08T00:41:10.950681026Z Error details: { error: 'Access to this endpoint is not authorized for bots' }
2024-02-08T00:41:11.047682332Z Error details: { error: 'Access to this endpoint is not authorized for bots' }
2024-02-08T00:41:11.047883147Z Error processing outgoing queue message: Error: Request failed with status code 401
2024-02-08T00:41:11.047914173Z at /app/Services/chatwoot.js:54:18
`

**Comment by sojan-official** [comment]
if its a super admin token

Please upgrade to 3.5.2
ref: https://github.com/chatwoot/chatwoot/issues/8719 



----------
If you are using a platform token to interact with the endpoint, This was an unintended behaviour in earlier versions and won't we supported going forward
