### ISSUE TITLE
bug: SMS Campaigns stop if one of the numbers error out

### ISSUE THREAD

**Issue by framatt** [chatwoot/chatwoot#9000]
### Describe the bug

When running a once off campaign and Twilio responds with  "The 'To' number XXXXXXXXXXX is not a valid phone number." it stops processing the rest of the queue

### To Reproduce

Create once off campaign, include invalid numbers, run campaign

### Expected behavior

Queue should continue on error

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu

### Additional context

 E, [2024-02-23T10:01:08.060544 #32360] ERROR -- : [ActiveJob] [Campaigns::TriggerOneoffCampaignJob] [09638651-ac66-4c70-a001-a430c5071cf9] Error performing Campaigns::TriggerOneoffCampaignJob (Job ID: 09638651-ac66-4c70-a001-a430c5071cf9) from Sidekiq(low) in 58360.56ms: Twilio::REST::RestError ([HTTP 400] 21211 : Unable to create record
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: The 'To' number XXXXXXXXXXXX is not a valid phone number.
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: https://www.twilio.com/docs/errors/21211
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: ):
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /usr/local/rvm/gems/ruby-3.2.2/gems/twilio-ruby-5.77.0/lib/twilio-ruby/framework/rest/version.rb:146:in `create'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /usr/local/rvm/gems/ruby-3.2.2/gems/twilio-ruby-5.77.0/lib/twilio-ruby/rest/api/v2010/account/message.rb:156:in `create'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /home/chatwoot/chatwoot/app/models/channel/twilio_sms.rb:52:in `send_message'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /home/chatwoot/chatwoot/app/services/twilio/oneoff_sms_campaign_service.rb:25:in `block in process_audience'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /home/chatwoot/chatwoot/app/services/twilio/oneoff_sms_campaign_service.rb:22:in `process_audience'
Feb 23 10:01:08 chatwoot chatwoot-worker.1[32360]: /home/chatwoot/chatwoot/app/services/twilio/oneoff_sms_campaign_service.rb:13:in `perform'

**Comment by pranavrajs** [comment]
@framatt We will investigate further. @sojan Can you please look into this?
