### ISSUE TITLE
Got "NoMethodError undefined method feature_response_bot" after update docker compose.

### ISSUE THREAD

**Issue by AnsonFreeman** [chatwoot/chatwoot#9157]
### Describe the bug

After update docker compose, when starting conversation, got: {status: 500, error: "Internal Server Error"}

[14d4cb89-98a6-4f10-86cf-7928b51628d1] NoMethodError (undefined method `feature_response_bot?' for #<Account id: 3, name: "Joyce", created_at: "2023-06-21 11:37:56.065561000 +0000", updated_at: "2024-03-14 09:26:39.756395000 +0000", locale: "en", domain: nil, support_email: "Contact <t@t.io>", feature_flags: 268435455, auto_resolve_duration: nil, limits: {"agents"=>"", "inboxes"=>""}, custom_attributes: {}, status: "active">):
[14d4cb89-98a6-4f10-86cf-7928b51628d1]
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/models/concerns/featurable.rb:45:in `feature_enabled?'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/models/conversation.rb:238:in `determine_conversation_status'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/api/v1/widget/base_controller.rb:24:in `create_conversation'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/api/v1/widget/conversations_controller.rb:12:in `block in create'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/api/v1/widget/conversations_controller.rb:10:in `create'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[14d4cb89-98a6-4f10-86cf-7928b51628d1] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

### To Reproduce

1、docker compose pull
2、docker compose up -d
3、docker compose run --rm rails bundle exec rails db:chatwoot_prepare

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Docker (if applicable)

$ docker version

Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker-compose version

docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

**Comment by AnsonFreeman** [comment]
Due to low version config files

**Comment by shivamkb17** [comment]
disable response_bot feature from super_admin panel. 
response_bot feature is for enterprise only.
