### ISSUE TITLE
Help Center: I18n::InvalidLocale ("nb" is not a valid locale)

### ISSUE THREAD

**Issue by KonstantinReido** [chatwoot/chatwoot#9271]
### Describe the bug

```
I18n::InvalidLocale ("nb" is not a valid locale):
app/controllers/public/api/v1/portals/base_controller.rb:53:in `switch_locale_with_article'
app/controllers/public/api/v1/portals/base_controller.rb:24:in `set_locale'
```

On the UI (`Help Center > Settings > Locales > Add locale`), you provide the option to select several dialects of the Norwegian language, but your code doesn't recognize them.

<img width="397" alt="Screenshot 2024-04-22 at 13 08 03" src="https://github.com/chatwoot/chatwoot/assets/172571/9e2ed53e-5520-4c35-ba0d-a2b4d6773353">

You set available locales [here](https://github.com/chatwoot/chatwoot/blob/develop/config/initializers/languages.rb#L34C3-L34C92). And as result 
 `I18n.available_locales` returns the next list: `[:en, :ar, :nl, :fr, :de, :it, :ja, :ko, :pt, :ru, :es, :ml, :ca, :el, :pt_BR, :ro, :ta, :fa, :zh_TW, :vi, :da, :tr, :cs, :fi, :id, :sv, :hu, :no, :zh_CN, :pl, :sk, :uk, :th, :lv, :is, :he, :lt, :sr]`, so Rails do not accept codes from the screenshot.

### To Reproduce

1) Set the locale for a portal to `nb`
2) Create an article
3) Try to preview it

### Environment

Heroku

### Cloud Provider

None

### Platform

Browser

**Comment by nawafinity** [comment]
I experienced this issue with the Arabic (Saudi) locale as well. I'll work on fixing it and submit a pull request.

**Comment by sojan-official** [comment]
should be fixed by https://github.com/chatwoot/chatwoot/pull/11021
