### ISSUE TITLE
Error Conversation Created but has no messages

### ISSUE THREAD

**Issue by PP-Contrib** [chatwoot/chatwoot#9506]
### Describe the bug

Sometimes (almost 2/5) when the first message of a new contact is received, chatwoot creates the contact, creates a conversation but can't create the message.

### To Reproduce

1. Docker Installation
2.
3. Send a new mensage as a new contact
4. [Webhooks::WhatsappEventsJob] [6aae8580-3e41-42d4-aab6-f5c065c17efc]   Conversation Load (2.4ms)  SELECT "conversations".* FROM "conversations" WHERE "conversations"."id" = $1 LIMIT $2  [["id", 977], ["LIMIT", 1]]
E, [2024-05-20T15:47:47.262737 #1] ERROR -- : [ActiveJob] [Webhooks::WhatsappEventsJob] [6aae8580-3e41-42d4-aab6-f5c065c17efc] Error performing Webhooks::WhatsappEventsJob (Job ID: 6aae8580-3e41-42d4-aab6-f5c065c17efc) from Sidekiq(low) in 111.92ms: ActiveRecord::RecordNotFound (Couldn't find Conversation with 'id'=977):
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb:381:in `raise_record_not_found_exception!'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb:475:in `find_one'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb:457:in `find_with_ids'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation/finder_methods.rb:69:in `find'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:1024:in `_find_record'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:951:in `block in reload'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation.rb:881:in `_scoping'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/relation.rb:428:in `scoping'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/scoping/default.rb:43:in `unscoped'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:951:in `reload'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/attribute_methods/dirty.rb:58:in `reload'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/autosave_association.rb:237:in `reload'
/gems/ruby/3.2.0/gems/activestorage-7.0.8.1/lib/active_storage/attached/model.rb:237:in `reload'
/gems/ruby/3.2.0/gems/acts-as-taggable-on-9.0.1/lib/acts_as_taggable_on/taggable/core.rb:233:in `reload'
/gems/ruby/3.2.0/gems/acts-as-taggable-on-9.0.1/lib/acts_as_taggable_on/taggable/ownership.rb:90:in `reload'
/app/app/models/conversation.rb:264:in `set_display_id'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:400:in `block in make_lambda'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:261:in `block in conditional'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:599:in `block in invoke_after'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:599:in `each'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:599:in `invoke_after'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:108:in `run_callbacks'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:929:in `_run_commit_callbacks'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:321:in `committed!'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:345:in `block in within_new_transaction'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:302:in `save!'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/suppressor.rb:54:in `save!'
/gems/ruby/3.2.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:55:in `create!'
/app/app/services/whatsapp/incoming_message_base_service.rb:113:in `set_conversation'
/app/app/services/whatsapp/incoming_message_base_service.rb:36:in `process_messages'
/app/app/services/whatsapp/incoming_message_base_service.rb:15:in `perform'
/app/app/jobs/webhooks/whatsapp_events_job.rb:10:in `perform'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:65:in `block in _perform_job'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/gems/ruby/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:64:in `_perform_job'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:20:in `_perform_job'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:52:in `perform_now'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:25:in `block in instrument'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:35:in `instrument'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:14:in `perform_now'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:18:in `block in perform_now'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:25:in `tag_logger'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:18:in `perform_now'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:30:in `block in execute'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:28:in `execute'
/gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:210:in `execute_job'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/metrics/tracking.rb:26:in `track'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/metrics/tracking.rb:126:in `call'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/job_retry.rb:113:in `local'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/rails.rb:16:in `block in call'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:72:in `block in wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
/gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:71:in `wrap'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/rails.rb:15:in `call'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:271:in `stats'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/job_logger.rb:13:in `call'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/job_retry.rb:80:in `global'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:128:in `block in dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/job_logger.rb:39:in `prepare'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:127:in `dispatch'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:177:in `block in process'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:176:in `process'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:82:in `process_one'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/processor.rb:72:in `run'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/component.rb:10:in `watchdog'
/gems/ruby/3.2.0/gems/sidekiq-7.2.1/lib/sidekiq/component.rb:19:in `block in safe_thread'
ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=INFO ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=INFO msg=fail ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=INFO ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=INFO msg=fail ctx={"class":"Webhooks::WhatsappEventsJob","jid":"5391ea9dc0ec8fb98a25d920","elapsed":0.114}
ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=WARN ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=WARN msg={"context":"Job raised exception","job":{"retry":true,"queue":"low","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Webhooks::WhatsappEventsJob","args":[{"job_class":"Webhooks::WhatsappEventsJob","job_id":"6aae8580-3e41-42d4-aab6-f5c065c17efc","provider_job_id":null,"queue_name":"low","priority":null,"arguments":[{"object":"whatsapp_business_account","entry":[{"id":"351211458113","changes":[{"value":{"messaging_product":"whatsapp","metadata":{"display_phone_number":"351211458113","phone_number_id":"351211458113","_aj_hash_with_indifferent_access":true},"messages":[{"from":"351912490567","id":"3EB02E9DCBF0B0E3061EC9","timestamp":"1716220066","text":{"body":"Boa tarde! Envie o material do orçamento: 256726 pf!","_aj_hash_with_indifferent_access":true},"type":"text","_aj_hash_with_indifferent_access":true}],"contacts":[{"profile":{"name":"Pedro Paiva","picture":"https://pps.whatsapp.net/v/t61.24694-24/55964011_438122210089073_3341015021873266688_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_Q5AaIJ5DvdNPtsIa0MRGl6p4wBxB1WJTWLMQltUyRVsOvBUu&oe=6658838C&_nc_sid=e6ed6c&_nc_cat=100","_aj_hash_with_indifferent_access":true},"wa_id":"351912490567","_aj_hash_with_indifferent_access":true}],"statuses":[],"errors":[],"_aj_hash_with_indifferent_access":true},"field":"messages","_aj_hash_with_indifferent_access":true}],"_aj_hash_with_indifferent_access":true}],"controller":"webhooks/whatsapp","action":"process_payload","phone_number":"351211458113","whatsapp":{"object":"whatsapp_business_account","entry":[{"id":"351211458113","changes":[{"value":{"messaging_product":"whatsapp","metadata":{"display_phone_number":"351211458113","phone_number_id":"351211458113","_aj_hash_with_indifferent_access":true},"messages":[{"from":"351912490567","id":"3EB02E9DCBF0B0E3061EC9","timestamp":"1716220066","text":{"body":"Boa tarde! Envie o material do orçamento: 256726 pf!","_aj_hash_with_indifferent_access":true},"type":"text","_aj_hash_with_indifferent_access":true}],"contacts":[{"profile":{"name":"Pedro Paiva","picture":"https://pps.whatsapp.net/v/t61.24694-24/55964011_438122210089073_3341015021873266688_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_Q5AaIJ5DvdNPtsIa0MRGl6p4wBxB1WJTWLMQltUyRVsOvBUu&oe=6658838C&_nc_sid=e6ed6c&_nc_cat=100","_aj_hash_with_indifferent_access":true},"wa_id":"351912490567","_aj_hash_with_indifferent_access":true}],"statuses":[],"errors":[],"_aj_hash_with_indifferent_access":true},"field":"messages","_aj_hash_with_indifferent_access":true}],"_aj_hash_with_indifferent_access":true}],"_aj_hash_with_indifferent_access":true},"_aj_hash_with_indifferent_access":true}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-05-20T15:47:47Z"}],"jid":"5391ea9dc0ec8fb98a25d920","created_at":1716220067.1479168,"enqueued_at":1716220067.1480079}}
ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=WARN ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 ts=2024-05-20T15:47:47.264Z ts=2024-05-20T15:47:47.264Z pid=1 tid=agnv1 lvl=WARN msg=ActiveRecord::RecordNotFound: Couldn't find Conversation with 'id'=977
ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 tid=agnv1 lvl=WARN ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 tid=agnv1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 ts=2024-05-20T15:47:47.265Z ts=2024-05-20T15:47:47.265Z pid=1 tid=agnv1 lvl=WARN msg=app/models/conversation.rb:264:in `set_display_id'

### Expected behavior

A contact, a conversation and a message should have been created.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@PP-Contrib This seems to be an issue with the docker configuration. Can you please check if the Rails and Sidekiq workers are pointing to the same database?

**Comment by PP-Contrib** [comment]
Yes they are pointing to the same database.
