### ISSUE TITLE
Email invitation wont send email & unable to reset user password.

### ISSUE THREAD

**Issue by yetto** [chatwoot/chatwoot#9517]
### Describe the bug

When creating a user account, the account is created correctly, email invite on the other hand is not send. Afterwards I tried to to click on "Reset Password" but it throw a 500.

I also tried to check the code and DB, but at that point I hit a wall, I'm not familiar at all with Ruby. My intuition tells me it might be a configuration error, or so I hope. One account is set to ES the rest EN. Let me know if there's more I can provide that might be relevant.

### To Reproduce

Honestly I'm not sure, it used to worked until it stop working. Now: Invite new user,  change password failed for all users.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux

### Browser and version

Chrone, Firefox, happens regarless of browser

### Docker (if applicable)

Version 26.1.3
docker-compose version 1.29.2

### Additional context

What I've done so far:
Check .env to be configure:
```
FRONTEND_URL='https://chatwoot.example.com/'
HELPCENTER_URL="https://help.example.com"
DEFAULT_LOCALE='en'
FORCE_SSL=false
ENABLE_ACCOUNT_SIGNUP=false
REDIS_URL=redis://redis:6379
REDIS_PASSWORD=redispassword
REDIS_SENTINELS=
REDIS_SENTINEL_MASTER_NAME=
POSTGRES_HOST=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=password
RAILS_ENV=development
RAILS_MAX_THREADS=5
MAILER_SENDER_EMAIL=chatwoot@example.com
SMTP_ADDRESS=email-smtp.us-east-2.amazonaws.com
SMTP_PORT=587
SMTP_USERNAME=username
SMTP_PASSWORD=password
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=peer
ACTIVE_STORAGE_SERVICE=amazon
S3_BUCKET_NAME='buck'
AWS_ACCESS_KEY_ID='name'
AWS_SECRET_ACCESS_KEY='pass'
AWS_REGION='us-east-2'
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
LOG_SIZE=500
ENABLE_RACK_ATTACK=false
RACK_ATTACK_LIMIT=300
ENABLE_RACK_ATTACK_WIDGET_API=false
ENABLE_PUSH_RELAY_SERVER=true
``` 

Check logs for user creation:
```
rails-1     | I, [2024-05-21T19:48:19.653242 #1]  INFO -- : RoomChannel#update_presence
sidekiq-1   | {"ts":"2024-05-21T19:48:29.855Z","pid":1,"tid":"5mu9","lvl":"INFO","msg":"start","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"b643283e81ac647bd3da89d0"}}
sidekiq-1   | I, [2024-05-21T19:48:29.862181 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [f37270bf-4836-414e-ac17-d80015137756] Performing ActionMailer::MailDeliveryJob (Job ID: f37270bf-4836-414e-ac17-d80015137756) from Sidekiq(default) enqueued at 2024-05-21T19:47:10Z with arguments: "Devise::Mailer", "confirmation_instructions", "deliver_now", {:params=>{:account=>#<GlobalID:0x00007fa455ab1430 @uri=#<URI::GID gid://chatwoot/Account/4>>}, :args=>[#<GlobalID:0x00007fa455ab06e8 @uri=#<URI::GID gid://chatwoot/User/62>>, "hkxx19hy1JdJWWbgsUxK", {:client_config=>"default", :redirect_url=>nil}]}
sidekiq-1   | I, [2024-05-21T19:48:29.884846 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [f37270bf-4836-414e-ac17-d80015137756]   Rendered devise/mailer/confirmation_instructions.html.erb within layouts/mailer/base (Duration: 12.2ms | Allocations: 1966)
sidekiq-1   | I, [2024-05-21T19:48:29.885002 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [f37270bf-4836-414e-ac17-d80015137756]   Rendered layout layouts/mailer/base.liquid (Duration: 12.4ms | Allocations: 2001)
sidekiq-1   | E, [2024-05-21T19:48:29.885520 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [f37270bf-4836-414e-ac17-d80015137756] Error performing ActionMailer::MailDeliveryJob (Job ID: f37270bf-4836-414e-ac17-d80015137756) from Sidekiq(default) in 29.45ms: ActionView::Template::Error (no implicit conversion of Symbol into String):
sidekiq-1   | /usr/local/lib/ruby/3.2.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac'
sidekiq-1   | /usr/local/lib/ruby/3.2.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/key_generator.rb:40:in `generate_key'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/key_generator.rb:55:in `generate_key'
sidekiq-1   | /gems/ruby/3.2.0/gems/devise-4.9.4/lib/devise/token_generator.rb:29:in `key_for'
sidekiq-1   | /gems/ruby/3.2.0/gems/devise-4.9.4/lib/devise/token_generator.rb:17:in `generate'
sidekiq-1   | /gems/ruby/3.2.0/gems/devise-4.9.4/lib/devise/models/recoverable.rb:90:in `set_reset_password_token'
sidekiq-1   | /app/app/views/devise/mailer/confirmation_instructions.html.erb:26:in `_app_views_devise_mailer_confirmation_instructions_html_erb__3026684826153202571_262980'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/base.rb:244:in `public_send'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/base.rb:244:in `_run'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/template.rb:157:in `block in render'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:208:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/template.rb:361:in `instrument_render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/template.rb:155:in `render'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/rendering.rb:117:in `block in _render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/base.rb:270:in `in_rendering_context'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/rendering.rb:116:in `_render_template'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/rendering.rb:103:in `render_to_body'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionpack-7.0.8.1/lib/abstract_controller/rendering.rb:27:in `render'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:992:in `block in collect_responses_from_templates'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:989:in `each'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:989:in `each'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:989:in `map'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:989:in `collect_responses_from_templates'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:967:in `collect_responses'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:875:in `mail'
sidekiq-1   | /gems/ruby/3.2.0/gems/devise-4.9.4/lib/devise/mailers/helpers.rb:19:in `devise_mail'
sidekiq-1   | /gems/ruby/3.2.0/gems/devise-4.9.4/app/mailers/devise/mailer.rb:9:in `confirmation_instructions'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb:215:in `process_action'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
sidekiq-1   | /app/app/mailers/application_mailer.rb:82:in `switch_locale'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/actiontext-7.0.8.1/lib/action_text/rendering.rb:20:in `with_renderer'
sidekiq-1   | /gems/ruby/3.2.0/gems/actiontext-7.0.8.1/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionpack-7.0.8.1/lib/abstract_controller/callbacks.rb:233:in `process_action'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionpack-7.0.8.1/lib/abstract_controller/base.rb:151:in `process'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/rescuable.rb:27:in `block in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/rescuable.rb:19:in `handle_exceptions'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/rescuable.rb:26:in `process'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionview-7.0.8.1/lib/action_view/rendering.rb:39:in `process'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:646:in `block in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/base.rb:645:in `process'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/parameterized.rb:136:in `block in processed_mailer'
sidekiq-1   | <internal:kernel>:90:in `tap'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/parameterized.rb:134:in `processed_mailer'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/actionmailer-7.0.8.1/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:65:in `block in _perform_job'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:64:in `_perform_job'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:20:in `_perform_job'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:52:in `perform_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:14:in `block in perform_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:25:in `block in instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `block in instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/notifications.rb:206:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:35:in `instrument'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/instrumentation.rb:14:in `perform_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:18:in `block in perform_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:37:in `tagged'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/tagged_logging.rb:99:in `tagged'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:25:in `tag_logger'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/logging.rb:18:in `perform_now'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:30:in `block in execute'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:71:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/execution.rb:28:in `execute'
sidekiq-1   | /gems/ruby/3.2.0/gems/activejob-7.0.8.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:210:in `execute_job'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:180:in `traverse'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:26:in `track'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/metrics/tracking.rb:126:in `call'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/middleware/chain.rb:173:in `invoke'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:113:in `local'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:16:in `block in call'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/activesupport-7.0.8.1/lib/active_support/reloader.rb:71:in `wrap'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/rails.rb:15:in `call'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:271:in `stats'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:13:in `call'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_retry.rb:80:in `global'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:128:in `block in dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/job_logger.rb:39:in `prepare'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:127:in `dispatch'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `handle_interrupt'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:177:in `block in process'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `handle_interrupt'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:176:in `process'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:82:in `process_one'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/processor.rb:72:in `run'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:10:in `watchdog'
sidekiq-1   | /gems/ruby/3.2.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
sidekiq-1   | {"ts":"2024-05-21T19:48:29.886Z","pid":1,"tid":"5mu9","lvl":"INFO","msg":"Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job b643283e81ac647bd3da89d0","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"b643283e81ac647bd3da89d0"}}
sidekiq-1   | {"ts":"2024-05-21T19:48:29.888Z","pid":1,"tid":"5mu9","lvl":"INFO","msg":"fail","ctx":{"class":"ActionMailer::MailDeliveryJob","jid":"b643283e81ac647bd3da89d0","elapsed":0.033}}
sidekiq-1   | {"ts":"2024-05-21T19:48:29.888Z","pid":1,"tid":"5mu9","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"f37270bf-4836-414e-ac17-d80015137756\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"Devise::Mailer\",\"confirmation_instructions\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/4\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/User/62\"},\"hkxx19hy1JdJWWbgsUxK\",{\"client_config\":\"default\",\"redirect_url\":null,\"_aj_symbol_keys\":[\"client_config\",\"redirect_url\"]}],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2024-05-21T19:47:10Z\"}],\"jid\":\"b643283e81ac647bd3da89d0\",\"created_at\":1716320830.3683925,\"enqueued_at\":1716320909.8540537,\"error_message\":\"no implicit conversion of Symbol into String\",\"error_class\":\"ActionView::Template::Error\",\"failed_at\":1716320830.483481,\"retry_count\":2,\"retried_at\":1716320869.043136}}"}
sidekiq-1   | {"ts":"2024-05-21T19:48:29.888Z","pid":1,"tid":"5mu9","lvl":"WARN","msg":"ActionView::Template::Error: no implicit conversion of Symbol into String"}
sidekiq-1   | {"ts":"2024-05-21T19:48:29.890Z","pid":1,"tid":"5mu9","lvl":"WARN","msg":"app/views/devise/mailer/confirmation_instructions.html.erb:26\napp/mailers/application_mailer.rb:82:in `switch_locale'"}
``` 

Check logs for password reset:
```
rails-1     | I, [2024-05-21T19:57:26.719408 #1]  INFO -- : [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] Started POST "/auth/password" for 2806:10ae:8:f23e:6251:62cd:1384:a203 at 2024-05-21 19:57:26 +0000
rails-1     | I, [2024-05-21T19:57:26.721856 #1]  INFO -- : [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] Processing by DeviseOverrides::PasswordsController#create as HTML
rails-1     | I, [2024-05-21T19:57:26.721956 #1]  INFO -- : [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2]   Parameters: {"email"=>"ag1@yetto.me", "password"=>{"email"=>"ag1@yetto.me"}}
rails-1     | I, [2024-05-21T19:57:26.725504 #1]  INFO -- : [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.6ms | Allocations: 484)
rails-1     | F, [2024-05-21T19:57:26.726684 #1] FATAL -- : [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2]   
rails-1     | [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] TypeError (no implicit conversion of Symbol into String):
rails-1     | [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2]   
rails-1     | [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] app/controllers/devise_overrides/passwords_controller.rb:10:in `create'
rails-1     | [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails-1     | [0fd9d7f7-7147-47ff-9354-0ebcd7e802a2] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'
``` 

Check dead queue
```
{"account"=>"gid://chatwoot/Account/4"}, ["gid://chatwoot/User/62", "hkxx19hy1JdJWWbgsUxK", {"client_config"=>"default", "redirect_url"=>nil}]
ActionView::Template::Error: no implicit conversion of Symbol into String

{"account"=>"gid://chatwoot/Account/4"}, ["gid://chatwoot/User/61", "JLzsyzns891zxsSPYZYx", {"client_config"=>"default", "redirect_url"=>nil}]
ActionView::Template::Error: no implicit conversion of Symbol into String
```

**Comment by pranavrajs** [comment]
@yetto Did you miss adding \`SECRET_KEY_BASE\`? Please add a long string as SECRET_KEY_BASE to the environment variables. This is used to hash, encrypt some of the values in the application.

**Comment by yetto** [comment]
> @yetto Did you miss adding `SECRET_KEY_BASE`? Please add a long string as SECRET_KEY_BASE to the environment variables. This is used to hash, encrypt some of the values in the application.

Tanks for the reply, it was configured.

```
# Used to verify the integrity of signed cookies. so ensure a secure value is set
SECRET_KEY_BASE=':&v6+vwdqg#m>tuc?QErps!Gx[R;u:0A*nqG=tCM'
```

(And changed since shared in public).

**Comment by yetto** [comment]
> > @yetto Did you miss adding `SECRET_KEY_BASE`? Please add a long string as SECRET_KEY_BASE to the environment variables. This is used to hash, encrypt some of the values in the application.
> 
> Tanks for the reply, it was configured.
> 
> ```
> # Used to verify the integrity of signed cookies. so ensure a secure value is set
> SECRET_KEY_BASE=':&v6+vwdqg#m>tuc?QErps!Gx[R;u:0A*nqG=tCM'
> ```
> 
> (And changed since shared in public).

Lets not waste anymore time here. In the spirit of trying I change the SECRET_KEY_BASE to a string without special characters and now everything works as expected. Mind you not, if I use the string documented previously, fails again in the same fashion.

Might be the semicolon? Maybe. Thanks for pointing me in the right direction, I was going insane double checking every detail LOL.

**Comment by vishnu-narayanan** [comment]
@yetto Thank you for reporting back.

**Comment by pranavrajs** [comment]
@vn Let us update the docs and the .env.sample to include this information.
